### ISSUE TITLE
Ability to tag a service with a version number

### ISSUE THREAD

**Issue by rprieto** [hashicorp/consul#1131] opened 2015-07-27 05:35 UTC
Hi,

The docs at https://www.consul.io/docs/agent/services.html mention that
> The tags property is a list of values that are opaque to Consul but can be used to distinguish [...] between different versions

However it seems that the `.` character is not allowed as a tag value. What would you think of making versions a first-class citizen?

For now I could transform version numbers into a `version-1-2-3` tag, but this seems awkward to transform and query. I think it might be a common use-case to want to query services per version, not necessarily via the DNS interface, but at least via the HTTP API:
- to make blue-green deployments easy: "which services are running?" "which ones can we turn off?"
- to easily query the cluster for version info: "which versions of all services are running?"
  - this would even allow other tools to query and save this info, potentially on a schedule, and answer questions like "when did version 1.2.3 go live?"

Could a service be defined like this?

```
"name": "my-service",
"tags": ["something"],
"version": ["1.2.3-alpha"]  # semver
```

The Consul UI could even show the version split when displaying services (e.g. 5 instances running `1.2.3`, 2 instances running `1.2.4`).

Or have I missed an existing feature that already makes all of this easy?

**Comment by armon** [comment] 2015-07-27 16:26
@rprieto This is a duplicate of #697 in ways. With a V2 API we wan tot have a richer K/V tagging on services, and then you could simply have a 'version' metadata. We don't want to make this a first-class thing as everybody and every org has their own opinionated way of doing things.

**Closed by armon** 2015-07-27 16:26 UTC

**Comment by rprieto** [comment] 2015-07-27 23:06
Thanks, it definitely sounds like a specific use-case of the new metadata concept :+1: Looking forward to it.
