### ISSUE TITLE
Checks transition to critical state during reload

### ISSUE THREAD

**Issue by Farskies** [hashicorp/consul#6914] opened 2019-12-10 14:10 UTC
#### Overview of the Issue

When running `consul reload`, checks temporarily transitions to a critical state, triggering the check watcher. The behavior was changed in version 1.5.3, and is not apparent in version 1.5.2.

#### Reproduction Steps

1. Create a service with a check
1. Create a watcher for type `checks`, e.g. redirecting stdin to a file
1. Start consul agent
1. Run consul reload
1. Notice that the service temporarily transitioned to a critical state

Output on version 1.5.3:

```json
[]
[{"Node":"*","CheckID":"service:web","Name":"Service 'web' check","Status":"critical","Notes":"","Output":"","ServiceID":"web","ServiceName":"web","ServiceTags":["php"],"Definition":{"Interval":"0s","Timeout":"0s","DeregisterCriticalServiceAfter":"0s","HTTP":"","Header":null,"Method":"","TLSSkipVerify":false,"TCP":""},"CreateIndex":10,"ModifyIndex":21}]
[]
```

Output on version 1.5.2:

```json
[]
```

Service definition:

```json
{
  "service": {
    "name": "web",
    "tags": [
      "php"
    ],
    "port": 8000,
    "check": {
      "args": [
        "curl",
        "localhost:8000"
      ],
      "interval": "3s"
    }
  }
}
```

Config:

```json
{
  "watches": [
    {
      "type": "checks",
      "state": "critical",
      "handler_type": "script",
      "args": ["/home/*/consul/consul_watcher.sh"]
    }
  ]
}
```

Watcher

```bash
#!/bin/bash

exec >> /tmp/consul_watch_output.json
while IFS= read -r line; do
  printf '%s\n' "$line"
done
```

### Consul info for both Client and Server

<details>
  <summary>Server info</summary>

```
agent:                   
        check_monitors = 1    
        check_ttls = 0   
        checks = 1            
        services = 1                       
build:
        prerelease =
        revision = a42ded47                                                                                                                                                                                        
        version = 1.5.3                                                                                                                                     
consul:
        acl = disabled
        bootstrap = false                                                                                                                                                                                          
        known_datacenters = 1                                                                                                                               
        leader = true
        leader_addr = 127.0.0.1:8300                                                                                                                                                                               
        server = true                                                                                                                                       
raft:
        applied_index = 29                                                                                                                                                                                         
        commit_index = 29                                                                                                                                   
        fsm_pending = 0                    
        last_contact = 0
        last_log_index = 29
        last_log_term = 2                                                                                                                                                                                          
        last_snapshot_index = 0                                                                                                                             
        last_snapshot_term = 0
        latest_configuration = [{Suffrage:Voter ID:325d7d09-642d-7917-41b4-c0b1024587dc Address:127.0.0.1:8300}]
        latest_configuration_index = 1                                                                                                                                                                             
        num_peers = 0                                                                                                                                       
        protocol_version = 3
        protocol_version_max = 3                                                                                                                                                                                   
        protocol_version_min = 0                                                                                                                            
        snapshot_version_max = 1
        snapshot_version_min = 0                                                                                                                                                                                   
        state = Leader                                                                                                                                      
        term = 2
runtime:               
        arch = amd64
        cpu_count = 8     
        goroutines = 84
        max_procs = 8
        os = linux  
        version = go1.12.1
serf_lan:           
        coordinate_resets = 0
        encrypted = false
        event_queue = 1
        event_time = 2
        failed = 0       
        health_score = 0     
        intent_queue = 0
        left = 0                    
        member_time = 1
        members = 1
        query_queue = 0   
        query_time = 1   
serf_wan:              
        coordinate_resets = 0
        encrypted = false  
        event_queue = 0  
        event_time = 1         
        failed = 0            
        health_score = 0                                                                                        
        intent_queue = 0              
        left = 0     
        member_time = 1     
        members = 1             
        query_queue = 0         
        query_time = 1
```

</details>

### Operating system and Environment details

Ubuntu 18

### Log Fragments

```
2019/12/10 14:57:06 [DEBUG] agent: Check "service:web" is passing
    2019/12/10 14:57:08 [INFO] agent: Caught signal:  hangup
    2019/12/10 14:57:08 [INFO] agent: Reloading configuration...
    2019/12/10 14:57:08 [DEBUG] agent: removed check "service:web"
    2019/12/10 14:57:08 [DEBUG] agent: removed service "web"
    2019/12/10 14:57:08 [DEBUG] tlsutil: Update with version 4
    2019/12/10 14:57:08 [DEBUG] http: Request PUT /v1/agent/reload (6.73415ms) from=127.0.0.1:59426
    2019/12/10 14:57:08 [INFO] agent: Synced service "web"
    2019/12/10 14:57:08 [DEBUG] agent: Check "service:web" in sync
    2019/12/10 14:57:08 [DEBUG] agent: Node info in sync
    2019/12/10 14:57:08 [DEBUG] http: Request GET /v1/health/state/critical (204.153µs) from=127.0.0.1:59428
    2019/12/10 14:57:08 [DEBUG] http: Request GET /v1/health/state/critical?index=31 (1m38.761499769s) from=127.0.0.1:59124
    2019/12/10 14:57:08 [DEBUG] agent: watch handler '[/consul_watcher.sh]' output: 
    2019/12/10 14:57:10 [DEBUG] agent: Check "service:web" is passing
    2019/12/10 14:57:10 [DEBUG] agent: Service "web" in sync
    2019/12/10 14:57:10 [INFO] agent: Synced check "service:web"
    2019/12/10 14:57:10 [DEBUG] agent: Node info in sync
    2019/12/10 14:57:10 [DEBUG] http: Request GET /v1/health/state/critical?index=40 (1.035382454s) from=127.0.0.1:59428
    2019/12/10 14:57:10 [DEBUG] agent: watch handler '[/consul_watcher.sh]' output:
```

Might be related to https://github.com/hashicorp/consul/pull/6144

**Comment by lvets** [comment] 2020-02-14 18:30
What's the reason for marking passing checks as critical when doing `consul reload`?

In our use case (Fabio + Consul), when we do `consul reload`, checks are transitioned to critical state temporarily. At this point, routes are removed from Fabio only to be added again when the check passes again...

**Comment by gsolic** [comment] 2020-03-23 13:51
Seems to be a duplicate of #7318 and fixed with #7345?

**Comment by lvets** [comment] 2020-06-05 16:38
I _think_ we had the same issue (https://github.com/hashicorp/consul/issues/7318) which is indeed fixed with https://github.com/hashicorp/consul/pull/7345.

**Comment by jsosulska** [comment] 2020-06-09 19:49
Thank you @gsolic and @lvets , you are both correct. If this issue still persists, please open a new issue and reference this and the other 2 prs/issues.  Closing now.

**Closed by jsosulska** 2020-06-09 19:49 UTC
Labels: theme/config-reload, theme/health-checks
