### ISSUE TITLE
Applying Tags and Service Names to Initially Bootstrapped Consul Service

### ISSUE THREAD

**Issue by jaredvacanti** [hashicorp/consul#4631] opened 2018-09-04 19:04 UTC
**Old UI or New UI**
Consul 1.2.2

**Describe the problem you're having**
When bootstrapping an initial consul cluster with `n` nodes using `-bootstrap-expect n`, the service `consul` is automatically registered in consul and shows in the ui as `consul`.  I can adjust any additional service I register to consul using service definitions with tags and naming convetions, but I can't adjust the initially bootstrapped consul service's name and tags to match convention elsewhere. There is no way of editing this information in the consul ui.

(I have deployed with docker here for ease of reproduction)

```
version: '3.6'

x-consul: &consul
    image: consul:latest
    volumes:
      - consul:/consul

volumes:
  consul:

services:

  server:
    <<: *consul
    ports:
      - "8500:8500"
    depends_on:
      - server-bootstrap
    command: "agent -server -retry-join server-bootstrap -client 0.0.0.0 -bind '{{ GetInterfaceIP \"eth0\" }}' -ui"
    deploy:
      replicas: 2

  # only this server will attempt to bootstrap once three servers are available
  server-bootstrap:
    image: consul
    command: "agent -server -bootstrap-expect 3 -node-meta TAGS:consul,server,http,web,ui -client 0.0.0.0 -bind '{{ GetInterfaceIP \"eth0\" }}'"
    deploy:
      placement:
        constraints: [node.role == manager]
```

This will result in this services page in my consul UI:

<img width="1435" alt="screen shot 2018-09-04 at 2 01 49 pm" src="https://user-images.githubusercontent.com/2007559/45051961-21befa80-b04b-11e8-8f89-2a8fc79c20bf.png">

When I add my other services, the tags and conventions become more important. I've made a contrived example here, again with docker, that will register all listening ports as services with `registrator`:

 ```
version: '3.6'

x-consul: &consul
    image: consul:latest
    volumes:
      - consul:/consul

volumes:
  consul:

services:
  server:
    <<: *consul
    ports:
      - "8500:8500"
    depends_on:
      - server-bootstrap
    command: "agent -server -retry-join server-bootstrap -client 0.0.0.0 -bind '{{ GetInterfaceIP \"eth0\" }}' -ui"
    environment:
      - "SERVICE_TAGS=consul-server"
      - "SERVICE_REGION=none"
      - "SERVICE_NAME=consul-server"
      - "SERVICE_8300_NAME=consul-server"
      - "SERVICE_8300_TAGS=consul,server"
      - "SERVICE_8301_TAGS=consul,Serf-LAN,local-area-network"
      - "SERVICE_8302_TAGS=consul,Serf-WAN,wide-area-network"
      - "SERVICE_8500_NAME=consul-http"
      - "SERVICE_8500_TAGS=consul,http,web,ui"
      - "SERVICE_8600_NAME=consul-dns-server"
      - "SERVICE_8600_TAGS=dns,consul"
    deploy:
      replicas: 2

  ## only this server will attempt to bootstrap once three servers are available
  server-bootstrap:
    image: consul
    command: "agent -server -bootstrap-expect 3 -node-meta TAGS:consul,server,http,web,ui -client 0.0.0.0 -bind '{{ GetInterfaceIP \"eth0\" }}'"
    environment:
      - "SERVICE_TAGS=consul-bootstrap-server"
      - "SERVICE_REGION=none"
      - "SERVICE_8300"
      - "SERVICE_NAME=consul-boostrap-server"
      - "SERVICE_8300_NAME=consul-server"
      - "SERVICE_8300_TAGS=consul,server"
      - "SERVICE_8301_TAGS=consul,Serf-LAN,local-area-network"
      - "SERVICE_8302_TAGS=consul,Serf-WAN,wide-area-network"
      - "SERVICE_8500_NAME=consul-http"
      - "SERVICE_8500_TAGS=consul,http,web,ui"
      - "SERVICE_8600_NAME=consul-dns-bootstrap"
      - "SERVICE_8600_TAGS=dns,consul"
    deploy:
      placement:
        constraints: [node.role == manager]

  registrator:
    image: gliderlabs/registrator:latest
    command: -internal consul://server-bootstrap:8500
    depends_on:
      - server
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    # environment:
    deploy:
      mode: global
```

This will result in this services page on my consul ui:

<img width="1435" alt="screen shot 2018-09-04 at 1 55 36 pm" src="https://user-images.githubusercontent.com/2007559/45051652-4b2b5680-b04a-11e8-9ddf-06523b41b753.png">

Some of my attempts have included using `-node-meta TAGS:...` when launching consul, or attempting some environment variables. These haven't been successful. I haven't found a way to adjust tags through the UI.

**Describe the solution you'd like**
Is there a way to set the tags and associated data with the consul server's initially bootstrapped service either programmatically, or edit/add/remove them from the UI?

**Comment by pearkes** [comment] 2018-09-12 17:12
@jaredvacanti I think you're asking for a similar feature described in https://github.com/hashicorp/consul/issues/4628. Note with the catalog endpoints you can modify tags after creation, but that is not currently possible be the UI.

**Comment by pearkes** [comment] 2019-01-18 17:19
I realize this is a duplicate of #4628 with some extra coverage of the CLI there. I'm going to close this in favor of that but it will link back for context.

**Closed by pearkes** 2019-01-18 17:19 UTC
Labels: ui

**Comment by Lasering** [comment] 2019-02-14 15:42
I would also like to change the service name which consul uses to register itself in Consul. #4628 is not related.

I would also like to change its tags when I bootstrap the cluster, preferably via some configuration. Although changing it afterwards using #4628 would suffice.
