### ISSUE TITLE
Vault is not appearing in consul(ui) services list

### ISSUE THREAD

**Issue by MamatmurodovA** [hashicorp/consul#7658] opened 2020-04-17 06:53 UTC
Configs:
- **consul-config.json**:

```json
{
    "datacenter": "localhost",
    "data_dir": "/consul/data",
    "log_level": "DEBUG",
    "server": true,
    "ui": true,
    "ports": {
      "dns": 53
    }
}
```
- **vault-config.json**:

```json
{
  "ui": true,
  "backend": {
    "consul": {
      "address": "consul:8500",
      "path": "vault/"
    }
  },
  "listener": {
    "tcp":{
      "address": "0.0.0.0:8200",
      "tls_disable": 1
    }
  }
}
```
**Problem:**
1. Vault appears in services list of consul, when i've used:

- consul - **v1.7.2**
- vault - **v1.3.4**

![](https://i.ibb.co/Tr8P7B6/Screenshot-at-2020-04-17-11-34-19.png)

2. **But**, when i'm using another versions, there's no vault service in the list(in consul ui):
- consul - **v1.6.5**
- vault - **v1.4.0**

![](https://i.ibb.co/wLyw01m/Screenshot-at-2020-04-17-11-48-13.png)

I need solution to use 2nd variant, i searched stackoverflow, documentation and other resources, but there's no any solution, maybe i skipped :).
Have you experienced like this ?

**Comment by johncowen** [comment] 2020-04-17 09:14
Hi @MamatmurodovA 

Could you check and see if going to `http://yourhost/v1/internal/ui/services?dc=localhost` also gives you a vault service. I imagine it does, but its just to help us to triage this issue.

Thanks,

**Comment by MamatmurodovA** [comment] 2020-04-17 13:19
Hi, @johncowen !

Thank you for replying! 

The endpoint returning only one service:
![Uploading image.png…](https://i.ibb.co/8bPz2cZ/image.png)

I tried this solution [https://stackoverflow.com/a/55682755/4723929](https://stackoverflow.com/a/55682755/4723929), it added the service to the list, but i do not think it's right way! I think there's more optimal and right solution for that!

Thank you

**Comment by johncowen** [comment] 2020-04-17 13:29
Hmm, thats very strange, the UI only shows what is in that API endpoint.

Maybe it's best to check the Network panel in your browser developer tools when you see vault appear in the UIs service listing. If you can check any requests you see in there for `http://yourhost/v1/internal/ui/services?dc=localhost` and see if you see `vault` in there (there could be multiple requests to that URL if things have updated in a matter of a few seconds)

**Comment by MamatmurodovA** [comment] 2020-04-17 13:42
Endpoint returns:

![image](https://user-images.githubusercontent.com/13590706/79575264-f29fb480-80da-11ea-93c7-18de8c53e5be.png)

Networking panel:

![image](https://user-images.githubusercontent.com/13590706/79575367-1a8f1800-80db-11ea-80f0-cd67c8e81286.png)

**Comment by johncowen** [comment] 2020-04-17 14:10
Thanks for being so fast in coming back!

So we can see a `vault` service in the API response, which means the UI is showing the correct information.

Just to confirm, what are you expecting here?

1. Vault should not be in the API response.
2. Vault should be in the API response.

The title of the issue reads:

> Vault is not appearing in consul(ui) services list

but further down you say:

> I need solution to use 2nd variant

i.e. don't display vault.

So unsure what you are expecting to see here.

A little more information:

https://www.vaultproject.io/docs/configuration/service-registration

> When Consul is configured as the storage backend, Vault implicitly uses Consul for service registration, so the service_registration stanza is not needed.

So when consul is used a backend for vault (which is your case), it will register itself with consul, and you should see it in the UI.

**Comment by MamatmurodovA** [comment] 2020-04-17 14:18
Yes, maybe there's some misunderstanding in my question, sorry for that!

What i want to see vault in service list of consul - Vault should be in the API response!

Yes, you're right UI works fine, it renders what backend returns.
But, the problem why backend is not returning ?

Anyway, i know it's not UI issue, but i just added it to do problem more clear :), 
Thank you too!

**Comment by johncowen** [comment] 2020-04-17 14:21
Thanks for the detailed responses. I noticed that you are using the [vault-consul-docker](https://github.com/testdrivenio/vault-consul-docker) repo here, and it's a bit out of date. I recommend checking out our [learn guides](https://learn.hashicorp.com/vault?track=getting-started#getting-started) which provide some great ways to get started using Vault.
For questions or discussions around our HashiCorp tools, please take a look at [our forums](https://discuss.hashicorp.com/) where more folks in the community can provide feedback!

**Comment by MamatmurodovA** [comment] 2020-04-17 14:25
Thank you for your response!

Anyway, you think it's related to configuration ? I thought it's bug, because, it's working previous version, but not working with current!

I'll check the links which you mentioned!
Thank you for taking a time!

**Comment by johncowen** [comment] 2020-04-17 14:31
No problem! I thinks it's all a little confusing as in one set up you have a newer version of vault and an older version of consul, and in another setup vice versa.

I fairly certain it's not a bug. You might get more help in the forums if anyone else if using the same vault-consul-docker repo that you are.

**Comment by MamatmurodovA** [comment] 2020-04-17 14:34
okay, thank you!

**Comment by johncowen** [comment] 2020-04-17 14:49
I'm going to close this for the moment at least 👍

**Closed by johncowen** 2020-04-17 14:49 UTC

**Comment by MamatmurodovA** [comment] 2020-04-17 16:22
I could register vault in consul by adding this:

```json
{
    "datacenter": "localhost",
    "data_dir": "/consul/data",
    "log_level": "DEBUG",
    "server": true,
    "ui": true,
    "ports": {
      "dns": 53
    },
    "service":{
      "name": "vault",
      "address": "localhost",
      "port": 8200,
      "check":  {
         "http": "http://localhost:8200/v1/sys/health",
         "interval": "10s",
         "timeout": "5s"
      }
     }
}
```

And it's appeared in services list:

![image](https://user-images.githubusercontent.com/13590706/79591076-75336e80-80f1-11ea-850c-099a9fde60d0.png)
