### ISSUE TITLE
I am receiving these kind of error: Error starting userland proxy

### ISSUE THREAD

**Issue by eddamalique01** [hashicorp/consul#3808] opened 2018-01-16 09:17 UTC
admin@edwin-Vostro-3900:~$ consul info
agent:
	check_monitors = 0
	check_ttls = 0
	checks = 0
	services = 0
build:
	prerelease = 
	revision = b55059f
	version = 1.0.2
consul:
	bootstrap = false
	known_datacenters = 1
	leader = true
	leader_addr = 127.0.0.1:8300
	server = true
raft:
	applied_index = 766
	commit_index = 766
	fsm_pending = 0
	last_contact = 0
	last_log_index = 766
	last_log_term = 2
	last_snapshot_index = 0
	last_snapshot_term = 0
	latest_configuration = [{Suffrage:Voter ID:337e67b2-59cc-64b5-1950-0957e780bd2d Address:127.0.0.1:8300}]
	latest_configuration_index = 1
	num_peers = 0
	protocol_version = 3
	protocol_version_max = 3
	protocol_version_min = 0
	snapshot_version_max = 1
	snapshot_version_min = 0
	state = Leader
	term = 2
runtime:
	arch = amd64
	cpu_count = 4
	goroutines = 70
	max_procs = 4
	os = linux
	version = go1.9.2
serf_lan:
	coordinate_resets = 0
	encrypted = false
	event_queue = 1
	event_time = 2
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 1
	members = 1
	query_queue = 0
	query_time = 1
serf_wan:
	coordinate_resets = 0
	encrypted = false
	event_queue = 0
	event_time = 1
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 1
	members = 1
	query_queue = 0
	query_time = 1
admin@edwin-Vostro-3900:~$ ifconfig
docker0   Link encap:Ethernet  HWaddr 02:42:cc:f2:31:88  
          inet addr:172.17.0.1  Bcast:0.0.0.0  Mask:255.255.0.0
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

docker_gwbridge Link encap:Ethernet  HWaddr 02:42:84:18:ae:a7  
          inet addr:172.18.0.1  Bcast:0.0.0.0  Mask:255.255.0.0
          inet6 addr: fe80::42:84ff:fe18:aea7/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:1082 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:0 (0.0 B)  TX bytes:200442 (200.4 KB)

enp2s0    Link encap:Ethernet  HWaddr f4:8e:38:8a:67:cd  
          inet addr:172.16.15.167  Bcast:172.16.255.255  Mask:255.255.0.0
          inet6 addr: fe80::ffa0:b32c:f0ea:ba7e/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:2946750 errors:0 dropped:0 overruns:0 frame:0
          TX packets:944519 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:3757246968 (3.7 GB)  TX bytes:71479498 (71.4 MB)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:1707297 errors:0 dropped:0 overruns:0 frame:0
          TX packets:1707297 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1 
          RX bytes:1111908798 (1.1 GB)  TX bytes:1111908798 (1.1 GB)

vethb2b9be8 Link encap:Ethernet  HWaddr d6:79:ca:3c:2f:c2  
          inet6 addr: fe80::d479:caff:fe3c:2fc2/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:1151 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:0 (0.0 B)  TX bytes:209308 (209.3 KB)

virbr0    Link encap:Ethernet  HWaddr 00:00:00:00:00:00  
          inet addr:192.168.122.1  Bcast:192.168.122.255  Mask:255.255.255.0
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

admin@edwin-Vostro-3900:~$ sudo docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
2391/test1          new                 0d623475791c        4 months ago        194MB
php-simple-app      latest              0d623475791c        4 months ago        194MB
test1.1             latest              0d623475791c        4 months ago        194MB
test1               1                   0d623475791c        4 months ago        194MB
test1               latest              0d623475791c        4 months ago        194MB
2391/get-started    part2               5c7c45e88a5a        5 months ago        194MB
john/get-started    part1               5c7c45e88a5a        5 months ago        194MB
friendlyhello       latest              5c7c45e88a5a        5 months ago        194MB
ubuntu              16.04               ccc7a11d65b1        5 months ago        120MB
ubuntu              latest              ccc7a11d65b1        5 months ago        120MB
nginx               latest              b8efb18f159b        5 months ago        107MB
python              2.7-slim            451c85955bc2        5 months ago        182MB
busybox             latest              efe10ee6727f        6 months ago        1.13MB
alpine              latest              7328f6f8b418        6 months ago        3.97MB
hello-world         latest              1815c82652c0        7 months ago        1.84kB
progrium/consul     latest              09ea64205e55        2 years ago         69.4MB
jpetazzo/clock      latest              12068b93616f        2 years ago         2.43MB

admin@edwin-Vostro-3900:~$ sudo docker run -p 8400:8400 -p 8500:8500 -p 8600:53/udp -h node1 progrium/consul -server -bootstrap
docker: Error response from daemon: driver failed programming external connectivity on endpoint awesome_bartik (cdaa03d020e90d75c5a9184a1ec1525ebd626300866955241e9c9472f2bea609): Error starting userland proxy: listen tcp 0.0.0.0:8500: bind: address already in use.
ERRO[0001] error waiting for container: context canceled 
admin@edwin-Vostro-3900:~$ 
Kindly assist me.

 you have a question, please direct it to the
[consul mailing list](https://www.consul.io/community.html) if it hasn't been
addressed in either the [FAQ](https://www.consul.io/docs/faq.html) or in one
of the [Consul Guides](https://www.consul.io/docs/guides/index.html).

When filing a bug, please include the following:

### `consul version` for both Client and Server
Client: `[client version here]`
Server: `[server version here]`

### `consul info` for both Client and Server
Client:
```
[Client `consul info` here]
```

Server:
```
[Server `consul info` here]
```

### Log Fragments or Link to [gist](https://gist.github.com/)

Include appropriate Client or Server log fragments.  If the log is longer
than a few dozen lines, please include the URL to the
[gist](https://gist.github.com/).

TIP: Use `-log-level=TRACE` on the client and server to capture the maximum log detail.

**Comment by slackpad** [comment] 2018-01-25 01:26
Closing as a duplicate of https://github.com/hashicorp/consul/issues/3796.

**Closed by slackpad** 2018-01-25 01:26 UTC
