### ISSUE TITLE
'consul lock' should recognize '--' to stop processing command line switches

### ISSUE THREAD

**Issue by babbottscott** [hashicorp/consul#776] opened 2015-03-11 19:49 UTC
Under 'consul lock', on calling a child process that takes '-v' as an argument, we get the following:

```
$ consul lock --help
Usage: consul lock [options] prefix child...
...
$ consul lock -n 1 lock_it cat -v foo
Consul v0.5.0
Consul Protocol: 2 (Understands back to: 1)
$
```

We can enclose the child command line with quotes, but this adds a required layer of quoting to a bash command line (never a desirable thing if it can be avoided).

Desired solution: use '--' switch to end switch processing.  Anything that follows would be presumed to be part of "child"

```
$ consul lock -n 1 lock_it -- cat -v foo
cat: foo: No such file or directory
```

Alternatively: don't necessarily need a -- switch.  Just have first non-option argument be "prefix", and all following arguments be "child", as the --help message suggests.

**Comment by mfischer-zd** [comment] 2015-03-11 20:26
+1, this will make it consistent with other programs' behavior WRT argument passing

**Comment by ryanuber** [comment] 2015-03-11 23:35
Thanks for the report! This was a relatively simple fix, since Go's `flag` already supports the `--` splitter. The problem was just the `-v` or `--version` flags, which should be fixed after 45f5997.

**Comment by babbottscott** [comment] 2015-03-17 19:43
many thanks!

**Comment by babbottscott** [comment] 2015-07-07 18:36
I am still seeing this behavior on 0.5.2

**Comment by i0rek** [comment] 2020-02-18 22:12
Thank you for reporting! I can still reproduce the described behavior. Since there is a workaround by using quotes, I am going to close this issue, because it not such a big deal for us. If you or someone else would be willing to provide a PR, we would be happy to merge it.

**Closed by i0rek** 2020-02-18 22:12 UTC
Labels: enhancement, theme/cli-cleanup
