### ISSUE TITLE
client registration api occasionally not work

### ISSUE THREAD

**Issue by hehailong5** [hashicorp/consul#2177] opened 2016-07-11 07:47 UTC
version: 0.6.4

description: it is observed that sometimes the url "/v1/agent/service/register" was returned with 200 OK while neither the catalog nor client agent cache was updated.

**Comment by slackpad** [comment] 2016-07-14 06:53
Hi @hehailong5 can you provide some more detail about your request? There's a known issue where some of the agent endpoints don't properly report JSON errors (200 is returned but no update takes place) so that's the most likely issue. That's similar to https://github.com/hashicorp/consul/issues/1188.

**Comment by slackpad** [comment] 2016-08-11 01:27
Closing as a duplicate of #1188.

**Closed by slackpad** 2016-08-11 01:27 UTC
