### ISSUE TITLE
Adding header settings to HTTP health check

### ISSUE THREAD

**Issue by samber** [hashicorp/consul#1896] opened 2016-03-30 08:02 UTC
Hi guys, 

I'm writing this issue to discuss about an improvement.

Today, Consul is able to perform an HTTP health-check with a defined route (ex: /health).
It would be awesome to send a request with custom fields set in the HTTP header.
In this way, it should be possible to test:
- the routing rules of a reverse proxy with the field ```Host```, 
- an authentication with the field ```Authorization``` or custom
- or even test CORS with ```Origin```.

To illustrate:
adding: ```req.Header.Set("Host", "foo.bar.example.com")```
here: https://github.com/hashicorp/consul/blob/master/command/agent/check.go#L415

It can be done with scripting+curl, but using the http health check would be the best practice.

Rgds

**Comment by slackpad** [comment] 2016-04-13 04:55
Hi @samber thanks for opening an issue, I'm going to close this as a duplicate of #1184.

**Closed by slackpad** 2016-04-13 04:55 UTC
