### ISSUE TITLE
ServiceDeregister error

### ISSUE THREAD

**Issue by byronzoz** [hashicorp/consul#5851] opened 2019-05-16 03:16 UTC
[Version]
Consul version: 0.8.1

[Description]
When call agentServiceDeregister api, exception occurs:

```
{
    "service:/dubbo/com.alibaba.dubbo.test.injvmServie/providers": {
        "Node": "platform02.dev.rack.zhihu.com",
        "CheckID": "service:/dubbo/com.alibaba.dubbo.test.injvmServie/providers",
        "Name": "Service 'com.alibaba.dubbo.test.injvmServie' check",
        "Status": "critical",
        "Notes": "",
        "Output": "TTL expired",
        "ServiceID": "/dubbo/com.alibaba.dubbo.test.injvmServie/providers",
        "ServiceName": "com.alibaba.dubbo.test.injvmServie",
        "CreateIndex": 0,
        "ModifyIndex": 0
    }
}
```
ConsulClient consulClient = new ConsulClient("xxx", 8500);
Response<Map<String, Service>> result = consulClient.getAgentServices();
consulClient.agentServiceDeregister("/dubbo/com.alibaba.dubbo.test.injvmServie/providers");
output:

```
OperationException{statusCode=301, statusMessage='Moved Permanently', statusContent=''}
	at com.ecwid.consul.v1.agent.AgentConsulClient.agentServiceDeregister(AgentConsulClient.java:296)
	at com.ecwid.consul.v1.agent.AgentConsulClient.agentServiceDeregister(AgentConsulClient.java:284)
	at com.ecwid.consul.v1.ConsulClient.agentServiceDeregister(ConsulClient.java:315)
	at org.apache.dubbo.registry.consul.ConsulRegistryTest.test(ConsulRegistryTest.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:538)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)

```

**Comment by pierresouchay** [comment] 2019-05-16 18:11
Having service IDs with / in the name (and furthermore in ID) is really not a good idea, avoid it at all costs.

Try using only chars valid as DNS labels [a-z0-9-] for service name and ID (so, no dots, slashes, underscores if possible)

**Comment by pierresouchay** [comment] 2019-05-27 23:50
Looks very similar to #4992

**Comment by pearkes** [comment] 2019-06-26 23:38
Agree going to say this is likely a duplicate of #4992.

**Closed by pearkes** 2019-06-26 23:38 UTC
