### ISSUE TITLE
TLS hostname validation failure with version 1.0.0 on Alpine Linux 3.6

### ISSUE THREAD

**Issue by bhuisgen** [hashicorp/consul#3613] opened 2017-10-25 11:36 UTC
Since Consul 1.0.0, the TLS hostname verification seems to fail on RPC connections, using my own CA and client / server certificates. The problem I don't understand is why it failed on the server itself (RPC error)

Trying the same configuration and environment with consul v 0.9.3 works perfectly so something changed. The error log show the good server name for the certificate (consul config dc + domain OK).

### `consul version` for both Client and Server
Client: `1.0.0`
Server: `1.0.0`

### `consul info` for both Client and Server

Server:
```
agent:
	check_monitors = 0
	check_ttls = 0
	checks = 0
	services = 0
build:
	prerelease = 
	revision = 51ea240
	version = 1.0.0
consul:
	bootstrap = true
	known_datacenters = 1
	leader = true
	leader_addr = 192.168.178.52:8300
	server = true
raft:
	applied_index = 214
	commit_index = 214
	fsm_pending = 0
	last_contact = 0
	last_log_index = 214
	last_log_term = 2
	last_snapshot_index = 0
	last_snapshot_term = 0
	latest_configuration = [{Suffrage:Voter ID:aaa5513f-3f2a-caee-8941-673abeb56fce Address:192.168.178.52:8300}]
	latest_configuration_index = 1
	num_peers = 0
	protocol_version = 3
	protocol_version_max = 3
	protocol_version_min = 0
	snapshot_version_max = 1
	snapshot_version_min = 0
	state = Leader
	term = 2
runtime:
	arch = amd64
	cpu_count = 4
	goroutines = 66
	max_procs = 4
	os = linux
	version = go1.9.1
serf_lan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 1
	event_time = 2
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 1
	members = 1
	query_queue = 0
	query_time = 1
serf_wan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 1
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 1
	members = 1
	query_queue = 0
	query_time = 1
```

### Operating system and Environment details

Docker environment, 1 server node only.

### Description of the Issue (and unexpected/desired result)

RPC connection failure due to invalid server hostname for the TLS certificate.

### Server config

```
# cat /etc/consul.d/config.json 
{
    "datacenter": "local",
    "data_dir": "/var/lib/consul",
    "log_level": "INFO",
    "disable_anonymous_signature": true,
    "disable_update_check": true
}
```
```
# cat /etc/consul.d/domain.json 
{
    "domain": "my.domain"
}
```
```
# cat /etc/consul.d/tls.json 
{
    
    "ca_file": "/etc/consul.d/ssl/ca.pem",
    "cert_file": "/etc/consul.d/ssl/server.pem",
    "key_file": "/etc/consul.d/ssl/server-priv-key.pem",
    "verify_server_hostname": true,
    "verify_incoming": true,
    "verify_outgoing": true,
    "ports": {
        "https": 8501
    }
    
}
```
### Log Fragments or Link to [gist](https://gist.github.com/)

```
2017/10/25 12:09:37 [WARN] consul: error getting server health from "consul": rpc error getting client: failed to get conn: x509: certificate is not valid for any names, but wanted to match server.local.my.domain
2017/10/25 12:09:37 [ERR] consul.rpc: failed to read byte: remote error: tls: bad certificate from=192.168.178.52:37564
2017/10/25 12:09:38 [WARN] consul: error getting server health from "consul": context deadline exceeded
```

**Comment by hvindin** [comment] 2017-10-25 13:22
I suspect that more help might be provided if you give the output of

`openssl x509 -in <server certificate>.pem -noout -text`

Because that error looks an awful lot like the alt-DNS entry on the cert is not set to include  DNS:server.local.my.domain

Not sure why it would have worked on 0.9.3 thought...

**Comment by bhuisgen** [comment] 2017-10-25 13:45
@hvindin the server certificate CN matches the rule server.<datacenter>.<domain> (CN=server.local.my.domain) and the certificate type is server. The alternative DNS entry is not required.

**Comment by bhuisgen** [comment] 2017-11-06 11:19
All my docker images use alpine 3.6. With consul server 0.9.3, no problem of validation for server certificates. With v 1.0.0 it breaks. 

On the client side (other containers) I have the same problems with consul-template 0.19.4, the TLS validation of the client certificate breaks. Using the old version 0.19.3, it works well.

Testing validation with openssl client, all tests are ok. So is it related to libressl or go ?

**Comment by slackpad** [comment] 2017-11-10 20:57
Hi @bhuisgen I didn't see anything fishy between the Go versions and libressl changes shouldn't matter to Consul since it's all statically linked. The "certificate is not valid for any names" message is a little weird - can you please dump some diagnostic info about your cert and we can try to reproduce?

**Comment by bhuisgen** [comment] 2017-11-13 13:37
@slackpad right it's not related to libressl.

Here is the truncated details of my server certificate:

````
bash-4.3# openssl x509 -in server.pem -noout -text
````
````
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number: 1 (0x1)
    Signature Algorithm: sha256WithRSAEncryption
        Issuer: C=***, ST=***, L=***, O=***, OU=***, CN=*** Issuing CA/emailAddress=***@***
        Validity
            Not Before: Jun  7 16:56:17 2016 GMT
            Not After : Jun  7 16:56:17 2018 GMT
        Subject: C=***, ST=***, L=***, O=***, OU=***, CN=server.local.my.domain/emailAddress=***@***
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                Public-Key: (2048 bit)
        X509v3 extensions:
            X509v3 Basic Constraints: 
                CA:FALSE
            Netscape Cert Type: 
                SSL Server
            Netscape Comment: 
                TinyCA Generated Certificate
            X509v3 Subject Key Identifier: 
            X509v3 Authority Key Identifier: 
                DirName:/C=***/ST=***/L=***/O=***/OU=***/CN=*** Root CA/emailAddress=***@***
                serial:01
            X509v3 Issuer Alternative Name: 
                email:***@***
            X509v3 Subject Alternative Name: 
                email:***@***
    Signature Algorithm: sha256WithRSAEncryption
````

Notice that I have the problem on the server himself (RPC connections). And since version v0.19.4 of consul-template, I add the problem on the client-side.

**Comment by discointheair** [comment] 2017-12-14 07:49
Hi

Maybe any common cause to this issue?:
[server_name](https://github.com/hashicorp/consul/issues/3641)

**Comment by michalmedvecky** [comment] 2018-08-15 16:37
I'm seeing this on 1.2.0 too :\

**Comment by i0rek** [comment] 2018-10-04 15:19
Thanks for reporting! I am wondering if this is still an issue, especially with the latest version of consul? If you can provide a repro, I will look into it!

**Comment by michalmedvecky** [comment] 2018-10-04 16:14
Hm, I got around it somehow...

**Comment by i0rek** [comment] 2018-10-22 20:50
Ok, I will close this for now. I would be happy to reopen in case this problem pops up again!

**Closed by i0rek** 2018-10-22 20:50 UTC
Labels: needs-investigation, theme/tls

**Comment by nhenneaux** [comment] 2019-05-03 10:51
If other people have the same problem, the certificate for consul server must has a Subject Alternative Name (SAN) with `server.$DC.$DOMAIN` with always `server`. For example `server.dc1.consul` or `server.brussels.mycompany.com`.

**Comment by morphace** [comment] 2022-06-07 09:34
thanks... so the server. part is hardcoded ?
