### ISSUE TITLE
Data race within consul server startup

### ISSUE THREAD

**Issue by mpuncel** [hashicorp/consul#3049] opened 2017-05-15 19:39 UTC
### Data race within consul code
```
==================
WARNING: DATA RACE
Read at 0x00c420360128 by goroutine 233:
  github.com/square/p2/vendor/github.com/hashicorp/consul/consul.(*Server).leaderLoop()
      /Users/mpuncel/Development/go/src/github.com/square/p2/vendor/github.com/hashicorp/consul/consul/leader.go:60 +0x12f

Previous write at 0x00c420360128 by goroutine 12:
  github.com/square/p2/vendor/github.com/hashicorp/consul/consul.NewServer()
      /Users/mpuncel/Development/go/src/github.com/square/p2/vendor/github.com/hashicorp/consul/consul/server.go:268 +0x146e
  github.com/square/p2/vendor/github.com/hashicorp/consul/command/agent.(*Agent).setupServer()
      /Users/mpuncel/Development/go/src/github.com/square/p2/vendor/github.com/hashicorp/consul/command/agent/agent.go:406 +0x162
  github.com/square/p2/vendor/github.com/hashicorp/consul/command/agent.Create()
      /Users/mpuncel/Development/go/src/github.com/square/p2/vendor/github.com/hashicorp/consul/command/agent/agent.go:203 +0x1010
  github.com/square/p2/pkg/store/consul/consulutil.NewFixture()
      /Users/mpuncel/Development/go/src/github.com/square/p2/pkg/store/consul/consulutil/consultest.go:80 +0x4eb
  github.com/square/p2/pkg/store/consul/consulutil.TestSessionBasics()
      /Users/mpuncel/Development/go/src/github.com/square/p2/pkg/store/consul/consulutil/session_controller_test.go:16 +0x6f
  testing.tRunner()
      /usr/local/opt/go/libexec/src/testing/testing.go:610 +0xc9

Goroutine 233 (running) created at:
  github.com/square/p2/vendor/github.com/hashicorp/consul/consul.(*Server).monitorLeadership()
      /Users/mpuncel/Development/go/src/github.com/square/p2/vendor/github.com/hashicorp/consul/consul/leader.go:39 +0x206

Goroutine 12 (running) created at:
  testing.(*T).Run()
      /usr/local/opt/go/libexec/src/testing/testing.go:646 +0x52f
  testing.RunTests.func1()
      /usr/local/opt/go/libexec/src/testing/testing.go:793 +0xb9
  testing.tRunner()
      /usr/local/opt/go/libexec/src/testing/testing.go:610 +0xc9
  testing.RunTests()
      /usr/local/opt/go/libexec/src/testing/testing.go:799 +0x4ba
  testing.(*M).Run()
      /usr/local/opt/go/libexec/src/testing/testing.go:743 +0x12f
  main.main()
      github.com/square/p2/pkg/store/consul/consulutil/_test/_testmain.go:82 +0x1b8
==================
```

### Reproduction steps

Run `agent.Create()` within a test under the race detector.

I was able to reproduce by running `while go test -race; do true; done` within `$GOPATH/src/github.com/square/p2/pkg/store/consul/consulutil`

### Possible fix:

This might be possible to fix by moving the Serf setup to before the Raft setup (see https://github.com/hashicorp/consul/blob/master/consul/server.go#L319).

This is because `setupRaft()` ultimately starts `leaderLoop()` on the leader, which does a read of `serfLAN` on the server struct, but `serfLan` isn't initialized until the subsequent `setupSerf` call.

Obviously there are other potential fixes, such as using a mutex.

**Comment by mpuncel** [comment] 2017-05-15 19:44
actually my proposed fix doesn't work because the serf handling code depends on knowing leadership

**Comment by magiconair** [comment] 2017-05-30 14:24
Looking.

**Comment by magiconair** [comment] 2017-05-30 14:28
@mpuncel which version are you testing? master?

**Comment by magiconair** [comment] 2017-05-30 14:35
Found it. 0.7.0.

**Comment by mpuncel** [comment] 2017-05-30 16:26
I believe I also tried it against master to see if the race had been fixed since 0.7.0 and still found this race

**Comment by magiconair** [comment] 2017-06-01 14:42
I can't reproduce this. I checked out https://github.com/square/p2/blob/29ee3ef7/pkg/store/consul/consulutil/consultest.go which is the current master and did this:

```
$ go version
go version go1.8.3 darwin/amd64
$ cd ~/go/src/github.com/square/p2/pkg/store/consul/consulutil
$ go test -race -c
$ while ./consulutil.test ; do true ; done
```

I've also added a test to the v0.7.0 codebase to reproduce this but get the same behavior:

```go
func TestSquareP2(t *testing.T) {
	cfg := DevConfig()
	cfg.BindAddr = "127.0.0.1"
	cfg.Bootstrap = true
	cfg.DisableCoordinates = true
	cfg.NodeName = "testnode"
	cfg.Ports = PortConfig{
		DNS:     10000,
		HTTP:    10001,
		RPC:     10002,
		SerfLan: 10003,
		SerfWan: 10004,
		Server:  10005,
	}
	cfg.ConsulConfig = consul.DefaultConfig()
	cfg.ConsulConfig.RaftConfig.LeaderLeaseTimeout = 10 * time.Millisecond
	cfg.ConsulConfig.RaftConfig.HeartbeatTimeout = 10 * time.Millisecond
	cfg.ConsulConfig.RaftConfig.ElectionTimeout = 20 * time.Millisecond

	a, err := Create(cfg, os.Stdout)
	if err != nil {
		t.Fatal("creating Consul agent:", err)
	}
	a.Shutdown()
}
```

**Comment by magiconair** [comment] 2017-06-01 15:08
ok, can repro it now. `watch_test.go` had the racy tests disabled.

**Comment by magiconair** [comment] 2017-06-01 15:51
This code reproduces it quite reliably on v0.7.0

```go
package agent

import (
	"fmt"
	"os"
	"testing"
	"time"

	"github.com/hashicorp/consul/consul"
)

func TestSquareP2(t *testing.T) {
	for i := 0; i < 10; i++ {
		basePort := 10000 + 10*i
		t.Run(fmt.Sprintf("sever %d", i), func(t *testing.T) {
			t.Parallel()
			cfg := DevConfig()
			cfg.BindAddr = "127.0.0.1"
			cfg.Bootstrap = true
			cfg.DisableCoordinates = true
			cfg.NodeName = "testnode"
			cfg.Ports = PortConfig{
				DNS:     basePort,
				HTTP:    basePort + 1,
				RPC:     basePort + 2,
				SerfLan: basePort + 3,
				SerfWan: basePort + 4,
				Server:  basePort + 5,
			}
			cfg.ConsulConfig = consul.DefaultConfig()
			cfg.ConsulConfig.RaftConfig.LeaderLeaseTimeout = 10 * time.Millisecond
			cfg.ConsulConfig.RaftConfig.HeartbeatTimeout = 10 * time.Millisecond
			cfg.ConsulConfig.RaftConfig.ElectionTimeout = 20 * time.Millisecond

			a, err := Create(cfg, os.Stdout)
			if err != nil {
				t.Fatal("creating Consul agent:", err)
			}
			defer a.Shutdown()

			t.Log("started consul server", basePort)
			time.Sleep(time.Second)
			t.Log("stopping", basePort)
		})
	}
}
```

```
cd command/agent
go test -race -c
while ./agent.test -test.run SquareP2 ; do true ; done
```

**Comment by magiconair** [comment] 2017-06-01 15:52
key seems to be to start multiple agents quickly to trigger this. On master I have a different data race in a lib which I need to fix first.

**Comment by magiconair** [comment] 2017-06-01 15:52
```
==================
WARNING: DATA RACE
Read at 0x0000067aeeb0 by goroutine 22:
  github.com/hashicorp/consul/vendor/github.com/shirou/gopsutil/host.BootTime()
      /Users/frank/go/src/github.com/hashicorp/consul/vendor/github.com/shirou/gopsutil/host/host_darwin.go:69 +0x41
  github.com/hashicorp/consul/vendor/github.com/shirou/gopsutil/host.Info()
      /Users/frank/go/src/github.com/hashicorp/consul/vendor/github.com/shirou/gopsutil/host/host_darwin.go:49 +0x24c
  github.com/hashicorp/consul/command/agent.(*Agent).makeNodeID()
      /Users/frank/go/src/github.com/hashicorp/consul/command/agent/agent.go:894 +0x90
  github.com/hashicorp/consul/command/agent.(*Agent).setupNodeID()
      /Users/frank/go/src/github.com/hashicorp/consul/command/agent/agent.go:940 +0x239
  github.com/hashicorp/consul/command/agent.(*Agent).Start()
      /Users/frank/go/src/github.com/hashicorp/consul/command/agent/agent.go:222 +0xd9
  github.com/hashicorp/consul/command/agent.TestSquareP2.func1()
      /Users/frank/go/src/github.com/hashicorp/consul/command/agent/squarep2_test.go:39 +0x4fc
  testing.tRunner()
      /Users/frank/go1.8.3/src/testing/testing.go:657 +0x107

Previous write at 0x0000067aeeb0 by goroutine 16:
  github.com/hashicorp/consul/vendor/github.com/shirou/gopsutil/host.BootTime()
      /Users/frank/go/src/github.com/hashicorp/consul/vendor/github.com/shirou/gopsutil/host/host_darwin.go:82 +0x18d
  github.com/hashicorp/consul/vendor/github.com/shirou/gopsutil/host.Info()
      /Users/frank/go/src/github.com/hashicorp/consul/vendor/github.com/shirou/gopsutil/host/host_darwin.go:49 +0x24c
  github.com/hashicorp/consul/command/agent.(*Agent).makeNodeID()
      /Users/frank/go/src/github.com/hashicorp/consul/command/agent/agent.go:894 +0x90
  github.com/hashicorp/consul/command/agent.(*Agent).setupNodeID()
      /Users/frank/go/src/github.com/hashicorp/consul/command/agent/agent.go:940 +0x239
  github.com/hashicorp/consul/command/agent.(*Agent).Start()
      /Users/frank/go/src/github.com/hashicorp/consul/command/agent/agent.go:222 +0xd9
  github.com/hashicorp/consul/command/agent.TestSquareP2.func1()
      /Users/frank/go/src/github.com/hashicorp/consul/command/agent/squarep2_test.go:39 +0x4fc
  testing.tRunner()
      /Users/frank/go1.8.3/src/testing/testing.go:657 +0x107

Goroutine 22 (running) created at:
  testing.(*T).Run()
      /Users/frank/go1.8.3/src/testing/testing.go:697 +0x543
  github.com/hashicorp/consul/command/agent.TestSquareP2()
      /Users/frank/go/src/github.com/hashicorp/consul/command/agent/squarep2_test.go:47 +0x17d
  testing.tRunner()
      /Users/frank/go1.8.3/src/testing/testing.go:657 +0x107

Goroutine 16 (running) created at:
  testing.(*T).Run()
      /Users/frank/go1.8.3/src/testing/testing.go:697 +0x543
  github.com/hashicorp/consul/command/agent.TestSquareP2()
      /Users/frank/go/src/github.com/hashicorp/consul/command/agent/squarep2_test.go:47 +0x17d
  testing.tRunner()
      /Users/frank/go1.8.3/src/testing/testing.go:657 +0x107
==================
```

**Comment by magiconair** [comment] 2017-06-01 16:18
I've submitted https://github.com/shirou/gopsutil/pull/379 but with this out of the way I cannot repro the consul agent startup data race on master.

**Comment by magiconair** [comment] 2017-06-01 16:19
Using this modified version since `agent.Create` no longer exists:

```go
package agent

import (
	"fmt"
	"testing"
	"time"

	"github.com/hashicorp/consul/consul"
)

func TestSquareP2(t *testing.T) {
	for i := 0; i < 10; i++ {
		basePort := 10000 + 10*i
		t.Run(fmt.Sprintf("sever %d", i), func(t *testing.T) {
			t.Parallel()
			cfg := DevConfig()
			cfg.BindAddr = "127.0.0.1"
			cfg.Bootstrap = true
			cfg.DisableCoordinates = true
			cfg.NodeName = "testnode"
			cfg.Ports = PortConfig{
				DNS:     basePort,
				HTTP:    basePort + 1,
				RPC:     basePort + 2,
				SerfLan: basePort + 3,
				SerfWan: basePort + 4,
				Server:  basePort + 5,
			}
			cfg.ConsulConfig = consul.DefaultConfig()
			cfg.ConsulConfig.RaftConfig.LeaderLeaseTimeout = 10 * time.Millisecond
			cfg.ConsulConfig.RaftConfig.HeartbeatTimeout = 10 * time.Millisecond
			cfg.ConsulConfig.RaftConfig.ElectionTimeout = 20 * time.Millisecond

			a, err := NewAgent(cfg)
			if err != nil {
				t.Fatal("creating Consul agent:", err)
			}
			if err := a.Start(); err != nil {
				t.Fatal("starting consul agent:", err)
			}
			defer a.Shutdown()

			t.Log("started consul server", basePort)
			time.Sleep(time.Second)
			t.Log("stopping", basePort)
		})
	}
}
```

**Comment by magiconair** [comment] 2017-06-02 07:21
I'm going to close this one unless there is more evidence that this is still an issue with master. Please comment if there is and I'll re-open.

**Closed by magiconair** 2017-06-02 07:21 UTC
Labels: bug, theme/internal-cleanup
