### ISSUE TITLE
Retrieve health check definition

### ISSUE THREAD

**Issue by DanielCharczynski** [hashicorp/consul#7330] opened 2020-02-21 07:20 UTC
#### Feature Description

There is no possibility to get health definition.

https://discuss.hashicorp.com/t/is-there-a-way-to-retrieve-a-health-check-definition-with-the-api/6107

#### Use Case(s)

We would like to use consul as a single point of truth about services.
We save there health check definition.
Unfortunately there is no possibility to retrievie this definition.

There is possibillity to get service definition but not health check definition. I do not understand why....

Please add such feature. It should be quite easy but usefull.

**Comment by pierresouchay** [comment] 2020-02-27 15:16
I think it is a duplicate of #1680

There are security reasons why you don't want to do that (for instance, you might have a password in your checks settings).
In our infrastructure, we handle this using the "notes" attributes which is properly retrieved, thus allowing us to get this information.

For an HTTP check, you can put the same value as in your HTTP field (but hiding the possible user/passwords), so it is available from your UIs as information, but not for an attacker

**Comment by jsosulska** [comment] 2020-06-15 20:34
Hello,

As there has been no movement on this topic, and it is a duplicate as @pierresouchay pointed out, I'll be closing this issue. Please follow #1680 and 👍 if this is something you are looking for.

Happy Coding!

**Closed by jsosulska** 2020-06-15 20:34 UTC
Labels: theme/health-checks, type/enhancement
