### ISSUE TITLE
Upgrading Consul from v1.5.3- to v1.6.0+ could lead to resetting of values in KVStore

### ISSUE THREAD

**Issue by a-zagaevskiy** [hashicorp/consul#9329] opened 2020-12-04 18:41 UTC
#### Overview of the Issue

We have a Consul cluster that functions on v1.5.3 or below. Its KVStore has been changing a lot, so we have some values with ModifyIndex != CreateIndex. But right after upgrading the cluster to any version since v1.6.0, some values in KVStore are changed to the values that were at the moment when they were just created (as if all or some of their changes have been lost).

#### Reproduction Steps

Currently, I'm thinking on a test so as not to disclose lots of details of the project where we use Consul. But the fact is that we have a Consul's snapshot on a drive which was made by Consul v1.5.2, and it helps to restore a cluster without missing any data in KVStore for released versions v1.5.2 and v1.5.3. But for v1.6.0 and above, restoring from the snapshot leads to data losses.

Moreover, I've already found the breaking change in the repository between v1.5.3 and v1.60 that causes the bug:
https://github.com/hashicorp/consul/commit/b839f521958df4c7d48a738a0ae8de1ba6122ac8
Reverting this commit fixes the bug. But I hope, you could figure out how to preserve an optimisation made by it and how to fix the bug with restoring from the snapshot made before the optimisation.

Previously, I made a fix for it in #7826 (PR: #7832). But it wasn't about restoring from a snapshot. 

### Consul info for both Client and Server

v1.5.3- to v1.6.0+

**Comment by a-zagaevskiy** [comment] 2020-12-04 20:47
**Reproduction Steps**

For simplicity, we'll run a cluster on a single server without clients. Both binaries (v1.5.3 and v1.6.0) are placed in one directory and renamed to ./consul_1.5.3 and ./consul_1.6.0 correspondingly.

Configuration (./config/main.conf): 
```
{
    "server": true,
    "bootstrap_expect": 1
}
```

### Step 1. Create a snapshot with Consul v1.5.3

Run an agent in the first terminal with a following command:
```
./consul_1.5.3 agent -config-dir=./config -data-dir=./data
```
Create and modify KVStore in the second terminal with following commands:
```
curl -XPUT http://localhost:8500/v1/txn -d '[{"KV": {"Verb": "set", "Key": "a", "Value": "MQ=="}}]'
curl -XPUT http://localhost:8500/v1/txn -d '[{"KV": {"Verb": "cas", "Key": "a", "Value": "MQ==", "Index": <INDEX_1>}}]'
curl -XPUT http://localhost:8500/v1/txn -d '[{"KV": {"Verb": "cas", "Key": "a", "Value": "b251", "Index": <INDEX_2>}}]'
```
NOTES: 
* second command DOES NOT change the value ("MQ==" stands for "1"), but you have to use real ModifyIndex instead of <INDEX_1> 
* third command DO change the value ("b251" stands for "one"), but here you also have to use real ModifyIndex, returned from the previous change, insead of <INDEX_2>

That's all the needed preparations.

### Check A. Read the value when the cluster is running by Consul v1.5.3:

Run an agent in the first terminal:
```
./consul_1.5.3 agent -config-dir=./config -data-dir=./data
```
Print the value for the key "a" in the second terminal (or find it via web-UI):
```
$ curl http://localhost:8500/v1/kv/b
```
_The result is always "b251" (= "one")._

### Check B. Read the value when the cluster is running by Consul v1.6.0:

Run an agent in the first terminal:
```
./consul_1.6.0 agent -config-dir=./config -data-dir=./data
```
Print the value for the key "a" in the second terminal (or find it via web-UI):
```
$ curl http://localhost:8500/v1/kv/b
```
_The result is always "MQ==" (= "1")._

### Summary

Checks A and B can be carried out many times one after another in any order and their results are permanent. It means that the same snapshot, that is saved in the data directory, is restored correctly with Consul v1.5.3 and isn't with Consul v1.6.0 and above.

**Comment by a-zagaevskiy** [comment] 2020-12-04 21:25
To add, despite the fact that downgrade is not usually supported, a snapshot created on v1.6.0+ isn't restored correctly in the similar way on v1.5.3-, e.g. it "skips" some logs and restores one of the previous values, when there are CAS-writes into KVStore which don't actually change a value.

**Comment by ChipV223** [comment] 2021-04-29 15:42
Hi @a-zagaevskiy 

I just tried running through your repro using both v1.9.5 and v1.10-beta1 and when I finish the upgrade to v1.10-beta1, the value for a remain the same:

```
vagrant@a7:/etc/consul.d$ curl http://localhost:8500/v1/kv/a | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   110  100   110    0     0  10692      0 --:--:-- --:--:-- --:--:-- 11000
[
  {
    "LockIndex": 0,
    "Key": "a",
    "Flags": 0,
    "Value": "b251",
    "Namespace": "default",
    "CreateIndex": 216,
    "ModifyIndex": 222
  }
]
vagrant@a7:/etc/consul.d$ consul kv get a
onu
vagrant@a7:/etc/consul.d$ consul leave
Graceful leave complete
vagrant@a7:/etc/consul.d$
vagrant@a7:/etc/consul.d$
vagrant@a7:/etc/consul.d$ consul kv get a
onu
vagrant@a7:/etc/consul.d$ curl http://localhost:8500/v1/kv/a | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   110  100   110    0     0   7881      0 --:--:-- --:--:-- --:--:--  8461
[
  {
    "LockIndex": 0,
    "Key": "a",
    "Flags": 0,
    "Value": "b251",
    "Namespace": "default",
    "CreateIndex": 216,
    "ModifyIndex": 222
  }
]
```

Closing this as the behavior seems to have been fixed in later versions of Consul, but do reach out if you are able to reproduce this now!

**Closed by ChipV223** 2021-04-29 15:42 UTC
Labels: theme/internals, type/bug

**Comment by a-zagaevskiy** [comment] 2021-04-29 18:47
Hi @ChipV223 

Did you try to reproduce the upgrade from the version equal to or less than v1.5.3 ? The issue is sensitive to the start version. If your cluster from the beginning is run by Consul v1.6.0 or higher, everything will be OK.

But thanks for the reply, I'll recheck the issue during the week.

**Comment by ChipV223** [comment] 2021-04-30 01:50
Hi @a-zagaevskiy !

I did not use v1.5.3 in my repro since v1.5.3 is a rather old version and my think is that if it still exists, the version _shouldn't_ matter

**Comment by a-zagaevskiy** [comment] 2021-04-30 09:41
The version does matter. And I found the commit that made the breaking changes: https://github.com/hashicorp/consul/commit/b839f521958df4c7d48a738a0ae8de1ba6122ac8
Reverting the commit helps to solve the issue with data lost after an upgrade.

But as you mentioned, v1.5.3 is truly an old version. There is a workaround: you need to take a snapshot of the cluster that you should roll out right after the upgrade from v1.5.3 (or less).
