### ISSUE TITLE
Consul node enters endless election loop after restart during network outage.

### ISSUE THREAD

**Issue by s-matyukevich** [hashicorp/consul#7750] opened 2020-05-01 13:43 UTC
### Overview of the Issue

If all the conditions mentioned in the title are met, even after the network connectivity is restored the node still can't enter the cluster and stuck in an endless election loop. This looks very similar to [this](https://github.com/hashicorp/consul/issues/4084) issue.

#### Reproduction Steps
This issue happens once in our kubernetes cluster, but here I'll describe how to reproduce it using docker.

1. Create a new docker network
```
docker network create consul
```
2. Run 2 consul nodes
```

docker run -d --rm \
        --name consul1 \
        --net consul \
        consul \
        consul agent  \
        -node=consul1 \
        -bootstrap-expect=3 \
        -retry-join=consul1 \
        -retry-join=consul2 \
        -retry-join=consul3 \
        -data-dir=/tmp/consul-data \
        -server

docker run -d --rm \
        --name consul2 \
        --net consul \
        consul \
        consul agent  \
        -node=consul2 \
        -bootstrap-expect=3 \
        -retry-join=consul1 \
        -retry-join=consul2 \
        -retry-join=consul3 \
        -data-dir=/tmp/consul-data \
        -server
```
3. Run the 3-rd node and make sure it list itself in the `-retry-join` parameter
```
docker run -d --rm \
        --name consul3 \
        --net consul \
        consul \
        consul agent  \
        -node=consul3 \
        -bootstrap-expect=3 \
        -retry-join=consul1 \
        -retry-join=consul2 \
        -retry-join=127.0.0.1 \
        -data-dir=/tmp/consul-data \
        -server
```
Ofcouse, in real world nobody is going to specify `127.0.0.1` in the `-retry-join` parameter but a lot of people would use `consul3` DNS name here. I used `127.0.0.1` in this example because it makes it easier to reproduce network outage on startup and still made it possible for the node to connect to itself on startup.

4. Wait until all nodes successfully joined the cluster.

5. Restart `consul3` node and simulate network outage on startup.
```
docker restart consul3
docker network disconnect consul consul3
```
6. At this point of time, the `consul3` node should enter the candidate state. It will constantly try to vote for itself. You should see the following logs over and over again.
```
    2020-05-01T13:03:05.881Z [INFO]  agent.server.raft: entering candidate state: node="Node at 127.0.0.1:8300 [Candidate]" term=10
    2020-05-01T13:03:05.886Z [WARN]  agent.server.raft: unable to get address for sever, using fallback address: id=42e2f99c-d0f0-c2ed-518f-1f33a436b240 fallback=172.19.0.3:8300 error="Could not find address for server id 42e2f99c-d0f0-c2ed-518f-1f33a436b240"
    2020-05-01T13:03:05.886Z [ERROR] agent.server.raft: failed to make requestVote RPC: target="{Voter 42e2f99c-d0f0-c2ed-518f-1f33a436b240 172.19.0.3:8300}" error="dial tcp <nil>->172.19.0.3:8300: connect: network is unreachable"
    2020-05-01T13:03:05.886Z [WARN]  agent.server.raft: unable to get address for sever, using fallback address: id=1b6de148-a20a-f58c-7a15-d62d4daf2458 fallback=172.19.0.2:8300 error="Could not find address for server id 1b6de148-a20a-f58c-7a15-d62d4daf2458"
    2020-05-01T13:03:05.887Z [ERROR] agent.server.raft: failed to make requestVote RPC: target="{Voter 1b6de148-a20a-f58c-7a15-d62d4daf2458 172.19.0.2:8300}" error="dial tcp <nil>->172.19.0.2:8300: connect: network is unreachable"
    2020-05-01T13:03:09.924Z [ERROR] agent: Coordinate update error: error="No cluster leader"
    2020-05-01T13:03:11.663Z [ERROR] agent.anti_entropy: failed to sync remote state: error="No cluster leader"
    2020-05-01T13:03:14.755Z [WARN]  agent.server.raft: Election timeout reached, restarting election
```

7. Now restore network connectivity
```
docker network connect consul consul3
```
Now the node is able to talk to the remaining 2 nodes in the cluster, but still it keeps voting for itself. You  should see the following logs
```
    2020-05-01T13:18:35.510Z [WARN]  agent.server.raft: Election timeout reached, restarting election
    2020-05-01T13:18:35.510Z [INFO]  agent.server.raft: entering candidate state: node="Node at 127.0.0.1:8300 [Candidate]" term=132
    2020-05-01T13:18:35.514Z [WARN]  agent.server.raft: unable to get address for sever, using fallback address: id=42e2f99c-d0f0-c2ed-518f-1f33a436b240 fallback=172.19.0.3:8300 error="Could not find address for server id 42e2f99c-d0f0-c2ed-518f-1f33a436b240"
    2020-05-01T13:18:35.514Z [WARN]  agent.server.raft: unable to get address for sever, using fallback address: id=1b6de148-a20a-f58c-7a15-d62d4daf2458 fallback=172.19.0.2:8300 error="Could not find address for server id 1b6de148-a20a-f58c-7a15-d62d4daf2458"
    2020-05-01T13:18:44.450Z [WARN]  agent.server.raft: Election timeout reached, restarting election
    2020-05-01T13:18:44.451Z [INFO]  agent.server.raft: entering candidate state: node="Node at 127.0.0.1:8300 [Candidate]" term=133
    2020-05-01T13:18:44.454Z [WARN]  agent.server.raft: unable to get address for sever, using fallback address: id=42e2f99c-d0f0-c2ed-518f-1f33a436b240 fallback=172.19.0.3:8300 error="Could not find address for server id 42e2f99c-d0f0-c2ed-518f-1f33a436b240"
    2020-05-01T13:18:44.454Z [WARN]  agent.server.raft: unable to get address for sever, using fallback address: id=1b6de148-a20a-f58c-7a15-d62d4daf2458 fallback=172.19.0.2:8300 error="Could not find address for server id 1b6de148-a20a-f58c-7a15-d62d4daf2458"
    2020-05-01T13:18:46.803Z [ERROR] agent: Coordinate update error: error="No cluster leader"
```

The remaining 2 nodes keep rejecting vote requests because they already have a leader. The following logs can be observed on both `consul1` and `consul2` nodes

```
    2020-05-01T13:31:57.624Z [WARN]  agent.server.raft: rejecting vote request since we have a leader: from=127.0.0.1:8300 leader=172.19.0.3:8300
    2020-05-01T13:32:04.116Z [WARN]  agent.server.raft: rejecting vote request since we have a leader: from=127.0.0.1:8300 leader=172.19.0.3:8300
    2020-05-01T13:32:09.172Z [WARN]  agent.server.raft: rejecting vote request since we have a leader: from=127.0.0.1:8300 leader=172.19.0.3:8300
    2020-05-01T13:32:17.148Z [WARN]  agent.server.raft: rejecting vote request since we have a leader: from=127.0.0.1:8300 leader=172.19.0.3:8300
    2020-05-01T13:32:23.837Z [WARN]  agent.server.raft: rejecting vote request since we have a leader: from=127.0.0.1:8300 leader=172.19.0.3:8300
```

Also, `consul3` node can't sync its state, because he doesn't have a leader
```
    2020-05-01T13:18:46.803Z [ERROR] agent: Coordinate update error: error="No cluster leader"
```

And the leader doesn't send heartbeat message to the `consul3` node, because this node isn't registered on the leader.

**Comment by s-matyukevich** [comment] 2020-05-01 17:52
I used `1.7.2` version of the consul docker image.

**Comment by moreinhardt** [comment] 2020-11-10 22:48
I am experiencing this on a fresh helm install of consul with default 3 server replicas within kubernetes. It installs and starts up fine. But as soon as I kill one pod (only tried with followers so far, haven't killed the leader) the new pod that's re-created cannot join the existing cluster.

I tried setting raft-protocol 3 explicitly as noted [here](https://github.com/hashicorp/raft/pull/413#issuecomment-669053456) but that didn't change things. It was default anyway if I understand correctly.

related `values.yaml`:
```
global:
  image: "consul:1.8.4"
  imageK8S: "hashicorp/consul-k8s:0.19.0"
  enabled: false

server:
  enabled: true
  hostNetwork: true
  extraConfig: |    
    {           
      "raft_protocol": 3
    }
```

The log of the restarting pod:
```
2020-11-10T22:35:45.676501901Z     2020-11-10T22:35:45.676Z [ERROR] agent.http: Request error: method=PUT url=/v1/catalog/register from=10.110.0.11:50040 error="No cluster leader"
2020-11-10T22:35:46.797401611Z     2020-11-10T22:35:46.797Z [ERROR] agent.anti_entropy: failed to sync remote state: error="No cluster leader"
2020-11-10T22:35:48.712217276Z     2020-11-10T22:35:48.632Z [WARN]  agent.server.raft: Election timeout reached, restarting election
2020-11-10T22:35:48.712252747Z     2020-11-10T22:35:48.712Z [INFO]  agent.server.raft: entering candidate state: node="Node at 10.110.0.13:8300 [Candidate]" term=129
2020-11-10T22:35:48.718036683Z     2020-11-10T22:35:48.717Z [WARN]  agent.server.raft: unable to get address for sever, using fallback address: id=ae2341c0-95da-6846-6f84-04ca557beb44 fallback=10.110.0.15:8300 error="Could not find address for server id ae2341c0-95da-6846-6f84-04ca557beb44"
2020-11-10T22:35:48.718125804Z     2020-11-10T22:35:48.717Z [WARN]  agent.server.raft: unable to get address for sever, using fallback address: id=f0c339ad-f12a-4b8c-e14c-eec985b052a0 fallback=10.110.0.11:8300 error="Could not find address for server id f0c339ad-f12a-4b8c-e14c-eec985b052a0"
2020-11-10T22:35:52.426502197Z     2020-11-10T22:35:52.426Z [ERROR] agent: Coordinate update error: error="No cluster leader"
```

Note that the pod IP changed from 10.110.0.21 to 10.110.0.13 because the new pod was assigned to a different node - could that be related? I guess a pod being destroyed and started should be a normal thing in a kubernetes deployment. So why is this not working?

I would appreciate any help :-)

**Comment by moreinhardt** [comment] 2020-11-12 17:32
Same thing happens with `1.9.0-beta3` although that should have the upstream fix mentioned above included...

**Comment by jsosulska** [comment] 2020-11-24 21:28
Hi @moreinhardt !

Thanks for posting this very detailed, but after talking with some members of the team, there's still some additional context needed.

Can you please use gist.github.com to upload the server logs during these events? This definitely requires more information for investigation, but we're interested at looking at this more.

**Comment by dnephin** [comment] 2020-11-24 22:56
I was able to reproduce the problem using the steps in this issue description. The logs are attached to this comment.
[consul3.log](https://github.com/hashicorp/consul/files/5593221/consul3.log)
[consul2.log](https://github.com/hashicorp/consul/files/5593222/consul2.log)
[consul1.log](https://github.com/hashicorp/consul/files/5593223/consul1.log)

**Comment by dnephin** [comment] 2020-11-24 23:32
I believe I understand the problem now. Looking at [`serf.handleRejoin`](https://github.com/hashicorp/serf/blob/master/serf/serf.go#L1752-L1772). It only attempts to join the LAN gossip pool once at start up. Since the network was down at that time, it failed to rejoin the pool and gave up.

```
    2020-11-24T22:50:13.073Z [INFO]  agent.server.raft: entering follower state: follower="Node at 172.18.0.4:8300 [Follower]" leader=
    2020-11-24T22:50:13.097Z [INFO]  agent.server.serf.wan: serf: EventMemberJoin: consul3.dc1 172.18.0.4
    2020-11-24T22:50:13.098Z [INFO]  agent.server.serf.wan: serf: Attempting re-join to previously known node: consul1.dc1: 172.18.0.2:8302
    2020-11-24T22:50:13.098Z [INFO]  agent.server.serf.wan: serf: Attempting re-join to previously known node: consul2.dc1: 172.18.0.3:8302
    2020-11-24T22:50:13.098Z [WARN]  agent.server.serf.wan: serf: Failed to re-join any previously known node
    2020-11-24T22:50:13.106Z [INFO]  agent.server.serf.lan: serf: EventMemberJoin: consul3 172.18.0.4
    2020-11-24T22:50:13.106Z [INFO]  agent.server.serf.lan: serf: Attempting re-join to previously known node: consul1: 172.18.0.2:8301
    2020-11-24T22:50:13.106Z [INFO]  agent.server: Adding LAN server: server="consul3 (Addr: tcp/172.18.0.4:8300) (DC: dc1)"
    2020-11-24T22:50:13.106Z [INFO]  agent.server: Raft data found, disabling bootstrap mode
    2020-11-24T22:50:13.106Z [INFO]  agent.server: Handled event for server in area: event=member-join server=consul3.dc1 area=wan
    2020-11-24T22:50:13.106Z [INFO]  agent.server.serf.lan: serf: Attempting re-join to previously known node: consul2: 172.18.0.3:8301
    2020-11-24T22:50:13.109Z [INFO]  agent: Retry join is supported for the following discovery methods: cluster=LAN discovery_methods="aliyun aws azure digitalocean gce k8s linode mdns os packet scaleway softlayer tencentcloud triton vsphere"
    2020-11-24T22:50:13.109Z [INFO]  agent: Joining cluster...: cluster=LAN
    2020-11-24T22:50:13.109Z [INFO]  agent: (LAN) joining: lan_addresses=[consul1, consul2, 127.0.0.1]
    2020-11-24T22:50:20.530Z [ERROR] agent.anti_entropy: failed to sync remote state: error="No cluster leader"
    2020-11-24T22:50:21.294Z [WARN]  agent.server.raft: heartbeat timeout reached, starting election: last-leader=
    2020-11-24T22:50:21.294Z [INFO]  agent.server.raft: entering candidate state: node="Node at 172.18.0.4:8300 [Candidate]" term=3
    2020-11-24T22:50:21.422Z [WARN]  agent.server.raft: unable to get address for sever, using fallback address: id=575bbaa9-7a22-886e-c431-bb6d762ebafc fallback=172.18.0.3:8300 error="Could not find address for server id 575bbaa9-7a22-886e-c431-bb6d762ebafc"
    2020-11-24T22:50:21.422Z [WARN]  agent.server.raft: unable to get address for sever, using fallback address: id=19067efc-dfc8-c8b9-dd27-6fe28fb96097 fallback=172.18.0.2:8300 error="Could not find address for server id 19067efc-dfc8-c8b9-dd27-6fe28fb96097"
    2020-11-24T22:50:21.422Z [ERROR] agent.server.raft: failed to make requestVote RPC: target="{Voter 19067efc-dfc8-c8b9-dd27-6fe28fb96097 172.18.0.2:8300}" error="dial tcp <nil>->172.18.0.2:8300: connect: network is unreachable"
    2020-11-24T22:50:21.422Z [ERROR] agent.server.raft: failed to make requestVote RPC: target="{Voter 575bbaa9-7a22-886e-c431-bb6d762ebafc 172.18.0.3:8300}" error="dial tcp <nil>->172.18.0.3:8300: connect: network is unreachable"
    2020-11-24T22:50:23.111Z [WARN]  agent.server.memberlist.lan: memberlist: Failed to resolve consul1: lookup consul1 on 127.0.0.11:53: read udp 127.0.0.1:52217->127.0.0.11:53: i/o timeout
```
The raft heartbeat timed out, so it started its own leader election. That seems correct.

After the network is reconnected I checked the member view from `consul3` using `consul members` and it only had itself listed. The other two nodes showed `consul3` as `left`. It seems that serf never reconnected at that point. I guess because there was no new event to inform raft of the change in state, it continued to attempt to elect a leader, even though it would have been able to rejoin at this point.

The logs may be a bit misleading, because it is raft complaining. Raft uses the addresses it gets from serf to find the other servers. In the logs we see `consul3` failing to get the addresses (because serf doesn't have them), but it is using a fallback address which was still correct, which is why the other nodes keep receiving leader vote requests.

Running `consul join consul1` from the `consul3` node resolves the problem. Once `consul3` re-joins the LAN gossip pool it logs:

```
    2020-11-24T23:08:36.815Z [INFO]  agent: (LAN) joining: lan_addresses=[consul1]
    2020-11-24T23:08:36.820Z [INFO]  agent.server.serf.lan: serf: EventMemberJoin: consul1 172.18.0.2
    2020-11-24T23:08:36.820Z [INFO]  agent.server.serf.lan: serf: EventMemberJoin: consul2 172.18.0.3
    2020-11-24T23:08:36.820Z [INFO]  agent: (LAN) joined: number_of_nodes=1
    2020-11-24T23:08:36.820Z [INFO]  agent.server: Adding LAN server: server="consul1 (Addr: tcp/172.18.0.2:8300) (DC: dc1)"
    2020-11-24T23:08:36.820Z [INFO]  agent.server: Adding LAN server: server="consul2 (Addr: tcp/172.18.0.3:8300) (DC: dc1)"
    2020-11-24T23:08:36.822Z [INFO]  agent.server.serf.wan: serf: EventMemberJoin: consul1.dc1 172.18.0.2
    2020-11-24T23:08:36.822Z [INFO]  agent.server.serf.wan: serf: EventMemberJoin: consul2.dc1 172.18.0.3
    2020-11-24T23:08:36.822Z [INFO]  agent.server: Handled event for server in area: event=member-join server=consul1.dc1 area=wan
    2020-11-24T23:08:36.822Z [INFO]  agent.server: Handled event for server in area: event=member-join server=consul2.dc1 area=wan
    2020-11-24T23:08:39.184Z [WARN]  agent.server.raft: Election timeout reached, restarting election
    2020-11-24T23:08:39.185Z [INFO]  agent.server.raft: entering candidate state: node="Node at 172.18.0.4:8300 [Candidate]" term=148
    2020-11-24T23:08:41.069Z [ERROR] agent: Coordinate update error: error="No cluster leader"
    2020-11-24T23:08:44.624Z [WARN]  agent.server.raft: failed to get previous log: previous-index=132 last-index=17 error="log not found"
    2020-11-24T23:08:44.624Z [INFO]  agent.server.raft: entering follower state: follower="Node at 172.18.0.4:8300 [Follower]" leader=172.18.0.3:8300
    2020-11-24T23:08:44.728Z [INFO]  agent.server: New leader elected: payload=consul2
```

As far as I can tell, raft on `consul3` required some event to make it understand that the other nodes are available once again. I'm not sure what that is supposed to be. Clearly serf can signal it once it rejoins, but I'm not sure if it would be appropriate for `retry-join` to keep retrying, or if it should be some other event.

**Comment by dnephin** [comment] 2020-11-25 03:13
I was looking at the wrong rejoin earlier. That function is serf is attempting to reconnect to the existing nodes. The `retry-join` handling is https://github.com/hashicorp/consul/blob/master/agent/retry_join.go. It does retry multiple times. 

I think the problem may be that `-retry-join=127.0.0.1` stops the retry attempts because it sees connecting to itself as a successful join.

**Comment by rboyer** [comment] 2020-11-25 15:21
Related https://github.com/hashicorp/consul/issues/2868

**Comment by dnephin** [comment] 2020-11-25 17:03
Ah yes, #2868 does look like the right solution! I'm going to close this issue since we have one that describes the necessary fix.

Thank you again for reporting the problem and providing a way to reproduce it!

**Closed by dnephin** 2020-11-25 17:03 UTC
Labels: needs-investigation, theme/operator-usability, type/enhancement
