### ISSUE TITLE
"acl_datacenter" configuration is case sensitive, if you set it to uppder case, the ACL won't work

### ISSUE THREAD

**Issue by WUMUXIAN** [hashicorp/consul#2095] opened 2016-06-06 06:43 UTC
### `consul version` for both Client and Server
Client: `Consul v0.6.4`
Server: `Consul v0.6.4`

### `consul info` for both Client and Server
Client:
```
agent:
	check_monitors = 1
	check_ttls = 0
	checks = 2
	services = 2
build:
	prerelease =
	revision = 26a0ef8c
	version = 0.6.4
consul:
	known_servers = 3
	server = false
runtime:
	arch = amd64
	cpu_count = 1
	goroutines = 41
	max_procs = 1
	os = linux
	version = go1.6
serf_lan:
	encrypted = true
	event_queue = 0
	event_time = 300
	failed = 0
	intent_queue = 0
	left = 0
	member_time = 129
	members = 8
	query_queue = 0
	query_time = 11
```

Server:
```
agent:
	check_monitors = 3
	check_ttls = 0
	checks = 4
	services = 5
build:
	prerelease =
	revision = 26a0ef8c
	version = 0.6.4
consul:
	bootstrap = false
	known_datacenters = 1
	leader = false
	server = true
raft:
	applied_index = 1005718
	commit_index = 1005718
	fsm_pending = 0
	last_contact = 43.997383ms
	last_log_index = 1005718
	last_log_term = 606
	last_snapshot_index = 1001689
	last_snapshot_term = 369
	num_peers = 2
	state = Follower
	term = 606
runtime:
	arch = amd64
	cpu_count = 1
	goroutines = 73
	max_procs = 1
	os = linux
	version = go1.6
serf_lan:
	encrypted = true
	event_queue = 0
	event_time = 300
	failed = 0
	intent_queue = 0
	left = 0
	member_time = 129
	members = 8
	query_queue = 0
	query_time = 11
serf_wan:
	encrypted = true
	event_queue = 0
	event_time = 1
	failed = 0
	intent_queue = 0
	left = 0
	member_time = 1
	members = 1
	query_queue = 0
	query_time = 1
```

### Operating system and Environment details
AWS Linux AMI (Based on Centos 6)

### Description of the Issue (and unexpected/desired result)
If you set the "acl_datacenter" configuration to an upper case string, the ACL function will not work. An error "Unexpected response code: 500 (No path to datacenter)" will be through if you try to update ACL.

### Reproduction steps
1. Set acl_datacenter to an uppder case string, such as "Test-DataCenter"
2. Start consul servers and clients.
3. Try to update acl now: 
"consul-cli acl-update --token={{ consul_acl_master_token }} --name="Secure Token" --rule='key:secure:write' --rule='service::write' {{ consul_acl_secure_token }}"
4. The operation fails with error "Unexpected response code: 500 (No path to datacenter)"

### Verifications
If I set the acl_datacenter to a lower case string, such as "test-datacenter", everything works fine.

**Comment by slackpad** [comment] 2016-06-06 14:44
Hi @WUMUXIAN thanks for the bug report! I'm going to close this as a duplicate of https://github.com/hashicorp/consul/issues/1778 - they have the same root cause.

**Closed by slackpad** 2016-06-06 14:44 UTC
