### ISSUE TITLE
consul 1.19.0 breaks all tags

### ISSUE THREAD

**Issue by maxadamo** [hashicorp/consul#21336] opened 2024-06-13 21:11 UTC
#### Overview of the Issue

after upgrading to version 1.19 I have lost the ability to use tags, because it started behaving in an odd way. 

For instance, my consul domain is: `service.ha.mydomain.net`

My consul server is: `consul.service.ha.mydomain.net`

Whichever string I add to the left, it's being resolved successfully. 

For instance `blahblah.consul.service.ha.mydomain.net` works and it resolves to the same IPs of `consul.service.ha.mydomain.net`

`heyhey.consul.service.ha.mydomain.net` works as well. 

I had tags to specify primaries and standby nodes, and all the tags where broken, because primary was associated to all the hosts in the pool. 

for instance, I was creating `primary.postgres.service.ha.domain.net` and `standby.postgres.ha.geant.net`, but both records where resolving either as standby and primary. 

this is what happened: 

```bash
dig tags.are.definitely.borked.consul.service.ha.geant.net @127.0.0.1 -p8600 -t SRV +short

1 1 8300 test-consul02.node.test-geant.ha.geant.net.
1 1 8300 test-consul03.node.test-geant.ha.geant.net.
1 1 8300 test-consul01.node.test-geant.ha.geant.net.
```

```bash
dig consul.service.ha.geant.net @127.0.0.1 -p8600 -t SRV +short

1 1 8300 test-consul02.node.test-geant.ha.geant.net.
1 1 8300 test-consul03.node.test-geant.ha.geant.net.
1 1 8300 test-consul01.node.test-geant.ha.geant.net.
```

I downgraded to 1.18.2, and it started working again.  

---

#### Reproduction Steps

upgrade from 1.18.2 to 1.19.0

### Consul info for both Client and Server

<details>
  <summary>Server info</summary>

```
agent:
	check_monitors = 0
	check_ttls = 0
	checks = 0
	services = 0
build:
	prerelease =
	revision = bf0166d8
	version = 1.19.0
	version_metadata =
consul:
	acl = enabled
	bootstrap = false
	known_datacenters = 1
	leader = true
	leader_addr = 192.168.1.10:8300
	server = true
raft:
	applied_index = 10113186
	commit_index = 10113186
	fsm_pending = 0
	last_contact = 0
	last_log_index = 10113186
	last_log_term = 24764
	last_snapshot_index = 10110459
	last_snapshot_term = 24717
	latest_configuration = [{Suffrage:Voter ID:38fe16dc-14d0-50d1-0f74-36b51df475e8 Address:192.168.1.10:8300} {Suffrage:Voter ID:12272fb0-9c55-734a-13a8-fcab4eafe224 Address:192.168.1.11:8300} {Suffrage:Voter ID:7cb1fde9-07d0-be57-8964-f62c849814e7 Address:192.168.1.12:8300}]
	latest_configuration_index = 0
	num_peers = 2
	protocol_version = 3
	protocol_version_max = 3
	protocol_version_min = 0
	snapshot_version_max = 1
	snapshot_version_min = 0
	state = Leader
	term = 24764
runtime:
	arch = amd64
	cpu_count = 2
	goroutines = 232
	max_procs = 2
	os = linux
	version = go1.22.4
serf_lan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 795
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 13358
	members = 3
	query_queue = 0
	query_time = 1
serf_wan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 1
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 6786
	members = 3
	query_queue = 0
	query_time = 1```
```

</details>

<details>
  <summary>Server JSON</summary>

```json
{
    "acl": {
        "default_policy": "allow",
        "down_policy": "extend-cache",
        "enabled": true,
        "tokens": {
            "master": "xxxxxxxxxxxx"
        }
    },
    "addresses": {
        "dns": "0.0.0.0",
        "http": "0.0.0.0",
        "https": "0.0.0.0"
    },
    "advertise_addr": "192.168.1.10",
    "alt_domain": "ha.mydomain.org",
    "bind_addr": "192.168.1.10",
    "ca_file": "/etc/consul_certs/COMODO_OV.crt",
    "cert_file": "/etc/consul_certs/test-consul.mydomain.org_fullchain.crt",
    "client_addr": "192.168.1.10",
    "data_dir": "/var/consul",
    "datacenter": "test-mydomain",
    "dns_config": {
        "allow_stale": true,
        "node_ttl": "5s",
        "service_ttl": {
            "*": "5s"
        }
    },
    "domain": "ha.mydomain.net",
    "enable_script_checks": true,
    "encrypt": "I0W6U36qeLiN2eZIb8cZhg==",
    "key_file": "/etc/consul_certs/test-consul.mydomain.org.key",
    "log_level": "INFO",
    "node_name": "test-consul01",
    "ports": {
        "dns": 8600,
        "http": 8500,
        "https": 443
    },
    "primary_datacenter": "test-mydomain",
    "retry_join": [
        "192.168.1.11",
        "192.168.1.12"
    ],
    "server": true,
    "ui_config": {
        "enabled": true
    }
}
```

</details>

### Operating system and Environment details

Ubuntu 22.04

### Log Fragments

n/a

**Comment by maxadamo** [comment] 2024-06-13 21:12
if this is a bug, and I did not misread the changelog, you should retire this version, because it caused an outage in my environment.

**Comment by maxadamo** [comment] 2024-06-13 21:36
duplicate of #21325

**Comment by DanStough** [comment] 2024-06-25 20:36
This should be resolved with the linked PR. We're discussing putting out 1.19.1 sooner than expected. BOLO for that release.

**Comment by svenstaro** [comment] 2024-06-28 12:35
At the chance of this being basically a +1, I entirely agree with @ygersie. This is the most fundamental functionality of Consul and the longer Hashicorp waits to cut a release, the more clusters will just stop working on some very unexpected fashion. Hashicorp _needs_ to rush out a patched release.

**Comment by maxadamo** [comment] 2024-06-29 07:25
I have to admit that I wrote an initial comment to ask to delete the existing release which breaks the consul cluster for everyone. 
Until this version available is available for download, someone else is going to install it and get into troubles. 
And we are not speaking about minor troubles: in my case all the Postgres servers that we have, became masters, and at standby at same time.

**Comment by drustan** [comment] 2024-07-03 10:14
Wow, I just ran into the same issue. Luckily, it was only in the dev environment. It's surprising that this bug has been around for so long without a fix. I'm really hoping it gets addressed soon!

**Comment by maxadamo** [comment] 2024-07-03 18:23
@DanStough hi 😸 What do you think? 
If I were you, I would delete these releases, because they should not be downloaded and installed by anyone. While I am writing, maybe someone else is installing it and he's facing an outage.

**Comment by dot1q** [comment] 2024-07-08 07:36
Same as @drustan, I caught it in my dev cluster, but it took me way to long to find this thread and I was almost convinced that I was insane. This is the last time that I go to cutting edge simply because I was notified that a newer version existed.

**Comment by drustan** [comment] 2024-07-12 13:07
It seems that this is still an issue in version 1.19.1 :-(

**Comment by DanStough** [comment] 2024-07-12 13:57
@drustan let me see if I can reproduce. If you have any interesting details, let me know. One special case that might be interesting: do you have any periods in the tag name? e.g. `this.is.my.tag.foo.service.consul`

**Comment by drustan** [comment] 2024-07-12 14:33
Hello @DanStough

No, no periods in tags.

![Screenshot from 2024-07-12 16-28-17](https://github.com/user-attachments/assets/545e3f2c-0f67-4c49-89d3-e6e554c4beac)

```
$ host master.13-pgcluster01.service.consul-dev
master.13-pgcluster01.service.consul-dev has address 10.0.1.168
master.13-pgcluster01.service.consul-dev has address 10.0.1.170
master.13-pgcluster01.service.consul-dev has address 10.0.1.169
```

**Comment by DanStough** [comment] 2024-07-12 19:13
@drustan I tried manual testing with 1.19.1 and couldn't reproduce the issue. I also believe the new tests I added should be exercising a similar case. Maybe we could dig into your environment more. I see from the UI this server is running 1.19.1. Is it possible you're running the DNS query against a client agent or another server? In that case, would all agent you are hitting also be updated to 1.19.1?

This is actually my last day at Hashi, but I've alerted others to 👀 this thread.

**Comment by jmurret** [comment] 2024-07-12 19:20
@drustan on top of what Dan asked I am curious if you can recognize differences in the service registration or another aspect of the test [TestDNS_ServiceAddressWithTagLookup](https://github.com/hashicorp/consul/blob/9f62fb4113d286a5642dff9da0138aa3bbef05da/agent/dns_service_lookup_test.go#L388).  I have tried variations of this test such as adding your DNS config with allowing stale, resitering services that have nodes, using a prepared query, and I am not able to replicate this locally.  I would love any information you have about how the service registration or something else is different.

**Comment by drustan** [comment] 2024-07-13 08:38
Hi guys! My bad, the servers hosting the service were running version 1.19.1, but my DNS resolvers were not. After updating the resolvers, everything is working fine now. Sorry for the confusion, and thanks for your reactivity :) Good luck for what comes next @DanStough

**Comment by svenstaro** [comment] 2024-07-15 08:56
So should this be closed?

**Comment by drustan** [comment] 2024-07-15 09:32
Yes, all good now

**Comment by jmurret** [comment] 2024-07-15 20:01
that's great to hear @drustan.  thank you for the feedback.  closing issue.

**Closed by jmurret** 2024-07-15 20:01 UTC
