### ISSUE TITLE
Missing leadership metrics?

### ISSUE THREAD

**Issue by TylerLubeck** [hashicorp/consul#5235] opened 2019-01-17 22:44 UTC
#### Overview of the Issue

I'm attempting to configure some more monitoring, and would like to set alerts on the metrics described here: https://www.consul.io/docs/agent/telemetry.html#leadership-changes

Unfortunately, I can't find any instances of `consul.raft.state.candidate` or `consul.raft.state.leader`. It's fully possible that this is a PEBKAC situation - should those metrics be emitted if there isn't a leadership election in progress? Or are they actually missing?

#### Reproduction Steps

Steps to reproduce this issue, eg:

1. On a running cluster (I'm using v1.4.0), trigger metrics to be emitted - `kill -SIGUSR1 $(pgrep consul)`
1. Check the logs for `consul.raft.state.candidate` and `consul.raft.state.leader`.

### Consul info for Server
```
tylerl@z1consul200aop1:~$ consul info
agent:
        check_monitors = 0
        check_ttls = 0
        checks = 0
        services = 0
build:
        prerelease =
        revision = 0bddfa23
        version = 1.4.0
consul:
        acl = disabled
        bootstrap = false
        known_datacenters = 1
        leader = true
        leader_addr = 10.141.145.5:8300
        server = true
raft:
        applied_index = 9315368
        commit_index = 9315368
        fsm_pending = 0
        last_contact = 0
        last_log_index = 9315368
        last_log_term = 13946
        last_snapshot_index = 9299612
        last_snapshot_term = 13946
        latest_configuration = [{Suffrage:Voter ID:2b238fd6-e3f0-2b06-76b5-94165f46e5d9 Address:10.141.17.4:8300} {Suffrage:Voter ID:e18d3220-181d-705c-8f0f-e8b638829c87 Address:10.141.17.5:8300} {Suffrage:Voter ID:1c580da5-ca32-45bb-d66f-35f399294254 Address:10.141.145.5:8300}]
        latest_configuration_index = 7856012
        num_peers = 2
        protocol_version = 3
        protocol_version_max = 3
        protocol_version_min = 0
        snapshot_version_max = 1
        snapshot_version_min = 0
        state = Leader
        term = 13946
runtime:
        arch = amd64
        cpu_count = 2
        goroutines = 164
        max_procs = 2
        os = linux
        version = go1.11.1
serf_lan:
        coordinate_resets = 0
        encrypted = true
        event_queue = 0
        event_time = 10720
        failed = 0
        health_score = 0
        intent_queue = 0
        left = 0
        member_time = 3639
        members = 23
        query_queue = 0
        query_time = 1
serf_wan:
        coordinate_resets = 0
        encrypted = true
        event_queue = 0
        event_time = 1
        failed = 0
        health_score = 0
        intent_queue = 0
        left = 0
        member_time = 1684
        members = 3
        query_queue = 0
        query_time = 1
```

### Operating system and Environment details

These are running on Ubuntu 16.04.04 under systemd, no docker, in AWS on t2.mediums

**Comment by pierresouchay** [comment] 2019-01-29 18:47
Probably a duplicate of https://github.com/hashicorp/consul/issues/5140

**Comment by pearkes** [comment] 2019-02-08 17:19
Similar to #5140 but I think it's worth stating that these metrics will only be sent if they exist -- there's no way to "initialize" them or similar -- so without a leadership transition you wouldn't see `consul.raft.state.leader`.

You could see it by triggering a leadership transition with a multi-node local setup and do the metrics dump. Hopefully that explains this behavior!

**Closed by pearkes** 2019-02-08 17:19 UTC
