### ISSUE TITLE
consul1.4.4 run after a while crash always

### ISSUE THREAD

**Issue by xuxiaodong1989** [hashicorp/consul#5680] opened 2019-04-18 10:29 UTC
panic: cannot free page 0 or 1: 0

goroutine 22 [running]:
github.com/hashicorp/consul/vendor/github.com/boltdb/bolt.(*freelist).free(0xc000148d80, 0x559, 0x7ff46c360000)
	/go/src/github.com/hashicorp/consul/vendor/github.com/boltdb/bolt/freelist.go:113 +0x398
github.com/hashicorp/consul/vendor/github.com/boltdb/bolt.(*Tx).Commit(0xc0002efa40, 0xc0007eff70, 0x8)
	/go/src/github.com/hashicorp/consul/vendor/github.com/boltdb/bolt/tx.go:176 +0x1e8
github.com/hashicorp/consul/vendor/github.com/hashicorp/raft-boltdb.(*BoltStore).StoreLogs(0xc00038db20, 0xc000165128, 0x1, 0x1, 0x0, 0x0)
	/go/src/github.com/hashicorp/consul/vendor/github.com/hashicorp/raft-boltdb/bolt_store.go:157 +0x26b
github.com/hashicorp/consul/vendor/github.com/hashicorp/raft.(*LogCache).StoreLogs(0xc00017c3c0, 0xc000165128, 0x1, 0x1, 0x1, 0x1)
	/go/src/github.com/hashicorp/consul/vendor/github.com/hashicorp/raft/log_cache.go:61 +0xec
github.com/hashicorp/consul/vendor/github.com/hashicorp/raft.(*Raft).dispatchLogs(0xc0003078c0, 0xc00032db28, 0x1, 0x1)
	/go/src/github.com/hashicorp/consul/vendor/github.com/hashicorp/raft/raft.go:863 +0x308
github.com/hashicorp/consul/vendor/github.com/hashicorp/raft.(*Raft).leaderLoop(0xc0003078c0)
	/go/src/github.com/hashicorp/consul/vendor/github.com/hashicorp/raft/raft.go:606 +0x63e
github.com/hashicorp/consul/vendor/github.com/hashicorp/raft.(*Raft).runLeader(0xc0003078c0)
	/go/src/github.com/hashicorp/consul/vendor/github.com/hashicorp/raft/raft.go:420 +0x34b
github.com/hashicorp/consul/vendor/github.com/hashicorp/raft.(*Raft).run(0xc0003078c0)
	/go/src/github.com/hashicorp/consul/vendor/github.com/hashicorp/raft/raft.go:140 +0x68
github.com/hashicorp/consul/vendor/github.com/hashicorp/raft.(*Raft).run-fm()
	/go/src/github.com/hashicorp/consul/vendor/github.com/hashicorp/raft/api.go:505 +0x2a
github.com/hashicorp/consul/vendor/github.com/hashicorp/raft.(*raftState).goFunc.func1(0xc0003078c0, 0xc000558800)
	/go/src/github.com/hashicorp/consul/vendor/github.com/hashicorp/raft/state.go:146 +0x53
created by github.com/hashicorp/consul/vendor/github.com/hashicorp/raft.(*raftState).goFunc
	/go/src/github.com/hashicorp/consul/vendor/github.com/hashicorp/raft/state.go:144 +0x66

**Comment by mkeeler** [comment] 2019-04-18 13:21
Closing this as a duplicate of #3771

**Closed by mkeeler** 2019-04-18 13:21 UTC
