### ISSUE TITLE
Import KV Yaml files using command line

### ISSUE THREAD

**Issue by SundareshKumar** [hashicorp/consul#12563] opened 2022-03-16 03:11 UTC

**Comment by Amier3** [comment] 2022-03-16 16:23
Hey @SundareshKumar 

I see this is your first post here 👀  , so welcome to the consul community! Looks like the body text of your feature request didn't show up. Could you edit your request with the following or create a new one: 


> 
> #### Feature Description
> 
> A written overview of the feature.
> 
> #### Use Case(s)
> 
> Any relevant use-cases that you see.
>

**Comment by SundareshKumar** [comment] 2022-03-17 05:50
Hello Bro,

Actually, we are using consul hashicorp for KV feature and the solution is deployed in the docker.

But we are trying to use the docker volume to store the KV as yaml file, and when we restarts the container all the values are get losing.

so tried to use the custom image by executing the sh script to import the yaml file to the kv, but we are not able to find any solutions.

Kindly help me on this.

**Comment by Amier3** [comment] 2022-03-21 17:21
@SundareshKumar 

Happy to help, are you running consul in development mode? I suspect that may be the cause of your issue. Running the consul container image from docker without any arguments specifying `server` or `client` mode will default to dev mode. In dev mode, data isn't persisted to docker volumes.

This part from the [docker hub image](https://hub.docker.com/_/consul/) explains it: 

> The container exposes VOLUME /consul/data, which is a path where Consul will place its persisted state. This isn't used in any way when running in development mode. For client agents, this stores some information about the cluster and the client's health checks in case the container is restarted. For server agents, this stores the client information plus snapshots and data related to the consensus algorithm and other state like Consul's key/value store and catalog.

**Comment by Amier3** [comment] 2022-04-05 18:23
Hey @SundareshKumar 

I hope you were able to figure out your solution. I'm going to close this issue out for now but feel free to re-open it if you're still having problems 😄

**Closed by Amier3** 2022-04-05 18:23 UTC
Labels: theme/kv
