### ISSUE TITLE
Full consul crash - version 0.6.4 

### ISSUE THREAD

**Issue by shakisha** [hashicorp/consul#2082] opened 2016-06-01 13:22 UTC
Today i have got first consul total crash on my systems, this is the log about the error:

´´´   

2016/06/01 14:52:15 [ERR] memberlist: Failed to send TCP ack: write tcp 10.135.22.19:8301->10.135.13.236:43359: i/o timeout from=10.135.13.236:43359
    2016/06/01 14:52:15 [ERR] dns: rpc error: rpc error: session shutdown
    2016/06/01 14:52:15 [ERR] agent: failed to sync changes: rpc error: EOF
    2016/06/01 14:52:15 [ERR] http: Request GET /v1/health/service/asterisk, error: rpc error: stream closed from=127.0.0.1:33347
    2016/06/01 14:52:15 [ERR] dns: rpc error: rpc error: stream closed
    2016/06/01 14:52:15 [ERR] yamux: keepalive failed: session shutdown
    2016/06/01 14:52:15 [ERR] dns: rpc error: rpc error: EOF
    2016/06/01 14:52:15 [ERR] yamux: Failed to write header: write tcp 10.135.22.19:58615->10.135.1.75:8300: write: broken pipe
    2016/06/01 14:52:15 [ERR] dns: rpc error: rpc error: session shutdown
    2016/06/01 14:52:15 [ERR] http: Request GET /v1/health/service/asterisk?index=1309796&passing=1&stale=&wait=60000ms, error: rpc error: session shutdown from=127.0.0.1:52734
    2016/06/01 14:52:15 [ERR] http: Request GET /v1/health/service/asterisk, error: rpc error: stream closed from=127.0.0.1:33352
    2016/06/01 14:52:16 [WARN] memberlist: Was able to reach mariadb-de-02 via TCP but not UDP, network may be misconfigured and not allowing bidirectional UDP
    2016/06/01 14:52:44 [ERR] memberlist: Failed to send TCP ack: write tcp 10.135.22.19:8301->10.135.13.236:43363: i/o timeout from=10.135.13.236:43363
    2016/06/01 14:52:48 [WARN] memberlist: Refuting a suspect message (from: metronic-de-01)
    2016/06/01 14:53:13 [ERR] memberlist: failed to receive: read tcp 10.135.22.19:8301->10.135.7.161:40557: i/o timeout from=10.135.7.161:40557
    2016/06/01 14:53:33 [WARN] memberlist: Refuting a suspect message (from: metronic-de-01)

´´´

What happened exactly?

**Comment by c4milo** [comment] 2016-06-01 13:50
@shakisha, did you verify your networking configuration? it seems the node `mariadb-de-02` couldn't be reached through UDP but TCP.

**Comment by shakisha** [comment] 2016-06-01 14:11
@c4milo yes, everything is fine in the network.

What about suspect message?

**Comment by c4milo** [comment] 2016-06-01 14:21
that's just a warning and is part of Consul's failure detection mechanism. `metronic-de-01` is avoiding signaling himself as dead by refuting a `suspect` message saying it is alive.

**Comment by shakisha** [comment] 2016-06-01 14:25
What can i do for troubleshooting and fixing this problem?

**Comment by shakisha** [comment] 2016-06-01 14:59
because restarting consul temporary fixed the issue but I'm afraid it can stucks again

**Comment by c4milo** [comment] 2016-06-01 15:12
If you are afraid you need to get more confortable operating Consul. My
suggestion is to play around with Consul more: start another cluster,
remove nodes, add nodes, make it lose quorum, see if you can recover it,
etc. Until you no longer feel afraid :)

**Comment by slackpad** [comment] 2016-06-01 15:43
Hi @shakisha, @c4milo is correct - this looks a lot like there was a temporary network disruption on that node that caused the server to close the TCP connection to this agent and caused other nodes to think the agent was failed. This can be caused by problems with the network itself, or it's also common on cloud platforms like AWS with small instance types where periods of high activity can steal resources from network packet processing and cause high packet loss. From the log I don't think Consul actually crashed, it seems like it's starting to recover near the end there (seeing some suspect messages from other nodes thinking it's down), though there are still i/o timeouts so it looks like it's not fully back yet. I suspect that if you ran a network test when this was happening you'd see heavy packet loss independent of Consul.

**Comment by shakisha** [comment] 2016-06-01 17:02
Again some issues, and networking is working perfectly, i don't know what is happening; 

    2016/06/01 17:37:50 [ERR] memberlist: Failed to send TCP ack: write tcp 10.135.22.19:8301->10.135.13.236:43719: i/o timeout from=10.135.13.236:43719
    2016/06/01 17:37:50 [ERR] memberlist: Failed to send TCP ack: write tcp 10.135.22.19:8301->10.135.21.188:38974: i/o timeout from=10.135.21.188:38974
    2016/06/01 17:37:50 [ERR] memberlist: Failed to send TCP ack: write tcp 10.135.22.19:8301->10.135.21.230:51723: i/o timeout from=10.135.21.230:51723
    2016/06/01 17:37:50 [ERR] memberlist: Failed to send TCP ack: write tcp 10.135.22.19:8301->10.135.7.161:47435: i/o timeout from=10.135.7.161:47435
    2016/06/01 17:37:51 [WARN] memberlist: Refuting a dead message (from: asterisk-de-01)
    2016/06/01 17:38:04 [WARN] memberlist: Refuting a suspect message (from: callburn.com-de-01)
    2016/06/01 18:33:38 [WARN] memberlist: Refuting a suspect message (from: mariadb-de-01)
    2016/06/01 18:33:46 [WARN] memberlist: Was able to reach mariadb-de-01 via TCP but not UDP, network may be misconfigured and not allowing bidirectional UDP
    2016/06/01 18:33:52 [WARN] memberlist: Refuting a suspect message (from: metronic-de-01)
    2016/06/01 18:34:02 [WARN] memberlist: Refuting a suspect message (from: asterisk-de-01)
    2016/06/01 18:34:32 [ERR] memberlist: Failed to push local state: write tcp 10.135.22.19:8301->10.135.4.10:38431: i/o timeout from=10.135.4.10:38431
    2016/06/01 18:34:32 [WARN] memberlist: Refuting a suspect message (from: metronic-de-01)
    2016/06/01 18:34:39 [WARN] memberlist: Refuting a suspect message (from: mariadb-de-01)
    2016/06/01 18:34:44 [ERR] memberlist: Failed TCP fallback ping: read tcp 10.135.22.19:49923->10.135.1.75:8301: i/o timeout
    2016/06/01 18:34:46 [ERR] dns: rpc error: rpc error: No cluster leader
    2016/06/01 18:34:46 [ERR] dns: rpc error: rpc error: No cluster leader
    2016/06/01 18:34:46 [ERR] dns: rpc error: rpc error: No cluster leader
    2016/06/01 18:34:46 [ERR] dns: rpc error: rpc error: No cluster leader
    2016/06/01 18:34:46 [ERR] dns: rpc error: rpc error: No cluster leader
    2016/06/01 18:34:49 [ERR] dns: rpc error: rpc error: No cluster leader
    2016/06/01 18:34:49 [ERR] dns: rpc error: rpc error: No cluster leader
    2016/06/01 18:34:49 [ERR] dns: rpc error: rpc error: No cluster leader
    2016/06/01 18:34:54 [ERR] dns: rpc error: rpc error: No cluster leader
    2016/06/01 18:34:54 [ERR] dns: rpc error: rpc error: No cluster leader
    2016/06/01 18:34:57 [ERR] http: Request GET /v1/health/service/asterisk, error: rpc error: No cluster leader from=127.0.0.1:38478
    2016/06/01 18:35:10 [ERR] memberlist: Failed to send TCP ack: write tcp 10.135.22.19:8301->10.135.13.236:43840: i/o timeout from=10.135.13.236:43840
    2016/06/01 18:35:10 [ERR] dns: rpc error: rpc error: No cluster leader
    2016/06/01 18:35:20 [WARN] memberlist: Refuting a dead message (from: callburn.com-de-01)
    2016/06/01 18:35:48 [ERR] memberlist: Failed to send TCP ack: write tcp 10.135.22.19:8301->10.135.7.161:49858: i/o timeout from=10.135.7.161:49858
    2016/06/01 18:35:54 [WARN] memberlist: Refuting a suspect message (from: metronic-de-01)
    2016/06/01 18:36:08 [WARN] memberlist: Refuting a suspect message (from: metronic-de-01)
    2016/06/01 18:36:42 [WARN] memberlist: Was able to reach asterisk-de-01 via TCP but not UDP, network may be misconfigured and not allowing bidirectional UDP
    2016/06/01 18:36:46 [WARN] memberlist: Refuting a suspect message (from: old-metronic)
    2016/06/01 18:37:05 [ERR] memberlist: Failed to send TCP ack: write tcp 10.135.22.19:8301->10.135.10.124:37900: i/o timeout from=10.135.10.124:37900

**Comment by shakisha** [comment] 2016-06-01 17:08
Now when i "dig somehost" i have got:

; <<>> DiG 9.8.2rc1-RedHat-9.8.2-0.37.rc1.el6_7.7 <<>> somehost.service.consul
;; global options: +cmd
;; connection timed out; no servers could be reached

and i have got to restart consul to let it work again, but it will stucks again like this morning.

**Comment by shakisha** [comment] 2016-06-01 17:09
When i run **consul info** i have got:

Error connecting to Consul agent: dial tcp 127.0.0.1:8400: getsockopt: connection refused

**Comment by slackpad** [comment] 2016-06-01 17:13
When you get the message running `consul info` above is the consul process still running?

**Comment by shakisha** [comment] 2016-06-03 10:19
(dead) process, but i think i have found the reason why, just let me investigate a little more.

**Comment by slackpad** [comment] 2016-09-21 22:49
Closing this since we never heard back. Please re-open if you are still having issues.

**Closed by slackpad** 2016-09-21 22:49 UTC
