### ISSUE TITLE
Support for binding client interface(s) to multiple addresses

### ISSUE THREAD

**Issue by blalor** [hashicorp/consul#473] opened 2014-11-14 13:28 UTC
In a containerized (ok, fine: "Docker") environment, I want to expose the consul agent to applications running in containers, but I'm uncomfortable exposing it to the entire world.  Unfortunately, those are the only real options unless I want to muck about with iptables (which, trust me, I very much do _not_).  I'd like to be able to specify multiple addresses in the config file as an array (`"client_addrs": ["127.0.0.1", "172.42.17.1"]`), and that implies multiple `-client` command-line flags.  Related (in my head, anyway) to #421.

**Comment by saulshanabrook** [comment] 2015-05-12 21:48
So it is impossible right now to have consul available on localhost and on the machines global IP?

**Comment by saulshanabrook** [comment] 2015-05-12 22:02
Lemme know if there is an easier way, but I set up consul to bind on localhost (the default) and then used `socat` to forward incoming traffic to that port.

```
socat -d -d TCP-L:8500,bind=10.128.1.72,fork TCP:localhost:8500
```

Where `10.128.1.72` is my IP.

Also had to set `advertise_addr` in my consul config to that IP as well.

**Comment by Esya** [comment] 2015-10-09 02:20
+1 for this feature, same usecase and we'd like to avoid using socat or iptables on top of consul just to redirect the traffic

**Comment by smreichling** [comment] 2015-10-26 23:21
Adding my vote for this feature. This is causing us pain because we want the Consul Web UI to be accessible from other machines (no just localhost) but changing the HTTP bind address requires an extra argument to every command line tool that uses the HTTP API and assumes localhost.

**Comment by markeijsermans** [comment] 2015-11-25 07:20
Same situation here. I have Consul and Registrator both in Docker containers with `--net=host`, and have mixed workloads of native & containerized apps. Inside the the containerized workloads (with `--net=bridge`) I access the host by contacting it's gateway - ie `ip route | grep default | awk '{print $3}'`

**Comment by blalor** [comment] 2015-11-25 12:42
I'd also like to see the unix domain socket be supported along with the list of listening addresses.

**Comment by IainColledge** [comment] 2015-12-22 13:07
Would be a good option

**Comment by tgeens** [comment] 2016-01-10 09:33
@blalor I'm inferring from your original post that you run consul in docker with --net=host.

I think there is a workaround if you use --net=bridge:

* you can bind consul -client=0.0.0.0 to all interfaces (inside the net-container-space)
* map 8400/8500/8600 to your bridge0 (172.42.17.1) on the host
* map 8300-8302 to your private-network ip on the host

**Comment by techwolf359** [comment] 2016-05-19 22:54
I ran across this one today using addresses->http so I can access the Web UI on server1.
```
"addresses": {
    "http": "10.xx.xx.xx"
}
```

Local `consul rtt` fails because:
```
server1> consul rtt $FQDN
Unable to look up agent info: Get http://127.0.0.1:8500/v1/agent/self: dial tcp 127.0.0.1:8500: getsockopt: connection refused`
```

Switching http to 0.0.0.0 actually fixed this by binding to all network interfaces, so now I can use 127.0.0.1 and 10.xx.xx.xx to connect to HTTP. This is slightly different than client_addr above, and is different than some users requests where they would like to bind to explicitly 2 IPs, but maybe not *all* IPs.

This might be worth calling out in the documentation for the [addresses](https://www.consul.io/docs/agent/options.html#addresses) section because in the [bind](https://www.consul.io/docs/agent/options.html#_bind) section, the use of 0.0.0.0 is different:
```
By default, this is "0.0.0.0", meaning Consul will use the first available private IPv4 address.
```

Suggest adding to the `addresses` section, the use of 0.0.0.0 to bind to all network interfaces. It might even solve @saulshanabrook's issue.

**Comment by steve-jansen** [comment] 2016-05-20 01:46
@techwolf359 

Believe the behavior of the `0.0.0.0` wildcard in golang's net package is to [bind to the first available interface, not all available interfaces](https://github.com/golang/go/issues/9334).  So, I think the docs are correct.

> By default, this is "0.0.0.0", meaning Consul will use the first available private IPv4 address.

**Comment by techwolf359** [comment] 2016-05-20 03:54
I wonder if that's left to a system call and OS implementation. On CentOS 7, setting client_addr to 0.0.0.0 is binding to all interfaces for me and fixed the above scenario where `consul rtt` was unable to connect via 127.0.0.1. External requests still work fine. In any event, if docs aren't updated, trying 0.0.0.0 could possibly help out people in the thread.

**Comment by hvpareja** [comment] 2016-07-04 11:33
Hi all, 

+1 for this feature. It would be very useful in my case. I need Consul servers to be listening in 2 of 3 different interfaces.

**Comment by ajvb** [comment] 2016-08-12 20:22
+1 - I have a set of servers on a different subnet, and it would be nice to be able to configure multiple interfaces for them. My use case would also be solved by being able to specify an outbound interface and an inbound interface.

Also, if you have multiple interfaces on a machine and you try to bind to `0.0.0.0`, consul throws this error:
```
==> Error starting agent: Failed to get advertise address: Multiple private IPs found. Please configure one.
```

**Comment by kawikao** [comment] 2016-09-02 17:59
I ran into this as well a config file. If I do docker run and use -bind or a custom command in docker-compose file then I get the expected behavior. If I use a config file with advertise_addr or any other bind setting, I can't bind to the host and cannot access services. I don't want custom docker-compose files, that's what config files are for. Thanks.

**Comment by number5** [comment] 2016-11-09 05:39
set client address to `0.0.0.0` on Ubuntu 14.04 will bind to all interfaces include `lo` and docker's `docker0` /`172.17.0.1`

**Comment by cthumuluru** [comment] 2017-02-09 07:15
Is there a way to specify the bind port and client port for the agent similar to http port?

**Comment by jnials** [comment] 2017-02-17 15:05
+1 as well.  I need to be able to run local for most things, but the UI on the external port.

**Comment by zh99998** [comment] 2017-03-26 15:45
+1 for this request

I'm in a hybrid cloud and this feature is essential for me.

**Comment by ryansmithevans** [comment] 2017-03-30 10:17
:+1:  pretty much required

**Comment by sean-** [comment] 2017-03-30 15:00
In your confit you can now add an undocumented (yet) flag: `{{ GetInterfaceIP "eth0" }}` and it should do the right thing. See the sockaddr library for more details and options.

**Comment by jcortejoso** [comment] 2017-04-25 08:52
Is this issue still active? I have configured ```"client_addr": "0.0.0.0"``` and consul seems to be listening on all interfaces:
```
[root@intprivate05 ~]# netstat -tlpn | grep consul
tcp        0      0 10.200.0.136:8301       0.0.0.0:*               LISTEN      29797/consul        
tcp        0      0 127.0.0.1:8400          0.0.0.0:*               LISTEN      29797/consul        
tcp6       0      0 :::8500                 :::*                    LISTEN      29797/consul        
tcp6       0      0 :::8600                 :::*                    LISTEN      29797/consul        
[root@intprivate05 ~]# consul version
Consul v0.7.0
Protocol 2 spoken by default, understands 2 to 3 (agent will automatically use protocol >2 when speaking to compatible agents)
```

**Comment by slackpad** [comment] 2017-04-25 21:04
Closing this as a duplicate of https://github.com/hashicorp/consul/issues/2217, since there's an active PR against that one.

**Closed by slackpad** 2017-04-25 21:04 UTC
