### ISSUE TITLE
Acl operations via cli

### ISSUE THREAD

**Issue by alexandrustaetu** [hashicorp/consul#3862] opened 2018-02-05 23:25 UTC
Hello,

Would it be appropriate for the consul binary to also allow users to interact with the ACL database via additional parameters, mirroring the acl api?

As an example, consul executable can be called as follows:

`consul acl create -id $(uuidgen -r) -name build-server-read -type client -rules /path/to/rules.hcl`
`consul acl destroy -id $(uuidgen -r)`

As an alternative, one can create wrappers/scripts around the http api and proceed with creating/deleting/etc tokens. Having the option to interact with the api via the consul cli client would remove the need to create custom wrappers.

Let me know if this can be seen as an improvements and if it's ok to create a series of push requests for implementing it.

Thanks,
Alex.

**Comment by slackpad** [comment] 2018-02-06 02:38
Hi @alexandrustaetu thanks for opening an issue I'll close this as a duplicate of #3208 which also captures writing a CLI for ACLs.

This would eventually be a good thing to get from the community but I think we'd want to sort out https://github.com/hashicorp/consul/issues/2027 so all the CLI operations could take an ID instead of the ACL tokens (where they would end up in bash history, etc.). We could use https://www.nomadproject.io/docs/commands/acl.html as a model for the CLI interface.

**Closed by slackpad** 2018-02-06 02:38 UTC
