### ISSUE TITLE
Updating connect Vault CA configuration drops intermediate certificates

### ISSUE THREAD

**Issue by mr-miles** [hashicorp/consul#14564] opened 2022-09-12 00:19 UTC
When filing a bug, please include the following headings if possible. Any example text in this template can be deleted.

#### Overview of the Issue

Upgrading from 1.11 to 1.12 we observed that clients no longer had valid certificate chains after an auto-encrypt startup.  They were missing the intermediate certificate.

#### Reproduction Steps

Steps to reproduce this issue, eg:

1. Create a cluster with 1 client node and 1 server nodes
2. Configure the client with autoencrypt
3. Configure the server with the vault CA provider.  Set up the root and intermediate certificate paths.
4. Start the client and server
5. Observe that the TLS certificate chain is valid - e.g. visit https://<client>:8501/v1/agent/connect/ca/roots in the browser
6. PUT the identical vault ca config to https://<server>:8501/v1/connect/ca/configuration
7. Restart the client
8. Observe that the TLS certificate chain is now invalid and is missing the intermediate certificates - e.g. visit https://<client>:8501/v1/agent/connect/ca/roots in the browser (the text response still contains the intermediate but the cert chain for https does not)

### Consul info for both Client and Server
1.12,4 for both
Vault Connect CA with intermediate certificate

### Root cause
In leader_connect_ca.go:891 - primaryUpdateRootCA - the root is updated but the intermediates aren't, before a short-circuit check on line 921.  Comparing this code to that of leader_connect_ca.go:471 - primaryInitialize - indicates that GenerateIntermediate should be called but isn't.  It is currently called much later (line 992) which is after the early exit.  So effectively updating an existing vault CA config strips the intermediate certificates.

If I alter leader_connect_ca.go:897 to add intermediate handling before the early exit, the error I experience goes away:

```	newRootPEM := providerRoot.PEM
	newActiveRoot, err := newCARoot(newRootPEM, args.Config.Provider, args.Config.ClusterID)
	if err != nil {
		return err
	}

        # new code starts here
	interPEM, err := newProvider.GenerateIntermediate()
	if err != nil {
		return fmt.Errorf("error generating intermediate cert: %v", err)
	}

	// Add the local leaf signing cert to the rootCA struct. This handles both
	// upgrades of existing state, and new rootCA.
	if c.getLeafSigningCertFromRoot(newActiveRoot) != interPEM {
		newActiveRoot.IntermediateCerts = append(newActiveRoot.IntermediateCerts, interPEM)
	}
```

There are some TODO comments in the code around intermediates, and I didn't fully grasp the subtleties of behaviour wrt cross-signing or secondary data centers so wasn't sure if the fix is just to remove the early exit or something else.

**Comment by dclaisse** [comment] 2022-10-11 15:57
Hi @mr-miles, I believe this could be fixed by a PR I submitted (https://github.com/hashicorp/consul/pull/14888, especially this line: https://github.com/hashicorp/consul/pull/14888/files#diff-94251fa3128564c2e929d8c5250264dd3bf3dc2e1873bd4db7c62d80f8b3f12aR543). I thought it only fixed secondary CA initialization using consul provider by might fix your issue too. By any chance, do you have a testbed where you could test it?

**Closed** 2023-03-13 21:33 UTC
Labels: type/bug, theme/consul-vault, theme/certificates

**Comment by kisunji** [comment] 2023-03-14 14:11
This should be resolved with the next patch releases for v1.15.2, v1.14.6, v1.13.8 which should be released sometime this week.

**Comment by kisunji** [comment] 2023-03-14 14:12
Thank you @mr-miles for the root cause analysis; it was spot-on and helped figure out the issue.

**Comment by mr-miles** [comment] 2023-03-14 14:16
@kisunji - Happy to help, thanks for fixing!
