### ISSUE TITLE
How to Register a Service in Consul with tags "urlprefix-"

### ISSUE THREAD

**Issue by gagan2u2002** [hashicorp/consul#2634] opened 2017-01-05 11:12 UTC
### `consul version` for both Client and Server
Client: `0.7.2

### Operating system and Environment details
Using Window 7 

### Description of the Issue (and unexpected/desired result)
**Unable to register my service in consul with tags urlprefix , please suggest me how can i register my service in consul using urlprefix tag**

Problem statement :
A Restful Service is going to register itself in consul ( it is a tool for discovering and configuring services in your infrastructure ) .
Now I need to add a Load Balancer  (Fabio ) on top of Consul but as I understand  Fabio is looking only those service they are registered in Consul with urlPrefix tag and I am not able to understand how can I add UrlPrefix tag so that Fabio can pick from consul.

**Comment by moofish32** [comment] 2017-01-06 06:35
@gagan2u2002 

There is actually some good [documentation](https://www.consul.io/docs/agent/services.html) on this and [fabio-example](https://github.com/magiconair/fabio-example/blob/master/main.go#L68-L81) 

The document I linked is using the consul configuration to set the tags you would want something like:

```json
{
  "service": {
    "name": "foobar",
    "tags": ["urlprefix-/foo, urlprefix-/bar"],
    "address": "",
    "port": 8000,
    "enableTagOverride": false,
    "checks": [
      {
           "id": "api",
           "name": "HTTP API on port 5000",
           "http": "http://localhost:5000/health",
           "interval": "2s",
           "timeout": "1s"
      }
    ]
  }
}
```
In addition to the tags don't forget to define a health check.

A quick start video from [Fabio](https://www.youtube.com/watch?v=gvxxu0PLevs)

Recommend closing this issue.

**Comment by gagan2u2002** [comment] 2017-01-06 09:44
@moofish32 
Hi i have tried the same but not get any luck to resolve urlprefix issue  , 
 
 **project-stages.yml file** 

service:
    hpgdtv:
        service-name: "GAGAN"
        service-tags: ["urlprefix-/hpgdtv"]
swarm:
    port:
        offset: 100
    consul:
        url: "http://127.0.0.1:8500"
---
project:
    stage: production
service:
    hpgdtv:
        service-name: "GAGAN"
        service-tag: "/hpgdtv"
swarm:
    port:
        offset: 100
    consul:
        url: "http://127.0.0.1:8500"

**Fabio Log and Consul log also attached , please go with once so that you can provide me better solution to fix this-**

[consullog.txt](https://github.com/hashicorp/consul/files/689496/consullog.txt)
[Fabio_log.txt](https://github.com/hashicorp/consul/files/689497/Fabio_log.txt)

**Comment by raben2** [comment] 2017-01-06 10:18
@magiconair you seeing this, i assume it is a issue with fabio, i tried to use several urlprefixes.

**Comment by magiconair** [comment] 2017-01-06 12:08
try `"tags": ["urlprefix-/foo", "urlprefix-/bar"],`

**Comment by magiconair** [comment] 2017-01-06 13:19
@gagan2u2002 It looks like you did not register a health check. If you look at the last line of the consullog.txt file you'll notice 

```
agent: check 'service:fabio-C40-BF91-9998' is passing
```

but I don't see anything like that for your `GAGAN` service. fabio will only consider services which have a passing health check. Please have a look at the fabio quickstart which you can find here: https://github.com/eBay/fabio#getting-started Step 3 talks about the health check.

Feel free to open an issue at https://github.com/eBay/fabio if this isn't working since this is most likely not a consul issue.

**Comment by gagan2u2002** [comment] 2017-01-07 02:47
@magiconair  : if you looking Fabio_log.txt 
consul: Registered fabio with health check to "http://[10.131.126.127]:9998/health"
consul: Health changed to #39
from that i understand service is passing health check.
As per the fabio log 
consul: Registered fabio with tags ""
from that statement i understand in consul tag is not set properly.

 even in console UI ,  i can able to see service GAGAN is GREEN , consul service  is GREEN and Fabio service also registered in consul and it is also GREEN but when i look routing table interface (http://localhost:9998/routes ) it will not have any records. 

can you share one example on git hub which have basic service who registered in consul and Fabio can pick this it would be a great help.

And yes i am going to open the same ticket on Fabio too.

**Comment by magiconair** [comment] 2017-01-07 07:06
This is the health check of Fabio itself when it registers in consul. Your service needs to register its own health check. 

Frank Schröder

**Comment by gagan2u2002** [comment] 2017-01-09 06:33
@magiconair  Still i am not able to get any solution , when i am looking consul log it now say , health of service GAGAN is passing as true -
 **2017/01/09 11:43:10 [DEBUG] http: Request GET /v1/health/service/GAGAN?passing=true&wait=5s&index=117 (5.046s) from=127.0.0.1:65260**
 but still Fabio is not able to pick this -

Again i am share with you the screen shot of Consul UI , fabio_log.txt , consul_log.txt and Project-stages.yml in text format.  Please have a look and suggest me how can i resolve this issue or where i need to correct myself.
[consul_log

.txt](https://github.com/hashicorp/consul/files/692808/consul_log.txt)
![consul_ui](https://cloud.githubusercontent.com/assets/10513267/21758576/358c4608-d663-11e6-9925-c4b49d820aaf.png)
[fabio_log.txt](https://github.com/hashicorp/consul/files/692809/fabio_log.txt)
[Project-stages.yml.txt](https://github.com/hashicorp/consul/files/692810/Project-stages.yml.txt)

**Comment by moofish32** [comment] 2017-01-09 06:53
@gagan2u2002 

I have no idea what project-stages.yml is for, but can you try using array syntax for tags.

```yaml
service:
    hpgdtv:
        service:
          name: "GAGAN"
          tags: 
             - "urlprefix-/hpgdtv"
          check:
            id: "hpgdtv" 
            name: "GAGAN"
            http: "http://127.0.0.1:8180/health"
            interval: "3s"
            timeout: "1s"
swarm:
    port:
        offset: 100
    consul:
        url: "http://127.0.0.1:8500"
```

Purely a guess on my part since I know the consul syntax is array.

**Comment by gagan2u2002** [comment] 2017-01-09 07:14
@moofish32  Project-stages.yml is only a configuration file and if you are looking it i am able to assign helthcheck and urlprefix tags into this  and on the same time consul is able to pass healthcheck parameter as true if you are looking consul log which i shared earlier. 
So i need to understand where i am doing wrong or how can i resolve this issue as it become bottleneck for my project.

Or if you have any simple example of REST service  (like Hello world ) which is registered in consul with url prefix tags  and fabio can pick the same service then it would be helpful at my end.

**Comment by moofish32** [comment] 2017-01-09 07:17
@gagan2u2002 -- I am suggesting that your yml syntax is wrong. Did you try modifying as I suggested?

```yaml
          tags: 
             - "urlprefix-/hpgdtv"
```
instead of 
```yaml
          tags: "urlprefix-/hpgdtv"
```

**Comment by gagan2u2002** [comment] 2017-01-09 07:28
@moofish32  i have tried it as you suggest but i am getting same result :(

**Comment by moofish32** [comment] 2017-01-09 07:31
@gagan2u2002 - I would suggest opening an issue with what ever framework is reading that yml file. Consul and Fabio I believe are behaving as expected.  The most likely issue is that yml file is not getting translated correctly into a consul configuration. Perhaps @magiconair has additional experience, but I don't know the framework you are using.

**Comment by gagan2u2002** [comment] 2017-01-09 07:48
@moofish32 - for creating service i am using wild fly-swarm and then i will register this service in consul below is the Java code which i am using to get resource from  "project-stages.yml" , So i am not reading anyhow any yml file i am just get Resource from Yml and assign it to swarm container.

URL stageConfig = Main.class.getClassLoader().getResource("project-stages.yml");
Swarm swarm = new Swarm().withStageConfig(stageConfig);

Configuration overlays using stage properties
https://wildfly-swarm.gitbooks.io/wildfly-swarm-users-guide/content/v/2016.11.0/configuration/project_stages.html

**Comment by magiconair** [comment] 2017-01-09 09:46
@gagan2u2002 if you look at the screenshot then you can see that there is no `urlprefix-` tag registered with the GAGAN service. You should be able to see that as well if you check the output of `curl -i http://localhost:8500/v1/health/service/GAGAN?pretty` assuming that your consul instance is on `localhost:8500`.

You need to figure out how to pass the service tags to the wildfly-swarm library since it is interfacing with consul. Unfortunately, their documentation regarding the wildfly-consul integration documentation is a bit basic (https://wildfly-swarm.gitbooks.io/wildfly-swarm-users-guide/content/topology/consul.html). See what you can find out.

**Comment by gagan2u2002** [comment] 2017-01-09 10:42
@magiconair  yes now we are on same page , this is the challenge i am facing at my end urlprefix- tag is not registered.
  i have window 7 machine with me . i have consul , Fabio and wild fly service on my box . 
To validate this point whether wildfly service have issue with consul i need to validate 
whether a  simple service is working with consul and Fabio.  **Now one quick question are you have any service example ready at your end so that i can validate this with consul and Fabio on window box.**

**Comment by magiconair** [comment] 2017-01-09 10:44
@gagan2u2002 yes, you can go into the `demo/server` subdirectory of https://github.com/eBay/fabio and build that with `go build`. This is the test server that I'm using which does what you need.

**Comment by gagan2u2002** [comment] 2017-01-10 04:31
@magiconair  No i am not looking for this , i am looking for one Rest Service which i can deployed on App server like JBoss / Wildfly and then check this service integration with Consul and Fabio . Have we tested Consul and Fabio Integration with Jboss / Wildfly ?

**Comment by raben2** [comment] 2017-01-12 11:38
I guess the issue is really with consul i just tried the following using ansible. when i provide a tag list the consul server errors with:
`400 Request decode failed: 1 error(s) decoding:\n\n* 'Tags[3]' expected type 'string', got unconvertible type '[]interface {}'"
}`

the request looks like this:
`
            "tags": [
                "prod", 
                "zp", 
                "0.2", 
                [
                    "urlprefix-www.deposit-solutions.com/", 
                    "urlprefix-deposit-solutions.com/", 
                    "urlprefix-comonea.de/", 
                    "urlprefix-www.comonea.de/"
                ]
            ],
`

**Comment by magiconair** [comment] 2017-01-12 11:46
@raben2 why are you encoding a list in a list? That doesn't look right. I think this should be

```
            "tags": [
                "prod", 
                "zp", 
                "0.2", 
                "urlprefix-www.deposit-solutions.com/", 
                "urlprefix-deposit-solutions.com/", 
                "urlprefix-comonea.de/", 
                "urlprefix-www.comonea.de/"
            ],
```

**Comment by raben2** [comment] 2017-01-12 12:58
Yes you are absolutely right, that worked
FYI How to build a tag list in ansible with several URLprefixes
```
    - name: register all urlprefixes for services
      set_fact:
          prefixes: "urlprefix-{{ item }}{{ endpoint }}"
      with_items: 
        - "{{ urlprefix }}"
      register: service_urls
    
    - name: build taglist
      set_fact: 
        tag_list: "{{ service_urls.results |map(attribute='ansible_facts.prefixes') |list }} + [ '{{ tenant }}' ] + [ '{{ env }}' ] + [ '{{ version }}' ]"
```

**Comment by gagan2u2002** [comment] 2017-01-17 10:40
Spring Boot , Fabio and Consul integration is possible and i have upload the code in git hub 
https://github.com/gagan2u2002/springboot-consul-Fabio-Integration-example

but when i use with wildfly swarm ,   i am not able to pass urlprefix tag . Can some one share one example where we use wildfly-swarm service with consul and Fabio.

**Comment by magiconair** [comment] 2017-01-17 14:41
@gagan2u2002 Wouldn't it make more sense to ask this the `wildfly-swarm` community? Once you have the tags in consul things will work as expected.

**Comment by gagan2u2002** [comment] 2017-01-17 18:25
@magiconair  yes it make sense.  i already put this in front of wildfly swarm community.

**Comment by slackpad** [comment] 2017-05-02 00:16
Closing this out as it looks like the forward work here is in wildfly-swarm, and not in Consul.

**Closed by slackpad** 2017-05-02 00:16 UTC
