### ISSUE TITLE
agent hangs/loops with too many open files

### ISSUE THREAD

**Issue by ingardm** [hashicorp/consul#907] opened 2015-05-05 14:08 UTC
I don't know what causes it but this is happening every once in a while. Its usually only for a few seconds and then it resolves itself. This is what we see in the logs:

```
2015/05/05 06:32:12 [DEBUG] http: Request /v1/kv/b2/delete_queue_workers/dn-096 (609.83µs)
2015/05/05 06:32:13 [ERR] memberlist: Error accepting TCP connection: accept tcp [::]:8301: too many open files
2015/05/05 06:32:13 [ERR] memberlist: Error accepting TCP connection: accept tcp [::]:8301: too many open files
2015/05/05 06:32:13 [ERR] memberlist: Error accepting TCP connection: accept tcp [::]:8301: too many open files
```

... line repeated a few thousand times ....

Followed by :
    2015/05/05 06:32:13 [WARN] Dropping logs to rpc.client: &{{0xc208db1880}}
    2015/05/05 06:32:13 [WARN] Dropping logs to rpc.client: &{{0xc208db1880}}
    2015/05/05 06:32:13 [WARN] Dropping logs to rpc.client: &{{0xc208db1880}}
    2015/05/05 06:32:13 [WARN] Dropping logs to rpc.client: &{{0xc208db1880}}
    2015/05/05 06:32:13 [WARN] Dropping logs to rpc.client: &{{0xc208db1880}}

a few thousand times

and then back to too many open files etc etc

These two messages occur ~ 35k times in the space of 2 seconds.

And then on the "3rd" second:
    2015/05/05 06:32:15 [DEBUG] http: Request /v1/health/service/ourservice?passing (1.638473ms)

back to normal

This is with consul 0.5.0

**Comment by armon** [comment] 2015-05-05 20:46
@ingardm Consul handles running out of file descriptors in a really poor manner currently. The best solution is to increase ulimit to something insane such that it's never reached.

**Comment by ChrisMcKenzie** [comment] 2015-11-17 00:19
I am experiencing this with `0.5.2` as well.

**Comment by max0d41** [comment] 2015-11-20 01:27
This happens here too with consul 0.5.2 in combination with nomad 0.2.0. I can see new open sockets at consul and nomad every few seconds. After a restart of nomad all the zombie sockets are gone.

**Comment by slackpad** [comment] 2016-01-30 06:58
The root cause of this with Nomad was fixed under https://github.com/hashicorp/consul/issues/688, but we should keep this open to handle the situation more gracefully and not spam.

**Comment by lettrung99** [comment] 2016-05-08 20:04
We are experiencing the same problem with consul 0.6.3, nomad 0.3.0 and docker 1.10.2

2016/05/07 05:47:43 [ERR] memberlist: Error accepting TCP connection: accept tcp 10.9.43.57:8301: accept4: too many open files

This eat up the FS really quick making the agent hang and cause tons of all issues with nomad scheduler.
Any fix or workaround please lets us know.

the transport that consul used:

// DefaultTransport returns a new http.Transport with the same default values
// as http.DefaultTransport, but with idle connections and keepalives disabled.
func DefaultTransport() *http.Transport {
	transport := DefaultPooledTransport()
	transport.DisableKeepAlives = true
	transport.MaxIdleConnsPerHost = -1
	return transport
}

// DefaultPooledTransport returns a new http.Transport with similar default
// values to http.DefaultTransport. Do not use this for transient transports as
// it can leak file descriptors over time. Only use this for transports that
// will be re-used for the same host(s).
func DefaultPooledTransport() *http.Transport {
	transport := &http.Transport{
		Proxy: http.ProxyFromEnvironment,
		Dial: (&net.Dialer{
			Timeout:   30 * time.Second,
			KeepAlive: 30 * time.Second,
		}).Dial,
		TLSHandshakeTimeout: 10 * time.Second,
		DisableKeepAlives:   false,
		MaxIdleConnsPerHost: 1,
	}
	return transport
}

// DefaultClient returns a new http.Client with similar default values to
// http.Client, but with a non-shared Transport, idle connections disabled, and
// keepalives disabled.
func DefaultClient() *http.Client {
	return &http.Client{
		Transport: DefaultTransport(),
	}
}

Thanks,

David

**Comment by preetapan** [comment] 2017-06-28 15:25
Ran consul with a small ulimit, and saw that commands like consul info/consul reload hang forever. Doing a  kv read against the agent's http api also hangs, but after it establishes a connection. I see something like below:
```
preetha@preetha-work ~/Downloads $curl -v http://localhost:8500/v1/kv/saass
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 8500 (#0)
> GET /v1/kv/saass HTTP/1.1
> Host: localhost:8500
> User-Agent: curl/7.47.0
> Accept: */*
> 
```
Something downstream of that is in a wait or retry loop instead of terminating with an error.

**Comment by preetapan** [comment] 2017-07-06 19:17
Closing this out - Consul internals have changed quite a bit since this was originally reported. Did some testing and didn't see an unexpectedly high number of open file descriptors.

**Closed** 2017-07-07 19:30 UTC
Labels: bug, theme/internal-cleanup

**Comment by nh2** [comment] 2017-12-30 23:58
@preetapan This just happened to me on 0.9.3:

```
[root@node-3:~]# journalctl -u consul -f

-- Logs begin at Sat 2017-12-23 02:33:45 UTC. --
Dec 30 23:50:29 node-3 consul[26388]:     2017/12/30 23:50:29 [ERR] memberlist: Error accepting TCP connection: accept tcp 10.0.0.3:8301: accept4: too many open files    2017/12/30 23:50:29 [ERR] memberlist: Error accepting TCP connection: accept tcp 10.0.0.3:8302: accept4: too many open files
Dec 30 23:50:29 node-3 consul[26388]:     2017/12/30 23:50:29 [ERR] consul.rpc: failed to accept RPC conn: accept tcp 10.0.0.3:8300: accept4: too many open files
Dec 30 23:50:29 node-3 consul[26388]:     2017/12/30 23:50:29 [ERR] memberlist: Error accepting TCP connection: accept tcp 10.0.0.3:8301: accept4: too many open files
Dec 30 23:50:29 node-3 consul[26388]:     2017/12/30 23:50:29 [ERR] memberlist: Error accepting TCP connection: accept tcp 10.0.0.3:8302: accept4: too many open files    2017/12/30 23:50:29 [ERR] consul.rpc: failed to accept RPC conn: accept tcp 10.0.0.3:8300: accept4: too many open files    2017/12/30 23:50:29 [ERR] memberlist: Error accepting TCP connection: accept tcp 10.0.0.3:8301: accept4: too many open files
Dec 30 23:50:29 node-3 consul[26388]:     2017/12/30 23:50:29 [ERR] memberlist: Error accepting TCP connection: accept tcp 10.0.0.3:8301: accept4: too many open files
Dec 30 23:50:29 node-3 consul[26388]:     2017/12/30 23:50:29 [ERR] consul.rpc: failed to accept RPC conn: accept tcp 10.0.0.3:8300: accept4: too many open files
```
