### ISSUE TITLE
Consul server high system cpu usage on kernel 4.14.15-1.el7

### ISSUE THREAD

**Issue by kamaradclimber** [hashicorp/consul#4028] opened 2018-04-13 09:19 UTC
### Description of the Issue (and unexpected/desired result)

When running consul server on linux 4.14.15-1.el7 (upstream version, no redhat patches), cpu usage is much higher than usual.
Load quickly rises to >40 (on 24 cpus server). Most of the cpu is system but user cpu is also higher than usual.
On normal conditions (this is our preprod environment), load is below 1.

We've tried with other kernels:

| kernel | issue present|
|-----|-----|
| 4.4.126-1.el7.elrepo.x86_64 (our previous working kernel) | no |
| 4.14.15-1.el7.elrepo.x86_64 (our first buggy kernel) | yes |
| 4.14.34 2018-04-12 (latest LTS kernel published) | yes |
| 4.16.2-1.el7.elrepo.x86_64 (latest published kernel on elrepo) | yes|

I've deactivated meltdown mitigation without seeing improvement (4.14.15 has meltdown patches, 4.4.126 hasn't)

### Reproduction steps

Running centos using upstream kernel 4.14.15-1.el7 (from elrepo).
Start a consul server with some traffic.

### `consul version` for both Client and Server
Server:
```
Consul 1.0.6-criteo7
Protocol 2 spoken by default, understands 2 to 3 (agent will automatically use protocol >2 when speaking to compatible agents)
```

The version `criteo7` is a build of consul with some PR merged upstream but not released yet (https://github.com/criteo-forks/consul/tree/v1.0.6-criteo7). This version has been running in production for ~20 days without any issue.

EDIT: I've tried the upstream v.1.0.6, and I see exactly the same issue.

### `consul info` for both Client and Server

Server:
```
agent:
	check_monitors = 0
	check_ttls = 0
	checks = 2
	services = 3
build:
	prerelease = criteo7
	revision = 
	version = 1.0.6
consul:
	bootstrap = false
	known_datacenters = 2
	leader = false
	leader_addr = 10.251.1.97:8300
	server = true
raft:
	applied_index = 302655899
	commit_index = 302659474
	fsm_pending = 128
	last_contact = 71.395µs
	last_log_index = 302659474
	last_log_term = 91
	last_snapshot_index = 302655712
	last_snapshot_term = 85
	latest_configuration = [{Suffrage:Voter ID:830c08a0-34d2-ed54-57ff-a30d9b1b6e35 Address:10.251.1.97:8300} {Suffrage:Voter ID:7a985997-3925-4f18-8613-637c81bd750b Address:10.251.1.96:8300} {Suffrage:Voter ID:c7c272e6-7de9-8d45-691f-6b7b3f899bc4 Address:10.251.1.98:8300}]
	latest_configuration_index = 278740989
	num_peers = 2
	protocol_version = 3
	protocol_version_max = 3
	protocol_version_min = 0
	snapshot_version_max = 1
	snapshot_version_min = 0
	state = Follower
	term = 96
runtime:
	arch = amd64
	cpu_count = 24
	goroutines = 1465
	max_procs = 23
	os = linux
	version = go1.10
serf_lan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 9183
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 1166788
	members = 759
	query_queue = 0
	query_time = 1957
serf_wan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 1
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 6595
	members = 6
	query_queue = 0
	query_time = 1
```

### Operating system and Environment details

Centos release: `CentOS Linux release 7.4.1708 (Core)`
HPGen9 servers

### Log Fragments or Link to [gist](https://gist.github.com/)

Consul server logs: https://gist.github.com/kamaradclimber/e16369a2a98367b24bae518c8fb34e96
(I initiate a leave at some point but it takes a very long time to complete)
![2018-04-13-111621_1904x873_scrot](https://user-images.githubusercontent.com/503537/38727139-77a9eeba-3f0c-11e8-825f-848f490d48e7.png)

**Comment by jippi** [comment] 2018-04-13 09:25
We use `4.14.21-041421` from ubuntu mainline kernel, and don't see these issues

**Comment by kamaradclimber** [comment] 2018-04-13 09:44
https://gist.github.com/kamaradclimber/27800900d7c9259e797dc032c33971a9 for the pprof

**Comment by kamaradclimber** [comment] 2018-04-13 09:55
@jippi good info. Would you have a estimation of the cluster size and the qps?

When starting a `consul agent -dev` on the machine and not requesting it at all does not trigger the issue.
Also starting a simple consul agent on the machine (not a server one) and insert it in the cluster does not trigger the issue either.

We only see that with a consul agent in server mode and answering requests.

**Comment by kamaradclimber** [comment] 2018-04-13 10:05
@jippi already tested with 4.16 without success but I'll test with the latest available to be sure

**Comment by kamaradclimber** [comment] 2018-04-13 14:03
I've confirmed it is not the only server impacted, any consul server in this datacenter using recent enough kernel have that issue.
Next step: use that kernel version in a different datacenter to remove that possibility.

**Comment by kamaradclimber** [comment] 2018-04-13 15:15
Here is a profile on a good and bad servers.
[profile.tar.gz](https://github.com/hashicorp/consul/files/1907927/profile.tar.gz)

What we can see with `top10 -cum` is that the most called functions are exactly the same but timings are very different.

I've also tried sticking consul process to some cpus to try to rule numa out of the equation, but we still observe the same behavior (fully used cpus)

**Comment by kamaradclimber** [comment] 2018-04-14 08:26
Latest result from bisecting released kernel versions: bug introduced between 4.13.16 (good) and 4.14.0 (bad)

**Comment by pierresouchay** [comment] 2018-04-20 15:07
Disabling NUMA or using `numactl --interleave all` does not change anything with this Kernel it seems

**Comment by kamaradclimber** [comment] 2018-04-24 12:52
@preetapan would you have an idea on how we could move forward?

We've mitigated this issue by using GOMAXPROCS=7 but this is not very sustainable.

We sadly don't have any reproducable case but my guess is that interacting with consul with sufficient load is the right trigger.

**Comment by pearkes** [comment] 2018-10-26 19:02
Have you made any progress debugging this issue? Thank you for providing the detail, including profiles, but I'm not sure we'll be able to determine the root cause easily on our side even with the information provided.

**Comment by kamaradclimber** [comment] 2018-11-01 14:13
No progress so far, we've locked kernel version on consul servers for now and are using GOMAXPROCS workaround.
Since we are testing 4.18.16 kernel on another system, we'll likely consider moving to a recent kernel to try in a few weeks.

**Comment by pierresouchay** [comment] 2019-10-21 23:55
We don't have the problem anymore, you can close

**Comment by pierresouchay** [comment] 2020-01-10 07:57
We don't have this issue anymore, you can close it

**Comment by jsosulska** [comment] 2020-07-21 20:29
Closing this per Pierre's comment

**Closed by jsosulska** 2020-07-21 20:29 UTC
Labels: needs-investigation, theme/telemetry
