### ISSUE TITLE
[Usage]How can i get the version of agent that i am accessing into

### ISSUE THREAD

**Issue by lvhuat** [hashicorp/consul#4061] opened 2018-04-27 04:09 UTC
I want to implement a register of gRPC server:
- if the agent that i register my server is lower that v1.0.6, i'll use the health check of `TCP`.
- if not ,i'll use the health check of `GRPC`,which is new in ^v1.0.6.
The problem is: How can i get the version information of the agent?

**Comment by weiwei04** [comment] 2018-04-27 05:02
/v1/agent/self api can get consul agent version
 https://www.consul.io/api/agent.html

**Comment by shantanugadgil** [comment] 2018-04-27 07:40
possible duplicate of #4062  ???

**Comment by pearkes** [comment] 2018-05-02 16:57
As @weiwei04 mentioned you can get information about the agent with the [`/v1/agent/self` API](https://www.consul.io/api/agent.html#read-configuration).

```
$ curl --silent http://localhost:8500/v1/agent/self | jq '.Config.Version'
"1.0.7"
```

**Closed by pearkes** 2018-05-02 16:57 UTC
