### ISSUE TITLE
Cloud discovery documentation: bad Openstack parameters

### ISSUE THREAD

**Issue by mgrzybek** [hashicorp/consul#5031] opened 2018-11-30 14:00 UTC
#### Overview of the Issue

The parameters given to use Openstack Cloud Discovery are wrong:
* `user_name` should be used instead of `username` ;
* `domain_id` is required too.

#### Reproduction Steps

```
[root@pub-node-1 ~]# export|grep OS_
declare -x OS_AUTH_URL="https://xxxxx:5000/v3"
declare -x OS_IDENTITY_API_VERSION="3"
declare -x OS_INTERFACE="public"
declare -x OS_PASSWORD="xxxxx"
declare -x OS_PROJECT_ID="0505293ce38547adacb65ff1a5430815"
declare -x OS_PROJECT_NAME="xxxxxxxx"
declare -x OS_REGION_NAME="RegionOne"
declare -x OS_USERNAME="xxxxxxxxx"
declare -x OS_USER_DOMAIN_NAME="Default"
[root@pub-node-1 ~]#
[root@pub-node-1 ~]# cat /etc/consul.json 
{
        "retry_join" : ["provider=os tag_key=group tag_value=node username=xxxxx password=xxxxxx auth_url=https://xxxxx:5000/v3 project_id=0505293ce38547adacb65ff1a5430815 insecure=true"],
        "disable_remote_exec": true
}
[root@pub-node-1 ~]#
[root@pub-node-1 ~]# systemctl restart consul
[root@pub-node-1 ~]# systemctl status consul
● consul.service - Cluster Controlled consul
   Loaded: loaded (/etc/systemd/system/consul.service; enabled; vendor preset: disabled)
  Drop-In: /run/systemd/system/consul.service.d
           └─50-pacemaker.conf
   Active: active (running) since Fri 2018-11-30 14:55:03 CET; 4s ago
     Docs: http://www.consul.io
 Main PID: 14012 (consul)
   CGroup: /system.slice/consul.service
           └─14012 /usr/local/bin/consul agent -syslog -bind=172.16.0.6 -enable-script-checks -server -ui -bootstrap-expect 3 -domain services -datacenter xxxx -dns-port 8600 -config-file=/etc/consul.json -data-dir=/var/lib/co...

Nov 30 14:55:03 pub-node-1.novalocal consul[14012]: 2018/11/30 14:55:03 [ERR] agent: Join LAN: discover-os: Authentication failed: Exactly one of Username and UserID must be provided for password authentication
Nov 30 14:55:03 pub-node-1.novalocal consul[14012]: 2018/11/30 14:55:03 [WARN] agent: Join LAN failed: No servers to join, retrying in 30s
Nov 30 14:55:03 pub-node-1.novalocal consul[14012]: agent: Joining LAN cluster...
Nov 30 14:55:03 pub-node-1.novalocal consul[14012]: agent: Join LAN: discover-os: Authentication failed: Exactly one of Username and UserID must be provided for password authentication
Nov 30 14:55:03 pub-node-1.novalocal consul[14012]: agent: Join LAN failed: No servers to join, retrying in 30s
Nov 30 14:55:04 pub-node-1.novalocal consul[14012]: 2018/11/30 14:55:04 [DEBUG] raft-net: 172.16.0.6:8300 accepted connection from: 172.16.0.12:56126
Nov 30 14:55:04 pub-node-1.novalocal consul[14012]: 2018/11/30 14:55:04 [DEBUG] raft-net: 172.16.0.6:8300 accepted connection from: 172.16.0.12:58965
Nov 30 14:55:04 pub-node-1.novalocal consul[14012]: agent: Synced node info
Nov 30 14:55:04 pub-node-1.novalocal consul[14012]: 2018/11/30 14:55:04 [INFO] agent: Synced node info
Nov 30 14:55:07 pub-node-1.novalocal consul[14012]: ==> Failed to check for updates: Get https://checkpoint-api.hashicorp.com/v1/check/consul?arch=amd64&os=linux&signature=670b4aee-d031-22a7-74ba-b21b0baea383&version=1.4.0: dial ...
Hint: Some lines were ellipsized, use -l to show in full.
[root@pub-node-1 ~]# 
[root@pub-node-1 ~]# cp /tmp/consul.json /etc/consul.json 
cp: overwrite ‘/etc/consul.json’? y
[root@pub-node-1 ~]# 
[root@pub-node-1 ~]# cat /etc/consul.json 
{
        "retry_join" : ["provider=os tag_key=group tag_value=node user_name=xxxx password=xxxx auth_url=https://xxxx:5000/v3 project_id=0505293ce38547adacb65ff1a5430815 domain_name=Default insecure=true"],
        "disable_remote_exec": true
}
[root@pub-node-1 ~]#
[root@pub-node-1 ~]# systemctl restart consul
[root@pub-node-1 ~]# systemctl status consul
● consul.service - Cluster Controlled consul
   Loaded: loaded (/etc/systemd/system/consul.service; enabled; vendor preset: disabled)
  Drop-In: /run/systemd/system/consul.service.d
           └─50-pacemaker.conf
   Active: active (running) since Fri 2018-11-30 14:57:20 CET; 6s ago
     Docs: http://www.consul.io
 Main PID: 14135 (consul)
   CGroup: /system.slice/consul.service
           └─14135 /usr/local/bin/consul agent -syslog -bind=172.16.0.6 -enable-script-checks -server -ui -bootstrap-expect 3 -domain services -datacenter xxxx -dns-port 8600 -config-file=/etc/consul.json -data-dir=/var/lib/co...

Nov 30 14:57:23 pub-node-1.novalocal consul[14135]: discover-os: Filter instances with group=node
Nov 30 14:57:23 pub-node-1.novalocal consul[14135]: discover-os: Filter instances with group=node
Nov 30 14:57:23 pub-node-1.novalocal consul[14135]: discover-os: Filter instances with group=node
Nov 30 14:57:23 pub-node-1.novalocal consul[14135]: discover-os: Filter instances with group=node
Nov 30 14:57:23 pub-node-1.novalocal consul[14135]: agent: Discovered LAN servers: 172.16.0.12 172.16.0.7 172.16.0.6
Nov 30 14:57:23 pub-node-1.novalocal consul[14135]: agent: (LAN) joining: [172.16.0.12 172.16.0.7 172.16.0.6]
Nov 30 14:57:23 pub-node-1.novalocal consul[14135]: agent: (LAN) joined: 3 Err: <nil>
Nov 30 14:57:23 pub-node-1.novalocal consul[14135]: 2018/11/30 14:57:23 [INFO] agent: (LAN) joined: 3 Err: <nil>
Nov 30 14:57:23 pub-node-1.novalocal consul[14135]: 2018/11/30 14:57:23 [INFO] agent: Join LAN completed. Synced with 3 initial agents
Nov 30 14:57:23 pub-node-1.novalocal consul[14135]: agent: Join LAN completed. Synced with 3 initial agents
[root@pub-node-1 ~]# 

```

### Operating system and Environment details

Use consul version 1.4.0 and Openstack APIv3 endpoints.

**Comment by pearkes** [comment] 2018-11-30 20:40
I believe this is a duplicate of #4491 / hashicorp/go-discover#62.

Would love help debugging this further as I think it's been an issue since the release mentioned above for some versions of OpenStack.

**Closed by pearkes** 2018-11-30 20:40 UTC
