### ISSUE TITLE
Consul KV CLI 'GET' flags can't be set together

### ISSUE THREAD

**Issue by MatthiasGrandl** [hashicorp/consul#13412] opened 2022-06-09 17:34 UTC
So pretty weird issue:
I am creating 2 prefixes, one empty, one not empty like this...

```bash
consul kv put testprefix/
consul kv put testprefix2/testkey
```

then when I curl those prefixes recursively like:
```bash
curl localhost:8500/v1/kv/testprefix?keys
# this is the reply -> ["testprefix/","testprefix2/testkey"]
```

notice how only testprefix/ is specifically listed?

now odly enough this diverges from how the CLI behaves:

```bash
consul kv get -keys -recurse testprefix
# testprefix/
# testprefix2/
```

when you then put a key into the first prefix, it still gets listed with curl.

```bash
curl localhost:8500/v1/kv/testprefix?keys
# this is the reply -> ["testprefix/","testprefix/testkey","testprefix2/testkey"]
```

if you then issue another put on testprefix2, it will also be listed by the API

```bash
consul kv put testprefix2/
curl localhost:8500/v1/kv/testprefix?keys
# this is the reply -> ["testprefix/","testprefix/testkey","testprefix2/","testprefix2/testkey"]
```

I don't know if this is expected, but I feel like this behavior is a bit wonky...
I would expect the API to either always show prefixes, or to never show them.

**Comment by Amier3** [comment] 2022-06-09 20:45
Hey @MatthiasGrandl 

I see this is your first issue so welcome to the consul community! This is definitely weird behavior. Two things I noticed:  

1. The CLI didn't successfully give you the recursive value for `testprefix2`.  It looks like this is because `-key` and `-recurse` actually can't be set together. They're currently set up as [case statements](https://github.com/hashicorp/consul/blob/147476c10dd39ac940c60b6cac158c1b26256057/command/kv/get/kv_get.go#L116) so the `-recurse` isn't getting executed. I was able to run  `consul kv get -recurse testprefix` without `-keys` and successfully get back: 

```
testprefix/:
testprefix/testkey:
testprefix2/testkey:
```

2. You're seeing the intended behavior by seeing the the prefixes listed with the nested keys, but consul currently doesn't create root keys impliclity. Looks like this is [ intentional  ](https://github.com/hashicorp/consul/blob/147476c10dd39ac940c60b6cac158c1b26256057/api/kv.go#L159) and not a bug. It would definitely be less confusing if creating `testprefix2/testkey` lead to `testprefix2/` and `testprefix2/testkey` showing up in the API response.


#1 would be the easier thing to fix. #2 would requiring reworking the KV API which would be hard to prioritize. If it's okay with you, I can rename this issue  to reflect #1 and add a `good first issue` label to invite community members to fix the first issue 😄

**Comment by MatthiasGrandl** [comment] 2022-06-10 03:31
Sure that’s ok with me! Definitely not urgent either. I was just confused while playing around with consul.

**Comment by DanStough** [comment] 2022-08-25 22:25
@Amier3 I think we're good to close this one now, as I think we'd want to have more discussion about changing the behavior of root keys. Would you agree?

**Closed** 2023-07-27 16:51 UTC
Labels: type/enhancement, good first issue, theme/kv
