### ISSUE TITLE
Put information about associated service in environment of health checks

### ISSUE THREAD

**Issue by aidanhs** [hashicorp/consul#1176] opened 2015-08-16 20:05 UTC
I was pretty surprised nobody else has requested this so I had a look around, but no joy. I'm possibly missing something.

Let's say I have a health check I want to PUT via the http api like so:

```
{
  "Name": "mycheck",
  "ServiceID": "myservice",
  "Script": "curl localhost:6000 | grep -q mymatchstring",
  "Interval": "10s"
}
```

Note that I've had to hardcode the fact that this is located on port 6000. As far as I can tell, without doing something like this there is no way for a script check to get information about the service it's meant to check. My proposal would be to expose information in the environment (either the whole service json in one env variable, or individual env variables for port, name etc).

Then I could use an identical value for `Script` for all instances of a named service, even if they're on the same machine.

**Comment by aidanhs** [comment] 2015-08-17 03:15
On reflection, the only environment variable that you *need* is the service id the check is running for. If you need extra information you can make api requests as required.

**Comment by slackpad** [comment] 2015-08-17 20:07
This seems like a reasonable thing to want to do - I don't see a way people are getting around hard-coding, other than possibly using DNS.

**Comment by aidanhs** [comment] 2015-08-17 20:49
I too thought about DNS. Then I observed that as soon as the health check fails it'll always fail because it's removed from DNS.

**Comment by slackpad** [comment] 2015-08-17 20:51
Ah true, though DNS for the service host would be funky anyway since it'll randomly pick one. I was thinking for the service port.

**Comment by Tornado-Tim** [comment] 2015-09-07 00:25
+1 this request, I want to write a script that do multiple service checks but all the nodes and services are on dynamic IPs and ports. I have no way of getting the list of services ip and port. It would be great if consul could call the check script with params of the services on the node that check is being done on.

**Comment by gtmtech** [comment] 2015-12-11 11:37
+1 for this request

**Comment by brandoncormany** [comment] 2016-05-25 03:36
Any movement on this? 

I have this exact need with wanting to perform health checks on containers but they will start on dynamic ports.

**Comment by slackpad** [comment] 2017-05-02 22:49
Closing as a duplicate of #202.

**Closed by slackpad** 2017-05-02 22:49 UTC
Labels: enhancement
