### ISSUE TITLE
Hashicorp Buster APT package - Problem with MergeList /var/lib/apt/lists/apt.releases.hashicorp.com_dists_buster_main_binary-amd64_Packages.lz4

### ISSUE THREAD

**Issue by fitzy101** [hashicorp/consul#12181] opened 2022-01-25 01:42 UTC
#### Overview of the Issue
The consul package is broken on Debian Buster which is causing any `apt` commands to fail. This is the exact same issue as seen here https://github.com/hashicorp/consul/issues/11162..

#### Reproduction Steps

Follow the instructions from the [Ubuntu/Debian](https://learn.hashicorp.com/tutorials/consul/get-started-install) installation guide.

```
$ curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
$ sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
$ sudo apt-get update && sudo apt-get install consul
```

At this point you'll see output like

```
root@61dada14fcac:/# apt-get update && apt-get install consul
Hit:1 http://security.debian.org/debian-security buster/updates InRelease
Hit:2 https://apt.releases.hashicorp.com buster InRelease
Hit:3 http://deb.debian.org/debian buster InRelease
Hit:4 http://deb.debian.org/debian buster-updates InRelease
Reading package lists... Error!
E: Encountered a section with no Package: header
E: Problem with MergeList /var/lib/apt/lists/apt.releases.hashicorp.com_dists_buster_main_binary-amd64_Packages.lz4
E: The package lists or status file could not be parsed or opened.
```

### Operating system and Environment details

Debian Buster (the example above was in a docker container).

---

The issue is because of additional metadata that can be seen in the file located at https://apt.releases.hashicorp.com/dists/buster/main/binary-amd64/Packages - specifically the block

```
Filename: pool/amd64/main/consul_1.10.6-2_amd64.deb
SHA1: cb816a6eba8e327693b5b2e2be24baa3cb7d213f
SHA256: be9b4c3fa598a7c494912a8274ec2cebde406966aea763047f43bba94e1f39e5
Size: 38184670
```

**Comment by Amier3** [comment] 2022-01-25 14:52
Hey @fitzy101,

Thanks for the report! We'll get this sorted out with the help of @hashicorp/release-engineering , and keep this issue updated as we work on a fix. In the meantime, I pinned this issue at the top of our board for visibility due to the severity, and I  invite anyone to comment a work-around if they find one.

**Comment by Amier3** [comment] 2022-01-25 15:30
This issue should be resolved now. I'll leave this issue open for a bit so folks can test for themselves and verify 👍

**Comment by matt-moses** [comment] 2022-01-25 18:07
Thank you for resolving this so quickly!

**Comment by BenLiyanage** [comment] 2022-01-27 23:52
I am still having this problem.  Is there a regression?

**Comment by fitzy101** [comment] 2022-01-28 00:03
> I am still having this problem. Is there a regression?

I'm not able to repro the issue using the steps in the OP, so it doesn't look like it.

**Comment by DennisTT** [comment] 2022-01-28 00:08
> I am still having this problem. Is there a regression?

I'm seeing the same issue with xenial
`Get:8 https://apt.releases.hashicorp.com xenial/main amd64 Packages [46.9 kB]`
```E: Encountered a section with no Package: header
E: Problem with MergeList /var/lib/apt/lists/apt.releases.hashicorp.com_dists_xenial_main_binary-amd64_Packages
E: The package lists or status file could not be parsed or opened.```

**Comment by andykmiles** [comment] 2022-01-28 19:09
I have this issue having installed vagrant ; same as op

**Comment by ypadlyak** [comment] 2022-01-28 20:12
> E: Encountered a section with no Package: header
> E: Problem with MergeList /var/lib/apt/lists/apt.releases.hashicorp.com_dists_hirsute_main_binary-amd64_Packages

also happening in  Ubuntu hirsute

**Comment by ylfingr** [comment] 2022-01-31 18:03
It happened again @ Mon 31 Jan 2022 07:02:19 PM CET.

```
Reading package lists... Error!
E: Encountered a section with no Package: header
E: Problem with MergeList /var/lib/apt/lists/apt.releases.hashicorp.com_dists_buster_main_binary-amd64_Packages
E: The package lists or status file could not be parsed or opened.
axel.schmalowsky@myra-app-stg-fra3:~$ less /var/lib/apt/lists/apt.releases.hashicorp.com_dists_buster_main_binary-amd64_Packages
```

```
Filename: pool/amd64/main/vault_1.6.7_amd64.deb
SHA1: 0118c82ecdcc35cba05fb1bcea88b30b44b6ec00
SHA256: 1bf5193311a4922546abd0877e63416546d04d366915e3f876bc4b8dd83dcce2
Size: 65196942
```

**Comment by mdeggies** [comment] 2022-01-31 18:46
Hey all- We're actively looking into this and will post an update as soon as we can.

**Comment by ylfingr** [comment] 2022-01-31 20:34
Seems to be fixed now. Thanks.

**Comment by ptous** [comment] 2022-01-31 21:09
Seconded. We're able to install Consul from the Hashicorp repo now.

**Comment by malaney** [comment] 2022-02-01 13:59
I am definitely still experiencing this issue 

```
  sudo apt-get -y install build-essential
  shell: /bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.7.11/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.7.11/x64/lib
Reading package lists...
E: Encountered a section with no Package: header
E: Problem with MergeList /var/lib/apt/lists/apt.releases.hashicorp.com_dists_bionic_main_binary-amd64_Packages
E: The package lists or status file could not be parsed or opened.
```

**Comment by shaneholloman** [comment] 2022-02-02 02:55
```sh
(ssh) sholloman@tower : ~
[100] % sudo apt dist-upgrade -y
Reading package lists... Error!
E: Encountered a section with no Package: header
E: Problem with MergeList /var/lib/apt/lists/apt.releases.hashicorp.com_dists_hirsute_main_binary-amd64_Packages
E: The package lists or status file could not be parsed or opened.
```

**Comment by shaneholloman** [comment] 2022-02-02 02:57
@Amier3 still an issue

**Comment by kpenfound** [comment] 2022-02-02 05:05
Hi @shaneholloman , have you run `apt update` recently? and if not, does the problem persist after running `apt update`?

**Comment by shaneholloman** [comment] 2022-02-03 00:21
@kpenfound lol! well that's embarrassing!
Just needed to `apt update`

**Closed** 2022-02-04 16:49 UTC
Labels: type/bug, theme/packaging

**Comment by sathieu** [comment] 2022-07-22 09:51
@Amier3 The problem is back. See https://github.com/hashicorp/terraform/issues/31493 and https://github.com/hashicorp/consul/issues/13850.

**Comment by sathieu** [comment] 2022-07-22 09:54
@kpenfound The problem is back. See https://github.com/hashicorp/terraform/issues/31493 and https://github.com/hashicorp/consul/issues/13850.

**Comment by dxps** [comment] 2023-05-04 06:15
I know this ticket is closed, but just wanted to say that `apt update` does not solve the problem.
Or it will solve as long as the issue is solved at central / hashicorp level.

```shell
~ ❯ sudo apt update
Hit:1 https://linux.teamviewer.com/deb stable InRelease
Get:2 https://apt.releases.hashicorp.com jammy InRelease [12.9 kB]                                                
Ign:3 https://apt.releases.hashicorp.com jammy/main i386 Packages                                                 
Get:4 https://apt.releases.hashicorp.com jammy/main amd64 Packages [83.7 kB]                                      
Hit:5 https://deb.nodesource.com/node_16.x jammy InRelease                                                        
Get:3 https://apt.releases.hashicorp.com jammy/main i386 Packages [31.3 kB]                                       
Err:3 https://apt.releases.hashicorp.com jammy/main i386 Packages                                                 
  File has unexpected size (31295 != 31290). Mirror sync in progress? [IP: 54.192.235.74 443]
  Hashes of expected file:
   - Filesize:31290 [weak]
   - SHA256:a1aba716abdbf9f2e3bc13d25734ff9fcc58a399698795ebc98f7cec76146d2e
   - SHA1:20e1b9792e678e5223d1387e4e5effaf5a4ca24f [weak]
   - MD5Sum:647502cff7f79ac8a4641b6519696b30 [weak]
  Release file created at: Wed, 03 May 2023 21:28:51 +0000
Get:6 https://packages.microsoft.com/repos/ms-teams stable InRelease [5,931 B]                                    
Hit:8 https://packages.microsoft.com/repos/code stable InRelease                    
...
Reading package lists... Done
E: Failed to fetch https://apt.releases.hashicorp.com/dists/jammy/main/binary-i386/Packages.bz2  File has unexpected size (31295 != 31290). Mirror sync in progress? [IP: 54.192.235.74 443]
   Hashes of expected file:
    - Filesize:31290 [weak]
    - SHA256:a1aba716abdbf9f2e3bc13d25734ff9fcc58a399698795ebc98f7cec76146d2e
    - SHA1:20e1b9792e678e5223d1387e4e5effaf5a4ca24f [weak]
    - MD5Sum:647502cff7f79ac8a4641b6519696b30 [weak]
   Release file created at: Wed, 03 May 2023 21:28:51 +0000
E: Some index files failed to download. They have been ignored, or old ones used instead.
~ took 7s❯
```

**Comment by munarh** [comment] 2023-05-04 10:07
> I know this ticket is closed, but just wanted to say that `apt update` does not solve the problem. Or it will solve as long as the issue is solved at central / hashicorp level.
> 
> ```shell
> ~ ❯ sudo apt update
> Hit:1 https://linux.teamviewer.com/deb stable InRelease
> Get:2 https://apt.releases.hashicorp.com jammy InRelease [12.9 kB]                                                
> Ign:3 https://apt.releases.hashicorp.com jammy/main i386 Packages                                                 
> Get:4 https://apt.releases.hashicorp.com jammy/main amd64 Packages [83.7 kB]                                      
> Hit:5 https://deb.nodesource.com/node_16.x jammy InRelease                                                        
> Get:3 https://apt.releases.hashicorp.com jammy/main i386 Packages [31.3 kB]                                       
> Err:3 https://apt.releases.hashicorp.com jammy/main i386 Packages                                                 
>   File has unexpected size (31295 != 31290). Mirror sync in progress? [IP: 54.192.235.74 443]
>   Hashes of expected file:
>    - Filesize:31290 [weak]
>    - SHA256:a1aba716abdbf9f2e3bc13d25734ff9fcc58a399698795ebc98f7cec76146d2e
>    - SHA1:20e1b9792e678e5223d1387e4e5effaf5a4ca24f [weak]
>    - MD5Sum:647502cff7f79ac8a4641b6519696b30 [weak]
>   Release file created at: Wed, 03 May 2023 21:28:51 +0000
> Get:6 https://packages.microsoft.com/repos/ms-teams stable InRelease [5,931 B]                                    
> Hit:8 https://packages.microsoft.com/repos/code stable InRelease                    
> ...
> Reading package lists... Done
> E: Failed to fetch https://apt.releases.hashicorp.com/dists/jammy/main/binary-i386/Packages.bz2  File has unexpected size (31295 != 31290). Mirror sync in progress? [IP: 54.192.235.74 443]
>    Hashes of expected file:
>     - Filesize:31290 [weak]
>     - SHA256:a1aba716abdbf9f2e3bc13d25734ff9fcc58a399698795ebc98f7cec76146d2e
>     - SHA1:20e1b9792e678e5223d1387e4e5effaf5a4ca24f [weak]
>     - MD5Sum:647502cff7f79ac8a4641b6519696b30 [weak]
>    Release file created at: Wed, 03 May 2023 21:28:51 +0000
> E: Some index files failed to download. They have been ignored, or old ones used instead.
> ~ took 7s❯
> ```

I am having the same issue, trying to install VirtualBox and i am getting this error.
