### ISSUE TITLE
Sending data to Prometheus statsd_exporter generates errors

### ISSUE THREAD

**Issue by aantono** [hashicorp/consul#1855] opened 2016-03-21 17:54 UTC
Using Consul 0.6.3 configured to send data to the [statsd_exporter](https://github.com/prometheus/statsd_exporter) endpoint of Prometheus monitoring tool via `statsd_addr` telemetry config.
The exporter is full of errors of this kind:
`time="2016-03-21T17:32:40Z" level=info msg="Bad line from StatsD: consu" file=exporter.go line=307`

This looks related to https://github.com/hashicorp/consul/issues/1302

**Comment by magiconair** [comment] 2017-05-30 13:52
Looking

**Comment by magiconair** [comment] 2017-05-30 14:17
Hi @aantono, I cannot reproduce this. This is how I tried:

```
# config.json
{
	"server": true,
	"data_dir": "data",
	"bootstrap": true,
	"statsd_addr": "127.0.0.1:9125"
}

# start consul
$ ~/consul-0.6.3/consul agent -config-file config.json

# run nc in UDP mode
$ nc -u -l 9125
consul.raft.state.follower:1.000000|c
consul.memberlist.msg.alive:1.000000|c
consul.serf.member.join:1.000000|c
consul.serf.snapshot.appendLine:0.013041|ms
consul.memberlist.msg.alive:1.000000|c
consul.serf.member.join:1.000000|c
consul.serf.snapshot.appendLine:0.012573|ms
consul.memberlist.gossip:0.045012|ms
consul.memberlist.gossip:0.009695|ms
consul.memberlist.gossip:0.030488|ms
consul.memberlist.gossip:0.020021|ms
consul.memberlist.gossip:0.013907|ms

# install statsd_exporter
$ go get -u github.com/prometheus/statsd_exporter

# run statsd_exporter
$ statsd_exporter
WARN[0000] Warning: Using -statsd.add-suffix is discouraged. We recommend explicitly naming metrics appropriately in the mapping configuration.  source=main.go:126
INFO[0000] Starting StatsD -> Prometheus Exporter (version=, branch=, revision=)  source=main.go:128
INFO[0000] Build context (go=go1.8.3, user=, date=)      source=main.go:129
INFO[0000] Accepting StatsD Traffic on :9125             source=main.go:130
INFO[0000] Accepting Prometheus Requests on :9102        source=main.go:131

# check webui
$ curl localhost:9102/metrics
# HELP consul_198_100_100_35_static_gorillaservers_com_consul_session_ttl_active_gauge Metric autogenerated by statsd_exporter.
# TYPE consul_198_100_100_35_static_gorillaservers_com_consul_session_ttl_active_gauge gauge
consul_198_100_100_35_static_gorillaservers_com_consul_session_ttl_active_gauge 0
# HELP consul_198_100_100_35_static_gorillaservers_com_runtime_alloc_bytes_gauge Metric autogenerated by statsd_exporter.
# TYPE consul_198_100_100_35_static_gorillaservers_com_runtime_alloc_bytes_gauge gauge
consul_198_100_100_35_static_gorillaservers_com_runtime_alloc_bytes_gauge 1.828864e+06
# HELP consul_198_100_100_35_static_gorillaservers_com_runtime_free_count_gauge Metric autogenerated by statsd_exporter.
...
```

Could you try upgrading the `statsd_exporter`? I'd also suggest to upgrade consul from 0.6.3 since it seems to hang during shutdown. At least on OSX I always have to `kill -9` it.

**Comment by magiconair** [comment] 2017-06-02 07:22
I'm going to close this one unless there is more evidence that this is still an issue with master. Please comment if there is and I'll re-open.

**Closed by magiconair** 2017-06-02 07:22 UTC
Labels: bug, theme/operator-usability, waiting-reply
