### ISSUE TITLE
Squish spurious CI test failures

### ISSUE THREAD

**Issue by chadwhitacre** [hashicorp/consul#3807] opened 2018-01-16 00:47 UTC
Viz.:

- https://github.com/hashicorp/consul/pull/3174#issuecomment-357792856
- https://github.com/hashicorp/consul/pull/3188#issuecomment-357791209
- https://github.com/hashicorp/consul/pull/2640#issuecomment-357806578
- https://github.com/hashicorp/consul/pull/3825 &rarr; https://travis-ci.org/hashicorp/consul/builds/331624683

First step could be dropping parallelization at Travis per https://github.com/hashicorp/consul/pull/3785, but https://github.com/hashicorp/consul/pull/3785#issuecomment-357367605 makes me think it won't be that simple.

**Comment by whit537** [comment] 2018-01-30 12:40
Possible dupe of #3693.

**Comment by pearkes** [comment] 2018-10-26 17:16
We've made great progress here in many PRs and as a result are seeing regularly green CI in Travis. We've also introduced a test workflow for reproducing flaky tests by mimicking the CI environment:

https://github.com/hashicorp/consul/blob/master/.github/CONTRIBUTING.md#testing

**Closed by pearkes** 2018-10-26 17:16 UTC
Labels: unit-test
