### ISSUE TITLE
Consul Agent wrongly report "critical" warning

### ISSUE THREAD

**Issue by hehailong5** [hashicorp/consul#3852] opened 2018-02-01 08:44 UTC
version: 0.8.4

scenario: 
1. register a service with ttl set to 6 seconds
2. update the ttl every 2 seconds

problem:
the agent will report "critical" warning every 1~2 minute

http log======>
   2018/02/01 12:51:43 [DEBUG] http: Request PUT /v1/agent/check/pass/service:_scp199_10.47.160.11_5005?note= (33.758878ms) from=127.0.0.1:45695

   2018/02/01 12:51:45 [DEBUG] http: Request PUT /v1/agent/check/pass/service:_scp199_10.47.160.11_5005?note= (8.670771ms) from=127.0.0.1:45545

   2018/02/01 12:52:00 [DEBUG] http: Request PUT /v1/agent/check/pass/service:_scp199_10.47.160.11_5005?note= (**12.793983375s**) from=127.0.0.1:45697

   2018/02/01 12:52:02 [DEBUG] http: Request PUT /v1/agent/check/pass/service:_scp199_10.47.160.11_5005?note= (12.555733971s) from=127.0.0.1:45892

   2018/02/01 12:52:02 [DEBUG] http: Request PUT /v1/agent/check/pass/service:_scp199_10.47.160.11_5005?note= (11.520031247s) from=127.0.0.1:45924

agent log========>
    2018/02/01 12:51:43 [DEBUG] agent: Check 'service:_scp199_10.47.160.11_5005' status is now passing
    2018/02/01 12:51:45 [DEBUG] agent: Check 'service:_scp199_10.47.160.11_5005' status is now passing
    **2018/02/01 12:51:51 [WARN] agent: Check 'service:_scp199_10.47.160.11_5005' missed TTL, is now critica**l
    2018/02/01 12:51:59 [DEBUG] agent: Check 'service:_scp199_10.47.160.11_5005' status is now passing
    2018/02/01 12:52:02 [DEBUG] agent: Check 'service:_scp199_10.47.160.11_5005' status is now passing

question:
1. notice that when this happens, the duration indicated in the "note" looks quite big. what this "note" indicates? and the application api also hangs here for quite long time

**Comment by slackpad** [comment] 2018-02-05 20:50
The `(12.793983375s)` means that the RPC took this long to complete, which looks very similar to https://github.com/hashicorp/consul/issues/3738 which you reported as well.

**Comment by slackpad** [comment] 2018-02-05 20:51
Closing this as a duplicate of #3738.

**Closed by slackpad** 2018-02-05 20:51 UTC

**Comment by hehailong5** [comment] 2018-02-06 01:41
Hi,
Will the ttl update rpc be forwarded to the servers as well?
I understand it is the agent handles all the stuff related to the health check and it looks to me the #3738 was addressing some issue related to the servers.

**Comment by slackpad** [comment] 2018-02-06 02:21
> Will the ttl update rpc be forwarded to the servers as well?

It doesn't directly, but if the anti-entropy sync process is stuck because of a problem writing to the servers it can hold the check lock that the TTL update is trying to get, which can cause updates like this to fail.

**Comment by alitvak69** [comment] 2018-10-05 04:28
Sorry to piggyback on the issue but as recent as 10/01 we have experienced a system-wide outage because of the similar lockups.   With  TTL set u to 3 seconds for a number of services we had a wave of times out where TTL was exceeding 3 - 5 seconds.  Since this is a fairly small cluster updates normally take mS or even uS for us.   Can you please review the issue and let us know what may be done to prevent it from happening again.  

Any help is greatly appreciated,
