### ISSUE TITLE
ID field on service check

### ISSUE THREAD

**Issue by decoomanj** [hashicorp/consul#1289] opened 2015-10-12 15:26 UTC
Consul generates new IDs for service-health checks automatically. A client which does a TTL check has to figure out the ID by itself (the ID will be generated as service:<service-id>:<num>). It would be helpful to set a custom id to help the client know which check is doing what:

```json
{
  "service": {
    "name": "redis",
    "tags": ["master"],
    "address": "127.0.0.1",
    "port": 8000,
    "checks": [
      {
        "id": "myid",
        #..... whatever 
        "interval": "10s"
      }
    ]
  }
```

Like this, the client could update his TTL without guessing the ID.

**Comment by slackpad** [comment] 2016-02-02 22:42
Closing this as a duplicate of https://github.com/hashicorp/consul/issues/740.

**Closed by slackpad** 2016-02-02 22:42 UTC
Labels: enhancement
