### ISSUE TITLE
Consul UI doesn't handle large number of failing service checks very well

### ISSUE THREAD

**Issue by pvandervelde** [hashicorp/consul#6592] opened 2019-10-08 04:00 UTC
#### Overview of the Issue

When there are a large number of failing service checks the UI control overflows into the passing services area.

![image](https://user-images.githubusercontent.com/96201/66366318-8423c080-e9ec-11e9-8158-33a363c23b9c.png)

#### Reproduction Steps

* Create a service with many service checks that are failing
* Turn on consul UI
* See overflow as per above

### Consul info for both Client and Server

</details>

<details>
  <summary>Client info</summary>

```
agent:
        check_monitors = 0
        check_ttls = 0
        checks = 16
        services = 16
build:
        prerelease =
        revision = 9be6dfc3
        version = 1.6.1
consul:
        acl = disabled
        known_servers = 3
        server = false
runtime:
        arch = amd64
        cpu_count = 2
        goroutines = 120
        max_procs = 2
        os = linux
        version = go1.12.1
serf_lan:
        coordinate_resets = 0
        encrypted = true
        event_queue = 0
        event_time = 361
        failed = 0
        health_score = 0
        intent_queue = 0
        left = 1
        member_time = 5087
        members = 51
        query_queue = 0
        query_time = 10
```

</details>

<details>
  <summary>Server info</summary>

```
agent:
        check_monitors = 0
        check_ttls = 0
        checks = 0
        services = 0
build:
        prerelease =
        revision = 9be6dfc3
        version = 1.6.1
consul:
        acl = disabled
        bootstrap = false
        known_datacenters = 3
        leader = false
        leader_addr = 172.17.35.19:8300
        server = true
raft:
        applied_index = 33350890
        commit_index = 33350890
        fsm_pending = 0
        last_contact = 11.75002ms
        last_log_index = 33350890
        last_log_term = 27636
        last_snapshot_index = 33345705
        last_snapshot_term = 27636
        latest_configuration = [{Suffrage:Voter ID:eef6b17a-57c5-bed0-2db7-c50e323c8848 Address:172.17.35.19:8300} {Suffrage:Voter ID:78b92c13-9c2a-2411-e4b3-b93a00e13fdf Address:172.17.35.16:8300} {Suffrage:Voter ID:9a5770c4-1117-e214-2969-1fd6aa6f1f47 Address:172.17.35.17:8300}]
        latest_configuration_index = 33154536
        num_peers = 2
        protocol_version = 3
        protocol_version_max = 3
        protocol_version_min = 0
        snapshot_version_max = 1
        snapshot_version_min = 0
        state = Follower
        term = 27636
runtime:
        arch = amd64
        cpu_count = 1
        goroutines = 657
        max_procs = 2
        os = linux
        version = go1.12.1
serf_lan:
        coordinate_resets = 0
        encrypted = true
        event_queue = 0
        event_time = 361
        failed = 1
        health_score = 0
        intent_queue = 0
        left = 5
        member_time = 5087
        members = 55
        query_queue = 0
        query_time = 10
serf_wan:
        coordinate_resets = 0
        encrypted = true
        event_queue = 0
        event_time = 1
        failed = 0
        health_score = 0
        intent_queue = 0
        left = 0
        member_time = 571
        members = 9
        query_queue = 0
        query_time = 1
```

</details>

### Operating system and Environment details

Ubuntu 16.04 for both server and client

**Comment by johncowen** [comment] 2019-10-08 16:56
Hi @pvandervelde !

Thanks for posting this! I had a quick look today at trying to reproduce this and couldn't. Here's an example of what I'm seeing:

![Screenshot 2019-10-08 at 17 53 00](https://user-images.githubusercontent.com/554604/66415868-81c56480-e9f4-11e9-8069-e22dc6256c8b.png)

I tried quite a few combinations but obviously not the one you were using!

I think first things first, could you post the exact browser/version you are using? Looking at those fonts in your screengrab it looks like you are on linux there? If you can let me know that info and I can check using the same browser/version.

If we get no joy there, then if you could help me try to recreate your UI that would be great (a redacted dump of `/v1/internal/ui/nodes` would be ideal but understand you might not be able to provide that)

Thanks!

**Comment by pvandervelde** [comment] 2019-10-08 20:21
Hi @johncowen 

I'm on a Windows 10 box (Version 1903, build 18362.387). The browser is firefox (69.0.2 x64). 

I just tried running the export and got `[]` but that service is no longer in error mode. I shall try again when it errors out.

**Comment by pvandervelde** [comment] 2019-10-08 22:07
Given that this is in our test environment I replaced the service to recreate the issue.

It looks to be a Chrome vs Firefox thing. It works in Chrome but fails in Firefox.

**Comment by johncowen** [comment] 2019-10-09 08:28
Ah perfect thankyou! I gave it a quick go in my FF here which is 69.0.1 and its still a no go for me (but that's macOS).

![Screenshot 2019-10-09 at 09 08 03](https://user-images.githubusercontent.com/554604/66463260-a9f4a800-ea74-11e9-84a0-88717629b6c0.png)

I did notice one little overflow of about 5 pixels outside the containing box, but its never greater than ~5px, which isn't ideal but wouldn't cause the issue you are seeing I don't think (its a bit difficult to see in the below screengrab but you can just about see that the bottom of the column is ~5px outside of the containing element)

![Screenshot 2019-10-09 at 09 09 07](https://user-images.githubusercontent.com/554604/66463358-cee91b00-ea74-11e9-826a-c7edd007957c.png)

I also see that ^ in Chrome though, so that makes me think even more that this isn't related.

---

I'm going to try on a Windows machine a little later, but I'm thinking its more likely to be something to do with the JSON you are receiving (possibly).

We had a similar thing a while back where unexpected empty values in the JSON response would play havoc with the layout due to lack of unique id's - my rubbish spidey senses are making me think this _might_ be a similar thing, but they are the very same senses that made me think you were on linux 😆 

I'm guessing it might be a bit painful for you to redact parts of the JSON response from `/v1/internal/ui/nodes`? But if possible could you save off the response at that endpoint the next time you see the problem just so you have it, and we can go from there.

I'll pop back later once I've tried on a Windows machine.

**Comment by pvandervelde** [comment] 2019-10-09 09:36
Is that a KV entry or a UI entry? I tried getting it from the KV and that gave me an empty array so I'm guessing that's not it.

It's fairly easy for me to reproduce the issue (on Firefox on windows that is) so I'll grab it tomorrow when I'm back in the office (NZ time here)

**Comment by johncowen** [comment] 2019-10-09 09:39
Perfect thanks @pvandervelde . If you are running on localhost (guessing you're not) it would be `http://localhost:8500/v1/internal/ui/nodes?dc=dc-name`.

Have a good evening!

**Comment by pvandervelde** [comment] 2019-10-14 00:22
I grabbed the data you were asking about. Is there a sensible way to get it to you? Not sure it's wise posting it on the world wide intertubes

**Comment by johncowen** [comment] 2019-10-14 08:11
Hey Patrick!

Sorry mate, I was trying to keep my head down on a new feature we are adding over the past couple of weeks. Definitely don't post that on the `tubes if it contains things that should be redacted!

I think we have an email address we use for such things, I'm just finding out the correct process for that and I'll come back to you, thanks for your patience!

John

**Comment by johncowen** [comment] 2019-10-14 13:52
Hi Patrick,

When you get a moment, if you send that response in an email to `consul-oss-debug` at our usual/main domain name that'd be great.

Thanks,

John

**Comment by pvandervelde** [comment] 2019-10-14 18:17
Done :)

**Comment by johncowen** [comment] 2019-10-15 08:10
Perfect, thanks Patrick we got that, I'll be back in touch here when I've taken a look (should be over the next few days)

**Comment by johncowen** [comment] 2019-11-19 11:09
Hi @pvandervelde 

So sorry for the delay with this! I've just managed to try out the JSON you sent over. I tried in FF69.0.2 on macOS and FF70.0.1 on a Win10 machine. I could not replicate the issue, even with the JSON you sent over.

Let me know your thoughts, if we can think of anything else we can try I'd happily try to reproduce.

Thanks

**Comment by johncowen** [comment] 2019-12-17 13:22
Hi, I'm going to close this. Please feel free to reopen or make a new issue if this continues to cause problems,

**Closed by johncowen** 2019-12-17 13:22 UTC
Labels: bug, ui, waiting-reply
