### ISSUE TITLE
Health checks should track timestamp of last transition

### ISSUE THREAD

**Issue by superfell** [hashicorp/consul#825] opened 2015-03-30 18:19 UTC
The API reports the health check status of the checks, but doesn't indicate when the last transition was, this would be particularly useful to track when a check started failing. Either an explicit timestamp of when the check started failing, or a timestamp of the last state transition would be useful.

**Comment by ryanuber** [comment] 2015-03-30 18:31
Dupe of #461. Let's track exposing timestamps there, thanks!

**Closed by ryanuber** 2015-03-30 18:31 UTC
