### ISSUE TITLE
comment support

### ISSUE THREAD

**Issue by 435242634** [hashicorp/consul#3767] opened 2017-12-22 08:18 UTC
Consul kv store whether to support comments？like this:
![image](https://user-images.githubusercontent.com/13010570/34290683-bddbb840-e733-11e7-867c-066bb09649f7.png)

**Comment by alxark** [comment] 2017-12-24 15:58
I made another issue earlier (#3699)  by still waiting for any reply

**Comment by slackpad** [comment] 2018-01-04 02:37
Closing as a duplicate of #3699.

**Closed by slackpad** 2018-01-04 02:37 UTC
