### ISSUE TITLE
Consul to choose first private IP or IP from interface

### ISSUE THREAD

**Issue by grobinson-blockchain** [hashicorp/consul#1959] opened 2016-04-18 15:26 UTC
By default Consul will choose the first private IP as the advertise addr and raise an error when more than one private IP exists (https://github.com/hashicorp/consul/pull/1119/files#diff-fe5bbec36b59d60740ddb62b3b2f6befR193).

This is quite annoying when you want to run Consul on a node that also runs Docker (since the `docker0` virtual network interface listens on `172.17.42.1`) and therefore requires the advertise-addr be set manually. I'd much prefer Consul to either choose the first private IP or to be able to specify the address to advertise via interface name because:

1. In Google Compute nodes acquire their addresses from DHCP. In the event of a node failing, restarting and acquiring a different private IP address from the DHCP server the Consul service will have to be re-configured by configuration management (on that node) before it can work correctly.

2. When using tools such as Packer to build deployable machine images it is not possible to determine the IP address that the node will acquire in the future (nor do you want to hardcode this dynamic metadata into the image) yet you most likely will know the interface you want to advertise on (for example: `eth0`). Therefore, you need configuration management or some other out-of-band way to re-configure Consul on startup.

**Comment by slackpad** [comment] 2016-05-19 02:47
Hi @grobinson-blockchain closing this as a duplicate of https://github.com/hashicorp/consul/issues/1110, but linking these. For the case of docker, we [baked this into the official image](https://github.com/hashicorp/docker-consul/blob/master/0.6/docker-entrypoint.sh#L9-L18) via the entrypoint script, but we are still looking into adding this support in Consul itself.

**Closed by slackpad** 2016-05-19 02:47 UTC
