### ISSUE TITLE
Reverse DNS forwarding to consul results in a loop

### ISSUE THREAD

**Issue by thetuxkeeper** [hashicorp/consul#1800] opened 2016-03-07 13:15 UTC
Hi,

we use bind9 in combination with consul.
Forwarding the RDNS zone to consul will result in a loop when querying non-existant IP addresses.

```
Mar 07 13:28:00 coreos-tst1-mgmt1 docker[2067]: 2016/03/07 12:28:00 [ERR] dns: recurse failed: read udp 10.30.8.6:37427->10.30.8.1:53: i/o timeout
Mar 07 13:28:00 coreos-tst1-mgmt1 docker[2067]: 2016/03/07 12:28:00 [ERR] dns: all resolvers failed for {109.9.30.10.in-addr.arpa. 12 1} from client 10.20.50.6:38573 (udp)
```

Is it possible to configure consul as authoritative for the RDNS zone?
Currently we use the work-around to disable `forward only` for the RDNS zone. Then bind will answer the request (by default the empty 10.in-addr.arpa. zone is used).

Thanks
Daniel

Bind9 config:

```
zone "30.10.in-addr.arpa" {
        type forward;
        forward only;
        forwarders {
                10.30.8.6;
                10.30.8.7;
                10.30.8.8;
        };
};
zone "tst.<domain>" {
        type forward;
        forward only;
        forwarders {
                10.30.8.6;
                10.30.8.7;
                10.30.8.8;
        };
};
```

Consul config:

```
{
    "ui": true,
    "server": true,
    "dns_config": {
        "allow_stale": true
    },
    "bootstrap_expect": 3,
    "client_addr": "0.0.0.0",
    "ports": {
        "dns": 53
    },
    "data_dir": "/var/local/consul",
    "datacenter": "dc1",
    "domain": "tst.<domain>",
    "recursor": "<bind server>",
    "advertise_addr": "10.30.8.6",
    "node_name": "coreos-tst1-mgmt1"
}

```

**Comment by slackpad** [comment] 2016-03-21 22:31
Hi @thetuxkeeper this currently isn't configurable, if there's a recursor defined then Consul will try to use it if the reverse lookup fails.

**Comment by slackpad** [comment] 2017-05-12 21:28
Closing as a duplicate of https://github.com/hashicorp/consul/issues/2795.

**Closed by slackpad** 2017-05-12 21:28 UTC
Labels: enhancement
