### ISSUE TITLE
RPM / DEB packages 

### ISSUE THREAD

**Issue by alex-leonhardt** [hashicorp/consul#871] opened 2015-04-20 13:45 UTC
Hi,

It'd be great if RPM / DEB packages would be available - maybe even go into EPEL repos ? 

Alex

**Comment by sethvargo** [comment] 2015-04-20 13:57
Hi @alex-leonhardt 

Thank you for opening an issue. This is a duplicate of https://github.com/hashicorp/consul/issues/61, but the short version is that we prefer to focus on building new features at this time. The nature of the static binary distribution makes it very easy to distribute and install without native OS packages. Perhaps this will be something we can revisit in the future, but it is not a top priority at this time. Please let me know if you have any questions.

**Closed by sethvargo** 2015-04-20 13:57 UTC

**Comment by james-lawrence** [comment] 2017-08-10 11:45
but not as easy as having a single repository that an end user can just add and then install from.
