### ISSUE TITLE
Consul returned an error. You may have visited a URL that is loading an unknown resource

### ISSUE THREAD

**Issue by FunnyYish** [hashicorp/consul#7659] opened 2020-04-17 09:09 UTC
#### Overview of the Issue

Consul returned an error. You may have visited a URL that is loading an unknown resource, so you can try going back to the root or try re-submitting your ACL Token/SecretID by going back to ACLs.
Try looking in our documentation
#### Reproduction Steps

Steps to reproduce this issue, eg:

1. Run `consul.exe agent -dev`
2. request http://localhost:8500/ with chrome  81.0.4044.113
3.
![image](https://user-images.githubusercontent.com/7588136/79552767-0f81bb00-80ce-11ea-9440-126d802dc2a8.png)

### Consul info for both Client and Server

consul version :consul_1.7.2_windows_amd64

### Operating system and Environment details

windows 10 enterprise LTSC x64

**Comment by johncowen** [comment] 2020-04-17 09:21
Hi @FunnyYish !

Could you take a look in Web Inspector/Developer Tools (View > Developer > Developer Tools) in your browser and take a look at the Network panel and see if you are getting any error responses?. If there are any red messages in the Console tab that would also help us to see what the problem could be.

Thanks,

**Comment by FunnyYish** [comment] 2020-04-20 02:58
Everything is OK in Network panel:
![image](https://user-images.githubusercontent.com/7588136/79709226-3b7e8580-82f4-11ea-9e3d-ee8e2daedd5b.png)

but there is a error in console panel:
![image](https://user-images.githubusercontent.com/7588136/79709294-6c5eba80-82f4-11ea-9e85-ebd56ebfa4e9.png)

Finally I found if I check the Disable cache in Network panel ,consul will works fine,no more error.But why  does consul 1.6.x works fine without checking the Disable cache?
![image](https://user-images.githubusercontent.com/7588136/79709710-8220af80-82f5-11ea-9e1a-0936c29cccbe.png)

**Comment by johncowen** [comment] 2020-04-20 08:39
Oh perfect thanks for posting that @FunnyYish !

So this seems to be the same problem as another [issue](https://github.com/hashicorp/consul/issues/7643) which we fixed here

https://github.com/hashicorp/consul/pull/7644

It seems to be a Chrome only problem, and even then only 'sometimes', and is related in some way to Chrome 'performance resources' sometimes not being available immediately when those resources are loaded from the cache. So all your extra info here ^ confirms all of that, so thanks for that!

As you point out here, disabling the cache, or even holding shift down and clicking the refresh button will avoid the problem, and of course other browsers are fine.

The code which introduced the situation for this bug to occur was actually introduced in 1.6, so I'm not entirely sure if matters could further be confused by newer Chrome versions.

The code that fails is related to us detecting HTTP/2 support to avoid restricting the number of HTTP requests for HTTP/1. The fix includes a better fallback so that if something like this happens again, at least it will fail gracefully (by just falling back to assuming HTTP/1) and not affect the functioning of the UI. 

Thanks again for reporting the issue, it was a bit of a nasty one!

I'll close this now we know it a dupe of 7643

**Closed by johncowen** 2020-04-20 08:39 UTC
