### ISSUE TITLE
When upgrading to consul 1.2.2, agents run consul watch handlers

### ISSUE THREAD

**Issue by giladsh1** [hashicorp/consul#4610] opened 2018-08-29 14:49 UTC
#### Overview of the Issue

I've upgraded my Consul cluster from v1.2.0 to 1.2.2.
The upgrade process was done on 3 Consul servers one by one.
After this upgrade, all agents in the cluster ran their consul watch handler.
This is major issue IMHO, since it unfortunately executed a lot of unnecessary scripts.

This issue could be related to #4609 

#### Reproduction Steps

Steps to reproduce this issue, eg:

1. Create a cluster with n client nodes n and n server nodes with version 1.2.0.
1. Create a consul watch for a key  on some node with a script as the handler.
1. Upgrade the Consul servers to 1.2.2 (one at the time).
1. The agents will execute the handler

### Consul info for both Client and Server

<details>
  <summary>Client info</summary>

```
agent:
	check_monitors = 3
	check_ttls = 0
	checks = 7
	services = 6
build:
	prerelease =
	revision = 28141971
	version = 1.2.0
consul:
	known_servers = 3
	server = false
runtime:
	arch = amd64
	cpu_count = 2
	goroutines = 115
	max_procs = 2
	os = linux
	version = go1.10.1
serf_lan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 1186
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 415
	member_time = 22158
	members = 1019
	query_queue = 0
	query_time = 1
```

</details>

<details>
  <summary>Server info</summary>

```
agent:
	check_monitors = 0
	check_ttls = 0
	checks = 4
	services = 0
build:
	prerelease =
	revision = e716d1b5
	version = 1.2.2
consul:
	bootstrap = false
	known_datacenters = 2
	leader = true
	leader_addr = 10.224.9.55:8300
	server = true
raft:
	applied_index = 1097012
	commit_index = 1097012
	fsm_pending = 0
	last_contact = 0
	last_log_index = 1097012
	last_log_term = 8
	last_snapshot_index = 1082924
	last_snapshot_term = 4
	latest_configuration = [{Suffrage:Voter ID:229cbf97-30ba-1e53-e02c-ccb3eeb46f28 Address:10.224.9.55:8300} {Suffrage:Voter ID:94cb10fb-3d55-f62a-3881-4743cdc4f300 Address:10.225.20.171:8300} {Suffrage:Voter ID:1822c202-23e1-b611-c72e-ff117ad70613 Address:10.226.20.21:8300}]
	latest_configuration_index = 1096050
	num_peers = 2
	protocol_version = 3
	protocol_version_max = 3
	protocol_version_min = 0
	snapshot_version_max = 1
	snapshot_version_min = 0
	state = Leader
	term = 8
runtime:
	arch = amd64
	cpu_count = 2
	goroutines = 5878
	max_procs = 2
	os = linux
	version = go1.10.1
serf_lan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 5
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 36
	member_time = 5679
	members = 245
	query_queue = 0
	query_time = 1
serf_wan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 1
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 2463
	members = 6
	query_queue = 0
	query_time = 1
```

</details>

### Operating system and Environment details

OS, Architecture, and any other information you can provide about the environment.

### Log Fragments

<details>
  <summary>Log</summary>

```
2018/08/29 13:21:48 [ERR] consul: "KVS.Get" RPC failed to server <ip-address>:8300: rpc error making call: rpc error making call: EOF
    2018/08/29 13:21:48 [ERR] http: Request GET /v1/kv/<key-path>/<key-name>?index=1626980, error: rpc error making call: rpc error making call: EOF from=127.0.0.1:2228
    2018/08/29 13:21:48 [ERR] consul.watch: Watch (type: key) errored: Unexpected response code: 500, retry in 5s
    2018/08/29 13:21:48 [ERR] consul: "KVS.Get" RPC failed to server <ip-address>:8300: rpc error making call: EOF
    2018/08/29 13:21:48 [ERR] http: Request GET /v1/kv/<key-path>>/<key-name>?index=1625538&stale=&wait=60000ms, error: rpc error making call: EOF from=127.0.0.1:44756
    2018/08/29 13:21:48 [ERR] consul: "Health.ServiceNodes" RPC failed to server <ip-address>:8300: rpc error making call: EOF
    2018/08/29 13:21:48 [ERR] consul: "Health.ServiceNodes" RPC failed to server <ip-address>:8300: rpc error making call: EOF
    2018/08/29 13:21:48 [ERR] http: Request GET /v1/health/service/<some-service>?index=2070811&passing=1&stale=&wait=60000ms, error: rpc error making call: EOF from=127.0.0.1:44792
    2018/08/29 13:21:48 [ERR] consul: "Health.ServiceNodes" RPC failed to server <ip-address>:8300: rpc error making call: EOF
    2018/08/29 13:21:48 [ERR] http: Request GET /v1/health/service/<some-service>?index=2067103&passing=1&stale=&wait=60000ms, error: rpc error making call: EOF from=127.0.0.1:44780
    2018/08/29 13:21:48 [ERR] consul: "Health.ServiceNodes" RPC failed to server <ip-address>:8300: rpc error making call: EOF
    2018/08/29 13:21:48 [ERR] http: Request GET /v1/health/service/<some-service>?index=2070899&passing=1&stale=&wait=60000ms, error: rpc error making call: EOF from=127.0.0.1:44800
    2018/08/29 13:21:48 [ERR] consul: "Health.ServiceNodes" RPC failed to server <ip-address>:8300: rpc error making call: EOF
    2018/08/29 13:21:48 [ERR] http: Request GET /v1/health/service/<some-service>?index=2070582&passing=1&stale=&wait=60000ms, error: rpc error making call: EOF from=127.0.0.1:44814
    2018/08/29 13:21:48 [ERR] consul: "Health.ServiceNodes" RPC failed to server <ip-address>:8300: rpc error making call: EOF
    2018/08/29 13:21:48 [ERR] http: Request GET /v1/health/service/<some-service>?index=2067060&passing=1&stale=&wait=60000ms, error: rpc error making call: EOF from=127.0.0.1:44816
    2018/08/29 13:21:48 [ERR] consul: "Health.ServiceNodes" RPC failed to server <ip-address>:8300: rpc error making call: EOF
    2018/08/29 13:21:48 [ERR] http: Request GET /v1/health/service/<some-service>?index=2068447&passing=1&stale=&wait=60000ms, error: rpc error making call: EOF from=127.0.0.1:44818
    2018/08/29 13:21:48 [ERR] consul: "Health.ServiceNodes" RPC failed to server <ip-address>:8300: rpc error making call: EOF
    2018/08/29 13:21:48 [ERR] http: Request GET /v1/health/service/<some-service>?index=2067058&passing=1&stale=&wait=60000ms, error: rpc error making call: EOF from=127.0.0.1:44790
    2018/08/29 13:21:48 [ERR] consul: "Health.ServiceNodes" RPC failed to server <ip-address>:8300: rpc error making call: EOF
    2018/08/29 13:21:48 [ERR] http: Request GET /v1/health/service/<some-service>?index=2070240&passing=1&stale=&wait=60000ms, error: rpc error making call: EOF from=127.0.0.1:44774
    2018/08/29 13:21:48 [ERR] consul: "KVS.Get" RPC failed to server <ip-address>:8300: rpc error making call: EOF
    2018/08/29 13:21:48 [ERR] http: Request GET /v1/kv/<key-path>>/<key-name>?index=1625539&stale=&wait=60000ms, error: rpc error making call: EOF from=127.0.0.1:44752
    2018/08/29 13:21:48 [ERR] consul: "Catalog.ListServices" RPC failed to server <ip-address>:8300: rpc error making call: EOF
    2018/08/29 13:21:48 [ERR] http: Request GET /v1/catalog/services?index=2070571&stale=&wait=60000ms, error: rpc error making call: EOF from=127.0.0.1:44754
    2018/08/29 13:21:49 [ERR] consul: "Health.ServiceNodes" RPC failed to server <ip-address>:8300: rpc error making call: EOF
    2018/08/29 13:21:49 [ERR] http: Request GET /v1/health/service/<some-service>?index=2070411&passing=1&stale=&wait=60000ms, error: rpc error making call: EOF from=127.0.0.1:44784
    2018/08/29 13:21:49 [ERR] consul: "Health.ServiceNodes" RPC failed to server <ip-address>:8300: rpc error making call: EOF
    2018/08/29 13:21:49 [ERR] http: Request GET /v1/health/service/<some-service>?index=2066912&passing=1&stale=&wait=60000ms, error: rpc error making call: EOF from=127.0.0.1:44794
    2018/08/29 13:21:49 [ERR] consul: "Health.ServiceNodes" RPC failed to server <ip-address>:8300: rpc error making call: EOF
    2018/08/29 13:21:49 [ERR] http: Request GET /v1/health/service/<some-service>?index=2070908&passing=1&stale=&wait=60000ms, error: rpc error making call: EOF from=127.0.0.1:44812
    2018/08/29 13:21:49 [ERR] consul: "Health.ServiceNodes" RPC failed to server <ip-address>:8300: rpc error making call: EOF
    2018/08/29 13:21:49 [ERR] http: Request GET /v1/health/service/<some-service>?index=2066044&passing=1&stale=&wait=60000ms, error: rpc error making call: EOF from=127.0.0.1:44786
    2018/08/29 13:21:49 [ERR] http: Request GET /v1/health/service/<some-service>?index=2070396&passing=1&stale=&wait=60000ms, error: rpc error making call: EOF from=127.0.0.1:44772
    2018/08/29 13:21:49 [ERR] consul: "KVS.Get" RPC failed to server <ip-address>:8300: rpc error making call: EOF
    2018/08/29 13:21:49 [ERR] http: Request GET /v1/kv/<key-path>>/<key-name>?index=1625542&stale=&wait=60000ms, error: rpc error making call: EOF from=127.0.0.1:44758
    2018/08/29 13:21:49 [ERR] consul: "KVS.Get" RPC failed to server <ip-address>:8300: rpc error making call: EOF
    2018/08/29 13:21:49 [ERR] http: Request GET /v1/kv/<key-path>>/<key-name>?index=1625540&stale=&wait=60000ms, error: rpc error making call: EOF from=127.0.0.1:44760
    2018/08/29 13:21:49 [ERR] consul: "Health.ServiceNodes" RPC failed to server <ip-address>:8300: rpc error making call: EOF
    2018/08/29 13:21:49 [ERR] http: Request GET /v1/health/service/<some-service>?index=2068639&passing=1&stale=&wait=60000ms, error: rpc error making call: EOF from=127.0.0.1:44788
    2018/08/29 13:21:49 [ERR] consul: "Health.ServiceNodes" RPC failed to server <ip-address>:8300: rpc error making call: EOF
    2018/08/29 13:21:49 [ERR] http: Request GET /v1/health/service/<some-service>?index=2070789&passing=1&stale=&wait=60000ms, error: rpc error making call: EOF from=127.0.0.1:44820
    2018/08/29 13:21:49 [ERR] consul: "Health.ServiceNodes" RPC failed to server <ip-address>:8300: rpc error making call: EOF
    2018/08/29 13:21:49 [ERR] http: Request GET /v1/health/service/<some-service>?index=2070898&passing=1&stale=&wait=60000ms, error: rpc error making call: EOF from=127.0.0.1:44798
    2018/08/29 13:22:01 [INFO] memberlist: Marking consul-server-1 as failed, suspect timeout reached (2 peer confirmations)
    2018/08/29 13:22:01 [INFO] serf: EventMemberFailed: consul-server-1 <ip-address>
    2018/08/29 13:22:01 [INFO] consul: removing server consul-server-1 (Addr: tcp/<ip-address>:8300) (DC: <dc-name>)
    2018/08/29 13:22:02 [INFO] serf: EventMemberJoin: consul-server-1 <ip-address>
    2018/08/29 13:22:02 [INFO] consul: adding server consul-server-1 (Addr: tcp/<ip-address>:8300) (DC: <dc-name>)
    2018/08/29 13:23:09 [INFO] agent: Synced check "service:mysql:3"
    2018/08/29 13:23:44 [ERR] consul: "KVS.Get" RPC failed to server <consul-server-ip>:8300: rpc error making call: EOF
    2018/08/29 13:23:44 [ERR] http: Request GET /v1/kv/<key-path>/<key-name>?index=2058194, error: rpc error making call: EOF from=127.0.0.1:44420
    2018/08/29 13:23:44 [ERR] consul.watch: Watch (type: key) errored: Unexpected response code: 500, retry in 5s
    2018/08/29 13:23:44 [ERR] consul: "KVS.Get" RPC failed to server <ip-address>:8300: rpc error making call: rpc error making call: EOF
    2018/08/29 13:23:44 [ERR] http: Request GET /v1/kv/<key-path>/initial_config/environment_configuration/<key-name>?index=2058287, error: rpc error making call: rpc error making call: EOF from=127.0.0.1:2232
    2018/08/29 13:23:44 [ERR] consul.watch: Watch (type: key) errored: Unexpected response code: 500, retry in 5s
    2018/08/29 13:23:44 [ERR] consul: "KVS.List" RPC failed to server <consul-server-ip>:8300: rpc error making call: rpc error making call: EOF
    2018/08/29 13:23:44 [ERR] http: Request GET /v1/kv/<key-path>/templates/?index=1625535&recurse=, error: rpc error making call: rpc error making call: EOF from=127.0.0.1:2234
    2018/08/29 13:23:44 [ERR] consul.watch: Watch (type: keyprefix) errored: Unexpected response code: 500, retry in 5s
    2018/08/29 13:23:44 [ERR] consul: "KVS.Get" RPC failed to server <consul-server-ip>:8300: rpc error making call: rpc error making call: EOF
    2018/08/29 13:23:44 [ERR] http: Request GET /v1/kv/<key-path>/content_version?index=1626980, error: rpc error making call: rpc error making call: EOF from=127.0.0.1:27790
    2018/08/29 13:23:44 [ERR] consul.watch: Watch (type: key) errored: Unexpected response code: 500, retry in 5s
    2018/08/29 13:23:44 [ERR] consul: "Health.ServiceNodes" RPC failed to server <consul-server-ip>:8300: rpc error getting client: failed to get conn: dial tcp <consul-server-ip>:0-><consul-server-ip>:8300: connect: connection refused
    2018/08/29 13:23:44 [ERR] http: Request GET /v1/health/service/worker-m?index=2070995&passing=1&stale=&wait=60000ms, error: rpc error getting client: failed to get conn: dial tcp <consul-server-ip>:0-><consul-server-ip>:8300: connect: connection refused from=127.0.0.1:27722
    2018/08/29 13:23:48 [ERR] consul: "Coordinate.Update" RPC failed to server <ip-address>:8300: rpc error making call: rpc error getting client: failed to get conn: dial tcp <ip-address>:0-><consul-server-ip>:8300: connect: connection refused
    2018/08/29 13:23:48 [ERR] agent: Coordinate update error: rpc error making call: rpc error getting client: failed to get conn: dial tcp <ip-address>:0-><consul-server-ip>:8300: connect: connection refused
    2018/08/29 13:23:49 [ERR] consul: "KVS.Get" RPC failed to server <consul-server-ip>:8300: rpc error making call: rpc error getting client: failed to get conn: dial tcp <consul-server-ip>:0-><consul-server-ip>:8300: connect: connection refused
    2018/08/29 13:23:49 [ERR] http: Request GET /v1/kv/<key-path>/<key-name>, error: rpc error making call: rpc error getting client: failed to get conn: dial tcp <consul-server-ip>:0-><consul-server-ip>:8300: connect: connection refused from=127.0.0.1:29336
    2018/08/29 13:23:49 [ERR] consul.watch: Watch (type: key) errored: Unexpected response code: 500, retry in 20s
    2018/08/29 13:23:49 [ERR] consul: "KVS.Get" RPC failed to server <consul-server-ip>:8300: rpc error getting client: failed to get conn: dial tcp <consul-server-ip>:0-><consul-server-ip>:8300: connect: connection refused
    2018/08/29 13:23:49 [ERR] http: Request GET /v1/kv/<key-path>/initial_config/environment_configuration/<key-name>, error: rpc error getting client: failed to get conn: dial tcp <consul-server-ip>:0-><consul-server-ip>:8300: connect: connection refused from=127.0.0.1:29338
    2018/08/29 13:23:49 [ERR] consul.watch: Watch (type: key) errored: Unexpected response code: 500, retry in 20s
    2018/08/29 13:23:49 [ERR] consul: "KVS.List" RPC failed to server <ip-address>:8300: rpc error making call: rpc error getting client: failed to get conn: rpc error: lead thread didn't get connection
    2018/08/29 13:23:49 [ERR] http: Request GET /v1/kv/<key-path>/templates/?recurse=, error: rpc error making call: rpc error getting client: failed to get conn: rpc error: lead thread didn't get connection from=127.0.0.1:29340
    2018/08/29 13:23:49 [ERR] consul: "KVS.Get" RPC failed to server <ip-address>:8300: rpc error making call: rpc error getting client: failed to get conn: rpc error: lead thread didn't get connection
    2018/08/29 13:23:49 [ERR] http: Request GET /v1/kv/<key-path>/content_version, error: rpc error making call: rpc error getting client: failed to get conn: rpc error: lead thread didn't get connection from=127.0.0.1:29342
    2018/08/29 13:23:49 [ERR] consul.watch: Watch (type: keyprefix) errored: Unexpected response code: 500, retry in 20s
    2018/08/29 13:23:49 [ERR] consul.watch: Watch (type: key) errored: Unexpected response code: 500, retry in 20s
    2018/08/29 13:23:57 [INFO] serf: EventMemberFailed: consul-server-2 <consul-server-ip>
    2018/08/29 13:23:57 [INFO] consul: removing server consul-server-2 (Addr: tcp/<consul-server-ip>:8300) (DC: <dc-name>)
    2018/08/29 13:23:58 [INFO] consul: New leader elected: consul-server-3
    2018/08/29 13:24:15 [INFO] consul: adding server consul-server-2 (Addr: tcp/<consul-server-ip>:8300) (DC: <dc-name>)
    2018/08/29 13:24:22 [ERR] consul: "KVS.List" RPC failed to server <consul-server-ip>:8300: rpc error making call: No cluster leader
    2018/08/29 13:24:22 [ERR] http: Request GET /v1/kv/<key-path>/?recurse=1, error: rpc error making call: No cluster leader from=127.0.0.1:29570
    2018/08/29 13:24:23 [INFO] consul: New leader elected: consul-server-3
    2018/08/29 13:24:54 [WARN] agent: Check "service:mysql:1" socket connection failed: dial tcp 127.0.0.1:3306: connect: connection refused
    2018/08/29 13:24:55 [ERR] agent: Failed to run watch handler '[python /root/upgrade_db.py]': exit status 1
    2018/08/29 13:26:02 [INFO] serf: EventMemberLeave: consul-server-3 <consul-server-ip>
    2018/08/29 13:26:02 [INFO] consul: removing server consul-server-3 (Addr: tcp/<consul-server-ip>:8300) (DC: <dc-name>)
    2018/08/29 13:26:08 [INFO] consul: New leader elected: consul-server-1
    2018/08/29 13:26:11 [ERR] consul: "KVS.Get" RPC failed to server <ip-address>:8300: rpc error making call: rpc error making call: EOF
    2018/08/29 13:26:11 [ERR] http: Request GET /v1/kv/<key-path>/initial_config/environment_configuration/<key-name>?index=2058287, error: rpc error making call: rpc error making call: EOF from=127.0.0.1:29474
    2018/08/29 13:26:11 [ERR] consul.watch: Watch (type: key) errored: Unexpected response code: 500, retry in 5s
    2018/08/29 13:26:11 [ERR] consul: "KVS.Get" RPC failed to server <ip-address>:8300: rpc error making call: rpc error making call: EOF
    2018/08/29 13:26:11 [ERR] http: Request GET /v1/kv/<key-path>/<key-name>?index=2058194, error: rpc error making call: rpc error making call: EOF from=127.0.0.1:29472
    2018/08/29 13:26:11 [ERR] consul.watch: Watch (type: key) errored: Unexpected response code: 500, retry in 5s
    2018/08/29 13:26:11 [ERR] consul: "KVS.List" RPC failed to server <ip-address>:8300: rpc error making call: rpc error making call: EOF
    2018/08/29 13:26:11 [ERR] http: Request GET /v1/kv/<key-path>/templates/?index=1625535&recurse=, error: rpc error making call: rpc error making call: EOF from=127.0.0.1:29476
    2018/08/29 13:26:11 [ERR] consul.watch: Watch (type: keyprefix) errored: Unexpected response code: 500, retry in 5s
    2018/08/29 13:26:11 [ERR] consul: "KVS.Get" RPC failed to server <ip-address>:8300: rpc error making call: rpc error making call: EOF
    2018/08/29 13:26:11 [ERR] http: Request GET /v1/kv/<key-path>/content_version?index=1626980, error: rpc error making call: rpc error making call: EOF from=127.0.0.1:29478
    2018/08/29 13:26:11 [ERR] consul.watch: Watch (type: key) errored: Unexpected response code: 500, retry in 5s
    2018/08/29 13:26:22 [INFO] serf: EventMemberJoin: consul-server-3 <consul-server-ip>
    2018/08/29 13:26:22 [INFO] consul: adding server consul-server-3 (Addr: tcp/<consul-server-ip>:8300) (DC: <dc-name>)
    2018/08/29 13:26:40 [INFO] consul: New leader elected: consul-server-1
    2018/08/29 13:26:54 [ERR] consul: "Coordinate.Update" RPC failed to server <consul-server-ip>:8300: rpc error making call: rpc error making call: EOF
    2018/08/29 13:26:54 [ERR] agent: Coordinate update error: rpc error making call: rpc error making call: EOF
    2018/08/29 13:26:54 [ERR] consul: "Health.NodeChecks" RPC failed to server <consul-server-ip>:8300: rpc error making call: rpc error making call: EOF
    2018/08/29 13:26:54 [ERR] agent: failed to sync remote state: rpc error making call: rpc error making call: EOF
    2018/08/29 13:26:54 [ERR] consul: "KVS.List" RPC failed to server <consul-server-ip>:8300: rpc error making call: rpc error making call: unexpected EOF
    2018/08/29 13:26:54 [ERR] http: Request GET /v1/kv/<key-path>/templates/?recurse=, error: rpc error making call: rpc error making call: unexpected EOF from=127.0.0.1:30018
    2018/08/29 13:26:54 [ERR] consul: "KVS.List" RPC failed to server <consul-server-ip>:8300: rpc error making call: rpc error making call: EOF
    2018/08/29 13:26:54 [ERR] http: Request GET /v1/kv/devops/salt-config?recurse=1, error: rpc error making call: rpc error making call: EOF from=127.0.0.1:30252
    2018/08/29 13:26:54 [ERR] consul.watch: Watch (type: keyprefix) errored: Unexpected response code: 500, retry in 20s
    2018/08/29 13:27:37 [INFO] memberlist: Marking consul-server-1 as failed, suspect timeout reached (2 peer confirmations)
    2018/08/29 13:27:37 [INFO] serf: EventMemberFailed: consul-server-1 <ip-address>
    2018/08/29 13:27:37 [INFO] consul: removing server consul-server-1 (Addr: tcp/<ip-address>:8300) (DC: <dc-name>)
    2018/08/29 13:27:38 [INFO] serf: EventMemberJoin: consul-server-1 <ip-address>
    2018/08/29 13:27:38 [INFO] consul: adding server consul-server-1 (Addr: tcp/<ip-address>:8300) (DC: <dc-name>)
```
</details>

**Comment by pierresouchay** [comment] 2018-08-29 18:59
I wonder if this PR https://github.com/hashicorp/consul/pull/4554 might not fix this issue

**Comment by pearkes** [comment] 2018-09-12 17:01
As with #4609 I do believe this is a duplicate of #571.

**Closed by pearkes** 2018-09-12 17:01 UTC
Labels: question
