### ISSUE TITLE
consul 1.2.2: OpenStack authentication keeps failing on DomainId vs DomainName

### ISSUE THREAD

**Issue by Mathiasdm** [hashicorp/consul#4491] opened 2018-08-06 12:33 UTC
When filing a bug, please include the following headings if
possible. Any example text in this template can be deleted.

#### Overview of the Issue

I keep getting unexpected errors about DomainId and DomainName.

I provided values for all of the below (note: I originally gave OS_USER_DOMAIN_NAME instead of OS_DOMAIN_NAME, but I saw only OS_DOMAIN_NAME is read):

OS_AUTH_URL
OS_PROJECT_ID
OS_PROJECT_NAME
OS_DOMAIN_NAME
OS_USERNAME
OS_PASSWORD
OS_REGION_NAME
OS_INTERFACE
OS_IDENTITY_API_VERSION=3

I run consul with the following arguments: consul agent -log-level trace -node foo-96321 -ui -config-dir=/etc/consul.d -bind 192.168.x.y -data-dir=/tmp/consul -bootstrap-expect 1 -server -retry-join "provider=os tag_key=consul tag_value=server"

I would expect that authentication works, but I get the following errors:

`aug 06 07:08:41 buildmachine-template.novalocal startconsul[11136]: 2018/08/06 07:08:41 [INFO] agent: Joining LAN cluster...
aug 06 07:08:41 buildmachine-template.novalocal startconsul[11136]: 2018/08/06 07:08:41 [INFO] agent: Started HTTP server on [::]:8500 (tcp)
aug 06 07:08:41 buildmachine-template.novalocal startconsul[11136]: 2018/08/06 07:08:41 [INFO] agent: started state syncer
aug 06 07:08:41 buildmachine-template.novalocal startconsul[11136]: 2018/08/06 07:08:41 [INFO] discover-os: ProjectID not provided. Looking up in metadata...
...
aug 06 07:08:42 buildmachine-template.novalocal startconsul[11136]: 2018/08/06 07:08:42 [ERR] agent: Join LAN: discover-os: Authentication failed: You must provide exactly one of DomainID or DomainName to authenticate by Username
aug 06 07:08:42 buildmachine-template.novalocal startconsul[11136]: 2018/08/06 07:08:42 [WARN] agent: Join LAN failed: No servers to join, retrying in 30s

`

#### Reproduction Steps

Steps to reproduce this issue, eg:

1. Try to start consul with retry-join on OpenStack.
1. View error

### Consul info for both Client and Server

<details>
  <summary>Client info</summary>

```
agent:
	check_monitors = 0
	check_ttls = 0
	checks = 0
	services = 0
build:
	prerelease = 
	revision = e716d1b5
	version = 1.2.2
consul:
	bootstrap = true
	known_datacenters = 1
	leader = true
	leader_addr = 192.168.0.10:8300
	server = true
raft:
	applied_index = 147
	commit_index = 147
	fsm_pending = 0
	last_contact = 0
	last_log_index = 147
	last_log_term = 5
	last_snapshot_index = 0
	last_snapshot_term = 0
	latest_configuration = [{Suffrage:Voter ID:d24a6632-19fb-8384-3563-cdcb48104359 Address:192.168.0.10:8300}]
	latest_configuration_index = 1
	num_peers = 0
	protocol_version = 3
	protocol_version_max = 3
	protocol_version_min = 0
	snapshot_version_max = 1
	snapshot_version_min = 0
	state = Leader
	term = 5
runtime:
	arch = amd64
	cpu_count = 24
	goroutines = 80
	max_procs = 24
	os = linux
	version = go1.10.1
serf_lan:
	coordinate_resets = 0
	encrypted = false
	event_queue = 1
	event_time = 5
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 1
	members = 1
	query_queue = 0
	query_time = 1
serf_wan:
	coordinate_resets = 0
	encrypted = false
	event_queue = 0
	event_time = 1
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 1
	members = 1
	query_queue = 0
	query_time = 1

```

</details>

<details>
  <summary>Server info</summary>

```
see client info
```

</details>

### Operating system and Environment details

CentOS 7 64-bit on OpenStack

**Comment by arnobroekhof** [comment] 2018-08-07 08:07
having the same problem, can this issue be somehow related to:
https://github.com/hashicorp/go-discover/pull/42

**Comment by pearkes** [comment] 2018-08-07 22:49
@Mathiasdm @arnobroekhof to my understanding that change in hashicorp/go-discover#42 was purely additive, and previously you could not supply those credentials. Perhaps the issue is that the go-discover provide was not reading those values previously, but with the change introduced in 1.2.2 it is now, and thus behaving differently.

Can you try removing `OS_DOMAIN_NAME` and `OS_DOMAIN_ID` from your environment?

**Comment by Mathiasdm** [comment] 2018-08-08 09:37
That doesn't seem to make a difference for me: I get the same error message.

**Comment by arnobroekhof** [comment] 2018-08-08 10:34
**Consul Version:** 1.2.2

for me too: If have a config file called join.json with the following content ( left out the "sensitive" parts):

```
{
    "retry_join": ["provider=os domain_name=default user_name=*** password=****** auth_url=https://*******:5000/v3 tag_key=consul tag_value=server"]
}
```

which results in the following error:

```
Aug 08 12:25:59 ****** consul[5229]: ==> Starting Consul agent...
Aug 08 12:25:59 ****** consul[5229]: ==> Consul agent running!
Aug 08 12:25:59 ****** consul[5229]:            Version: 'v1.2.2'
Aug 08 12:25:59 ****** consul[5229]:            Node ID: 'a4f38b32-aa22-abb2-20d5-7b19244b68ff'
Aug 08 12:25:59 ****** consul[5229]:          Node name: '******'
Aug 08 12:25:59 ****** consul[5229]:         Datacenter: 'pdp' (Segment: '')
Aug 08 12:25:59 ****** consul[5229]:             Server: false (Bootstrap: false)
Aug 08 12:25:59 ****** consul[5229]:        Client Addr: [127.0.0.1] (HTTP: 8500, HTTPS: -1, DNS: 8600)
Aug 08 12:25:59 ****** consul[5229]:       Cluster Addr: 10.180.47.5 (LAN: 8301, WAN: 8302)
Aug 08 12:25:59 ****** consul[5229]:            Encrypt: Gossip: true, TLS-Outgoing: true, TLS-Incoming: true
Aug 08 12:25:59 ****** consul[5229]: ==> Log data will now stream in as it occurs:
Aug 08 12:25:59 ****** consul[5229]:     2018/08/08 12:25:59 [INFO] serf: EventMemberJoin: ****** 10.180.47.5
Aug 08 12:25:59 ****** consul[5229]:     2018/08/08 12:25:59 [INFO] agent: Started DNS server 127.0.0.1:8600 (tcp)
Aug 08 12:25:59 ****** consul[5229]:     2018/08/08 12:25:59 [INFO] agent: Started DNS server 127.0.0.1:8600 (udp)
Aug 08 12:25:59 ****** consul[5229]:     2018/08/08 12:25:59 [INFO] agent: Started HTTP server on 127.0.0.1:8500 (tcp)
Aug 08 12:25:59 ****** consul[5229]:     2018/08/08 12:25:59 [INFO] agent: started state syncer
Aug 08 12:25:59 ****** consul[5229]:     2018/08/08 12:25:59 [INFO] agent: Retry join LAN is supported for: aliyun aws azure digitalocean gce os packet scaleway softlayer triton vsphere
Aug 08 12:25:59 ****** consul[5229]:     2018/08/08 12:25:59 [INFO] agent: Joining LAN cluster...
Aug 08 12:25:59 ****** consul[5229]:     2018/08/08 12:25:59 [INFO] discover-os: ProjectID not provided. Looking up in metadata...
Aug 08 12:25:59 ****** consul[5229]:     2018/08/08 12:25:59 [WARN] manager: No servers available
Aug 08 12:25:59 ****** consul[5229]:     2018/08/08 12:25:59 [ERR] agent: failed to sync remote state: No known Consul servers
Aug 08 12:26:00 ****** consul[5229]:     2018/08/08 12:26:00 [INFO] discover-os: ProjectID is a80c83c7851f451182a7f596ed472db4
Aug 08 12:26:00 ****** consul[5229]:     2018/08/08 12:26:00 [ERR] agent: Join LAN: discover-os: Authentication failed: You must provide exactly one of DomainID or DomainName to authenticate by Username
Aug 08 12:26:00 ****** consul[5229]:     2018/08/08 12:26:00 [WARN] agent: Join LAN failed: No servers to join, retrying in 30s
```

if i run the same command with the discover tool:

```
discover addrs provider=os  domain_name=default user_name=***** password=******* auth_url=https://*******:5000/v3 tag_key=consul tag_value=server
```

i get the following output

```
Registered providers: [aliyun aws azure digitalocean gce os packet scaleway softlayer triton vsphere]
[DEBUG] discover: Using provider "os"
[INFO] discover-os: ProjectID not provided. Looking up in metadata...
[INFO] discover-os: ProjectID is a80c83c7851f451182a7f596ed472db4
2018/08/08 12:31:44 [DEBUG] discover-os: Using project_id=a80c83c7851f451182a7f596ed472db4 tag_key=consul tag_value=server
[DEBUG] discover-os: Authenticating...
[DEBUG] discover-os: Creating client...
[INFO] discover-os: Filter instances with consul=server
[INFO] discover-os: Filter instances with consul=server
[INFO] discover-os: Filter instances with consul=server
[INFO] discover-os: Filter instances with consul=server
[INFO] discover-os: Filter instances with consul=server
[INFO] discover-os: Filter instances with consul=server
[DEBUG] discover-os: Found ip addresses: [10.180.47.6 10.180.47.8 10.180.47.7]
10.180.47.6 10.180.47.8 10.180.47.7
```

**Comment by avoidik** [comment] 2018-08-08 16:13
I'm affected by this issue as well, any help appreciated

**Comment by arnobroekhof** [comment] 2018-08-08 20:47
@avoidik thanks for the workaround but that results into the same error...

**Comment by avoidik** [comment] 2018-08-09 06:37
@arnobroekhof what if

```
source ./openrc
TOKEN=$(openstack token issue -c id -f value)
for env_var in $(printenv | grep 'OS_.*' | cut -d '=' -f 1); do unset $env_var; done
export OS_AUTH_URL="https://<host>"
export OS_REGION_NAME="<region>"
export OS_AUTH_TOKEN="$TOKEN"
```

**Comment by arnobroekhof** [comment] 2018-08-09 08:00
@avoidik: thanks but that results into the same error and i don't think creating an PreStartScript for Consul with the workaround above in it is the right way to go ;-)

**Comment by pearkes** [comment] 2018-08-10 21:31
Apologies for us not really grokking the issue here from the Consul side. We don't have much OpenStack depth. I'm working on trying to get some infrastructure to tie into so we can get this provider into automated acceptance tests as most others are. If anyone can see where https://github.com/hashicorp/go-discover/pull/42 would cause incompatibility with certain flavors/versions of OpenStack would appreciate thoughts here as we try to figure this out.

**Comment by pearkes** [comment] 2018-10-26 18:50
Thanks again for reporting this. I'm closing it here in favor of https://github.com/hashicorp/go-discover/issues/62.

**Closed by pearkes** 2018-10-26 18:50 UTC
Labels: bug, needs-investigation
