### ISSUE TITLE
Atlas example infrastructure returns 404

### ISSUE THREAD

**Issue by ryanuber** [hashicorp/consul#1182] opened 2015-08-17 18:14 UTC
From #1181: We are linking to a 404 page in Atlas from our public Consul documentation.

/cc @pearkes @sethvargo

**Comment by sethvargo** [comment] 2015-08-17 19:06
Duplicate of https://github.com/hashicorp/roadmap/issues/798?

**Comment by slackpad** [comment] 2016-04-13 07:30
We need to update the screen shot, get rid of the broken link, and link to Consul Enterprise.

**Comment by batjko** [comment] 2016-04-15 13:53
Hi guys, Just came across this as well. has this really been outstanding since August last year?

**Comment by slackpad** [comment] 2016-04-15 14:10
Hi @batjko sorry about that. The problem is that Atlas dropped support for public infrastructures which can be viewed without signing in, so the problem is bigger than just fixing the link :-) We will update the static content so you can see a screenshot in the mean time.

**Comment by batjko** [comment] 2016-04-15 14:13
Ah ok, makes sense. No worries.

**Comment by slackpad** [comment] 2016-09-21 17:24
I deleted the link to prevent confusion.

**Closed by slackpad** 2016-09-21 17:24 UTC
Labels: docs
