### ISSUE TITLE
consul kv get should better buffer results

### ISSUE THREAD

**Issue by holtwilkins** [hashicorp/consul#2808] opened 2017-03-21 07:04 UTC
Running these commands on the server, which I was using as a client for my tests

### `consul version` for both Client and Server
`v0.7.3`

### `consul info` for both Client and Server
```
agent:
	check_monitors = 0
	check_ttls = 0
	checks = 3
	services = 4
build:
	prerelease =
	revision = 'a90bb8f
	version = 0.7.3
consul:
	bootstrap = false
	known_datacenters = 1
	leader = false
	leader_addr = 10.2.218.211:8300
	server = true
raft:
	applied_index = 4084213
	commit_index = 4084213
	fsm_pending = 0
	last_contact = 7.70337ms
	last_log_index = 4084213
	last_log_term = 94
	last_snapshot_index = 4079225
	last_snapshot_term = 94
	latest_configuration = [{Suffrage:Voter ID:10.2.219.111:8300 Address:10.2.219.111:8300} {Suffrage:Voter ID:10.2.218.111:8300 Address:10.2.218.111:8300} {Suffrage:Voter ID:10.2.218.211:8300 Address:10.2.218.211:8300}]
	latest_configuration_index = 1
	num_peers = 2
	protocol_version = 1
	protocol_version_max = 3
	protocol_version_min = 0
	snapshot_version_max = 1
	snapshot_version_min = 0
	state = Follower
	term = 94
runtime:
	arch = amd64
	cpu_count = 2
	goroutines = 132
	max_procs = 2
	os = linux
	version = go1.7.4
serf_lan:
	encrypted = true
	event_queue = 0
	event_time = 54
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 573
	members = 10
	query_queue = 0
	query_time = 1
serf_wan:
	encrypted = true
	event_queue = 0
	event_time = 1
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 1
	members = 1
	query_queue = 0
	query_time = 1
```

### Operating system and Environment details
Centos 7

### Description of the Issue (and unexpected/desired result)
Running `consul kv get -recurse` uses way too much memory

```
[centos@ip-10-2-218-123 ~]$ /usr/bin/time -v consul kv get -recurse -base64 -token='REDACTED' > file.yml
	Command being timed: "consul kv get -recurse -base64 -token=REDACTED"
	User time (seconds): 4.01
	System time (seconds): 0.33
	Percent of CPU this job got: 64%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:06.71
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 681200
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 0
	Minor (reclaiming a frame) page faults: 53107
	Voluntary context switches: 2110
	Involuntary context switches: 113
	Swaps: 0
	File system inputs: 0
	File system outputs: 434032
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 0
```

The resulting file in this case is `256M`, so I understand there's a decent amount of data in consul, but the recursive get should be buffering results periodically, whereas it appears to be collecting them all before printing them, given by the `Maximum resident set size` above.

**Comment by slackpad** [comment] 2017-05-25 01:22
Closing this as a duplicate of #1571 since this is a more general problem than just KV.

**Closed by slackpad** 2017-05-25 01:22 UTC
Labels: enhancement, post-0.9, theme/api-cleanup
