### ISSUE TITLE
Service health checks fail intermittently with 'use of closed network connection'

### ISSUE THREAD

**Issue by bmonkman** [hashicorp/consul#1320] opened 2015-10-19 18:40 UTC
In a service containing about 70 nodes I am seeing intermittent health check failures with the following message:

```
consul[1292]: agent: http request failed 'http://localhost:80/health-check': Get http://localhost:80/health-check: read tcp 127.0.0.1:80: use of closed network connection
consul[1292]: agent: Synced check 'service:web'
```

This doesn't seem to recur on specific servers or have any sort of noticeable pattern, and happens anywhere from 1-5 times per day, which then temporarily removes that machine from service.

This is using Consul 0.5.2, so should not suffer from the keepalive bug. The interval for this check is set to 20s, with the default timeout.

Any ideas?

Thanks!

**Comment by ryanuber** [comment] 2015-10-28 01:11
Hey @bmonkman, is it possible that the timeout is being reached? At first glance, I noticed a possibly related upstream bug which was released in go 1.5.1: https://github.com/golang/go/commit/01b25600689250b3672465ae30b821086645013d.

I'm not sure why else this would happen off the top of my head. Marking as a bug, thanks for reporting!

**Comment by bmonkman** [comment] 2015-10-28 20:42
It shouldn't be timing out intermittently but it's possible, I'll see if I can get more details.

**Comment by clstokes** [comment] 2015-11-05 16:56
Sound similar to #1287.

**Comment by loslosbaby** [comment] 2016-01-11 20:34
I've seen this too, on Ubuntu 15.10, when running consul 0.6.1.  Mainly when I control-C a consul server running in the foreground.

**Comment by loslosbaby** [comment] 2016-01-11 20:37
```
^C==> Caught signal: interrupt
==> Gracefully shutting down agent...
    2016/01/11 14:34:43 [INFO] consul: server starting leave
    2016/01/11 14:34:43 [INFO] serf: EventMemberLeave: agent-124.dc1 XXX.XXX.XXX.XXX
    2016/01/11 14:34:43 [INFO] consul: removing WAN server agent-124.dc1 (Addr: XXX.XXX.XXX.XXX:8300) (DC: dc1)
    2016/01/11 14:34:44 [INFO] serf: EventMemberLeave: agent-124 XXX.XXX.XXX.XXX
    2016/01/11 14:34:44 [INFO] consul: removing LAN server agent-124 (Addr: XXX.XXX.XXX.XXX:8300) (DC: dc1)
    2016/01/11 14:34:44 [INFO] raft: Removed ourself, transitioning to follower
    2016/01/11 14:34:44 [INFO] agent: requesting shutdown
    2016/01/11 14:34:44 [INFO] consul: shutting down server
    2016/01/11 14:34:44 [ERR] dns: error starting tcp server: accept tcp 127.0.0.1:8600: use of closed network connection
```

**Comment by slackpad** [comment] 2016-11-22 19:19
It seems like the most likely issue is that the app server takes a while to respond every once in a while - please re-open if that wasn't the cause of this. @loslosbaby I think your log looks normal - that's just things shutting down - please let us know if you still have any concerns.

**Closed by slackpad** 2016-11-22 19:19 UTC
Labels: bug
