### ISSUE TITLE
Retry check interval

### ISSUE THREAD

**Issue by andronux** [hashicorp/consul#1268] opened 2015-10-01 08:50 UTC
It'll be nice to have a retry_check_interval along with a retry_check_count option so a service can be marked as being down if, for instance, the check fails x times.

"retry_check_interval" : 3s,
"retry_check_count": 3

[check] ...wait 3s ... [check] ... wait 3s ... [check] === {warning or critical}

**Comment by ryanuber** [comment] 2015-10-02 17:18
One way you can have this functionality now using a script/interval check type is to take a longer interval, and do the retries within the script. It's possible we could add some quiescence for checks, marking as a thinking ticket for now. Thanks.

**Comment by thedebugger** [comment] 2017-01-27 21:06
We have been using script checks but we want to use native checks if this feature is supported. We don't want to manage script checks as they are hard to get right on first few attempts. So it would be nice to have this support in the native checks.

**Comment by slackpad** [comment] 2017-05-03 02:45
Closing as a duplicate of https://github.com/hashicorp/consul/issues/2890.

**Closed by slackpad** 2017-05-03 02:45 UTC
Labels: thinking
