### ISSUE TITLE
Allow immediate helthcheck upon registration

### ISSUE THREAD

**Issue by piersy** [hashicorp/consul#1179] opened 2015-08-17 10:45 UTC
Currently when registering a service it is not made available until the healthcheck is called, this means that services are sitting idle for up to the healthcheck interval.

Can you allow for the option to call the healthcheck immediately after registration?

**Comment by slackpad** [comment] 2015-08-17 21:52
Hi @piersy take a look at #954 which I think is a duplicate of this issue.

**Closed by slackpad** 2015-08-17 21:52 UTC
