### ISSUE TITLE
xds dependency on Consul 1.7.2

### ISSUE THREAD

**Issue by mmailhos** [hashicorp/consul#7765] opened 2020-05-04 07:30 UTC
#### Overview of the Issue

Trying to install consul with go modules.

#### Reproduction Steps

Steps to reproduce this issue, eg:

1. `go get github.com/hashicorp/consul`

```
go: github.com/hashicorp/consul upgrade => v1.7.2
go: finding module for package github.com/envoyproxy/go-control-plane/pkg/util
go: finding module for package github.com/envoyproxy/go-control-plane/pkg/util
../../../../go/pkg/mod/github.com/hashicorp/consul@v1.7.2/agent/xds/listeners.go:22:2: module github.com/envoyproxy/go-control-plane@latest found (v0.9.5), but does not contain package github.com/envoyproxy/go-control-plane/pkg/util
```

The `pkg/util` only exists in `v0.8.6` as you can see [there](https://github.com/envoyproxy/go-control-plane/tree/v0.8.6/pkg)
However when I ask for this particular version, I still can't install/update Consul:
```
go get github.com/envoyproxy/go-control-plane@v0.8.6

go get github.com/hashicorp/consul@v1.7.2
go: downloading github.com/gogo/protobuf v1.2.2-0.20190730201129-28a6bbf47e48
go: downloading cloud.google.com/go v0.34.0
# github.com/hashicorp/consul/agent/xds
../../../../go/pkg/mod/github.com/hashicorp/consul@v1.7.2/agent/xds/clusters.go:180:3: cannot use time.Duration(cfg.LocalConnectTimeoutMs) * time.Millisecond (type time.Duration) as type *time.Duration in field value
../../../../go/pkg/mod/github.com/hashicorp/consul@v1.7.2/agent/xds/clusters.go:184:4: cannot use []endpoint.LocalityLbEndpoints literal (type []endpoint.LocalityLbEndpoints) as type []*endpoint.LocalityLbEndpoints in field value
../../../../go/pkg/mod/github.com/hashicorp/consul@v1.7.2/agent/xds/clusters.go:186:6: cannot use []endpoint.LbEndpoint literal (type []endpoint.LbEndpoint) as type []*endpoint.LbEndpoint in field value
../../../../go/pkg/mod/github.com/hashicorp/consul@v1.7.2/agent/xds/clusters.go:229:4: cannot use time.Duration(cfg.ConnectTimeoutMs) * time.Millisecond (type time.Duration) as type *time.Duration in field value
../../../../go/pkg/mod/github.com/hashicorp/consul@v1.7.2/agent/xds/clusters.go:333:4: cannot use node.Resolver.ConnectTimeout (type time.Duration) as type *time.Duration in field value
../../../../go/pkg/mod/github.com/hashicorp/consul@v1.7.2/agent/xds/clusters.go:447:3: cannot use time.Duration(cfg.ConnectTimeoutMs) * time.Millisecond (type time.Duration) as type *time.Duration in field value
../../../../go/pkg/mod/github.com/hashicorp/consul@v1.7.2/agent/xds/endpoints.go:250:3: cannot use make([]endpoint.LocalityLbEndpoints, 0, len(endpointGroups)) (type []endpoint.LocalityLbEndpoints) as type []*endpoint.LocalityLbEndpoints in field value
../../../../go/pkg/mod/github.com/hashicorp/consul@v1.7.2/agent/xds/endpoints.go:285:25: cannot use endpoint.LocalityLbEndpoints literal (type endpoint.LocalityLbEndpoints) as type *endpoint.LocalityLbEndpoints in append
../../../../go/pkg/mod/github.com/hashicorp/consul@v1.7.2/agent/xds/endpoints.go:287:4: cannot use es (type []endpoint.LbEndpoint) as type []*endpoint.LbEndpoint in field value
../../../../go/pkg/mod/github.com/hashicorp/consul@v1.7.2/agent/xds/listeners.go:243:3: cannot use makeAddress(addr, port) (type core.Address) as type *core.Address in field value
../../../../go/pkg/mod/github.com/hashicorp/consul@v1.7.2/agent/xds/listeners.go:243:3: too many errors
```

This [hack](https://github.com/hashicorp/consul/issues/6931#issuecomment-582892308) does not work either:
```
go get -u github.com/envoyproxy/go-control-plane@61acc60f25df359e5c433b986a04b41c1da58a22
```

### OS, Architecture

go version go1.14.2 darwin/amd64

**Comment by mkeeler** [comment] 2020-05-04 11:57
@mmailhos Does it work if you pass `-mod=mod` along with `go get`. You shouldn’t need to but this would indicate a problem with the module vendoring.

**Comment by banks** [comment] 2020-05-04 13:26
Duplicate of #6931. Thanks for the info @mmailhos lets continue discussing there!

**Closed by banks** 2020-05-04 13:26 UTC
