### ISSUE TITLE
Add protocol (re)negotiation for automated upgrades

### ISSUE THREAD

**Issue by discordianfish** [hashicorp/consul#1017] opened 2015-06-09 21:25 UTC
Hi,

I want to upgrade a cluster from 0.5.0 (to 0.5.2) which is unfortunately a breaking change.
Therefore I need to follow the "Backward Incompatible Upgrades" as documented here: https://www.consul.io/docs/upgrading.html

I think it would be great if consul would just negotiate the highest common protocol version between peers. This way you can replace one peer (node A) with a newer consul / protocol version, which will fall back to the older protocol to communicate with the peers. Now if you upgrade the next node (node B), communication between A and B happens in the new protocol version. Once the whole cluster is upgraded, all communication happens in the new protocol.

This way upgrades would "just work" where the current behaviour is rather hard to automate. In my particular case I need to build a consul AMI with protocol=2, do a rolling upgrade, build a new AMI without protocol=2 and do another rolling upgrade.

**Comment by blalor** [comment] 2015-06-09 23:53
There's no protocol change from 0.5.0 to 0.5.2.  Not even from 0.4.1.

```
Node    Address            Status  Type    Build  Protocol  DC
host1   10.129.1.127:8301  alive   client  0.4.1  2         us-east-1_aws_dev
host2   10.129.1.193:8301  alive   client  0.5.2  2         us-east-1_aws_dev
host3   10.129.1.91:8301   alive   client  0.5.0  2         us-east-1_aws_dev
```

(yes, 0.4.1.  don't judge me.)

**Comment by discordianfish** [comment] 2015-06-09 23:55
Hrm.. it's possible that I mixed things up and ran the current master. Guess then the problem will occur when upgrading 0.5.2 to whatever the next released version will be.

**Comment by armon** [comment] 2015-06-10 15:57
@discordianfish We already to this internally! The protocol negotiations allow a Consul 0.1.0dev instance in our fleet (so we won't judge) to still talk with the 0.5.2 masters.

**Comment by discordianfish** [comment] 2015-06-10 16:10
@armon So there is a internal consul version doing that, just not the public / open source one? Or did I miss something?

**Comment by armon** [comment] 2015-06-10 16:26
@discordianfish I mean the public version should be doing this already. There should be no interoperability issues. Are you running into a problem with something currently?

**Comment by discordianfish** [comment] 2015-06-10 17:57
@armon I did, I tried to upgrade the cluster to #971 and ran into this issue (other nodes were running 0.5.0). Unfortunately I ended up destroyed the cluster and can't verify. Are there integration tests to test this compatibility?
Beside that, should this also work for downgrades / rollbacks?

**Comment by slackpad** [comment] 2015-06-10 18:31
@discordianfish it sounds like you built from master and picked up the pending protocol bump to v3 in the process. There's a chance in there that adds a new TCP ping mechanism that required a change to the protocol.

This sounds like a regression because v3 only extends the v2, so it should allow a v2 node to join a v3 server, but it currently does not:

```
memberlist: push/pull verification failed: Node 'agent-one' protocol version (3) is incompatible: [1, 2]
```

I'll take a look.

**Comment by slackpad** [comment] 2015-09-03 02:17
This got cleaned up in https://github.com/hashicorp/consul/pull/1209, closing this out for now since the next release won't be a breaking change.

**Closed by slackpad** 2015-09-03 02:17 UTC
