### ISSUE TITLE
health check add "max_fails" support 

### ISSUE THREAD

**Issue by huxos** [hashicorp/consul#1208] opened 2015-08-31 07:20 UTC
Hi, 
I use consul-templates to render  nginx config file. I found that the nginx  is always reload twice in a  short interval, as the check state switching. 
Would there be any interest in adding max_fails support  for health check.

thanks.

**Comment by slackpad** [comment] 2015-08-31 22:43
Hi @huxos there have been some requests for more sophisticated health check filtering, can you describe your use case in a little more detail, and how you'd imaging "max_fails" would work?

**Comment by huxos** [comment] 2015-09-01 03:09
it means that after several consecutive failures change the check state to critical , not the first time failures discovered.

**Comment by slackpad** [comment] 2015-09-01 05:10
Ok thanks. I'm going to mark this as a thinking ticket so we can see if something simple will meet a good 80% cut at people's needs.

**Comment by djenriquez** [comment] 2015-09-03 23:32
+1, will satisfy our requirements as an alternative to #1212

**Comment by cruatta** [comment] 2015-09-19 18:09
:+1:

**Comment by dbresson** [comment] 2016-10-05 00:23
+1, but also add minimum successes for recovering to healthy.

The lack of this is also the only reason I'm not using Consul Enterprise. Constant notifications because of a random blip in a health check is something I can't deal with.

**Comment by morokin** [comment] 2017-02-12 09:55
+1

**Comment by Perlovka** [comment] 2017-02-12 09:56
+1

**Comment by sirajmansour** [comment] 2017-03-13 02:11
+1 this very important in leader election scenarios where a session could get invalidated just because a service check skipped a beat which would trigger un-necessary change in leader.

**Comment by WolverineFan** [comment] 2017-04-19 13:06
To steal a page from a tool that already support this, Amazon ELB health checks have:
```
    healthy_threshold   = 2
    unhealthy_threshold = 2
```
This small change helps prevent a tremendous amount of flapping.

**Comment by slackpad** [comment] 2017-05-02 23:03
Closing this as a duplicate of https://github.com/hashicorp/consul/issues/2890.

**Closed by slackpad** 2017-05-02 23:03 UTC
Labels: enhancement, thinking
