### ISSUE TITLE
Snapshot open file descriptor permanently unusable after "filesystem full" condition

### ISSUE THREAD

**Issue by jjones-smug** [hashicorp/consul#1744] opened 2016-02-20 00:28 UTC
We've run into an interesting error scenario where an attempt to write to the local snapshot files fails with a "no space left on device" error.  The process seems to hold on to that error status and short-circuits subsequent write requests, indefinitely.  So even after the filesystem issue is resolve, the consul process continues to SYSLOG "no space left on device" errors for each "tryAppend" call.

Running "strace" on the process show that no write() system calls are made to the file descriptor open against the snapshot file.  Calls just result in writes to SYSLOG with an error returned to the application.

**Comment by jjones-smug** [comment] 2016-03-03 22:53
Bumping this one...  Any thoughts?

**Comment by slackpad** [comment] 2016-03-11 02:26
@jjones-smug sorry haven't had a chance to chase this down yet.

**Comment by jjones-smug** [comment] 2016-04-28 21:31
Bumping again, since I have a ticket open on this one that I'd like to close out.

**Comment by jjones-smug** [comment] 2016-07-14 08:27
Could this be related?

https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/consul-tool/pODmVVEy4Ds/6-LpTAZBAgAJ

**Comment by kunitake** [comment] 2016-08-03 03:40
Hi,

I'll test it.

Added following line to /etc/fstab.
```
tmpfs   /opt/diskfull    tmpfs   defaults,noatime,size=250M 0 0
```

and ...

```
# systemctl stop consul
# mount -a
```
set data_dir to /opt/diskfull

```
# dd if=/dev/zero of=/opt/diskfull/dummy.img bs=512 count=9999999999
dd: error writing ‘dummy.img’: No space left on device
511745+0 records in
511744+0 records out
262012928 bytes (262 MB) copied, 0.582111 s, 450 MB/s
# systemctl start consul
```

After reproduce,

```
# rm /opt/diskfull/dummy.img
```

Although I got free space, outputting the error messages continue.

I hope the problem will be fixed by following patch.
-> https://github.com/hashicorp/consul/pull/2236

best regards,

**Comment by SunSparc** [comment] 2016-12-19 17:41
I have a system that just ran into this problem as well:

`consul: 2016/12/19 17:35:21 [ERR] serf: Failed to update snapshot: write /var/lib/consul/serf/local.snapshot: no space left on device`

A `df -h` showed:
```
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda3        72G   30G   39G  44% /
```

Though a day or so ago that same machine did indeed run out of space, but obviously that space has since been cleared up.

We did a `systemctl restart consul` and consul is happy again.

**Comment by memelet** [comment] 2017-03-27 08:58
Just hit this (still) with 0.7.5 where agent never recovers after a disk full.

**Comment by kaskavalci** [comment] 2017-05-15 18:35
Is there a workaround for this issue?

**Comment by preetapan** [comment] 2017-07-06 14:14
Fixed in https://github.com/hashicorp/consul/pull/3236

**Closed by preetapan** 2017-07-06 14:14 UTC
Labels: bug, theme/internal-cleanup
