### ISSUE TITLE
Deregistering large number of client nodes 

### ISSUE THREAD

**Issue by roman-cnd** [hashicorp/consul#4881] opened 2018-11-01 13:42 UTC
#### Overview of the Issue

A relatively large number of nodes being added and removed in Nomad, say a few hundred in a high churn rate cluster.

They all registered correctly in consul and nomad with all health checks passing.
Then autoscaling group size decreased to a few nodes. Consul correctly removes most of them, but 10-15 are still displayed as alive with health checks passing. Gradually they are removed too, which takes hours. Nomad correctly marks all removed nodes as "down".

#### Reproduction Steps

Steps to reproduce this issue, eg:

1. Create a 200-300 nodes clients cluster, 3 servers for separated nomad and consul clusters  
2. decrease cluster size to 1 
3. few dozen nodes still registered in consul

### Consul info for both Client and Server

1.3.0 consul
0.8.6 nomad

```
agent:
	check_monitors = 4
	check_ttls = 0
	checks = 4
	services = 1
build:
	prerelease =
	revision = e8757838
	version = 1.3.0
consul:
	bootstrap = false
	known_datacenters = 1
	leader = false
	leader_addr = 10.x.x.x:8300
	server = true
raft:
	applied_index = 16815
	commit_index = 16815
	fsm_pending = 0
	last_contact = 64.273006ms
	last_log_index = 16815
	last_log_term = 6
	last_snapshot_index = 16387
	last_snapshot_term = 6
	latest_configuration = [{Suffrage:Voter ID:43d117ed-2929-4324-0dd6-5fca7e47151b Address:10.0.0.4:8300} {Suffrage:Voter ID:bdfad50e-652b-991f-182e-04d6f8161ae8 Address:10.0.0.3:8300} {Suffrage:Voter ID:2c7df945-e520-4f08-66da-564648630e33 Address:10.0.0.2:8300}]
	latest_configuration_index = 16781
	num_peers = 2
	protocol_version = 3
	protocol_version_max = 3
	protocol_version_min = 0
	snapshot_version_max = 1
	snapshot_version_min = 0
	state = Follower
	term = 6
runtime:
	arch = amd64
	cpu_count = 4
	goroutines = 96
	max_procs = 4
	os = linux
	version = go1.11.1
serf_lan:
	coordinate_resets = 0
	encrypted = false
	event_queue = 0
	event_time = 4
	failed = 1
	health_score = 0
	intent_queue = 0
	left = 33
	member_time = 257
	members = 41
	query_queue = 0
	query_time = 1
serf_wan:
	coordinate_resets = 0
	encrypted = false
	event_queue = 0
	event_time = 1
	failed = 16
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 48
	members = 19
	query_queue = 0
	query_time = 1
```
</details>

### Operating system and Environment details

debian 9 in gce

### Log Fragments
Will add some

**Comment by pearkes** [comment] 2018-12-12 17:19
I think this is similar behavior to that seen in https://github.com/hashicorp/consul/issues/2982 and https://github.com/hashicorp/consul/issues/2981 and https://github.com/hashicorp/consul/issues/4741.

This is assuming that the `members` command returns the expected value ("left"). If not let us know but I believe you're still seeing the same root cause which is a discrepancy between serf (members) and the Consul catalog.

Going to close this in favor of those.

**Closed by pearkes** 2018-12-12 17:19 UTC
