### ISSUE TITLE
agent: failed to sync remote state: No cluster leader

### ISSUE THREAD

**Issue by efuquen** [hashicorp/consul#738] opened 2015-02-25 23:19 UTC
I'm running consul 0.4.1 via this docker container on CoreOS:

https://github.com/progrium/docker-consul

I had a 5 node cluster on AWS that was fine, but in the AM today the cluster suddenly lose it's leader.  Or at least 4 of the nodes thought that.  One of them kept refuting  'suspect' and 'dead' messages.

There were no servers that hard crashed and as far as I know there were no internal network issues (though I can't definitively prove that), so I'm unsure why the cluster got into this state.  I had to hard reset it by killing all the containers and bootstrapping it again.  

By the way this is also a persistent issue since we've been using Consul over the last few months, the cluster will seem to go into a state of disarray at random moments for no perceivable reason and with no boxes going down.  First time I've gathered the logs together to submit an issue about it.  While I can't rule out internal network issues this also doesn't happen on our etcd cluster, so if it was some network hiccups I would expect the Consul cluster should be able to deal with it gracefully as well.

Any other thoughts based on the logs?  I don't know if it might also have something to do with running it in a container.  Thanks!

*EDIT: Forgot to link the logs, here you go:

https://gist.github.com/efuquen/777cc00977f2f722dfae

Obviously not the full logs but it has the relevant sections when something funky happened.  The 4 nodes continue to have 'No cluster leader' indefinitely while the 5th continues to refute all messages.

**Comment by armon** [comment] 2015-03-03 02:33
Hmm. There definitely is some type of routing issue with "ip-172-16-8-13.us-west-2.compute.internal" based on the number of refutations it is doing.

My guess is that node was restarted and triggered the Docker ARP caching bug. (See https://github.com/progrium/docker-consul/issues/26). Some time in the future, that node became the leader, BUT due to the ARP issue, it's not routable from any other node. This creates a rather strange scenario, where it becomes leader but cannot be reached by any of the other nodes causing the "No cluster leader".

All of this is caused by routing issues however. I hope that helps.

**Comment by armon** [comment] 2015-05-07 00:06
Closing as this is an external issue.

**Closed by armon** 2015-05-07 00:06 UTC
