### ISSUE TITLE
1.2.3 behaves differently then 1.2.2 on node re-registration

### ISSUE THREAD

**Issue by EugenMayer** [hashicorp/consul#5119] opened 2018-12-19 21:31 UTC
I could reproduce the issue with 1.2.3, while downgrading to 1.2.2 fixes the issues directly.

It seems, with 1.2.3, if i remove a node entirely and then a new node with the same name, i get an error that a different node has registered this name, but has a different UUID. 

No such error occurs on 1.2.2 - did i miss something in the docs / upgrade notes?

**Comment by pearkes** [comment] 2018-12-19 22:06
I believe this might be a dupe of #4741. Lots of good context on that thread and we are working on a solution for this in that scenario.

**Closed by pearkes** 2018-12-19 22:06 UTC

**Comment by EugenMayer** [comment] 2018-12-19 22:18
@pearkes exactly my issue, sorry did not find it - should have been easy. My bad
