### ISSUE TITLE
Consul fail to start after cold reboot

### ISSUE THREAD

**Issue by capone212** [hashicorp/consul#2278] opened 2016-08-16 12:17 UTC
### `consul version` for both Client and Server
`0.7dev`

### Operating system and Environment details
3 virtual box windows guests machines managed by vagrant. Each consul in server and client mode.
Host os is ubuntu.

### Description of the Issue (and unexpected/desired result)
I have multimachine vagrant file. After `vagrant -f halt` and `vagrant up` on one server consul would not start with following error:
`
==> Error starting agent: failed decoding service file "consul\\data\\services\\1e5682ced5ebc0c1167609d6ebc9af59": invalid character '\x00' looking for beginning of value
`
I believe if file is invalid consul should ignore it.
I have attached all  data, config and log files.
 
### Reproduction steps
vagrant up
sleep(120)
vagrant halt -f

reproduces 100% stable

[consul.zip](https://github.com/hashicorp/consul/files/420222/consul.zip)

**Comment by slackpad** [comment] 2016-09-16 22:39
Marking this as a duplicate of https://github.com/hashicorp/consul/issues/1221. Looks like the same root cause.

**Closed by slackpad** 2016-09-16 22:39 UTC
