### ISSUE TITLE
  // , The demo vagrant produces errors upon the first vagrant up command output 

### ISSUE THREAD

**Issue by v6** [hashicorp/consul#2725] opened 2017-02-10 02:14 UTC
// , 

### `consul version` for both Client and Server
Client: commit 997bd4aa94405b9f284b3a1511dc2e520b044f06
Server: commit 997bd4aa94405b9f284b3a1511dc2e520b044f06

### `consul info` for both Client and Server

(I don't think this is relevant for what seems like a relatively minor Vagrant configuration issue, but I also want to reduce the chance of someone knee-jerk closing this issue)

Client:
```
$ vagrant ssh n2
ssh_exchange_identification: Connection closed by remote host
```

Server:
```
$ vagrant ssh n1

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Fri Feb 10 02:51:21 2017 from 10.0.2.2
vagrant@n1:~$ consul info
agent:
	check_monitors = 0
	check_ttls = 0
	checks = 0
	services = 1
build:
	prerelease =
	revision = 'a9afa0c
	version = 0.7.2
consul:
	bootstrap = true
	known_datacenters = 1
	leader = true
	leader_addr = 172.20.20.10:8300
	server = true
raft:
	applied_index = 7
	commit_index = 7
	fsm_pending = 0
	last_contact = never
	last_log_index = 7
	last_log_term = 2
	last_snapshot_index = 0
	last_snapshot_term = 0
	latest_configuration = [{Suffrage:Voter ID:172.20.20.10:8300 Address:172.20.20.10:8300}]
	latest_configuration_index = 1
	num_peers = 0
	protocol_version = 1
	protocol_version_max = 3
	protocol_version_min = 0
	snapshot_version_max = 1
	snapshot_version_min = 0
	state = Leader
	term = 2
runtime:
	arch = amd64
	cpu_count = 2
	goroutines = 53
	max_procs = 2
	os = linux
	version = go1.7.3
serf_lan:
	encrypted = false
	event_queue = 1
	event_time = 2
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 1
	members = 1
	query_queue = 0
	query_time = 1
serf_wan:
	encrypted = false
	event_queue = 0
	event_time = 1
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 1
	members = 1
	query_queue = 0
	query_time = 1
vagrant@n1:~$
```

Vagrant: 
```
$ vagrant plugin list
vagrant-share (1.1.6, system)
vagrant-vbguest (0.13.0)
$ vagrant --version
Vagrant 1.9.1
```

### Operating system and Environment details
```
% uname -a
Darwin NBASANESE 16.4.0 Darwin Kernel Version 16.4.0: Thu Dec 22 22:53:21 PST 2016; root:xnu-3789.41.3~3/RELEASE_X86_64 x86_64
```

### Description of the Issue (and unexpected/desired result)

This is an issue with the Vagrantfile for the consul demo. 

It produces four error messages which surprised me: 

    ==> n2: stdin: is not a tty

( possibly related to https://github.com/mitchellh/vagrant/issues/1673 )

    ==> n2: dpkg-preconfigure: unable to re-open stdin: No such file or directory

    Timed out while waiting for the machine to boot. This means that
    Vagrant was unable to communicate with the guest machine within
    the configured ("config.vm.boot_timeout" value) time period.

    If you look above, you should be able to see the error(s) that
    Vagrant had when attempting to connect to the machine. These errors
    are usually good hints as to what may be wrong.

    If you're using a custom box, make sure that networking is properly
    working and you're able to connect to the machine. It is a common
    problem that networking isn't setup properly in these boxes.
    Verify that authentication configurations are also setup properly,
    as well.
    
    If the box appears to be booting properly, you may want to increase
    the timeout ("config.vm.boot_timeout") value.

```==> Newer Consul version available: 0.7.4 (currently running: 0.7.2)```

### Reproduction steps

https://www.consul.io/intro/getting-started/join.html

Clone the latest version of the code, navigate to the `consul/demo/vagrant-cluster` folder, install the latest Vagrant (1.9.1 by 2017 02 09) and Virtualbox (5.1.14 by 2017 02 09), and run `$ vagrant up`. 

### Log Fragments or Link to [gist](https://gist.github.com/)

Include appropriate Client or Server log fragments.  If the log is longer
than a few dozen lines, please include the URL to the
[gist of log](https://gist.github.com/v6/bfd334f5b7e205de955488074f44485d).

**Comment by v6** [comment] 2017-02-17 19:58
// , I actually think this demo section has a lot of potential, and I've used it to get more confidence in managing a Consul cluster.

**Comment by brianshumate** [comment] 2017-03-01 17:36
Hey there,

Thanks for the report. I am unable to reproduce the errors you've seen or the issue in logging into the VMs. I am on macOS 10.12.3 with Vagrant 1.9.2 and VirtualBox 5.1.14 + the latest master clone of the consul repo.

Here's my full `vagrant up` output:

```
› vagrant up
Bringing machine 'n1' up with 'virtualbox' provider...
Bringing machine 'n2' up with 'virtualbox' provider...
==> n1: Importing base box 'debian/jessie64'...
==> n1: Matching MAC address for NAT networking...
==> n1: Checking if box 'debian/jessie64' is up to date...
==> n1: Setting the name of the VM: vagrant-cluster_n1_1488386927179_35178
==> n1: Fixed port collision for 22 => 2222. Now on port 2202.
==> n1: Clearing any previously set network interfaces...
==> n1: Preparing network interfaces based on configuration...
    n1: Adapter 1: nat
    n1: Adapter 2: hostonly
==> n1: Forwarding ports...
    n1: 22 (guest) => 2202 (host) (adapter 1)
==> n1: Running 'pre-boot' VM customizations...
==> n1: Booting VM...
==> n1: Waiting for machine to boot. This may take a few minutes...
    n1: SSH address: 127.0.0.1:2202
    n1: SSH username: vagrant
    n1: SSH auth method: private key
    n1:
    n1: Vagrant insecure key detected. Vagrant will automatically replace
    n1: this with a newly generated keypair for better security.
    n1:
    n1: Inserting generated public key within guest...
    n1: Removing insecure key from the guest if it's present...
    n1: Key inserted! Disconnecting and reconnecting using new SSH key...
==> n1: Machine booted and ready!
==> n1: Checking for guest additions in VM...
    n1: No guest additions were detected on the base box for this VM! Guest
    n1: additions are required for forwarded ports, shared folders, host only
    n1: networking, and more. If SSH fails on this machine, please install
    n1: the guest additions and repackage the box to continue.
    n1:
    n1: This is not an error message; everything may continue to work properly,
    n1: in which case you may ignore this message.
==> n1: Setting hostname...
==> n1: Configuring and enabling network interfaces...
==> n1: Installing rsync to the VM...
==> n1: Rsyncing folder: /Users/brian/src/hashicorp/consul/demo/vagrant-cluster/ => /vagrant
==> n1: Running provisioner: shell...
    n1: Running: inline script
==> n1: Installing dependencies ...
==> n1: Hit http://security.debian.org jessie/updates InRelease
==> n1: Hit http://security.debian.org jessie/updates/main Sources
==> n1: Hit http://security.debian.org jessie/updates/main amd64 Packages
==> n1: Ign http://httpredir.debian.org jessie InRelease
==> n1: Hit http://httpredir.debian.org jessie Release.gpg
==> n1: Hit http://httpredir.debian.org jessie Release
==> n1: Hit http://httpredir.debian.org jessie/main Sources
==> n1: Hit http://httpredir.debian.org jessie/main amd64 Packages
==> n1: Reading package lists...
==> n1: Reading package lists...
==> n1: Building dependency tree...
==> n1: Reading state information...
==> n1: The following extra packages will be installed:
==> n1:   libcurl3
==> n1: Suggested packages:
==> n1:   zip
==> n1: The following NEW packages will be installed:
==> n1:   curl libcurl3 unzip
==> n1: 0 upgraded, 3 newly installed, 0 to remove and 22 not upgraded.
==> n1: Need to get 622 kB of archives.
==> n1: After this operation, 1,280 kB of additional disk space will be used.
==> n1: Get:1 http://httpredir.debian.org/debian/ jessie/main libcurl3 amd64 7.38.0-4+deb8u5 [259 kB]
==> n1: Get:2 http://httpredir.debian.org/debian/ jessie/main curl amd64 7.38.0-4+deb8u5 [200 kB]
==> n1: Get:3 http://httpredir.debian.org/debian/ jessie/main unzip amd64 6.0-16+deb8u2 [162 kB]
==> n1: dpkg-preconfigure: unable to re-open stdin: No such file or directory
==> n1: Fetched 622 kB in 4s (140 kB/s)
==> n1: Selecting previously unselected package libcurl3:amd64.
(Reading database ... 65% ...
==> n1: (Reading database ... 70%
==> n1: (Reading database ... 75%
==> n1: (Reading database ... 80%
==> n1: (Reading database ... 85%
==> n1: (Reading database ... 90%
==> n1: (Reading database ... 95%
(Reading database ... 28340 files and directories currently installed.)
==> n1: Preparing to unpack .../libcurl3_7.38.0-4+deb8u5_amd64.deb ...
==> n1: Unpacking libcurl3:amd64 (7.38.0-4+deb8u5) ...
==> n1: Selecting previously unselected package curl.
==> n1: Preparing to unpack .../curl_7.38.0-4+deb8u5_amd64.deb ...
==> n1: Unpacking curl (7.38.0-4+deb8u5) ...
==> n1: Selecting previously unselected package unzip.
==> n1: Preparing to unpack .../unzip_6.0-16+deb8u2_amd64.deb ...
==> n1: Unpacking unzip (6.0-16+deb8u2) ...
==> n1: Processing triggers for man-db (2.7.0.2-5) ...
==> n1: Processing triggers for mime-support (3.58) ...
==> n1: Setting up libcurl3:amd64 (7.38.0-4+deb8u5) ...
==> n1: Setting up curl (7.38.0-4+deb8u5) ...
==> n1: Setting up unzip (6.0-16+deb8u2) ...
==> n1: Processing triggers for libc-bin (2.19-18+deb8u7) ...
==> n1: Fetching Consul version 0.7.2 ...
==> n1: Installing Consul version 0.7.2 ...
==> n1: Archive:  consul.zip
==> n1:   inflating: consul
==> n2: Importing base box 'debian/jessie64'...
==> n2: Matching MAC address for NAT networking...
==> n2: Checking if box 'debian/jessie64' is up to date...
==> n2: Setting the name of the VM: vagrant-cluster_n2_1488386982036_85416
==> n2: Fixed port collision for 22 => 2222. Now on port 2203.
==> n2: Clearing any previously set network interfaces...
==> n2: Preparing network interfaces based on configuration...
    n2: Adapter 1: nat
    n2: Adapter 2: hostonly
==> n2: Forwarding ports...
    n2: 22 (guest) => 2203 (host) (adapter 1)
==> n2: Running 'pre-boot' VM customizations...
==> n2: Booting VM...
==> n2: Waiting for machine to boot. This may take a few minutes...
    n2: SSH address: 127.0.0.1:2203
    n2: SSH username: vagrant
    n2: SSH auth method: private key
    n2:
    n2: Vagrant insecure key detected. Vagrant will automatically replace
    n2: this with a newly generated keypair for better security.
    n2:
    n2: Inserting generated public key within guest...
    n2: Removing insecure key from the guest if it's present...
    n2: Key inserted! Disconnecting and reconnecting using new SSH key...
==> n2: Machine booted and ready!
==> n2: Checking for guest additions in VM...
    n2: No guest additions were detected on the base box for this VM! Guest
    n2: additions are required for forwarded ports, shared folders, host only
    n2: networking, and more. If SSH fails on this machine, please install
    n2: the guest additions and repackage the box to continue.
    n2:
    n2: This is not an error message; everything may continue to work properly,
    n2: in which case you may ignore this message.
==> n2: Setting hostname...
==> n2: Configuring and enabling network interfaces...
==> n2: Installing rsync to the VM...
==> n2: Rsyncing folder: /Users/brian/src/hashicorp/consul/demo/vagrant-cluster/ => /vagrant
==> n2: Running provisioner: shell...
    n2: Running: inline script
==> n2: Installing dependencies ...
==> n2: Hit http://security.debian.org jessie/updates InRelease
==> n2: Hit http://security.debian.org jessie/updates/main Sources
==> n2: Hit http://security.debian.org jessie/updates/main amd64 Packages
==> n2: Ign http://httpredir.debian.org jessie InRelease
==> n2: Hit http://httpredir.debian.org jessie Release.gpg
==> n2: Hit http://httpredir.debian.org jessie Release
==> n2: Hit http://httpredir.debian.org jessie/main Sources
==> n2: Hit http://httpredir.debian.org jessie/main amd64 Packages
==> n2: Reading package lists...
==> n2: Reading package lists...
==> n2: Building dependency tree...
==> n2: Reading state information...
==> n2: The following extra packages will be installed:
==> n2:   libcurl3
==> n2: Suggested packages:
==> n2:   zip
==> n2: The following NEW packages will be installed:
==> n2:   curl libcurl3 unzip
==> n2: 0 upgraded, 3 newly installed, 0 to remove and 22 not upgraded.
==> n2: Need to get 622 kB of archives.
==> n2: After this operation, 1,280 kB of additional disk space will be used.
==> n2: Get:1 http://httpredir.debian.org/debian/ jessie/main libcurl3 amd64 7.38.0-4+deb8u5 [259 kB]
==> n2: Get:2 http://httpredir.debian.org/debian/ jessie/main curl amd64 7.38.0-4+deb8u5 [200 kB]
==> n2: Get:3 http://httpredir.debian.org/debian/ jessie/main unzip amd64 6.0-16+deb8u2 [162 kB]
==> n2: dpkg-preconfigure: unable to re-open stdin: No such file or directory
==> n2: Fetched 622 kB in 1s (358 kB/s)
==> n2: Selecting previously unselected package libcurl3:amd64.
(Reading database ... 70% ...
==> n2: (Reading database ... 75%
==> n2: (Reading database ... 80%
==> n2: (Reading database ... 85%
==> n2: (Reading database ... 90%
==> n2: (Reading database ... 95%
(Reading database ... 28340 files and directories currently installed.)
==> n2: Preparing to unpack .../libcurl3_7.38.0-4+deb8u5_amd64.deb ...
==> n2: Unpacking libcurl3:amd64 (7.38.0-4+deb8u5) ...
==> n2: Selecting previously unselected package curl.
==> n2: Preparing to unpack .../curl_7.38.0-4+deb8u5_amd64.deb ...
==> n2: Unpacking curl (7.38.0-4+deb8u5) ...
==> n2: Selecting previously unselected package unzip.
==> n2: Preparing to unpack .../unzip_6.0-16+deb8u2_amd64.deb ...
==> n2: Unpacking unzip (6.0-16+deb8u2) ...
==> n2: Processing triggers for man-db (2.7.0.2-5) ...
==> n2: Processing triggers for mime-support (3.58) ...
==> n2: Setting up libcurl3:amd64 (7.38.0-4+deb8u5) ...
==> n2: Setting up curl (7.38.0-4+deb8u5) ...
==> n2: Setting up unzip (6.0-16+deb8u2) ...
==> n2: Processing triggers for libc-bin (2.19-18+deb8u7) ...
==> n2: Fetching Consul version 0.7.2 ...
==> n2: Installing Consul version 0.7.2 ...
==> n2: Archive:  consul.zip
==> n2:   inflating: consul

==> n1: Machine 'n1' has a post `vagrant up` message. This is a message
==> n1: from the creator of the Vagrantfile, and not from Vagrant itself:
==> n1:
==> n1: Vanilla Debian box. See https://atlas.hashicorp.com/debian/ for help and bug reports

==> n2: Machine 'n2' has a post `vagrant up` message. This is a message
==> n2: from the creator of the Vagrantfile, and not from Vagrant itself:
==> n2:
==> n2: Vanilla Debian box. See https://atlas.hashicorp.com/debian/ for help and bug reports
```

Two instances of this error from `dpkg-preconfigure` were seen, but they can be safely ignored:

```
dpkg-preconfigure: unable to re-open stdin: No such file or directory
```

The message you saw:

```
==> n2: stdin: is not a tty
```

is also not a problem (even though it appears in red text), and is actually a long running joke in the Vagrant community as well. 😄 

I don't find any issue with the `Vagrantfile` or Consul in the demo. The Consul version is out of date, so I'll go do a PR for that right now.

I'm not sure why your `vagrant ssh` would not work the one time, and could not reproduce that, but have seen similar issues when there's an ssh config problem with stale info in `~/.ssh/config`, env vars, or similar.

Unfortunately, I don't think that there is an issue with the demo per se since I could not reproduce it, and you're likely hitting an environmental issue.

I am in favor of closing this unless you need anything further.

Thanks for the input and glad you find the demo useful!

**Comment by slackpad** [comment] 2017-05-02 00:01
Closing per the previous comment.

**Closed by slackpad** 2017-05-02 00:01 UTC
