### ISSUE TITLE
Potentially return 400 from HTTP API /v1/health/state/foo

### ISSUE THREAD

**Issue by cablehead** [hashicorp/consul#757] opened 2015-03-04 22:40 UTC
At the moment the /health/state endpoint returns a 200 and an empty list if you request an undefined state. Would a 400 be better, in case of typos?

**Comment by ryanuber** [comment] 2015-03-04 23:18
Hey @cablehead, yeah that sounds reasonable to me, marking as an enhancement. Thanks!

**Comment by slackpad** [comment] 2018-01-30 22:33
This also applies to /v1/health/service/foo.

**Comment by s-christoff** [comment] 2019-11-12 18:44
Hey @cablehead  thank you so much for this issue. We are closing this as a duplicate of #6711 - this is because when we start working on modifying the endpoints to return standardized status codes we will take a holistic approach.

**Closed by s-christoff** 2019-11-12 18:44 UTC
Labels: enhancement, theme/api-cleanup
