### ISSUE TITLE
Consul left with many failed nodes (former agents) over time in cloud environment

### ISSUE THREAD

**Issue by owaaa** [hashicorp/consul#544] opened 2014-12-16 16:27 UTC
I'm experiencing a situation where over time, as boxes with agents are re-built and not always gracefully deregistered, I'm left in a situation where I have dozens of failed nodes with 0 services. If you issue deregister via the UI or the API the nodes still eventually come back. I have found that force-leave works but I have to issue these manually per failed node. Having many failed nodes makes things dirty and I'd like to figure out how to keep this clean as the failed state is not offering any value.

**Comment by c4milo** [comment] 2015-05-05 23:02
I had this same issue, I also tried issuing a `consul force-leave` but the nodes were still lingering.

**Comment by armon** [comment] 2015-05-07 00:13
@c4milo Were the nodes dead when you did a "force-leave"? Do they show up in "consul members" at all?

**Comment by c4milo** [comment] 2015-05-07 01:03
They were dead yes, they showed up as failed members.

**Comment by armon** [comment] 2015-05-07 01:14
@c4milo Hmm force-leave should push them into the "left" state. Nodes are not reaped until they are in failed for 72h or in the left state. Did "force-leave" not cause them to go to "left"?

**Comment by c4milo** [comment] 2015-05-07 01:35
Nop

**Comment by c4milo** [comment] 2015-05-07 01:37
Another interesting fact, the wan pool didn't have the failed nodes.

**Comment by c4milo** [comment] 2015-05-12 17:40
@armon I just ran into this again, here is a video: https://asciinema.org/a/bd1apr97vc45f4syahet3dxig

**Comment by armon** [comment] 2015-05-12 18:14
@c4milo Everything looks fine in that video, the nodes are in the left state. "force-leave" just moves a node from the "failed" -> "left" state. They are not removed from the members list for 24 or 72h.

**Comment by c4milo** [comment] 2015-05-12 18:49
I see. I'm going to need more sleep. Thanks @armon.

**Comment by gtmtech** [comment] 2015-06-11 11:11
+1 for making the reap time configurable

**Comment by bryanwb** [comment] 2015-11-11 14:05
+1 for making reap time configurable

**Comment by atrbgithub** [comment] 2015-11-20 13:50
Another +1 for making the reap time configurable

**Comment by c4milo** [comment] 2015-11-20 17:24
-1 if it makes the cluster unstable or it is prone to people having more issues than usual.

**Comment by goacid** [comment] 2015-11-23 13:47
+1 for making reap time configurable

**Comment by s1l0uk** [comment] 2016-01-19 12:46
+1 for making reap time configurable

**Comment by developerinlondon** [comment] 2016-01-22 16:21
+1 for the reap time configurable pls!

**Comment by erkules** [comment] 2016-02-18 20:29
+1 for the reap time configurable

**Comment by naydencho** [comment] 2016-02-22 15:44
+1 for configurable reap time

**Comment by dim** [comment] 2016-03-21 10:03
:+1:

**Comment by Poogles** [comment] 2016-03-21 10:03
:+1:

**Comment by nadirollo** [comment] 2016-04-07 10:47
:+1:

**Comment by ThomasGilbert** [comment] 2016-04-08 13:32
+1 for the reap time configurable

**Comment by slackpad** [comment] 2016-04-11 07:17
While implementing #1935 which makes this configurable, and reviewing it with @sean- we realized that lowering this too much can be fairly dangerous for the case of Consul servers. If there's a partition that isolates a server and this is set low, the server could get kicked prematurely and would need to be re-joined or restarted in order to work again, whereas with the current default setting you'd have to have 72 hours elapse before that's a problem.

Are people mostly worried about clutter in `consul members`, or is there some other problem people are hoping will be fixed by making this configurable?

**Comment by slackpad** [comment] 2016-04-11 07:49
I think at the very least if we make it configurable we should set the minimum relatively high, ~8 hours or more.

**Closed** 2016-04-20 20:50 UTC
Labels: bug

**Comment by lucaswxp** [comment] 2016-08-15 15:44
@slackpad For me, the problem that this causes is that /v1/catalog/service/service endpoint, still shows services from failed nodes, for me it makes more sense, once it's failed, the services get removed.

**Comment by slackpad** [comment] 2016-08-15 15:47
@lucaswxp usually clients use the https://www.consul.io/docs/agent/http/health.html#health_service endpoint to find healthy instances (there's a `?passing` parameter that will filter to only healthy ones).

**Comment by cornfeedhobo** [comment] 2017-04-28 19:40
@slackpad was there any follow up on this? I am having a terrible issue where I destroy nodes which were registered with their FQDN, then recreate the node. When using the API to re-describe the node, Consul registers it, then gets confused and puts it in the "left" state, even though the new node has a different IP, it's just the name that is the same.

**Comment by MitchFierro** [comment] 2018-05-01 17:13
@slackpad using the health API is not always convenient, we prefer the /v1/catalog/service/:service API.  The problem is that this returns service entries for failed nodes.  Is there a way to filter this response to only return services running on known active (not failed) nodes?

**Comment by nikgibbens** [comment] 2018-10-15 14:54
Agreed with @MitchFierro If the /v1/catalog/service/service endpoint could also take a passing=true parameter, this would be preferable in the interest of a smaller response payload.

**Comment by Dmitry1987** [comment] 2020-11-20 17:34
> While implementing #1935 which makes this configurable, and reviewing it with @sean- we realized that lowering this too much can be fairly dangerous for the case of Consul servers. If there's a partition that isolates a server and this is set low, the server could get kicked prematurely and would need to be re-joined or restarted in order to work again, whereas with the current default setting you'd have to have 72 hours elapse before that's a problem.
> 
> Are people mostly worried about clutter in `consul members`, or is there some other problem people are hoping will be fixed by making this configurable?

I have alerts firing for nodes that scaled-in by autoscaling policy... what's the official way to avoid having scaled-in services hanging and alerting in consul?  Does force-leave fix this?
