### ISSUE TITLE
Connect exposes absolute path for Consul proxies => might cause issues during consul updates

### ISSUE THREAD

**Issue by pierresouchay** [hashicorp/consul#4625] opened 2018-08-31 14:55 UTC
When registering a new Proxy, it seems the proxy is resolve with absolute path, for instance:

localhost:8500/v1/agent/services?pretty

returns:
```json
marathon-app-mesos-ping-probe-admin-31548": {

    "Kind": "",
    "ID": "marathon-app-mesos-ping-probe-admin-31548",
    "Service": "mesos-ping-probe-admin",
    "Tags": [
        "3d6c74a3ac7c11e8b3299cdc71473750",
        "http",
        "marathon",
        "marathon-start-20180830T174344Z",
        "marathon-user-mesos-ping"
    ],
    "Meta": {
        "start": "20180830T174344Z"
    },
    "Port": 31548,
    "Address": "",
    "EnableTagOverride": false,
    "CreateIndex": 0,
    "ModifyIndex": 0,
    "ProxyDestination": "",
    "Connect": {
        "Native": false,
        "Proxy": {
            "ExecMode": "daemon",
            "Command": [
                "/opt/consul/1.2.2-criteo1/consul-souchay",
                "connect",
                "proxy"
            ],
            "Config": null
        }
    }

},
```

Basically, consul did resolves it absolute path (here `/opt/consul/1.2.2-criteo1/consul-souchay`)

I wondering if it might cause issues when updating consul to a new version and removing the old executable.

I wonder if having:
```
            "Command": [
                "consul",
                "connect",
                "proxy"
            ]
```

instead would not be better... thus, when Consul would read "consul" as executable, it would consider to fork itself at the appropriate time. I suspect having `/opt/consul/1.2.2-criteo1/consul-souchay` will cause issue if file `/opt/consul/1.2.2-criteo1/consul-souchay` is removed.

**Comment by banks** [comment] 2018-09-18 16:01
> I wondering if it might cause issues when updating consul to a new version and removing the old executable.

The whole rationale for the `Executable()` magic was to make this just work. In your case it's true that if you remove the old binary while it's still running then it might attempt to launch a proxy and fail to find its own binary, but I can't imagine that is a recommended way to upgrade for many reasons.

If you don't remove the binary then this works as intended - which ever binary is running as Agent is the same one that gets invoked for proxy.

Either way, we are winding down efforts on managed proxies as we think they have big issues and we can make other ways to run proxies much more robust so it's unlikely we'll want to change this for now.

**Comment by banks** [comment] 2019-03-21 15:28
Going to close this for now as managed proxies are deprecated. Thanks for the effort here!

**Closed by banks** 2019-03-21 15:28 UTC
Labels: bug, theme/connect
