### ISSUE TITLE
Consul Date format Query

### ISSUE THREAD

**Issue by saswatp** [hashicorp/consul#1776] opened 2016-03-01 20:12 UTC
- Does Consul currently have the ability to log using ISO 8601 format. ( https://www.w3.org/TR/NOTE-datetime) . Is it configurable anywhere ?
- If not , is this something that can be done ? 

Reasoning - In a cloud deployment there are multiple applications (internal as well as opensource) . For log analysis and correlation it is helpful to send all logs from applications in one standard date format. 
ISO 8601 format is currently the standardizing date format that lot of applications use and is recommended in the enterprise world.

**Comment by slackpad** [comment] 2016-03-10 07:06
Hi @saswatp we are looking into some structured logging libraries so we can take a look at this along with that effort.

/cc @sean-

**Comment by saswatp** [comment] 2016-03-12 03:36
That would be great @slackpad  - Thanks !

**Comment by slackpad** [comment] 2017-05-12 21:27
Closing as a duplicate of https://github.com/hashicorp/consul/issues/1249.

**Closed by slackpad** 2017-05-12 21:27 UTC
Labels: enhancement
