### ISSUE TITLE
Meta will be overwritten to null if bring down the leader instance 

### ISSUE THREAD

**Issue by hehailong5** [hashicorp/consul#2809] opened 2017-03-21 09:24 UTC
version: 0.7.5

This is a 3-nodes cluster. 
Firstly, I use the catalog api to register a service  like below:
{
.....
.....
  "Node": "fake",
  "Address": "192.168.10.10",
  "TaggedAddresses": {
    "lan": "192.168.10.10",
    "wan": "10.0.10.10"
  },
  "NodeMeta": {
    "somekey": "somevalue"
  }
.....
.....
}

notice that the "fake" node does not really exist in the cluster.

Secondly, I bring down the leader, the cluster will perform the re-election and a new leader elected.

Lastly, I use the catalog api to query the same service registered before, I get this:

 {
    "ID": "40e4a748-2192-161a-0510-9bf59fe950b5",
    "Node": "fake",
    "Address": "192.168.10.10",
    "TaggedAddresses": {
      "lan": "192.168.10.10",
      "wan": "10.0.10.10"
    },
    "Meta": {
      null
    }
.....
....
  }

notice that the "Meta" field was overwritten to "null". and this happens occasionally.

**Comment by slackpad** [comment] 2017-03-24 06:46
Fixed in https://github.com/hashicorp/consul/pull/2826/commits/3f1c4a6f4453c8959dca67709cbc309bbae4bc82.

**Comment by gerbil** [comment] 2017-04-26 14:09
Not fixed! I can see the same bug on 0.8.0v

**Comment by slackpad** [comment] 2017-04-26 14:17
@gerbil have you updated your servers and still see this? The fix was actually on the server side and not the client in this case.

**Comment by gerbil** [comment] 2017-04-27 07:26
@slackpad what do you mean by 'updated your servers' ?

**Comment by slackpad** [comment] 2017-04-27 13:38
Are you servers running 0.8.0 as well as the clients?

**Comment by gerbil** [comment] 2017-06-09 11:27
@slackpad yes

**Comment by slackpad** [comment] 2017-06-09 14:20
@gerbil can you please open a new issue with the details about what you are seeing?

**Comment by slackpad** [comment] 2017-06-09 15:07
Actually this one is focused enough to just re-open.

**Comment by hehailong5** [comment] 2018-02-12 05:48
still see this in 0.8.4, do you have a plan to fix this?

**Comment by shantanugadgil** [comment] 2018-02-12 06:16
Considering this is an old issue, just curious, have you tried the latest GA 1.0.6 ?

**Comment by jacksontj** [comment] 2019-01-22 01:11
I'm seeing this same behavior on consul v1.2.2. The thing that tipped me off was that the `NodeMeta` was returning `null` instead of `{}`. Seems that there hasn't been any additional investigation into this issue in a while?

**Comment by jacksontj** [comment] 2019-01-31 18:24
Just upgraded to consul 1.4 and the issue is no longer present. IMO this issue can be closed, if anyone else is running into this an upgrade to 1.4 seems to resolve the issue.

**Closed** 2019-07-15 01:13 UTC
Labels: bug
