### ISSUE TITLE
ACL Tokens in split configuration files not loaded correctly

### ISSUE THREAD

**Issue by d-rupp** [hashicorp/consul#3976] opened 2018-03-21 08:52 UTC
### Description of the Issue (and unexpected/desired result)
In the consul.d configuration directory on the client agent we have several files (general agent config, service config, check config) including TWO acl configuration files. In one we have the general agent acl configuration and in the other just the acl_token. The one with the acl_token only was not loaded, only when we merged the files did it work as expected.

### Reproduction steps
1. Setup consul cluster
2. Enable ACLs, default deny
3. Generate an Agent Token for the client with the required agent acl permissions
4. Generate a Token for the client with service and node permissions
5. Make the client use a configuration directory
6. In the configuration directory create a agent acl file agent.json:
  ```
{
  "acl_datacenter": "dc1",
  "acl_down_policy": "extend-cache",
  "acl_agent_token": "agent-acl-token-here"
}
```
7. In the configuration directory create a client acl file client.json:
```
{  "acl_token": "client-acl-token-here" }
```
8. start consul client
9. Try to use permissions that are given to the acl token

 `consul version` for both Client and Server
Client: `1.0.6`
Server: `1.0.6`

### Operating system and Environment details
RHEL 7.4

**Comment by ChipV223** [comment] 2019-07-15 13:54
Hey @d-rupp !

Since it's been a while, I was wondering if you still observe this behavior when using the later versions of Consul?

**Comment by ChipV223** [comment] 2021-04-13 15:26
Closing this as I'm not able to reproduce using the latest Consul release(v1.9.4)

**Closed by ChipV223** 2021-04-13 15:26 UTC
Labels: type/bug
