### ISSUE TITLE
Unable to view multiple DC's in consul UI 

### ISSUE THREAD

**Issue by johntdyer** [hashicorp/consul#2081] opened 2016-06-01 11:33 UTC
### `consul version` for both Client and Server
Client: `0.6.4`
Server: `0.6.4`

### `consul info` for both Client and Server
DC One:
```
[root@discovery3-prod ~]# consul info
agent:
	check_monitors = 0
	check_ttls = 0
	checks = 0
	services = 1
build:
	prerelease =
	revision = 26a0ef8c
	version = 0.6.4
consul:
	bootstrap = false
	known_datacenters = 2
	leader = true
	server = true
raft:
	applied_index = 191852
	commit_index = 191852
	fsm_pending = 0
	last_contact = 0
	last_log_index = 191852
	last_log_term = 12
	last_snapshot_index = 188855
	last_snapshot_term = 3
	num_peers = 2
	state = Leader
	term = 12
runtime:
	arch = amd64
	cpu_count = 8
	goroutines = 88
	max_procs = 24
	os = linux
	version = go1.6
serf_lan:
	encrypted = true
	event_queue = 0
	event_time = 7
	failed = 0
	intent_queue = 0
	left = 0
	member_time = 66
	members = 9
	query_queue = 0
	query_time = 1
serf_wan:
	encrypted = true
	event_queue = 0
	event_time = 1
	failed = 0
	intent_queue = 0
	left = 0
	member_time = 4
	members = 6
	query_queue = 0
	query_time = 1
[root@discovery3-prod ~]#
```

DC Two: 

DC Two:
```
[root@discovery1-prod ~]# consul info
agent:
	check_monitors = 0
	check_ttls = 0
	checks = 0
	services = 1
build:
	prerelease =
	revision = 26a0ef8c
	version = 0.6.4
consul:
	bootstrap = false
	known_datacenters = 2
	leader = false
	server = true
raft:
	applied_index = 701201
	commit_index = 701201
	fsm_pending = 0
	last_contact = 19.634141ms
	last_log_index = 701201
	last_log_term = 23
	last_snapshot_index = 698499
	last_snapshot_term = 6
	num_peers = 2
	state = Follower
	term = 23
runtime:
	arch = amd64
	cpu_count = 8
	goroutines = 104
	max_procs = 24
	os = linux
	version = go1.6
serf_lan:
	encrypted = true
	event_queue = 0
	event_time = 2
	failed = 0
	intent_queue = 0
	left = 0
	member_time = 14
	members = 27
	query_queue = 0
	query_time = 1
serf_wan:
	encrypted = true
	event_queue = 0
	event_time = 1
	failed = 0
	intent_queue = 0
	left = 0
	member_time = 4
	members = 6
	query_queue = 0
	query_time = 1
```

### Operating system and Environment details

 CentOS 6.7

### Description of the Issue (and unexpected/desired result)

I have joined my masters in two data centers

```
[root@discovery1-prod ~]# consul members -wan
Node                                 Address              Status  Type    Build  Protocol  DC
discovery1-prod.lon.tropo.com.lon02  10.164.21.94:8302    alive   server  0.6.4  2         lon02
discovery1-prod.sjc.tropo.com.sjc03  10.160.166.138:8302  alive   server  0.6.4  2         sjc03
discovery2-prod.lon.tropo.com.lon02  10.164.21.71:8302    alive   server  0.6.4  2         lon02
discovery2-prod.sjc.tropo.com.sjc03  10.160.166.183:8302  alive   server  0.6.4  2         sjc03
discovery3-prod.lon.tropo.com.lon02  10.164.21.67:8302    alive   server  0.6.4  2         lon02
discovery3-prod.sjc.tropo.com.sjc03  10.160.166.167:8302  alive   server  0.6.4  2         sjc03
[root@discovery1-prod ~]#
```

However in the UI when I try to load lon02 from sjc03 or vice-versa I get a 500 error in the server logs

### Log Fragments or Link to [gist](https://gist.github.com/)

```
2016/06/01 11:31:44 [ERR] consul.rpc: failed to read byte: remote error: bad certificate from=10.160.166.138:52088
2016/06/01 11:31:45 [DEBUG] memberlist: Initiating push/pull sync with: 10.164.21.71:8302
2016/06/01 11:31:47 [DEBUG] memberlist: TCP connection from=10.164.88.87:47493
2016/06/01 11:31:48 [DEBUG] memberlist: Initiating push/pull sync with: 10.164.88.87:8301
2016/06/01 11:31:55 [DEBUG] agent: Service 'consul' in sync
2016/06/01 11:32:00 [DEBUG] memberlist: TCP connection from=10.160.166.167:35744
2016/06/01 11:32:07 [DEBUG] memberlist: TCP connection from=10.164.21.106:34617
2016/06/01 11:32:18 [DEBUG] memberlist: Initiating push/pull sync with: 10.164.101.94:8301
```

**Comment by johntdyer** [comment] 2016-06-01 11:38
So I just noticed that when I do a curl requests against LON02 to view nodes in SJC03 I get this error via CURL

```
[root@discovery1-prod ~]# curl http://localhost:8500/v1/catalog/nodes?dc=sjc03
rpc error: failed to get conn: x509: certificate is valid for *.sjc03.consul, not discovery1-prod-lon.lon02.consul[root@discovery1-prod ~]#
```

I guess my cert is not correctly setup?

**Comment by ssenaria** [comment] 2016-06-01 20:02
I'm actually getting the same error when I'm trying to use consul-replicate. Trying to sync one DC to another.  However, I'm able to curl properly.

**Comment by johntdyer** [comment] 2016-06-07 13:05
@ssenaria  were you ever able to resolve this ?

**Comment by ssenaria** [comment] 2016-06-07 13:15
@johntdyer I ended up using the correct hostname that the cert was intended for. I was using the hostname, but the cert wasn't valid for it. I changed it to one of the names we used in Apache's virtualhost and all is well.

The client I was running this on is also a web server for other things.

**Comment by slackpad** [comment] 2016-08-11 00:17
Closing this out as it looks like a cert issue. Please kick open if you are still having trouble.

**Closed by slackpad** 2016-08-11 00:17 UTC

**Comment by Evgen787** [comment] 2016-10-25 13:35
Hi, a have problem with multiply view DC, when i access to DC1 ui, i cant access to DC2( in main page ui multiple view dc).

 HTTP error code from Consul: 403 Forbidden

error in nodes in **DC1:**
http: Request GET /v1/internal/ui/nodes?dc=**dc2**&token=<hidden>, error: rpc error: ACL not found from=127.0.0.1:37293

Consul 0.7
