### ISSUE TITLE
DNS with delegation isn't returning node IP Addresses

### ISSUE THREAD

**Issue by hopperd** [hashicorp/consul#1191] opened 2015-08-21 18:18 UTC
We have configured our Bind servers to delegate a zone to consul (note we are using delegation not forward) and it seems as though when requests are made through the Bind server to consul we don't get the node IP Address back.  Here is a sample dig

```
dig test-service.service.dc1.dev.consul SRV

; <<>> DiG 9.8.2rc1-RedHat-9.8.2-0.10.rc1.el6_3.2 <<>> test-service.service.dc1.dev.consul SRV
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 25209
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 3, ADDITIONAL: 3

;; QUESTION SECTION:
;test-service.service.dc1.dev.consul. IN SRV

;; ANSWER SECTION:
test-service.service.dc1.dev.consul. 0 IN SRV 1 1 8480 node1.node.dc1.dev.consul.
test-service.service.dc1.dev.consul. 0 IN SRV 1 1 8480 node2.node.dc1.dev.consul.

;; AUTHORITY SECTION:
dc1.dev.consul. 300   IN      NS      ns1.dc1.consul.
dc1.dev.consul. 300   IN      NS      ns2.dc1.consul.
dc1.dev.consul. 300   IN      NS      ns3.dc1.consul.

;; ADDITIONAL SECTION:
ns2.dc1.consul. 300   IN      A       10.1.1.2
ns1.dc1.consul. 108   IN      A       10.1.1.16
ns3.dc1.consul. 111   IN      A       10.1.1.247
```

But when we query consul directly we get the IP address as expected

```
dig test-service.service.dc1.dev.consul SRV @ns1.dc1.consul

; <<>> DiG 9.8.2rc1-RedHat-9.8.2-0.10.rc1.el6_3.2 <<>> test-service.service.dc1.dev.consul SRV @ns1.dc1.consul
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 57922
;; flags: qr aa rd; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 2
;; WARNING: recursion requested but not available

;; QUESTION SECTION:
;test-service.service.dc1.dev.consul. IN SRV

;; ANSWER SECTION:
test-service.service.dc1.dev.consul. 0 IN SRV 1 1 8480 node1.node.dc1.dev.consul.
test-service.service.dc1.dev.consul. 0 IN SRV 1 1 8480 node2.node.dc1.dev.consul.

;; ADDITIONAL SECTION:
node1.node.dc1.dev.consul. 0 IN A 10.1.1.200
node2.node.dc1.dev.consul. 0 IN A 10.1.1.201
```

Is there any particular reason that consul wouldn't return the Additional Section containing the node IP address when being requested through Bind delegation?

**Comment by slackpad** [comment] 2015-08-31 21:53
Hi @split3 - not sure what's going on with this one - will have to take a deeper look with a test configuration. Is forwarding not possible with your setup?

**Comment by split3** [comment] 2015-09-01 17:38
Unfortunately in this particular setup forwarding isn't an option.

**Comment by ryanuber** [comment] 2015-09-01 18:02
The answer section looks correct. I think that Consul actually _is_ returning the additional section, but BIND sees that it is not authoritative for the records, so instead of returning them directly, it gives you the authoritative addresses to query if you want the IP's. I haven't confirmed this by trying to set up BIND myself, but there is no special logic and no extra break points in the Consul code which could prevent the additional section from being populated if the query is the same. You might explore BIND's documentation, they might have some kind of option for this behavior.

**Comment by westsouthnight** [comment] 2016-12-01 16:27
@slackpad sorry, but i try to do that by multiple ways, i think we need in consul normal DNS interface. Cannot work with service discovery with normal way. We need full DNS functional.

**Comment by slackpad** [comment] 2017-05-02 22:57
I'm going to close this out as we've since added SOA support, and done a ton of other work on the DNS interface.

**Closed by slackpad** 2017-05-02 22:57 UTC
