### ISSUE TITLE
Special 'this.node.consul' dns entry

### ISSUE THREAD

**Issue by far-blue** [hashicorp/consul#2300] opened 2016-08-23 15:13 UTC
It would be very useful for containers and VMs that have their own IP addresses to have a way to fetch the IP address of the host node they are running on - even if it is just so they can then talk to the local consul agent.

I would suggest a special 'this.node.consul' value that always returns the IP address of the local agent (the one responding to the DNS request).

**Comment by slackpad** [comment] 2016-08-23 16:35
In master there's a new https://www.consul.io/docs/agent/http/query.html#near feature in prepared queries that will let you set up a query to look for the Consul service "closest" to the agent, which will always give the local agent. Then you could query for something like `consul-agent.query.consul`.

That's a bit obscure for this use case though, so it's worth thinking about a first class feature. We'd probably want another namespace, maybe simply `agent.consul`.

**Comment by ryansch** [comment] 2016-09-24 01:58
This would really simplify the cases where I can't do service discovery with consul because I'm targeting an instance-local service.

**Comment by roman-cnd** [comment] 2018-03-05 22:33
Would be very handy especially given that sister's Nomad project still doesn't have node's IP exposed inside containers.

**Comment by i0rek** [comment] 2019-12-03 13:49
Closing per response https://github.com/hashicorp/consul/pull/2640#issuecomment-561175287.

**Comment by fastest963** [comment] 2019-12-03 14:02
We have a deployment script that updates files on the disk and then needs to talk to the local service to tell it to reload. It does this using a prepared query like so: `<service>.<hostname>. query.consul` and the query parses out hostname and service in order to lookup the service using tags. The problem is that whenever we want to use this query we have to inject the current hostname. We could use `near: _agent` but if the service has failed or isn't running locally for some reason it would end up reloading a different service on another host rather than failing when the DNS lookup returned nothing.

I agree that there should be a separate namespace but I would also want the functionality to extend to the prepared queries as well with an option in the prepared query definition to limit to the agent only.

Let me know if I should make a new issue or if this is the right one.

**Closed** 2019-12-03 14:53 UTC
Labels: enhancement, theme/api-cleanup, thinking

**Comment by i0rek** [comment] 2019-12-03 14:55
(I forgot to actually close this issue)

@fastest963 thank you for your response. If I understand you correctly, you need a way to query for services on localhost?! If thats the case, it wasn't covered by the corresponding PR. If you are using your deployment script to update service configurations, shouldn't the same script reload your services?

**Comment by fastest963** [comment] 2019-12-03 14:59
@i0rek yeah I was responding because you mentioned that people might want to query for services too so I was chiming in saying we do.

We make an RPC call to reload the service so we can get a success or failure back. If we just reloaded the service via SIGHUP or systemd then we'd get no response back and no way to understand if it failed or not. In order to make the RPC call we need a way to discover the port (randomized since we have Consul) on the host to make the RPC call to.

**Comment by i0rek** [comment] 2019-12-03 16:31
Thank you for letting us know!
