### ISSUE TITLE
empty bind_addr when using sockaddr template in config file to bind to vlan interface

### ISSUE THREAD

**Issue by protenhan** [hashicorp/consul#8434] opened 2020-08-05 08:51 UTC
#### Overview of the Issue

I'm trying to deploy a three node consul cluster in an embedded environment. The three machines have multiple physical network interfaces and even more vlans and ucarp addresses configured. I would like to use a sockaddr template in the consul configuration to be able to deploy the same config to all of the three nodes. However I found that while the sockaddr template that I validated by running sockaddr on the machines does return a single IP but when I provide that template as the `bind_addr` block in my hcl file consul does not start with a `bind_addr cannot be empty` error.

#### Reproduction Steps

Steps to reproduce this issue:

1. Configure a vlan interface (e.g. eth1.17@eth1)
1. Run 
```sh
$ sockaddr eval 'GetAllInterfaces | include "network" "10.17.0.0/15" | sort  "size,address" | attr "address" '
10.17.0.5
```
3. Configure the server.hcl with this template
```hcl
bind_addr = "GetAllInterfaces | include \"network\" \"10.17.0.0/15\" | sort \"size,address\" | attr \"address\" "
datacenter = "embedded1"
bootstrap_expect = 3
server = true
encrypt = "verySecretBase64String="  
rejoin_after_leave = true
retry_join = ["node1", "node2", "node3"]
```
4. Run 
```sh
$ consul validate server.hcl
Config validation failed: bind_addr cannot be empty
```
5. When I explicitly configure the IP `bind_addr = "10.17.1.16"` then consul starts just fine.

### Consul info for both Client and Server

Consul version is 1.7.4 but I have also tested 1.8.0 with the same result.

### Operating system and Environment details

Running on Debian Buster with Linux kernel 4.19.82 on amd64 

### Log Fragments
I cannot provide logs since the startup already fails :disappointed:

**Comment by protenhan** [comment] 2020-08-05 08:57
It also does not work when specifying the interface name `bind_addr = "GetInterfaceIP \"eth2.17\" "`

**Comment by jsosulska** [comment] 2020-08-07 14:47
Hello @protenhan 

Thanks for posting. Can you please add `{{ }}` and `' '` around your `bind_addr`? It should look like this:
```
'{{ GetAllInterfaces | include \"network\" \"10.17.0.0/15\" | sort \"size,address\" | attr \"address\" }}'
```

The go-sockaddr template library shows [examples](https://godoc.org/github.com/hashicorp/go-sockaddr/template), as well as in our [bind documentation](https://www.consul.io/docs/agent/options.html#_bind).

Hope this helps! If this answers your question, please close the issue. If this does not solve the issue, please comment with what errors you get, if any.

Best, 
Jono

**Comment by protenhan** [comment] 2020-08-12 07:43
Hi @jsosulska 

thank you for your help. 
I edited my `server.hcl` to your suggestion
```hcl
bind_addr = ' {{ GetAllInterfaces | include \"network\" \"10.17.0.0/15\" | sort \"size,address\" | attr \"address\" }}'
datacenter = "embedded1"
bootstrap_expect = 3
server = true
encrypt = "verySecretBase64String="  
rejoin_after_leave = true
retry_join = ["node1", "node2", "node3"]
```
But this throws the following error:
```shell
$ consul validate server.hcl
Config validation failed: Error parsing server.hcl: At 1:13: illegal char
```

So to me this really seems like a bug. Since my initial `server.hcl` works with any IP that is assigned to a pysical network interface but not with VLAN interfaces.

**Comment by protenhan** [comment] 2020-08-12 08:19
So I finally figured out the solution. 
The following `server.hcl` works also for VLAN interfaces:
```hcl
bind_addr = "{{ GetAllInterfaces | include \"network\" \"10.17.0.0/15\" | sort \"size,address\" | attr \"address\" }}"
datacenter = "embedded1"
bootstrap_expect = 3
server = true
encrypt = "verySecretBase64String="  
rejoin_after_leave = true
retry_join = ["node1", "node2", "node3"]
```

**Closed** 2020-09-11 06:48 UTC
Labels: theme/config, type/question

**Comment by blake** [comment] 2021-07-30 07:01
@protenhan I was looking to add this sockaddr example to our documentation, but in my testing I found that I am not able to reproduce this issue with Consul 1.7.4 or later. Consul correctly starts in my environment when providing the VLAN sub-interface name directly to `GetInterfaceIP`. See the following configuration:

```hcl
# config.hcl
server = true
bootstrap_expect = 1
bind_addr = "{{ GetInterfaceIP \"eth0.11\" }}"
data_dir = "/tmp/consul"
rejoin_after_leave = true
```

```shell
$ consul agent -config-file=config.hcl
BootstrapExpect is set to 1; this is the same as Bootstrap mode.
bootstrap = true: do not enable unless necessary
==> Starting Consul agent...
           Version: 'v1.7.4'
           Node ID: 'bdd45ffe-265e-86a3-be30-42a30f76c5d4'
         Node name: 'rpi4-2'
        Datacenter: 'dc1' (Segment: '<all>')
            Server: true (Bootstrap: true)
       Client Addr: [127.0.0.1] (HTTP: 8500, HTTPS: -1, gRPC: -1, DNS: 8600)
      Cluster Addr: 10.0.2.42 (LAN: 8301, WAN: 8302)
           Encrypt: Gossip: false, TLS-Outgoing: false, TLS-Incoming: false, Auto-Encrypt-TLS: false

==> Log data will now stream in as it occurs:
```

Here's my [Netplan](https://netplan.io/) interface config for reference.

```yaml
---
network:
  version: 2
  ethernets:
    eth0:
        dhcp4: true
        match:
            macaddress: dc:a6:32:04:33:a5

  vlans:
    eth0.10:
        addresses:
        - 10.0.2.12/27
        id: 10
        link: eth0
    eth0.11:
        addresses:
        - 10.0.2.42/27
        id: 11
        link: eth0
```

Let me know if you have any info which might help in reproducing this issue.
