### ISSUE TITLE
Consul Web UI Key/Value XML Mode

### ISSUE THREAD

**Issue by debjitk** [hashicorp/consul#6658] opened 2019-10-19 23:41 UTC
It would be really nice if XML is also supported in code mode for Consul Web UI Key/Value

**Comment by jnwright** [comment] 2019-11-22 19:38
Thanks for the feedback! That's not currently on our list of things to do, but we'll be sure to update you when/if it comes up during feature planning.

**Comment by jkirschner-hashicorp** [comment] 2021-10-18 22:27
Hello Consul community members,

We would welcome a PR contributed by the community for this UI enhancement!

If you're interested, please comment here so anyone interested can stay informed.

**The task**

- Add XML syntax highlighting as an option for the Key-Value editor
  - The XML option should be placed at the bottom of the format dropdown (after JSON, HCL, YAML)
  - Use the [codemirror XML mode](https://codemirror.net/mode/xml/) for the syntax highlighting (which is already a dependency of the repo). The mode should be configured with:
    - `htmlMode = false`
    - `matchClosing = true`
    - `alignCDATA = false`
- In the PR description, paste an image of what the results of your work look like!
- Optional: if you are experienced with Ember, we would welcome a proposal on how to better centralize the code editor's configuration!

**Getting started with Consul UI development**
To launch the UI in development mode, follow the directions in the [UI readme](https://github.com/hashicorp/consul/tree/main/ui/packages/consul-ui#installation).

When running the development app (make start), any changes you save in the website source files will be recompiled and reloaded in your browser pages pointed at the app (e.g., http://localhost:4200/ui/).

Please name your branch according to [these guidelines](https://github.com/hashicorp/consul/tree/main/ui/packages/consul-ui#branching) to ensure that the PR you submit triggers CI execution of the frontend test suite.

**Accessing the KV code editor**
You should be able to access the key-value screen at http://localhost:4200/ui/dc1/kv. The UI should be pre-populated with some key-value entries, but if not, you can create one using the blue button on the top-right of the page. Click on a KV entry to access the edit screen (with the code editor).

**Implementation guidance**
Configuration of available CodeMirror modes for the Code Editor component happens here: https://github.com/hashicorp/consul/blob/ed6918c6c2d10104d3055d22b1f57bef97e52ace/ui/packages/consul-ui/app/services/code-mirror/linter.js#L3-L19

Pulling in the CodeMirror mode dependencies happens here: https://github.com/hashicorp/consul/blob/26c9d5c135746794a6d9452ca2e6df3a35e914e7/ui/packages/consul-ui/ember-cli-build.js#L181-L200

**Comment by tmnhat2001** [comment] 2021-12-04 03:11
@jkirschner-hashicorp I would like to work on this issue. There is an issue with the `matchClosing` option because we are using a custom theme for CodeMirror. The `matchClosing` option will use the CSS class `.cm-error` to highlight the text when the closing tag does not match the opening tag (see the screenshot below). The custom style does not define this CSS class right now so the error text does not get highlighted in Consul UI. Could you advise which color should be used to highlight this text?
![Screenshot from 2021-12-03 22-09-43](https://user-images.githubusercontent.com/15841903/144694820-1c4647f6-6c43-4258-88e7-12df18a8c254.png)

**Comment by jkirschner-hashicorp** [comment] 2021-12-06 21:36
@tmnhat2001 : thanks for volunteering to work on this!

In your example above, it sounds like `</not>` would have the `.cm-error` class. What class(es) would the opening `<note>` tag have?

I need to check in with the design team about the syntax highlighting for open and close tags. Feel free to proceed without having that information yet though, as that should just be something we can add at the end (or even post-merge) - since it would just be defining CSS for `.cm-error` (right?).

**Comment by johncowen** [comment] 2021-12-07 09:17
Hey @tmnhat2001 

Just seconding what @jkirschner-hashicorp said here

> The custom style does not define this CSS class right now so the error text does not get highlighted in Consul UI. Could you advise which color should be used to highlight this text?

Feels like you'd be fine to go ahead and add this missing class and use whatever color you feel is appropriate, this page may be of help here:

https://consul-ui-staging-iddjh1n5f-hashicorp.vercel.app/ui/docs/styles/base/color

That ^ lists our current color swatches plus explanation of how we do things currently. Please note, this file is a little "tech debt-y", some info [here with the paragraph beginning "Our code editor syntax highlighting..." in the description](https://github.com/hashicorp/consul/pull/11200), so don't worry too much about how you go about doing it, as long as you are happy with it/the color then I'd say thats fine.

Lastly as @jkirschner-hashicorp said, once we've checked in with the team we can use whatever you do to replace the color as defined by design at a later date if need be.

Thanks again for your help with this 🎉 !

**Comment by tmnhat2001** [comment] 2021-12-08 03:12
@jkirschner-hashicorp @johncowen Thank you both for your guidance! I will proceed with the implementation and let you know which CSS class is being used for regular text within the code editor.

**Comment by tmnhat2001** [comment] 2021-12-09 02:35
@jkirschner-hashicorp @johncowen  The `<note>` tag in the example will have the CSS class [.cm-tag](https://github.com/hashicorp/consul/blob/b71fff9f1c3ad1d6c77352ccaf80b70fb0c1670a/ui/packages/consul-ui/app/components/code-editor/skin.scss#L127-L129).

I've opened a [PR](https://github.com/hashicorp/consul/pull/11785) for this. Please review it when you have time.

**Closed** 2022-01-04 16:24 UTC
Labels: type/enhancement, good first issue, theme/ui, theme/kv, Hacktoberfest
