### ISSUE TITLE
consul 0.4.1 crashes if the system is unresponsive

### ISSUE THREAD

**Issue by telmich** [hashicorp/consul#557] opened 2014-12-27 20:51 UTC
While experimenting with consul on ceph based VMs, which were hanging due to ceph i/o (deep scrub), the VM becomes very slow/hangs for some time (time > 60 seconds). When tihs happens, consul-0.4.1 crashed with the following traceback.

I hope this helps do diagnose the problem.

@sethvargo edit, moved to Gist: https://gist.github.com/sethvargo/5b9f38e1693f414241a3

**Comment by armon** [comment] 2015-01-02 16:31
This is a known issue. We use a simple timeout to detect an internal deadlock which can occur in certain conditions (internal bugs mostly). We've up'ed this timeout repeatedly, but I guess it's still an issue under some cases like this. I guess we can try to up it even further...

**Comment by mitchellh** [comment] 2015-01-02 16:42
@armon Is the only behavior we can do in this case to panic? Is there a way we can gracefully fail out somehow. And, in either case, perhaps we just make it configurable as an "advanced case".

**Comment by armon** [comment] 2015-01-02 16:48
Yeah unfortunately we are blocked in cgo trying to start a transaction, so there is no way for us to gracefully abort. We could log a message instead of panic, but if it is a deadlock the system will never recover anyways. The panic at least provides us with a backtrace to help debug the situation.

**Comment by mitchellh** [comment] 2015-01-02 16:50
Ah didn't realize its trapped in cgo. That is pretty terrible.

**Comment by telmich** [comment] 2015-01-02 21:41
For someone who hasn't seen much into the code - why do we need to detect a deadlock by a timer at all? Is it for debugging purposes or is it necessary for part of operation?

For me it would be hard to give an upper limit, as VMs can hang arbitrarily long. In case a timer is needed, I would prefer a soft restart of consul rather than a full crash, so manual work can be avoided.

Btw, happy increment to 0x7df.

**Comment by ryanuber** [comment] 2015-01-03 03:00
@telmich from my understanding, we have to use a timeout because a routine we call from the LMDB C code gets "stuck" on occasion, and rather than blocking forever (essentially causing an undetectable/unrecoverable condition), we set a conservative upper limit on execution time and bail if we aren't done by the deadline.

@armon is that correct? Do we have an open issue upstream yet by chance?

**Comment by telmich** [comment] 2015-01-04 10:15
I see - that is rather hideous issue if there is an external deadlock problem.

Is it possible to soft restart consul / reconnect to lmdb instead of completly crashing?

In our environment we will have to tolerate hanging processes for 1-5 minutes, as we are building our VMs on a ceph cluster that is not yet friendly enough to VMs to ensure they respond quickly (I know, this is another bug, but we are eating our own dog food so things improve).

**Comment by armon** [comment] 2015-01-05 19:20
@telmich One possibility is you could build from master and modify this constant:
https://github.com/hashicorp/consul/blob/master/consul/mdb_table.go#L31
If you set that to a huge value (10 minutes) it should work around this.

The issue is that LMDB is stuck blocking on IO and we have to way to get it to un-stick. It's not a deadlock per se, rather just arbitrarily slow IO. Restarting Consul or LMDB won't help since it will still need to interact with the disk and just block again.

**Comment by c4milo** [comment] 2015-04-06 19:42
@ryanuber will this be fixed with BoltDB backend?

**Comment by ryanuber** [comment] 2015-11-25 02:01
This should no longer happen on master, and will be released with Consul 0.6 shortly!

**Closed by ryanuber** 2015-11-25 02:01 UTC
