### ISSUE TITLE
Allow locks to be maintained for a minimum period of time.

### ISSUE THREAD

**Issue by rayward** [hashicorp/consul#2864] opened 2017-04-03 06:43 UTC
I'd like to use `consul lock` in conjunction with cron tasks. My aim is to have the cron configured on several nodes (for high availability reasons), but to only execute the cron once per configured period.

Due to the nature of the cron command itself being run periodically (as opposed to a long running daemon) there could be occasions where:

1) a task is executed very quickly on one node A, and
2) time or systems load variations on node B

may mean the cron is executed again on node B.

I'd like to see the addition of a feature where the lock can be maintained for a set period of time after the child process has exited (or alternatively since the lock was first acquired, ie. before executing the child) so that other nodes don't acquire the lock and execute the same task until the cron is due for its next iteration.

**Comment by slackpad** [comment] 2017-05-01 23:13
Hi @rayward I think https://github.com/hashicorp/consul/issues/2983 would work well for your use case, and not require any clock synchronization. You would generate your key based off the idealized cron time, like "2017-05-01-12-00-00" and the `once` semantics would ensure that the given slot only had one job run, even in the face of clock skew. I'll close this in favor of that, but feel free to comment if you think I've missed something.

**Closed by slackpad** 2017-05-01 23:13 UTC

**Comment by rayward** [comment] 2017-05-02 05:28
@slackpad thanks, I think that would work out. I presume I'd have to wrap my `consul lock` command in a script that can generate the time-based key for each invokation.

Would I need to be concerned about consul being filled up with lots of old keys, especially for crons that run often?

**Comment by slackpad** [comment] 2017-05-09 23:01
@rayward The `once` feature would need to clean up old keys by design (the lock holder can clear them out, kind of like a log rotation), or if we do expiring keys in the future we could use that mechanism.
