### ISSUE TITLE
Possible race condition in re-registering a failed service/check

### ISSUE THREAD

**Issue by armon** [hashicorp/consul#564] opened 2014-12-31 06:49 UTC
It sounds like from the bug report there may be a race condition in re-registering a service after it has failed it's health check. Not yet confirmed.

From email:

I'm using Consul 0.4.1. There are 3 machines each running a Consul server, no other machines or Consul agents/clients.

I have a client app that makes blocking calls to /v1/health/service/myService?passing&index=... in a loop, so it can monitor for myService instances being registered and deregistered. The client just checks each response for new or missing service IDs compared to the previous iteration to decide whether a service has just appeared or disappeared. So far so good.

When a myService instance starts it registers itself (including a TTL health check definition) via /v1/agent/service/register. It then starts reporting a periodic health check. The client immediately sees the registration. It also sees the service instance disappear when the service eventually deregisters itself on exit.

I had a situation where the only running myService instance was abruptly killed (kill -9) so it didn't get a chance to deregister. Its status went to critical and /v1/health/service/myService?passing&index=... stopped listing the dead service in its response. This is as expected, but when I next registered a new myService instance the following happened:

1) The client's call to /v1/health/service/myService?passing&index=... returned with the newly registered service listed in the response (as expected).
2) The client iterated, making another blocking call to /v1/health/service/myService?passing&index=...
3) The call returned immediately with no services listed in the response, even though the newly added service was still healthy.
4) The client iterated, calling /v1/health/service/myService?passing&index=... again. The response came back immediately with the new service reappearing back in the response!
5) At this point things stabilised as long as no services were added: /v1/health/service always correctly reported one healthy service no matter how many times it was called.
6) If another service instance was registered, the system would revert to being in the step #1 state above which would result in the two spurious responses from step #3 and #4, before stabilising again at step #5.

This is a problem for me because my client app thinks there was a registration -> deregistration -> registration for what is really a single service that has only registered once.

Eventually I restarted the Consul node that had the critical "kill -9" service registered and everything returned to normal. Registering a new service behaved as expected with steps #3 to #5 not happening any more, so it seems that the "critical" dead service was somehow to blame?

I wasn't able to replicate this on a couple of attempts so presumably there is a race condition that is causing it, or am I misunderstanding something here and using the API incorrectly? Assuming my API use is OK, I don't think the problem is in my code since the client is effectively just calling /v1/health/service/myService?passing&index=... in a loop and printing each response, and the service is just registering on startup by calling /v1/agent/service/register then sending a TTL every few seconds.

**Comment by chrismiller** [comment] 2015-01-02 12:19
Scratch my previous comment, the lack of the "passing" parameter doesn't seem to be a factor. I've now seen the problem occur even when the parameter is present.

**Comment by armon** [comment] 2015-01-05 19:59
@chrismiller Do you have a minimal repro case you could provide? That would be very helpful

**Comment by chrismiller** [comment] 2015-01-06 11:28
OK I think I've figured out the problem. When a service is first registered but before the service sends its first health check, Consul initially reports a service as available but then it immediately reports the service as not present again. Once the first health check arrives the service reappears.

This leads to a race condition. If the first health check is sent quickly enough the client doesn't notice. However if the client re-requests the available services after the service is registered but before the first health check has arrived, the service disappears.

Here are some example bash scripts that should reproduce the problem: https://www.dropbox.com/s/r3cydamyparcqf8/testcase.zip?dl=0

I also have pcap traces of "good" and "bad" HTTP traffic that show the issue. Let me know if you want these as well but I think the above should be enough.

**Comment by armon** [comment] 2015-01-06 18:49
Ahh okay. Yep this makes sense. Thinking about it, I think we have another open ticket for this too...

**Comment by armon** [comment] 2015-01-06 18:49
Thanks for nailing down the issue!

**Comment by ryanuber** [comment] 2015-01-14 00:07
I think I know why this is happening.

1. When a new service is registered, it registers with the agent and is later synced to Consul.
2. Currently, the agent syncs service definitions first, independently of health checks. Since there are no health checks registered at this point, it makes sense that the service appears healthy.
3. Consul then iterates over all of the health checks, and registers them in critical state. All health checks are registered initially with Critical status to avoid placing unhealthy nodes into the pool. This explains why the service would not show up when using `?passing`.
4. Health checks eventually are run, and once they are passing, that status is again synced to Consul from the agent, and the service enters a healthy state. This explains how the service magically came back.

I am working in a branch on service registration, and I think this issue will also be resolved once we get it merged in. I'll try to get some test cases against this kind of thing as well.

Thanks @chrismiller!

**Comment by chrismiller** [comment] 2015-01-14 11:43
Thanks for investigating and it's great to hear you've figured out the root cause. Looking forward to the new service registration code. Feel free to let me know if you want me to do any further testing.

**Comment by chrismiller** [comment] 2015-01-30 00:24
I'm wondering if a fix for this is scheduled for the 0.5 release or will it not come until later? (I'm not trying to pressure you to include it, just want to know so I can plan for it either way)

**Comment by ryanuber** [comment] 2015-01-30 07:27
@chrismiller this should actually be fixed in the master branch, from #591! There were a number of tickets that were related to this, I just forgot to update this one. This should be fixed in consul 0.5.1, including 0.5.1rc1.

Thanks again for the detailed report and repro cases!

**Closed by ryanuber** 2015-01-30 07:27 UTC
Labels: bug
