### ISSUE TITLE
Odd behavior with Cloud Auto-join feature for retry_join_wan parameter in AWS

### ISSUE THREAD

**Issue by zzantares** [hashicorp/consul#13828] opened 2022-07-21 01:55 UTC
Hi there, thanks for the great work you put into this product!

### Overview of the Issue

Using the [Cloud Auto-join](https://www.consul.io/docs/install/cloud-auto-join) feature for the [`retry_join_wan`](https://www.consul.io/docs/agent/config/cli-flags#retry-join) parameter in AWS with a EC2 VPC Endpoint results in:

```
[ERROR] agent: Cannot discover address: cluster=WAN address="provider=aws region=us-west-2 tag_key=Service tag_value=consul addr_type=private_v4 service=ec2 endpoint=https://vpce-redacted-redacted.ec2.us-west-2.vpce.amazonaws.com" error="discover-aws: DescribeInstancesInput failed: RequestError: send request failed
```

whereas the same request with AWS CLI in the same machine works fine. The odd thing is that the catalogs list both datacenters as if they were discovered ok? 🧐 

### Details

I'm in the works of setting up a Consul cluster however we're seeing an odd behavior when using the [Cloud Auto-join](https://www.consul.io/docs/install/cloud-auto-join) feature for the [`retry_join_wan`](https://www.consul.io/docs/agent/config/cli-flags#retry-join) parameter in the Consul servers.

To provide more context into the problem, we're setting up a cluster distributed in two AWS Regions (let's say `us-east-2` and `us-west-2`), the Consul servers in one region (eg. `us-east-2`) need the addresses of the Consul servers in the other region (eg. `us-west-2`) and viceversa to see each other and form the Consul WAN cluster.

Our environment looks like this:

- Traffic between our VPCs in both regions is enabled with VPC Peering so traffic from `us-east-2` and `us-west-2` datacenters is allowed.
- HTTPS traffic is allowed in the VPC's AWS Security Group (the auto-join feature sends requests to the AWS EC2 API which needs https) along with the usual TCP ports used by Consul (`8300`, `8302`, `8500`).
- Each of the VPC's has an AWS EC2 VPC Endpoint attached to it so that we can talk to AWS EC2 API from within the private subnet **since internet egress is disabled in our environment and there's no route through the public internet**.
- AWS Service Endpoints are not multi-region enabled which means that the VPC Endpoint in `us-east-2`'s VPC can't be requested to describe EC2 instances in `us-west-2`'s VPC. However, because of the VPC Peering and the Security Group rules we have in place between both regions we are able to use the VPC Endpoint from the other region to describe EC2 instances in that other region. For example, in `us-east-2` we can describe the EC2 instances that exist in `us-west-2` by sending the request to `us-west-2`'s VPC Endpoint, instead of the `us-east-2`'s VPC Endpoint; likewise for the opposite direction (`us-west-2` -> `us-east-2`).

The following works fine:

In `us-east-2`:

```console
# we can describe instances in this region
$ aws ec2 describe-instances --region=us-east-2

# we can describe instances in `us-west-2` by using the VPC Endpoint in `us-west-2` VPC.
$ aws ec2 describe-instances --region=us-west-2 --endpoint-url=https://vpce-XXXXXXXXXXXXXXXXX-XXXXXXXX.ec2.us-west-2.vpce.amazonaws.com
```

In `us-west-2`:

```console
# we can describe instances in this region
$ aws ec2 describe-instances --region=us-west-2

# we can describe instances in `us-east-2` by using the VPC Endpoint in `us-east-2` VPC.
$ aws ec2 describe-instances --region=us-east-2 --endpoint-url=https://vpce-XXXXXXXXXXXXXXXXX-XXXXXXXX.ec2.us-east-2.vpce.amazonaws.com
```

So with this in mind, we're setting the `retry_join_wan` parameter as follows in the server's configuration file:

For servers in `us-east-2`:

```hcl
retry_join_wan = ["provider=aws region=us-west-2 tag_key=Service tag_value=consul addr_type=private_v4 service=ec2 endpoint=https://vpce-XXXXXXXXXXXXXXXXX-XXXXXXXX.ec2.us-west-2.vpce.amazonaws.com"]
```

For servers in `us-west-2`:

```hcl
retry_join_wan = ["provider=aws region=us-east-2 tag_key=Service tag_value=consul addr_type=private_v4 service=ec2 endpoint=https://vpce-XXXXXXXXXXXXXXXXX-XXXXXXXX.ec2.us-east-2.vpce.amazonaws.com"]
```

However when starting the Consul Server, we see the following sequence of message in the logs (similar messages are seen in the servers of both `us-east-2` and `us-west-2` regions):

```
Jul 21 00:28:25 consul1.us-east-2 consul[9748]: 2022-07-21T00:28:25.892Z [INFO]  agent: discover-aws: Region is us-west-2: cluster=WAN
Jul 21 00:28:25 consul1.us-east-2 consul[9748]: 2022-07-21T00:28:25.892Z [INFO]  agent: discover-aws: Filter instances with Service=consul: cluster=WAN
Jul 21 00:30:26 consul1.us-east-2 consul[9748]: 2022-07-21T00:30:26.187Z [ERROR] agent: Cannot discover address: cluster=WAN address="provider=aws region=us-west-2 tag_key=Service tag_value=consul addr_type=private_v4 service=ec2 endpoint=https://vpce-XXXXXXXXXXXXXXXXX-XXXXXXXX.ec2.us-west-2.vpce.amazonaws.com" error="discover-aws: DescribeInstancesInput failed: RequestError: send request failed
Jul 21 00:30:26 consul1.us-east-2 consul[9748]: caused by: Post "https://ec2.us-west-2.amazonaws.com/": dial tcp 52.94.181.146:443: i/o timeout"
Jul 21 00:30:26 consul1.us-east-2 consul[9748]: 2022-07-21T00:30:26.187Z [WARN]  agent: Join cluster failed, will retry: cluster=WAN retry_interval=30s error="No servers to join"
```

The timeout error is expected, we don't have internet egress so the public EC2 API address can't be reached; but there's that message about not being able to discover addresses using the other's region VPC Endpoint (which AWS CLI in the same server has no problem with).

The odd behavior is that the following commands works fine, the servers can see each other in the catalogs:

In `us-east-2`:

```console
$ consul catalog datacenters
us-east-2
us-west-2

$ consul catalog nodes -datacenter="us-west-2"
Node             ID        Address      DC
consul1          e6abf0fd  10.251.22.4  us-west-2
consul2          60f2258b  10.251.22.5  us-west-2
consul3          9d2cc03f  10.251.22.6  us-west-2

$ consul members -wan
Node                 Address           Status  Type    Build   Protocol  DC           Partition  Segment
consul1.us-west-2    10.251.22.4:8302  alive   server  1.12.3  2         us-west-2    default    <all>
consul1.us-east-2    10.250.22.4:8302  alive   server  1.12.3  2         us-east-2    default    <all>
consul2.us-west-2    10.251.22.5:8302  alive   server  1.12.3  2         us-west-2    default    <all>
consul2.us-east-2    10.250.22.5:8302  alive   server  1.12.3  2         us-east-2    default    <all>
consul3.us-west-2    10.251.22.6:8302  alive   server  1.12.3  2         us-west-2    default    <all>
consul3.us-east-2    10.250.22.6:8302  alive   server  1.12.3  2         us-east-2    default    <all>
```

And the case is similar for Consul Servers in `us-west-2`, there I'm able to query `us-east-2` catalogs and see the nodes in the other region, so I'm puzzled about the error message in the logs.

Why does this happen?

**Comment by Amier3** [comment] 2022-07-25 16:31
Hey @zzantares 

Thanks for the detailed report, much appreciated! Are you seeing this error persist and/or any other indications that something is wrong with the cluster? I ask because that  " error="No servers to join " is common on cluster startup as the leader election is occurring -- and should drop off eventually if the cluster is healthy.

**Comment by zzantares** [comment] 2022-07-25 21:53
Hi @Amier3, it appears the message has stopped being logged now, so there's no indication that this is still occurring; however the message was consistently showing every ~10mins or so for a full 26 hours on the day I opened the issue.

**Comment by Amier3** [comment] 2022-07-26 20:16
@zzantares 

That's definitely odd. It could've been a potential bug with raft leader election but that'd be hard to figure out now. I'm going to close this for now since we cant reproduce but please "@" me on this closed post or make a separate bug report if this issue comes up again.

**Closed by Amier3** 2022-07-26 20:16 UTC
Labels: type/bug
