### ISSUE TITLE
Mesh Gateways high memory consumption until out of memory

### ISSUE THREAD

**Issue by rdemachkovych** [hashicorp/consul#8188] opened 2020-06-25 09:47 UTC
### Overview of the Issue

After connecting two datacenters into wan federation using mesh getaway the RAM on servers dry faster until all RAM used and receive `out of memory`.
```
~$ free -m
              total        used        free      shared  buff/cache   available
Mem:          32146        8030       23082          32        1034       23594
Swap:             0           0           0
~$ free -m
              total        used        free      shared  buff/cache   available
Mem:          32146        8214       22898          32        1034       23410
Swap:             0           0           0

~$ consul members -wan
Node                        Address           Status  Type    Build       Protocol  DC                Segment
consul-01.dc2            10.118.2.34:8302  alive   server  1.8.0beta2  2         dc2            <all>
consul-01.dc1            10.118.2.34:8302  alive   server  1.8.0beta2  2         dc1            <all>
```

#### Reproduction Steps

Steps to reproduce this issue, eg:

1. Create a two DC cluster with one 1 server nodes on each
1. Gossip Encryption
1. Secure Agent Communication with TLS Encryption
1. Enable Connect with `enable_mesh_gateway_wan_federation = true` on primary DC
1. Use [WAN Federation via Mesh Gateways ](https://www.consul.io/docs/connect/wan-federation-via-mesh-gateways) documentation to start Mesh Gateways
1. Run `consul connect envoy -gateway=mesh -register -service "gateway-primary" -address 10.118.2.34:8443 -expose-servers` on both DC
1. Observe memory
1. Receive `fatal error: runtime: out of memory`

### Consul info for both Client and Server
<details>
  <summary>Server info</summary>

```
consul info
agent:
	check_monitors = 0
	check_ttls = 0
	checks = 2
	services = 2
build:
	prerelease = beta2
	revision = a774d9b1
	version = 1.8.0
consul:
	acl = disabled
	bootstrap = true
	known_datacenters = 1
	leader = true
	leader_addr = 10.118.2.34:8400
	server = true
raft:
	applied_index = 51989
	commit_index = 51989
	fsm_pending = 0
	last_contact = 0
	last_log_index = 51989
	last_log_term = 34
	last_snapshot_index = 49167
	last_snapshot_term = 30
	latest_configuration = [{Suffrage:Voter ID:69a833c2-7884-1117-202b-fd74c07e6712 Address:10.118.2.34:8400}]
	latest_configuration_index = 0
	num_peers = 0
	protocol_version = 3
	protocol_version_max = 3
	protocol_version_min = 0
	snapshot_version_max = 1
	snapshot_version_min = 0
	state = Leader
	term = 34
runtime:
	arch = amd64
	cpu_count = 4
	goroutines = 181
	max_procs = 4
	os = linux
	version = go1.14.1
serf_lan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 47
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 55
	members = 5
	query_queue = 0
	query_time = 3
serf_wan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 1
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 50
	members = 1
	query_queue = 0
	query_time = 80
```

</details>

### Operating system and Environment details
Azure VMSS
SKU: Standard_D8_v3
16.04.1-Ubuntu

### Log Fragments
-n/a-

**Comment by david-yu** [comment] 2023-10-12 05:43
Given the age of this issue, and since it is reported on 1.8.0, we will close this issue. Please go ahead and re-file as a new version on the current supported versions of Consul, i.e. 1.16.x, 1.15.x, and 1.14.x. Also we would likely need more config details and details on the traffic sent through mesh gateways to try to reproduce what is happening.

**Closed by david-yu** 2023-10-12 05:43 UTC
Labels: type/bug, theme/connect, theme/mesh-gw
