### ISSUE TITLE
consul node failed repeatedly

### ISSUE THREAD

**Issue by ambiguous** [hashicorp/consul#887] opened 2015-04-26 12:35 UTC
Hi. Im using consul 0.5.

Consul output log repeatedly and node down.
It's only high load servers.
```sh
2015/04/26 13:30:46 [INFO] memberlist: Suspect HOSTNAME has failed, no acks received
2015/04/26 13:30:47 [INFO] memberlist: Marking HOSTNAME as failed, suspect timeout reached
2015/04/26 13:30:47 [INFO] serf: EventMemberFailed: HOSTNAME XX.XX.XX.XX
```

I fix to write this line to DefaultConfig() in consul/consul/config.go
```sh
conf.SerfLANConfig.MemberlistConfig.ProbeInterval = 5 * time.Second
```

Have consul plan to add ProbeInterval to Configuration File?
or another solving problem

**Comment by ryanuber** [comment] 2015-04-29 04:46
Hi @ambiguous,

This is a dupe of #741. We do have plans to support controlling the low-level timing values for the gossip layer via the configuration file. Let's track this over in the other issue.

Thanks!

**Closed by ryanuber** 2015-04-29 04:46 UTC
