### ISSUE TITLE
Internal watches should use TLS automatically

### ISSUE THREAD

**Issue by slackpad** [hashicorp/consul#3093] opened 2017-05-31 22:37 UTC
Since internal watches are talking to the local agent, the API client should automatically configure itself for TLS if the agent has TLS enabled. Otherwise, you need to set the environment variables from https://www.consul.io/docs/commands/index.html#environment-variables on Consul itself to get it to make the client correctly, which is confusing and not intuitive.

**Comment by jwasinger** [comment] 2017-06-26 01:51
@slackpad I'd like to take a crack at this issue.  I'm wondering if you could clarify for me what exactly an "internal watch" is?  I've looked through Consul's documentation but was unable to find an explanation.

Thanks,
Jared

**Comment by jwasinger** [comment] 2017-06-26 21:01
Hi @slackpad, I'd like to take a crack at this issue.  I've been trying to reproduce the problem but I am not quite sure how.  I'm wondering if you could clarify the meaning of an "internal watch" for me?

**Comment by slackpad** [comment] 2017-06-27 18:14
Hi @jwasinger thanks for taking a look at this one. Unfortunately we are in the middle of a refactor that will clean this up, so it's probably not a good one to tackle right now!

Internal watches are ones that are configured on the agent directly via config files (https://www.consul.io/docs/agent/watches.html), so run from inside the agent itself, vs. `consul watch` (https://www.consul.io/docs/commands/watch.html), which run as totally separate processes. For internal watches, the agent configures how the watch handler talks back to its API automatically, and that's where the issue is.

**Comment by jwasinger** [comment] 2017-06-28 21:06
Ah I see.  Thanks for the heads up.  I'll keep on the lookout for issues to tackle!

**Comment by shayangz** [comment] 2018-01-19 18:24
any chance this can get on the roadmap?

**Comment by i0rek** [comment] 2018-10-22 20:36
If HTTPS is enabled and HTTP disabled, the agent will use HTTPS for watches. I will close the issue since it seems to me that it is resolved. I would be happy to reopen if I missed something.

**Closed by i0rek** 2018-10-22 20:36 UTC
Labels: enhancement, theme/operator-usability
