### ISSUE TITLE
panic when Starting Consul agent

### ISSUE THREAD

**Issue by hehailong5** [hashicorp/consul#2933] opened 2017-04-20 09:26 UTC
version: 0.7.1
```
==＞ Starting Consul agent...
panic: log not found
goroutine 1 [running]:
panic(0xd01e60, 0xc42014a0d0)
 /goroot/src/runtime/panic.go:500 +0x1a1
github.com/hashicorp/consul/vendor/github.com/hashicorp/raft.NewRaft(0xc420196750, 0x1340440, 0xc420210180, 0x1346340, 0xc420210280, 0x1342740, 0xc4202121a0, 0x1340900, 0xc4202122e0, 0x1347300, ...)
 /gopath/src/github.com/hashicorp/consul/vendor/github.com/hashicorp/raft/api.go:491 +0xa5c
github.com/hashicorp/consul/consul.(*Server).setupRaft(0xc4201c01e0, 0x0, 0x0)
 /gopath/src/github.com/hashicorp/consul/consul/server.go:488 +0x830
github.com/hashicorp/consul/consul.NewServer(0xc420180380, 0xc420180380, 0x0, 0x0)
 /gopath/src/github.com/hashicorp/consul/consul/server.go:263 +0xa18
github.com/hashicorp/consul/command/agent.(*Agent).setupServer(0xc42016c300, 0x1, 0xc42014d020)
 /gopath/src/github.com/hashicorp/consul/command/agent/agent.go:406 +0xf7
github.com/hashicorp/consul/command/agent.Create(0xc4201cb800, 0x1339e80, 0xc4201c6440, 0x0, 0x0, 0x0)
 /gopath/src/github.com/hashicorp/consul/command/agent/agent.go:196 +0xac7
github.com/hashicorp/consul/command/agent.(*Command).setupAgent(0xc420147110, 0xc4201cb800, 0x1339e80, 0xc4201c6440, 0xc4201c4420, 0x0, 0x1339e80)
 /gopath/src/github.com/hashicorp/consul/command/agent/command.go:469 +0xaf
github.com/hashicorp/consul/command/agent.(*Command).Run(0xc420147110, 0xc42000a100, 0xc, 0xc, 0x0)
 /gopath/src/github.com/hashicorp/consul/command/agent/command.go:842 +0x99d
github.com/hashicorp/consul/vendor/github.com/mitchellh/cli.(*CLI).Run(0xc42015c540, 0xc42015c540, 0xc420141a00, 0x9)
 /gopath/src/github.com/hashicorp/consul/vendor/github.com/mitchellh/cli/cli.go:153 +0x24e
main.realMain(0xc4200001a0)
 /gopath/src/github.com/hashicorp/consul/main.go:46 +0x1f1
main.main()
 /gopath/src/github.com/hashicorp/consul/main.go:18 +0x22
```

**Comment by slackpad** [comment] 2017-04-20 16:58
Panic is coming from here:

https://github.com/hashicorp/consul/blob/v0.7.1/vendor/github.com/hashicorp/raft/api.go#L485-L494.

@hehailong5 do you have any more info on what was happening before you started the agent? It looks like something happened to the database file used for the Raft log, with the error coming from down here:

https://github.com/hashicorp/consul/blob/v0.7.1/vendor/github.com/hashicorp/raft-boltdb/bolt_store.go#L115-L130

**Comment by hehailong5** [comment] 2017-04-21 01:25
Hi,

this can be reproduced as followings:

1) fresh start the consul
2) kill -9 
3) bring up again the consul

 I guess the "kill -9" may be blamed for this issue, but how to recover from this situation with old data?

**Comment by magiconair** [comment] 2017-05-30 11:04
@hehailong5 I cannot reproduce this. Tested this with 0.7.1 on a 3 node cluster on `linux/amd64` as follows:

```
# setup 3 node linux cluster with
# https://github.com/magiconair/vagrant/tree/master/consul-3node-cluster

./consul-0.7.1 agent -server -data-dir data -bind 192.168.33.11 -bootstrap-expect 3
./consul-0.7.1 agent -server -data-dir data -bind 192.168.33.12 -join 192.168.33.11
./consul-0.7.1 agent -server -data-dir data -bind 192.168.33.13 -join 192.168.33.11
# wait until leader is elected
pkill -9 -f consul # on any node
# restart consul with the same command
```

**Comment by magiconair** [comment] 2017-05-30 11:06
@hehailong5 Some more questions which could help us to track this down:

* Could you specify the exact commands you are executing to reproduce this behavior?
* Is this reproducible every time?
* Which platform are you running on?

**Comment by chiefy** [comment] 2017-06-27 14:16
just ran into this running `0.8.0`:

```
==> Starting Consul agent...
panic: log not found

goroutine 1 [running]:
github.com/hashicorp/consul/vendor/github.com/hashicorp/raft.NewRaft(0xc420178870, 0x1870800, 0xc4202db090, 0x1876ac0, 0xc4202fa780, 0x1872c40, 0xc4202f6be0, 0x1870d40, 0xc4202f6d60, 0x1877e40, ...)
	/gopath/src/github.com/hashicorp/consul/vendor/github.com/hashicorp/raft/api.go:491 +0xb0b
github.com/hashicorp/consul/consul.(*Server).setupRaft(0xc420255180, 0x0, 0x0)
	/gopath/src/github.com/hashicorp/consul/consul/server.go:558 +0x554
github.com/hashicorp/consul/consul.NewServer(0xc420282d80, 0xc420282d80, 0x0, 0x0)
	/gopath/src/github.com/hashicorp/consul/consul/server.go:300 +0xc18
github.com/hashicorp/consul/command/agent.(*Agent).setupServer(0xc420167d40, 0x1, 0xc420226960)
	/gopath/src/github.com/hashicorp/consul/command/agent/agent.go:591 +0xe1
github.com/hashicorp/consul/command/agent.Create(0xc42021c400, 0x1868900, 0xc420217f00, 0xc4201e1da0, 0xc420226240, 0x10c0a00, 0xc420141828, 0x40f712)
	/gopath/src/github.com/hashicorp/consul/command/agent/agent.go:236 +0xc60
github.com/hashicorp/consul/command/agent.(*Command).setupAgent(0xc4201d6b00, 0xc42021c400, 0x1868900, 0xc420217f00, 0xc4201e1da0, 0x0, 0x1)
	/gopath/src/github.com/hashicorp/consul/command/agent/command.go:686 +0xac
github.com/hashicorp/consul/command/agent.(*Command).Run(0xc4201d6b00, 0xc42000e120, 0x6, 0x6, 0x0)
	/gopath/src/github.com/hashicorp/consul/command/agent/command.go:1032 +0xaf4
github.com/hashicorp/consul/vendor/github.com/mitchellh/cli.(*CLI).Run(0xc4200d8900, 0xc4200d8900, 0x40, 0xc4201f0560)
	/gopath/src/github.com/hashicorp/consul/vendor/github.com/mitchellh/cli/cli.go:153 +0x1a8
main.realMain(0xc4200001a0)
	/gopath/src/github.com/hashicorp/consul/main.go:54 +0x40d
main.main()
	/gopath/src/github.com/hashicorp/consul/main.go:18 +0x22
```

**Comment by magiconair** [comment] 2017-10-20 09:27
I've reworked the way we're setting up logs after 0.8.3 so this should no longer happen. I'm going to close the issue. If you see this happening, please comment and we'll reopen.

**Comment by hehailong5** [comment] 2017-11-28 10:20
still see this when running 0.8.4

==> WARNING: Bootstrap mode enabled! Do not enable unless necessary
==> Starting Consul agent...
panic: log not found

goroutine 1 [running]:
github.com/hashicorp/consul/vendor/github.com/hashicorp/raft.NewRaft(0xc4201ce990, 0x18eac80, 0xc4203485f0, 0x18f1040, 0xc420355fc0, 0x18ed1c0, 0xc4203589a0, 0x18eb380, 0xc420358ae0, 0x18f2360, ...)
	/gopath/src/github.com/hashicorp/consul/vendor/github.com/hashicorp/raft/api.go:491 +0xb0b
github.com/hashicorp/consul/consul.(*Server).setupRaft(0xc42025aa00, 0x0, 0x0)
	/gopath/src/github.com/hashicorp/consul/consul/server.go:595 +0x5e9
github.com/hashicorp/consul/consul.NewServerLogger(0xc42025a780, 0xc420235810, 0x0, 0x0, 0x0)
	/gopath/src/github.com/hashicorp/consul/consul/server.go:320 +0xc1f
github.com/hashicorp/consul/command/agent.(*Agent).makeServer(0xc42022e6c0, 0x1, 0xc42028c900, 0x0)
	/gopath/src/github.com/hashicorp/consul/command/agent/agent.go:860 +0x112
github.com/hashicorp/consul/command/agent.(*Agent).Start(0xc42022e6c0, 0xc42022e6c0, 0x0)
	/gopath/src/github.com/hashicorp/consul/command/agent/agent.go:238 +0x4f6
github.com/hashicorp/consul/command/agent.(*Command).run(0xc42018e0f0, 0xc42007e020, 0xd, 0xd, 0x0)
	/gopath/src/github.com/hashicorp/consul/command/agent/command.go:720 +0x4db
github.com/hashicorp/consul/command/agent.(*Command).Run(0xc42018e0f0, 0xc42007e020, 0xd, 0xd, 0xc4201ebde0)
	/gopath/src/github.com/hashicorp/consul/command/agent/command.go:669 +0x56
github.com/hashicorp/consul/vendor/github.com/mitchellh/cli.(*CLI).Run(0xc42011ea80, 0xc42011ea80, 0x40, 0xc42022d5a0)
	/gopath/src/github.com/hashicorp/consul/vendor/github.com/mitchellh/cli/cli.go:160 +0x1cc
main.realMain(0xc420000340)
	/gopath/src/github.com/hashicorp/consul/main.go:54 +0x40d
main.main()
	/gopath/src/github.com/hashicorp/consul/main.go:18 +0x22

**Comment by hehailong5** [comment] 2017-11-28 10:24
1. command issued:
consul agent -server -bootstrap -data-dir /home/release-test/1.17.30.03.p02/consul/../consul-works/data-dir -config-dir /home/release-test/1.17.30.03.p02/consul/../consul-works/config-dir -config-dir /home/release-test/1.17.30.03.p02/consul/../consul-works/custom-config-dir -node=server -domain=msb -disable-host-node-id -bind=127.0.0.1 -client=0.0.0.0

2. No, this rarely happens
3. Linux x64

**Comment by igal-stratoscale** [comment] 2017-11-28 18:20
same issue on 0.8.4

**Comment by rom-stratoscale** [comment] 2017-11-28 20:25
Command used: ['consul', 'agent', '-bind=1.120.4.70', '-data-dir=/mnt/data/consul', '-clien
t=0.0.0.0', '-config-file=/etc/consul_config.json', '-config-dir=/etc/consul.d', '-server', u'-retry-join=1.120.3.142', u'-retry-join=1.120.0.5', '-re
try-interval=5s']

**Comment by rom-stratoscale** [comment] 2017-11-29 09:22
So, if my understanding is correct, what happend is that the node (with consul server) which crashed, had most recent index that was not yet propagated to other servers. 
Once restarted, it cannot find the index remotely and hence keep on crashing. Restarting other servers, leading to the same issue - they cannot find that index and fail to start.
What we did was manually restoring the cluster from older snapshot, but we lost some data due to this.

@slackpad  any suggestion how can we overcome this failure without going back in time?

Thanks,
Rom

**Comment by wubo0067** [comment] 2017-12-19 07:26
Consul 1.0.1-rc1

[root@VM_138_179_centos conf.d]# consul agent -node agent-0 -bind 10.135.138.179 -server -client 10.135.138.179 -syslog -ui -data-dir /tmp/consul -config-dir=/root/consul/conf.d
==> Starting Consul agent...
panic: log not found

goroutine 1 [running]:
github.com/hashicorp/consul/vendor/github.com/hashicorp/raft.NewRaft(0xc420242750, 0x1caa220, 0xc4202f8f50, 0x1cb1320, 0xc4202607c0, 0x1cad260, 0xc420314f60, 0x1cab460, 0xc4203150a0, 0x1cb29e0, ...)
	/root/go/src/github.com/hashicorp/consul/vendor/github.com/hashicorp/raft/api.go:491 +0x14ef
github.com/hashicorp/consul/agent/consul.(*Server).setupRaft(0xc420154c80, 0x0, 0x0)
	/root/go/src/github.com/hashicorp/consul/agent/consul/server.go:620 +0x603
github.com/hashicorp/consul/agent/consul.NewServerLogger(0xc420154280, 0xc4202f8af0, 0xc4200768a0, 0x0, 0xc4202f8af0, 0xc42011ff00)
	/root/go/src/github.com/hashicorp/consul/agent/consul/server.go:364 +0xda9
github.com/hashicorp/consul/agent.(*Agent).Start(0xc42022da00, 0xc42022da00, 0x0)
	/root/go/src/github.com/hashicorp/consul/agent/agent.go:288 +0x2ed
github.com/hashicorp/consul/command/agent.(*cmd).run(0xc420293000, 0xc420010100, 0xc, 0xc, 0x0)
	/root/go/src/github.com/hashicorp/consul/command/agent/agent.go:337 +0x414
github.com/hashicorp/consul/command/agent.(*cmd).Run(0xc420293000, 0xc420010100, 0xc, 0xc, 0xc42006d630)
	/root/go/src/github.com/hashicorp/consul/command/agent/agent.go:77 +0x50
github.com/hashicorp/consul/vendor/github.com/mitchellh/cli.(*CLI).Run(0xc420083560, 0xc420083560, 0x40, 0xc42029b560)
	/root/go/src/github.com/hashicorp/consul/vendor/github.com/mitchellh/cli/cli.go:242 +0x1eb
main.realMain(0xfbcfa7)
	/root/go/src/github.com/hashicorp/consul/main.go:52 +0x3fb
main.main()
	/root/go/src/github.com/hashicorp/consul/main.go:19 +0x22

**Comment by hehailong5** [comment] 2018-03-28 03:29
Hi,

Any progress on this one?
We found the cluster can be recovered by removing the raft.db file, and the services registered via agent interface before come back as well while those registered via catalog interface Not coming back. Is this as expected?

**Comment by nh2** [comment] 2018-05-26 13:03
I just ran into this with Consul 1.0.6, and indeed removing `raft.db` as @hehailong5 said immediately fixed the problem.

**Comment by codybentson** [comment] 2018-10-15 18:37
@hehailong5 solution fixed my issue! 

`sudo find / -name "raft.db"` revealed 3 raft.db's related to consul, deleted all 3 with `rm -f` and consul is back to working!

**Comment by harika224121** [comment] 2019-01-04 19:31
Hi, We are getting Panic: log not found error when we downgrade the consul server version from 1.3.0 to 0.8.4.

![consul-error-downgrade](https://user-images.githubusercontent.com/9380139/50706947-2fde5100-1014-11e9-8d78-62b4370ba878.PNG)

 can anyone help us with an alternative other than deleting the raft.db file since we might lose data regarding our cluster state, services registered, KV pairs etc., and also can we downgrade the version from 1.3.0 to 0.8.4 because I see that once we upgrade to version 1.4.0 we cannot downgrade it.

**Comment by harika224121** [comment] 2019-02-06 13:22
@pearkes can you please suggest any solution for this other then removing the raft.db file since we might lose data

**Comment by GummyDonut** [comment] 2019-04-15 21:04
Small note here removing raft.db fixed the problem with our consul version 1.0.2, However we now noticed that after regenerating the raft.db we can no longer take snapshots.
`2019/04/09 13:24:45 [ERR] snapshot: Failed to get meta data to open snapshot: open /opt/evertz/insite/parasite/applications/py-1/data/consul/raft/snapshots/1-1578046-1554830685069/meta.json: no such file or directory`

Note we restored to a snapshot at one point and then removed raft.db to fix the panic log not found issue mentioned above.

**Comment by Nmishin** [comment] 2019-06-27 09:26
How I get this error:
1. My Consul instance goes out of disk space.
2. After when I clean some log files and free disk space, I tried to start Consul server but get the error:
`Failed to start Raft: failed to load any existing snapshots`
2. I go to the Consul data dir and moved the raft/snapshot folder to the raft/snapshot.bk 
3. Restart Consul server, and get the error:
`Starting Consul agent...
panic: log not found`
4. After that, I mowed all raft folder from raft to the raft.bk and restart Consul server. All works as expected.

If I understand correctly if I have only one Consul node,  I will have no problems after these actions, because the Raft protocol responsible for a cluster managing.

**Comment by jsosulska** [comment] 2020-07-28 14:11
Hi All,

Apologies for raising a dead topic, but I will close this issue. Consul is now on 1.8 major release, and has had many consistency improvements since < 1.0.

If you are still running into this issue on higher than 1.0, please open a new topic, reference this issue, and provide replication steps with log files.

Thank you all.

**Closed by jsosulska** 2020-07-28 14:11 UTC
Labels: theme/internal-cleanup, type/bug, type/crash

**Comment by zhangcan12138** [comment] 2022-01-18 05:52
> Small note here removing raft.db fixed the problem with our consul version 1.0.2, However we now noticed that after regenerating the raft.db we can no longer take snapshots. `2019/04/09 13:24:45 [ERR] snapshot: Failed to get meta data to open snapshot: open /opt/evertz/insite/parasite/applications/py-1/data/consul/raft/snapshots/1-1578046-1554830685069/meta.json: no such file or directory`
> 
> Note we restored to a snapshot at one point and then removed raft.db to fix the panic log not found issue mentioned above.

Excuse me, have you solved the problem that you can't take snapshots? We also encountered deleting raft.db The snapshot cannot be taken after the DB file is. Can you tell me how to solve it in the end。

**Comment by earchibald-lv** [comment] 2022-06-29 17:37
This is absolutely still happening with 1.11.5. Absolutely maddening. Why was this abandoned?

**Comment by YukkiKaze** [comment] 2023-07-26 08:15
still happen with 1.12.4, don't  know if latest version fix this issue,  panic log: 
```
==> Starting Consul agent...
           Version: '1.12.4'
           Node ID: '12286ed9-53d9-6d26-3469-ea78c32df6df'
         Node name: 'node1_server'
        Datacenter: 'dc1' (Segment: '<all>')
            Server: true (Bootstrap: false)
       Client Addr: [10.0.79.101] (HTTP: 8510, HTTPS: -1, gRPC: -1, DNS: -1)
      Cluster Addr: 10.0.79.101 (LAN: 8311, WAN: -1)
           Encrypt: Gossip: true, TLS-Outgoing: false, TLS-Incoming: false, Auto-Encrypt-TLS: false

==> Log data will now stream in as it occurs:

2023-07-26T10:03:18.597+0800 [WARN]  agent: The 'ui' field is deprecated. Use the 'ui_config.enabled' field instead.
2023-07-26T10:03:18.597+0800 [WARN]  agent: Node name "node1_server" will not be discoverable via DNS due to invalid characters. Valid characters include all alpha-numerics and dashes.
2023-07-26T10:03:18.597+0800 [WARN]  agent: bootstrap_expect > 0: expecting 5 servers
2023-07-26T10:03:18.924+0800 [WARN]  agent.auto_config: The 'ui' field is deprecated. Use the 'ui_config.enabled' field instead.
2023-07-26T10:03:18.925+0800 [WARN]  agent.auto_config: Node name "node1_server" will not be discoverable via DNS due to invalid characters. Valid characters include all alpha-numerics and dashes.
2023-07-26T10:03:18.925+0800 [WARN]  agent.auto_config: bootstrap_expect > 0: expecting 5 servers
2023-07-26T10:03:19.741+0800 [INFO]  agent.server.raft: starting restore from snapshot: id=1759-81930-1690336783499 last-index=81930 last-term=1759 size-in-bytes=230471
2023-07-26T10:03:20.006+0800 [INFO]  agent.server.raft: snapshot restore progress: id=1759-81930-1690336783499 last-index=81930 last-term=1759 size-in-bytes=230471 read-bytes=230471 percent-complete=100.00%
2023-07-26T10:03:20.006+0800 [INFO]  agent.server.raft: restored from snapshot: id=1759-81930-1690336783499 last-index=81930 last-term=1759 size-in-bytes=230471
2023-07-26T10:03:20.006+0800 [ERROR] agent.server.raft: failed to get log: index=81931 error="log not found"
panic: log not found

goroutine 1 [running]:
github.com/hashicorp/raft.NewRaft(0xc000e659a0, {0x3516de8?, 0xc000ebe0f0}, {0x35248d8?, 0xc000ee0440}, {0x3521ee8?, 0xc000ec3ad0}, {0x3517028?, 0xc000bc4030}, {0x352bcc8, ...})
        /home/runner/go/pkg/mod/github.com/hashicorp/raft@v1.3.6/api.go:568 +0xf56
github.com/hashicorp/consul/agent/consul.(*Server).setupRaft(0xc001486380)
        /home/runner/work/consul/consul/agent/consul/server.go:907 +0x10ac
github.com/hashicorp/consul/agent/consul.NewServer(0xc001437600, {{0x3533810, 0xc000cedc20}, 0xc0004f67e0, 0xc0001bd810, 0xc00153a000, 0xc00152e0a0, {0x3514f58, 0xc00074e720}, {0x34f6ec0, ...}, ...}, ...)
        /home/runner/work/consul/consul/agent/consul/server.go:533 +0x160e
github.com/hashicorp/consul/agent.(*Agent).Start(0xc0015ed200, {0x3521858, 0xc00154e000})
        /home/runner/work/consul/consul/agent/agent.go:568 +0x57b
github.com/hashicorp/consul/command/agent.(*cmd).run(0xc001674000, {0xc000126060, 0x2, 0x2})
        /home/runner/work/consul/consul/command/agent/agent.go:247 +0xc4b
github.com/hashicorp/consul/command/agent.(*cmd).Run(0xc001674000, {0xc000126060?, 0x8?, 0x0?})
        /home/runner/work/consul/consul/command/agent/agent.go:61 +0x27
github.com/mitchellh/cli.(*CLI).Run(0xc0006d4c80)
        /home/runner/go/pkg/mod/github.com/mitchellh/cli@v1.1.0/cli.go:260 +0x5f8
main.realMain()
        /home/runner/work/consul/consul/main.go:53 +0x40b
main.main()
        /home/runner/work/consul/consul/main.go:23 +0x19
```

**Comment by razvanabagiu89** [comment] 2023-08-01 12:07
Still happening even with latest version, 1.16.0. This cannot be ignored as deploying of Consul right now is very hard and causes a lot of friction and manual intervention.

**Comment by RVSNS** [comment] 2024-02-20 10:52
The issue is observed in 1.16.2. This is observed when consul was stopped and restarted. The other two consul server nodes(out of 3) are fine. To bring it up removed the data and restarted. 
```
==> Starting Consul agent...
               Version: '1.16.2'
            Build Date: '2023-09-19 19:29:18 +0000 UTC'
               Node ID: '925cea0c-7784-cf4d-73d2-bfb0558b231e'
             Node name: 'ConsulPri2'
            Datacenter: '1' (Segment: '<all>')
                Server: true (Bootstrap: false)
           Client Addr: [0.0.0.0] (HTTP: 8500, HTTPS: -1, gRPC: -1, gRPC-TLS: -1, DNS: 8600)
          Cluster Addr: 10.7.5.76 (LAN: 8301, WAN: 8302)
     Gossip Encryption: false
      Auto-Encrypt-TLS: false
           ACL Enabled: true
     Reporting Enabled: false
    ACL Default Policy: allow
             HTTPS TLS: Verify Incoming: true, Verify Outgoing: true, Min Version: TLSv1_2
              gRPC TLS: Verify Incoming: true, Min Version: TLSv1_2
      Internal RPC TLS: Verify Incoming: true, Verify Outgoing: true (Verify Hostname: false), Min Version: TLSv1_2

==> Log data will now stream in as it occurs:

2024-02-20T15:14:12.567+0530 [INFO]  agent.server.raft: starting restore from snapshot: id=1664-49173-1708416365109 last-index=49173 last-term=1664 size-in-bytes=3641569
2024-02-20T15:14:12.744+0530 [INFO]  agent.server.raft: snapshot restore progress: id=1664-49173-1708416365109 last-index=49173 last-term=1664 size-in-bytes=3641569 read-bytes=3641569 percent-complete="100.00%"
2024-02-20T15:14:12.744+0530 [INFO]  agent.server.raft: restored from snapshot: id=1664-49173-1708416365109 last-index=49173 last-term=1664 size-in-bytes=3641569
2024-02-20T15:14:12.744+0530 [ERROR] agent.server.raft: failed to get log: index=49174 error="log not found"
panic: log not found

goroutine 1 [running]:
github.com/hashicorp/raft.NewRaft(0xc001343c20, {0x4dea230?, 0xc000961c68}, {0x4e01528?, 0xc0013b3900}, {0x4dfb0d0?, 0xc0013bdf08}, {0x4dec240?, 0xc0013e83f0}, {0x4e0ae30, ...})
    github.com/hashicorp/raft@v1.5.0/api.go:585 +0x105d
github.com/hashicorp/consul/agent/consul.(*Server).setupRaft(0xc001f81400)
    github.com/hashicorp/consul/agent/consul/server.go:1184 +0x1925
github.com/hashicorp/consul/agent/consul.NewServer(0xc0008e5c00, {0xc0009738b0, {0x4e1f308, 0xc001454d20}, 0xc000cd8000, 0xc000a08340, 0xc000fde680, 0xc000d05860, {0x4dea3e0, 0xc000d129f0}, ...}, ...)
    github.com/hashicorp/consul/agent/consul/server.go:667 +0x1ef5
github.com/hashicorp/consul/agent.(*Agent).Start(0xc001d00c00, {0x4dfa570, 0xc00041c050})
    github.com/hashicorp/consul/agent/agent.go:683 +0x81f
github.com/hashicorp/consul/command/agent.(*cmd).run(0xc00096d000, {0xc0001b4060, 0x2, 0x2})
    github.com/hashicorp/consul/command/agent/agent.go:248 +0x153b
github.com/hashicorp/consul/command/agent.(*cmd).Run(0xc00096d000, {0xc0001b4060?, 0xffffffffffffffff?, 0x0?})
    github.com/hashicorp/consul/command/agent/agent.go:74 +0x27
github.com/mitchellh/cli.(*CLI).Run(0xc0004368c0)
    github.com/mitchellh/cli@v1.1.4/cli.go:262 +0x5f8
main.realMain()
    github.com/hashicorp/consul/main.go:51 +0x40f
main.main()
    github.com/hashicorp/consul/main.go:21 +0x19
```

The conffiguration 
```{
    "disable_update_check": true,
    "data_dir": "/opt/consul",
    "enable_local_script_checks": true,
    "log_level": "INFO",
    "datacenter": "1",
    "bind_addr": "10.7.5.76",
    "client_addr": "0.0.0.0",
    "domain": "xxxxxxxxxxx.com",
    "node_name": "ConsulPri2",
    "server": true,
    "dns_config": {
        "allow_stale": true,
        "node_ttl": "10s",
        "only_passing": true,
        "max_stale": "168h",
        "service_ttl": {
            "*": "10s",
        }
    },
    "recursors": [],
    "ports":{
        "dns":8600,
        "grpc_tls": -1
    },
    "connect": {
        "enabled": false
    },
    "peering": {
        "enabled": false
    },
    "addresses":{
        "dns": "0.0.0.0"
    },
    "limits": {
        "http_max_conns_per_client": 1000
    },
    "skip_leave_on_interrupt": false,
    "leave_on_terminate": true,
    "retry_join": ["10.7.5.76","10.7.5.77","10.7.0.15"],
    "retry_join_wan": ["10.7.1.15","10.7.6.76","10.7.6.77"],
    "rejoin_after_leave": true
}
```

**Comment by GeorgeInLimbo** [comment] 2024-03-22 23:11
@RVSNS This is the exact issue that I'm facing right now. Did you ever get a fix?
