### ISSUE TITLE
Client gets repeatedly disconnected

### ISSUE THREAD

**Issue by polds** [hashicorp/consul#1007] opened 2015-06-05 17:17 UTC
Hi, I am experiencing the exact same symptoms as Issue #352 . The difference is I am not running consul in a docker container, it is running straight on an EC2 instance. Basically I see the following in my logs:

```
memberlist: Suspect consul1 has failed, no acks received
memberlist: Marking consul1 as failed, suspect timeout reached
serf: EventMemberFailed: consul1 10.0.1.140
memberlist: Suspect consul1 has failed, no acks received
consul: removing server consul1 (Addr: 10.0.1.140:8300) (DC: us-west-1)
serf: attempting reconnect to consul1 10.0.1.140:8301
serf: EventMemberJoin: consul1 10.0.1.140
consul: adding server consul1 (Addr: 10.0.1.140:8300) (DC: us-west-1)
memberlist: Suspect consul1 has failed, no acks received
memberlist: Marking consul1 as failed, suspect timeout reached
serf: EventMemberFailed: consul1 10.0.1.140
consul: removing server consul1 (Addr: 10.0.1.140:8300) (DC: us-west-1)
```

Per other issues I have found, some have suggested firewall rules. As such I presently have:

```
ALL TCP        10.0.0.0/16
ALL UDP        10.0.0.0/16
```

Just to make sure that's not the issue. Though even before completely opening it up it would jump back and forth between alive and failed:
#### Check 1

```
Node                  Address          Status  Type    Build  Protocol  DC
consul1          10.0.1.140:8301  alive   server   0.5.2       2      us-west-1
consul2          10.0.2.56:8301    alive   server   0.5.2       2      us-west-1
```
#### Check 2

```
Node                  Address          Status  Type    Build  Protocol  DC
consul1          10.0.1.140:8301  failed   server   0.5.2       2      us-west-1
consul2          10.0.2.56:8301    alive    server   0.5.2       2      us-west-1
```

Any ideas?

**Edit**: Just thought I would add. I have two Consul clusters in two different Amazon Regions. They are both using the exact same AMI yet one cluster works and the other does not.

**Comment by ryanuber** [comment] 2015-06-05 17:54
Hey @polds, We have seen this issue crop up on occasion in various networks. Many times there is simply an intermittent connectivity problem when talking UDP between nodes. Other times, some people have success after stopping/flushing iptables and conntrack.

Just recently the constant failed/joined cycle was addressed in the underlying gossip layer by adding code to fall back to a TCP probe if both direct and indirect UDP pings fail. This should stabilize environments which suffer from this kind of issue so that the nodes do not enter a hard failed state. We hope to have a new Consul release soon which would include this feature, but you could try building the master branch of Consul (make sure all deps are up-to-date) to see if this improves.

**Comment by kopax** [comment] 2016-01-26 01:46
I have the same issue, still not fixed yet?

**Comment by slackpad** [comment] 2016-02-02 02:40
Hi @kopax have you tried Consul 0.6.x? This included the new TCP pings.

**Comment by kopax** [comment] 2016-02-03 17:47
@slackpad I have Consul 0.6.3

**Comment by mrwilby** [comment] 2016-02-06 14:01
How can we tell if the new TCP pings feature is working as intended? Last night we had a node drop out (for just a few seconds). Checking the node logs reveals no sign of issue, but the consul-server logs show:

2016/02/06 03:59:16 [INFO] memberlist: Marking 1.2.3.4 as failed, suspect timeout 
2016/02/06 03:59:16 [INFO] serf: EventMemberFailed: 1.2.3.4 1.2.3.4
...
2016/02/06 03:59:24 [INFO] serf: EventMemberJoin: 1.2.3.4 1.2.3.4
2016/02/06 03:59:24 [INFO] consul: member '1.2.3.4' joined, marking health alive

This network glitch triggered consul-template on another instance, which in turn caused some other knock-on issues.

We are using v0.6.3, running inside AWS ECS (i.e. using docker).

**Comment by slackpad** [comment] 2016-02-13 02:01
@mrwilby you'll see a message like this in the consol when the TCP pings were the only way the node could be contacted:

```
2015/12/08 18:52:39 [WARN] memberlist: Was able to reach w9vnge via TCP but not UDP, network may be misconfigured and not allowing bidirectional UDP
```

Both nodes (ping-er and ping-ee) need to be running Consul 0.6.0 or higher and this feature will enable itself.

**Comment by dominikschulz** [comment] 2016-02-15 10:34
We experience the same issues: Consul 0.6.0 and 0.6.3 running on AWS (not inside docker) with frequent "EventMemberFailed" events. No TCP fallback observed in the logs, so far.

**Comment by rgardam** [comment] 2016-02-18 17:09
I am also seeing this in AWS. Consul 0.6.1

**Comment by helle** [comment] 2016-02-27 14:57
I'm also seeing the same problem several times a day. I'm using Consul 0.6.0 on AWS with VPC, no docker. Security Groups are configured to TCP and UDP communication between all nodes on port 8301.

Mostly short term failures like this one:

```
# Node consul03 (one of the server nodes)

2016/02/27 13:44:00 [INFO] memberlist: Marking analytics-collector-production-d3fdf95e as failed, suspect timeout reached
2016/02/27 13:44:00 [INFO] serf: EventMemberFailed: analytics-collector-production-d3fdf95e 10.1.47.182
2016/02/27 13:44:04 [INFO] serf: EventMemberJoin: analytics-collector-production-d3fdf95e 10.1.47.182

# Node analytics-collector-production-d3fdf95e (a random agent)

2016/02/27 13:43:43 [INFO] serf: EventMemberFailed: consul03 10.1.48.4
2016/02/27 13:43:43 [INFO] consul: removing server consul03 (Addr: 10.1.48.4:8300) (DC: eu-west-1)
2016/02/27 13:43:49 [INFO] serf: EventMemberJoin: consul03 10.1.48.4
2016/02/27 13:43:49 [INFO] consul: adding server consul03 (Addr: 10.1.48.4:8300) (DC: eu-west-1)
2016/02/27 13:44:04 [WARN] memberlist: Refuting a suspect message (from: analytics-collector-production-d3fdf95e)
```

**Comment by 123BLiN** [comment] 2016-03-01 15:24
I have exact same problem - AWS VPC, networkk ACL - all open, securyty group - opened 8300-8302 TCP **AND** UDP. I have mixed centos/ubuntu/windows2012r2 infrustructure - and don't see any OS related pattern.

**Comment by 123BLiN** [comment] 2016-03-03 12:10
Hello all, I have some more info that maybe could help:
I am pinging next host in Amazon VPC with tcp ping (hping3) on TCP 80 (nginx) and 8301 (consul)
results are very strange:

- nginx

```
sudo hping3 -S -p 80 10.11.2.8
HPING 10.11.2.8 (eth0 10.11.2.8): S set, 40 headers + 0 data bytes
len=44 ip=10.11.2.8 ttl=64 DF id=0 sport=80 flags=SA seq=0 win=26883 rtt=1.5 ms
...
len=44 ip=10.11.2.8 ttl=64 DF id=0 sport=80 flags=SA seq=3 win=26883 rtt=1.4 ms
17 packets transmitted, 17 packets received, 0% packet loss
round-trip min/avg/max = 1.4/1.4/1.5 ms
```

- consul
```
sudo hping3 -S -p 8301 10.11.2.8
HPING 10.11.2.8 (eth0 10.11.2.8): S set, 40 headers + 0 data bytes
len=44 ip=10.11.2.8 ttl=64 DF id=0 sport=8301 flags=SA seq=0 win=26883 rtt=1.4 ms
len=83 ip=10.11.2.8 ttl=64 DF id=33578 seq=0 rtt=0.0 ms
len=44 ip=10.11.2.8 ttl=64 DF id=0 sport=8301 flags=SA seq=1 win=26883 rtt=1.5 ms
len=211 ip=10.11.2.8 ttl=64 DF id=33581 seq=0 rtt=0.0 ms
len=44 ip=10.11.2.8 ttl=64 DF id=0 sport=8301 flags=SA seq=2 win=26883 rtt=7.9 ms
...
--- 10.11.2.8 hping statistic ---
24 packets transmitted, 30 packets received, -25% packet loss
round-trip min/avg/max = 1.4/1.9/7.9 ms
```
We were suspecting AWS VPC network problems, but now it seems to me that consul agent (0.6.3) has some glitches in answering to UDP and than TCP pings.
I would be very appreciated if someone could comment on this. We spent a lot of time to configure current consul test environment and now ready to move it to prod, but this is defenetly blocking issue :(

**Comment by adamlc** [comment] 2016-03-10 16:07
We're slowly introducing consul into our cluster and keep randomly getting this on an EC2 VPC. Weirdly one server reports that it can't do bidirectional UDP but the other one can, not quite sure why! 

All the instances actually have the same Consul security group, so theres no reason why some should work and not others. We're always having network related issues either other things too, like RabbitMQ :(

**Comment by 123BLiN** [comment] 2016-03-10 16:28
@adamlc could you check your consul protocol version with 
`consul version`
command?

**Comment by adamlc** [comment] 2016-03-10 16:42
```
Consul v0.6.3
Consul Protocol: 3 (Understands back to: 1)
```

```
Node                          Address          Status  Type    Build  Protocol  DC
queue-consumer-eu-west1-1c-1  10.0.2.47:8301   alive   client  0.6.3  2         dc1
support-eu-west1-1a-2         10.0.1.94:8301   alive   server  0.6.3  2         dc1
support-eu-west1-1b-2         10.0.0.138:8301  alive   server  0.6.3  2         dc1
support-eu-west1-1c-2         10.0.2.190:8301  alive   server  0.6.3  2         dc1
swarm-node-eu-west1-1a-1      10.0.1.117:8301  alive   client  0.6.3  2         dc1
swarm-node-eu-west1-1b-1      10.0.0.177:8301  alive   client  0.6.3  2         dc1
swarm-node-eu-west1-1c-1      10.0.2.136:8301  alive   client  0.6.3  2         dc1
webserver-eu-west1-1a-1       10.0.1.15:8301   alive   client  0.6.3  2         dc1
webserver-eu-west1-1b-1       10.0.0.92:8301   alive   client  0.6.3  2         dc1
```

Not sure why all the members are on protocol 2 :confused: 

As regards the UDP issue, it turned out to be docker/docker#8795

**Comment by 123BLiN** [comment] 2016-03-10 17:10
Hm, same here. consul members command gives Protocol 2.
But I don't have any issues now in logs.

**Comment by slackpad** [comment] 2016-03-10 17:26
@adamlc @123BLiN that's normal for the protocol version (sorry if it's a little confusing). Consul 0.6.x speaks version 2 but understands version 3, so the "speaking" version what's being reflected in the `consul members` output, and `consul version` shows what version it understands.

**Comment by adamlc** [comment] 2016-03-11 10:46
Makes sense now thanks! Well things seemed to have calmed down with the flapping, I think its generally down to EC2's poor network, still it does pose some sort of issue.

**Comment by clintonm9** [comment] 2016-03-30 02:05
I seem to be having the same issue as some of these people, but I don't think I see a solution in this thread. 

```
[root@TESTDevConsul01 HC]# /usr/local/bin/consul members
Node              Address          Status  Type    Build  Protocol  DC
TESTDevCB01        10.0.0.10:8301   failed  client  0.6.4  2         east-us
TESTDevCB02        10.0.0.11:8301   failed  client  0.6.4  2         east-us
TESTDevChat02      10.200.0.5:8301  alive   client  0.6.4  2         east-us
TESTDevChat03      10.200.0.9:8301  alive   client  0.6.4  2         east-us
TESTDevConsul01    10.254.0.6:8301  alive   server  0.6.4  2         east-us
TESTDevEastRiak02  10.200.0.7:8301  alive   client  0.6.4  2         east-us
TESTDevEastRiak03  10.200.0.8:8301  failed  client  0.6.4  2         east-us
TESTDevJump        10.0.0.9:8301    failed  client  0.6.4  2         east-us
TESTdeveast        10.200.0.6:8301  alive   client  0.6.4  2         east-us
[root@TESTDevConsul01 HC]# /usr/local/bin/consul version
Consul v0.6.4
Consul Protocol: 3 (Understands back to: 1)
```

Nodes are just going to alive to failed.

Here is the log:
```

2016/03/29 21:01:10 [INFO] serf: attempting reconnect to TESTDevEastRiak03 10.200.0.8:8301
2016/03/29 21:01:23 [ERR] memberlist: Push/Pull with TESTDevChat03 failed: dial tcp 10.200.0.9:8301: i/o timeout
2016/03/29 21:01:33 [INFO] memberlist: Suspect TESTDevChat02 has failed, no acks received
2016/03/29 21:01:38 [INFO] memberlist: Marking TESTDevChat02 as failed, suspect timeout reached
2016/03/29 21:01:38 [INFO] serf: EventMemberFailed: TESTDevChat02 10.200.0.5
2016/03/29 21:01:49 [INFO] serf: EventMemberJoin: TESTDevCB02 10.0.0.11
2016/03/29 21:01:49 [INFO] serf: EventMemberJoin: TESTDevEastRiak02 10.200.0.7
2016/03/29 21:01:50 [INFO] serf: attempting reconnect to TESTdeveast 10.200.0.6:8301
2016/03/29 21:01:51 [INFO] serf: EventMemberJoin: TESTDevChat02 10.200.0.5
2016/03/29 21:01:51 [INFO] serf: EventMemberJoin: TESTdeveast 10.200.0.6
2016/03/29 21:01:51 [INFO] serf: EventMemberJoin: TESTDevEastRiak03 10.200.0.8
2016/03/29 21:01:52 [INFO] memberlist: Suspect TESTDevEastRiak03 has failed, no acks received
2016/03/29 21:01:54 [WARN] memberlist: Refuting a suspect message (from: TESTDevChat02)
2016/03/29 21:01:56 [INFO] serf: EventMemberFailed: TESTDevChat03 10.200.0.9
2016/03/29 21:01:57 [INFO] serf: EventMemberFailed: TESTDevJump 10.0.0.9
2016/03/29 21:01:58 [INFO] memberlist: Marking TESTDevEastRiak02 as failed, suspect timeout reached
2016/03/29 21:01:58 [INFO] serf: EventMemberFailed: TESTDevEastRiak02 10.200.0.7
2016/03/29 21:02:00 [INFO] memberlist: Marking TESTdeveast as failed, suspect timeout reached
2016/03/29 21:02:00 [INFO] serf: EventMemberFailed: TESTdeveast 10.200.0.6
2016/03/29 21:02:00 [INFO] serf: EventMemberJoin: TESTDevEastRiak02 10.200.0.7
2016/03/29 21:02:10 [INFO] agent: Synced node info
2016/03/29 21:02:10 [INFO] memberlist: Marking TESTDevEastRiak03 as failed, suspect timeout reached
2016/03/29 21:02:10 [INFO] serf: EventMemberFailed: TESTDevEastRiak03 10.200.0.8
```


I am using a Azure using a VNET VPN from different resource groups. Not sure if that makes a difference.

**Comment by asheshambasta** [comment] 2016-06-11 10:42
I was trying to experiment with consul with our EC2 clusters as well and this was a roadblock for us.
I've verified and re-verified that all communication is possible between the instances (all traffic open for the CIDR of all Consul running instances.)

I keep seeing 
```
EventMemberJoin …
memberlist: Suspect … has failed, no acks received
```

Which is disappointing.

**Comment by composer22** [comment] 2016-06-13 20:47
Jun 13 20:30:20 <SNIP> docker[721]:     2016/06/13 20:30:20 [WARN] memberlist: Was able to reach <SNIP> via TCP but not UDP, network may be misconfigured and not allowing bidirectional UDP

**Comment by asheshambasta** [comment] 2016-06-14 07:37
In our case, the problem went away with `-net=host` docker flag.

**Comment by slackpad** [comment] 2017-05-02 22:21
Going to close this out - these almost always are the result of configuration errors at the firewall level, and `-net=host` often helps w/Docker (though I think more recent Docker versions are getting better wrt. UDP issues).

Consul 0.7.0 also introduced [lifeguard enhancements](https://www.consul.io/docs/internals/gossip.html#lifeguard-enhancements) to the gossip protocol which automatically tune probe timing when this happens for non-configuration reasons, like a low-end EC2 instance dropping packets when it has exhausted its CPU credits. Lifeguard also limits the damage a degraded host can do to the rest of the cluster in terms of falsely marking other hosts failed.

**Closed by slackpad** 2017-05-02 22:21 UTC
