### ISSUE TITLE
Consul server nodes consume lots or RAM

### ISSUE THREAD

**Issue by NIR-Ginko** [hashicorp/consul#4809] opened 2018-10-17 08:16 UTC
#### Overview of the Issue

I'm starting 3 Consul server nodes in Docker containers via Ansible for development purposes and the nodes are working just fine during the day. I'm leaving the development machine with containers turned on when I'm going home but on another day I can't access the machine.

I ran `docker stats` and found out that 3 Consul containers consumed about 2Gb of RAM each (a little bit lesser than 6 Gb). The development machine have about 7 Gb of RAM in total and there is no serious load is expected on Consul so I'm disappointed with such memory consumption.

**I may try to reproduce the bug but it will require day or two.**

#### Reproduction Steps

I'm starting 3 Consul servers in Docker containers via Ansible like:
```
consul agent -server -bind={{ consul_address }} -data-dir=/consul/data -config-dir=/consul/config  -rejoin -disable-host-node-id -bootstrap -bootstrap-expect=1 -node={{ consul_name }}
```
and then another node like:
```
consul agent -server -bind={{ consul_address }} -data-dir=/consul/data -config-dir=/consul/config  -rejoin -disable-host-node-id -retry-join={{ lbc_dedicated_network_consul_server_1_address }} -retry-join={{ lbc_dedicated_network_consul_server_3_address }}  -node={{ consul_name }}
```
and then the 3rd node like:
```
consul agent -server -bind={{ consul_address }} -data-dir=/consul/data -config-dir=/consul/config  -rejoin -disable-host-node-id -retry-join={{ lbc_dedicated_network_consul_server_1_address }} -retry-join={{ lbc_dedicated_network_consul_server_2_address }}  -node={{ consul_name }}
```

### Consul info for both Client and Server

<details>
  <summary>Server info</summary>

```
agent:
	check_monitors = 0
	check_ttls = 0
	checks = 0
	services = 0
build:
	prerelease = 
	revision = e8757838
	version = 1.3.0
consul:
	bootstrap = true
	known_datacenters = 1
	leader = false
	leader_addr = 
	server = true
raft:
	applied_index = 0
	commit_index = 0
	fsm_pending = 0
	last_contact = never
	last_log_index = 556
	last_log_term = 573262
	last_snapshot_index = 0
	last_snapshot_term = 0
	latest_configuration = [{Suffrage:Voter ID:9b3d076c-6ef7-735b-01b1-2a29d50670ff Address:10.3.0.4:8300} {Suffrage:Nonvoter ID:75498d5f-8ee0-7496-1297-e1b363b804bc Address:10.3.0.11:8300} {Suffrage:Voter ID:de9de147-92a0-a89f-3022-a1fa6c1fe664 Address:10.3.0.7:8300} {Suffrage:Voter ID:ecb52983-0ed6-5863-8f4b-af5446cae9ea Address:10.3.0.8:8300} {Suffrage:Voter ID:79857e09-4994-1b15-fd1c-2b02e6491a92 Address:10.3.0.6:8300} {Suffrage:Voter ID:78888019-4c19-a9f9-a4d8-5523418b798f Address:10.3.0.3:8300} {Suffrage:Nonvoter ID:a5759f6d-1aa4-67bd-418c-f3f5c3b17cab Address:10.3.0.2:8300} {Suffrage:Voter ID:4d85b750-46e3-9672-c34a-08dd0ac737b4 Address:10.3.0.9:8300}]
	latest_configuration_index = 546
	num_peers = 5
	protocol_version = 3
	protocol_version_max = 3
	protocol_version_min = 0
	snapshot_version_max = 1
	snapshot_version_min = 0
	state = Candidate
	term = 895317
runtime:
	arch = amd64
	cpu_count = 1
	goroutines = 77
	max_procs = 1
	os = linux
	version = go1.11.1
serf_lan:
	coordinate_resets = 0
	encrypted = false
	event_queue = 0
	event_time = 40243
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 41
	members = 1
	query_queue = 0
	query_time = 1
serf_wan:
	coordinate_resets = 0
	encrypted = false
	event_queue = 0
	event_time = 1
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 125
	members = 1
	query_queue = 0
	query_time = 1
```
Consul v1.3.0
Protocol 2 spoken by default, understands 2 to 3 (agent will automatically use protocol >2 when speaking to compatible agents)
</details>

*Please note that the info from `consul info` in this case is displayed for fresh start of master node, not for the situation with memory consumption.*

### Operating system and Environment details

- Linux &lt;hostname&gt; 3.10.0-862.14.4.el7.x86_64 #1 SMP Wed Sep 26 15:12:11 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- CentOS Linux release 7.5.1804 (Core)
- Docker CE from official repos:
```
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:23:03 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:25:29 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Comment by pearkes** [comment] 2018-10-26 16:38
This is unexpected behavior and should definitely not be occurring. Can you confirm it is the Consul process consuming this amount of memory? Additionally, are you utilizing Consul at all (eg. storing entries in K/V)?

**Comment by NIR-Ginko** [comment] 2018-11-18 19:02
The problem occured when no entry created in Consul for a long period of time (until the start of another working day). So I created 3 nodes and just left them "AS IS" and I was not able to log into the machine for a period of 40 minutes because nodes ate all RAM.

I used `docker stats` and `top` commands to show the memory consumed by the processed but I haven't done any further research because it was really uncomfortable to wait for each command to respond so I just killed the nodes to get back some resources.

**Comment by pearkes** [comment] 2018-11-28 17:01
We don't have any known memory leaks that would exhibit that behavior, my best guess is that something unexpected (either another process or something interacting with Consul) within that Docker container that causes this. I'm going to close this because I don't think we have enough to go on in order to determine the root cause but would welcome more info in a new report.

Thanks for opening an issue!

**Closed by pearkes** 2018-11-28 17:01 UTC
Labels: waiting-reply
