### ISSUE TITLE
How can I specify token ID while creating token in new consul 1.4.2

### ISSUE THREAD

**Issue by sushovan23** [hashicorp/consul#5359] opened 2019-02-19 15:18 UTC
In older version of consul (1.2.3) 
I could specify the token ID in the payload while creating a client token.

Following used to be the body:
'{ "Name": "App-token","ID": "{{ consul_client_token }}","Rules": "key \"\" { policy = \"write\" } agent \"\" { policy = \"write\" } node \"\" { policy = \"write\" } service \"\" { policy = \"write\" }  operator = \"write\"" }

If you see I could specify the ID myself. This would help us in rebuilding the server with same tokens which were shared or integrated earlier into different application.

In the new APIs I see that we need to create a policy & then specify policy name or ID.
But there is not way to specify the ID in new payload.
```
{
   "Description": "Agent client token 2",
   "SecretID": "{{ secret }}",
   "Policies": [
      {
         "Name": "app-token-policy"
      }
   ],
   "Local": false
}
```

Could let me know if it is possible and how to do it?

**Comment by mkeeler** [comment] 2019-02-19 15:20
@sushovan23 Going to close this as a duplicate of #4977. Currently you can't set the ids of ACL related data but there are plans to enable this. I have a PR open to add this functionality but there are a couple of other bits that need to be worked out prior to merging it in order to make it work correctly.

**Closed by mkeeler** 2019-02-19 15:20 UTC
