### ISSUE TITLE
[Mesh] updating service-tags on the pods isn't reflected until a modification is done on the parent service

### ISSUE THREAD

**Issue by remiphilippe** [hashicorp/consul#12510] opened 2022-03-03 17:07 UTC
#### Overview of the Issue

We have specific tags we assign on the pods directly using `consul.hashicorp.com/service-tags` (we couldn't get tags override to work with mesh). We don't set any service-tags on the service.

service-tags are seen on the pod in kubernetes, but they don't reflect in consul until we do some modification to the service (any update works).

#### Reproduction Steps

Steps to reproduce this issue, eg:

1. Deploy Consul with Mesh
2. Deploy a service and a deployment with 1 or more pods
3. Assign a tag to the pod using the consul annotation  `consul.hashicorp.com/service-tags`
4. Check consul, the tag should not be there
5. Change any parameter on the service
6. Check consul, the tag should be there  

### Consul info for both Client and Server

<details>
  <summary>Server info</summary>

```
agent:
        check_monitors = 0
        check_ttls = 1
        checks = 1
        services = 1
build:
        prerelease = 
        revision = 37c7d06b
        version = 1.11.2
consul:
        acl = enabled
        bootstrap = true
        known_datacenters = 1
        leader = true
        leader_addr = 10.1.13.97:8300
        server = true
raft:
        applied_index = 13728
        commit_index = 13728
        fsm_pending = 0
        last_contact = 0
        last_log_index = 13728
        last_log_term = 2
        last_snapshot_index = 0
        last_snapshot_term = 0
        latest_configuration = [{Suffrage:Voter ID:305d575f-f13a-9c17-f337-52f49eb07d94 Address:10.1.13.97:8300}]
        latest_configuration_index = 0
        num_peers = 0
        protocol_version = 3
        protocol_version_max = 3
        protocol_version_min = 0
        snapshot_version_max = 1
        snapshot_version_min = 0
        state = Leader
        term = 2
runtime:
        arch = arm64
        cpu_count = 6
        goroutines = 310
        max_procs = 6
        os = linux
        version = go1.17.5
serf_lan:
        coordinate_resets = 0
        encrypted = false
        event_queue = 0
        event_time = 2
        failed = 0
        health_score = 0
        intent_queue = 0
        left = 0
        member_time = 3
        members = 2
        query_queue = 0
        query_time = 1
serf_wan:
        coordinate_resets = 0
        encrypted = false
        event_queue = 0
        event_time = 1
        failed = 0
        health_score = 0
        intent_queue = 0
        left = 0
        member_time = 1
        members = 1
        query_queue = 0
        query_time = 1
```

</details>

### Operating system and Environment details

Kubernetes on MacOS ARM64
```
Consul v1.11.2
Revision 37c7d06b
Protocol 2 spoken by default, understands 2 to 3 (agent will automatically use protocol >2 when speaking to compatible agents)
```

**Comment by Amier3** [comment] 2022-03-10 16:22
Hey @remiphilippe 

Looked into this a bit and it looks like this is intended behavior. Our consul-k8s integration monitors the endpoints of the pods to sync changes to the consul cluster, not the pod itself. Annotations don't update the config automatically, so you'll either have to redeploy the pod after changing annotations or reload the yaml config in the consul cluster ( which seems like what you did in the reproduction steps ). 

I'm going to close this issue for now but let me know if you have any questions. You're also welcome to make an enhancement request in the  [consul-k8s repo](https://github.com/hashicorp/consul-k8s/issues) for some sort of continuous checking of service configs.

**Closed by Amier3** 2022-03-10 16:22 UTC
Labels: type/bug, theme/kubernetes
