### ISSUE TITLE
KV delete excessively slow

### ISSUE THREAD

**Issue by wwalker** [hashicorp/consul#1278] opened 2015-10-07 21:42 UTC
Vault created 2.8M KV entries.  This made consul perform very very poorly.

So, we decided to reinstall vault.  Shut down vault, then :

curl -X DELETE 'http://localhost:8500/v1/kv/vault?recurse'

Probably take an hour...  4hours later... surely by morning... next day surely by tonight ...

Next morning, 40 hours after starting the DELETE, it had neither finished nor errored.

We killed and reinstall consul from scratch.

I understand that vault had created a crazy number of KV entries, but 40 hours was not enough?

That is only 20 deletes per second (and it did not finish, so even slower), in a single batch, and as I read the code, Commit() is never called till the end.  The machine was using 1 core constantly for the entire 40 hours (as were the other two servers in the cluster) and did not finish.

During this 40 hours, no snapshots and no elections occurred.  But some requests were handled, many were not.

**Comment by armon** [comment] 2015-10-08 18:37
@wwalker Yeah this is a terrible case for Consul in general. All the transactions against Consul are applied atomically, so a large scale delete is just devastating. This effectively fans out to about ~6 million key updates that must be done in an atomic update. 

Hopefully some of the architectural changes in 0.6 will ease this pain, but ultimately any transaction involving millions of entries will be very sad for Consul, and likely the cause of instability.

**Comment by wwalker** [comment] 2015-10-08 20:27
@armon could we add chunk=true to delete endpoint so that recursive deletes will be done in smaller chunks, sacrificing the atomicity of the overall delete for performance?  For me I saw a 7.8 X performance improvement doing 10 separate 10,000 key deletes serially (8.5 seconds each, total time 84.6 seconds) versus doing a 100,000 key delete (660 seconds).   Then I ran 10 deletes of 10,000 keys each in parallel, and the last of them finished within 17 seconds.

So if the system did chunks in separate go routines, at the sacrifice of overall DELETE atomicity, could provide 40X improvement.  I could look into writing this,but only if it has a chance of being accepted :-)

**Comment by wwalker** [comment] 2015-10-08 21:21
Interestingly, doing 100 deletes of 1,000 each, in parallel, is quite slow.  (30 minutes total, 5 miutes for most).

**Comment by armon** [comment] 2015-10-13 00:37
@wwalker Not sure why the smaller deletes took longer, that is odd... I think we could certainly support something like `chunk` which would break the promise of atomicity, but I think it's hard to understand the implications of that in the case of things like blocking queries and consul template. E.g. if those systems see a partial delete, they will be in a bad state, due to how the indexing is done.

e.g. Records [A B C] exist. Delete is issues at time T. Consul template does a read of keys [A B] at time T (partial delete). It now does a blocking query to wait for T+1, which may happen at some arbitrary point in the future, even though the state of the world it has is wrong.

That may be a bit terse (apologies), but I hope it makes sense!

**Comment by wwalker** [comment] 2015-10-17 14:34
Agreed.  If ```chunk``` comes with documentation that says "only use for deleting unused massive deletes where nothing that cares will be reading those keys during the delete.  If the existence of the keys being deleted is depended upon by other things, do not use ```chunk``` so that you may keep the deterministic behavior of atomic delete".  Something better wordsmithed though.

**Comment by mitchellh** [comment] 2015-11-16 19:45
In the context of Vault, another idea I had is: rather than break the atomocity guarantee of `recurse`, would be instead provide a way for Vault to just page over the values within there. If Vault could request 100,000 keys at a time (keys only, not values necessarilly), and delete those 100,000 keys atomically (or any N number of keys), it might be able to help speed this up significantly.

The issue Vault appears to be running into is that in this case of millions of keys, the recurse operation is timing out somewhere and causing the cleanup to fail which just perpetuates the issue. 

However, if Vault can batch the work on its own, we don't need to get rid of or complicate Consul's atomocity guarantees. We can just do the more complex logic in Vault. It would increase bandwidth significantly for a short period of time (shipping down/up N keys) but it should be a sufficiently rare operation.

**Comment by slackpad** [comment] 2015-11-17 02:33
One other idea I wanted to capture: for the case of recursive deletes I'm pretty sure (need to think it through) we could put in a single tombstone instead of one for each key. Batching might take away the advantage of doing this, but it's something to consider.

**Comment by armon** [comment] 2015-11-17 19:55
I'm curious to benchmark this with MemDB, as even millions of keys being updated in memory may only take a second or two instead of minutes today.

**Comment by slackpad** [comment] 2015-11-18 02:22
I tried it with the 0.6.0-rc1 build on a cluster of 3 m3.large instances and was able to delete 2M keys in about 34 seconds. Unfortunately, the memory pressure is super high and I got a kernel OOM as well as a Go runtime panic due to memory, so we've got work to do. Documented the panic over in https://github.com/hashicorp/consul/issues/1421. That one was related to creating the tombstones.

**Comment by msabramo** [comment] 2015-11-19 04:48
I like @mitchellh's idea of providing some kind of paging in the APIs. That would allow tools to delete in chunks and it would be obvious that atomicity is not guaranteed across the entire set.  The paging could possibly be useful for other uses too if it applies to GET and not just DELETE. I'm imagining some kind of key browser like the Consul UI for instance. In fact, the Consul KV UI started timing out like crazy when I had millions of keys, so it could probably benefit from being able to do queries win paging. 

I would think that it would be very, very good if Consul could refuse to delete more than a certain number of keys, say 1000 or something. That way if you have millions to delete, you would be forced to use paging and wouldn't be able to hang yourself like @wwalker and I did by attempting to mass delete millions in one query.

**Comment by msabramo** [comment] 2015-11-19 05:13
So assuming I missed @wwalker's warning and did `curl -X DELETE 'http://localhost:8500/v1/kv/vault?recurse'` and my Consul is now stuck like his was, is there anything I can do to undo that; make Consul forget about that or abort it and release any associated locks?

**Comment by slackpad** [comment] 2015-11-19 07:10
Hi @msabramo unfortunately this is on the wrong side of the Raft log so the quorum has accepted the huge KV delete operation and it's now trying to commit to the state store which is taking a huge amount of time, and locking up all the rest of the writes because it's occurring in a transaction with the database. There's currently no mechanism to cancel something like this, though I opened https://github.com/hashicorp/consul/issues/1418 which might be a possible automated way of of this situation in the future. We also plan to enable huge deletes via paging or some other mechanism after we get 0.6.0 out.

Reads should still be working so you should be able to get your data out using the APIs and then rebuild your cluster. I know this option is super painful but it's probably the cleanest way to get moving again.

If you've safely backed up your data and you are considering rebuilding the cluster, you could give the 0.6.0-rc2 build a try (see https://groups.google.com/forum/#!topic/consul-tool/VqPBuSIjFTI for details). It should be an easy upgrade from 0.5.2 where you basically update to the new binary and then restart the Consul server. I was able to chug through 2M keys on an m3.large in about 34 seconds, though on about 2 out of 5 runs I ran into out-of-memoy panics and one kernel OOM kill of Consul, as written up in #1421. If your server is a beefy machine with lots of RAM this might be worth a shot. The 0.6.0-rc2 build is much faster because Consul 0.6 has a completely new in-memory state store that's much more efficient.

If you wanted to give a 0.6 build a little better chance of succeeding you could even try patching this:

```diff
diff --git a/consul/state/state_store.go b/consul/state/state_store.go
index 76a8b5f..ac981b4 100644
--- a/consul/state/state_store.go
+++ b/consul/state/state_store.go
@@ -1732,10 +1732,6 @@ func (s *StateStore) KVSDeleteTree(idx uint64, prefix string) error {
        var modified bool
        var objs []interface{}
        for entry := entries.Next(); entry != nil; entry = entries.Next() {
-               e := entry.(*structs.DirEntry)
-               if err := s.kvsGraveyard.InsertTxn(tx, e.Key, idx); err != nil {
-                       return fmt.Errorf("failed adding to graveyard: %s", err)
-               }
                objs = append(objs, entry)
                modified = true
        }
```

You'd have to make a build to get that change, but it will prevent Consul from making tombstones during the delete which makes the delete a lot less costly memory-wise. This will keep blocking queries from working properly for these keys, but you don't care in this case since you just want to delete them. The tricky thing about doing this is that you'd have to wait for Consul to kick out a snapshot before you restart it with an un-patched version so that you don't run into the same problem when the server starts up and replays the Raft log. Once it snapshots and gets that huge delete out of the Raft log it should be fine.

Definitely apologize that this has caused you all this trouble, and we've captured several ideas for fixing this in the release following 0.6.0.

**Comment by msabramo** [comment] 2015-11-19 15:04
Alright, well I went ahead and reinitialized things and stuff looks healthy so far. Thanks for the info about 0.6.0 and the patch, though now that I've reinitialized, it's probably not worth my time to try that. Thank you for all the time invested in helping folks with these issues. The issues are unfortunate for sure, but Hashicorp support has been very responsive!

**Comment by wwalker** [comment] 2016-01-04 16:00
@slackpad is the patch above part of 0.6.0?

I just got hit with this again (1.6 M vault/core/leader/* entries....)

**Comment by slackpad** [comment] 2016-01-04 16:37
@wwalker unfortunately that patch isn't in there since it breaks the tombstone behavior for those keys, so it's not a good general solution.

**Comment by wwalker** [comment] 2016-01-05 19:37
So, i tried to delete these manually.  Now, even though I stopped attempts to delete hours ago, my cluster is braid dead.  every request that comes in ends with "timed out enqueuing request".

**Comment by slackpad** [comment] 2016-01-05 21:14
@wwalker I don't think there's a very good recovery option if that huge delete is queued up in the Raft log, you may have to reinitialize Consul. Sorry about running into this again.

**Comment by armon** [comment] 2016-01-05 22:45
@wwalker I think the cluster should return to being healthy once it finishes chewing through the operation, but let us know if not. With 0.6.0 the operation should take on the order of minutes now instead of hours.

**Comment by slackpad** [comment] 2016-01-08 05:51
Wanted to update this - we made some performance improvements via https://github.com/hashicorp/go-immutable-radix/pull/4 that went out today with Consul 0.6.1 that help make deletes more efficient. I was able to make a couple runs deleting 2M keys without OOM-ing - both finished in about 1.5 minutes. This isn't the final fix, but things should be a little better with the new release.

**Comment by kongchen** [comment] 2016-12-21 03:37
@saifabid I use 0.6.4 and try to delete a folder on KV which contains much more than 10M entries, using the HTTP API `curl -X DELETE http://localhost:8500/v1/kv/locks\?recurse\&token=xxxx`

As my understanding, this is a block operation and must be done on leader, and once I send my delete request, my consul cluster leader looks unresponsive and other peers in cluster start to election, and my entire cluster became unstable, which becomes`No cluster leader`. Very frustrating.

The delete operation is not returned and the big entry still there also makes my cluster unavailable.
Is there any other efficient way to delete such big entry?

**Closed** 2017-07-26 14:52 UTC
Labels: crash, theme/internal-cleanup
