### ISSUE TITLE
Snapshot replication failing

### ISSUE THREAD

**Issue by kaithar** [hashicorp/consul#5608] opened 2019-04-05 08:04 UTC
#### Overview of the Issue

I keep running in to an issue where a node trying to join the cluster can't get a snapshot.  I haven't been able to find any applicable information on what is happening.
Right now I've just reinitialized the cluster so I only have the logs, but I'm sure it'll happen again pretty soon.

### Log Fragments
One side of the mess:
```
2019/04/05 06:59:06 [ERR] raft: Failed to install snapshot X-XXXXX-XXXXXXXX: read tcp xx.xx.0.3:x->xx.xx.0.4:xx: i/o timeout
2019/04/05 06:59:06 [ERR] raft: Failed to send snapshot to {Nonvoter xxx xx.xx.0.4:xx}: read tcp xx.xx.0.3:xx->xx.xx..0.4:xx: i/o timeout
2019/04/05 06:59:06 [ERR] raft: Failed to get log at index 64: log not found
2019/04/05 06:59:08 [WARN] consul: error getting server health from "node-4": context deadline exceeded
2019/04/05 06:59:09 [WARN] consul: error getting server health from "node-4": last request still outstanding
2019/04/05 06:59:11 [WARN] consul: error getting server health from "node-4": last request still outstanding
2019/04/05 06:59:13 [WARN] consul: error getting server health from "node-4": last request still outstanding
2019/04/05 06:59:15 [WARN] consul: error getting server health from "node-4": last request still outstanding
2019/04/05 06:59:16 [ERR] raft: Failed to install snapshot (same snapshot as before): read tcp xx.xx.0.3:xx->xx.xx.0.4:xx: i/o timeout
2019/04/05 06:59:16 [ERR] raft: Failed to send snapshot to {Nonvoter xxx xx.xx.0.4:xx}: read tcp xx.xx.0.3:xx->xx.xx.0.4:xx: i/o timeout
```

And an (older failure) example from the other side...
```
    2019/04/05 06:58:47 [ERR] raft: Failed to receive whole snapshot: 0 / 171363
```

None of these boxes are under load such that it should be timing out... I can't figure out where to even start tweaking since I can't find any settings relating to related timeouts.

**Comment by pearkes** [comment] 2019-04-05 16:50
Looks like a duplicate of the issue described here in #4135. Probably CPU starvation on the nodes reporting issues.

**Closed by pearkes** 2019-04-05 16:50 UTC

**Comment by kaithar** [comment] 2019-04-06 02:46
@pearkes um, unless we have very different definitions of cpu starvation, that would be a no.
I already considered and eliminated resource starvation as a problem.  This includes CPU use and IO throughput.

As context, node-4 is probably the heaviest load as it "only" has ~75% cpu free... it's running an Intel E3-1220.

**Comment by pearkes** [comment] 2019-04-08 17:20
@kaithar sorry for the fast close, we see a lot of issues with those symptoms that are a result of an underlying resource starvation issue. I would experiment with testing network reachability during that same window of time when you're seeing errors. Consul isn't doing much more than raising errors that it can't communicate on the network to the other Consul server. This could be because the Consul server process on the receiving end is starved of CPU (most common) or the network is not able to transmit properly (less common).

**Comment by pearkes** [comment] 2019-04-08 17:22
If this is reproducible in a variety of environments with plenty of resources it'd be great to detail that – unfortunately as-is it is pretty hard to pin down the specific problem.
