### ISSUE TITLE
Manual names for service-bound check names

### ISSUE THREAD

**Issue by akmalabbasov** [hashicorp/consul#1480] opened 2015-12-08 22:17 UTC
Hi, is there a way to use manual names for checks defined inside service definition file? If not, are you considering adding this feature? 
Thanks.

**Comment by daveadams** [comment] 2015-12-11 14:46
The workaround for this is to define checks outside the "services" section of the config in the agent-scope "checks" section and map them back to the service by setting `service_id`.

Example:

    {
      "service": {
        "id": "database",
        "port": 1234,
        "name": "Relational Database Service"
      },
      "checks": [
        {
          "id": "my-check-id",
          "service_id": "database",
          "script": "/path/to/check.sh"
          "interval": "10s"
        }
      ]
    }

**Comment by das-vinculum** [comment] 2015-12-16 15:02
Thank you for the tip @daveadams . Unfortunately this currently disqualifies the use of the official client https://github.com/Ecwid/consul-api or the puppet module https://forge.puppetlabs.com/KyleAnderson/consul since those do not offer such a way easily. The documentation also states here https://consul.io/docs/agent/checks.html that one is able to specify a name for the check. 
So, is there the idea of adding that?

**Comment by slackpad** [comment] 2016-02-02 22:40
Closing this one as a duplicate of https://github.com/hashicorp/consul/issues/1289.

**Closed by slackpad** 2016-02-02 22:40 UTC
Labels: enhancement
