### ISSUE TITLE
check Output not updated at all

### ISSUE THREAD

**Issue by imcom** [hashicorp/consul#1057] opened 2015-06-25 08:59 UTC
Hi all,

Has anyone experienced the same situation like below:
1) consul agent is configured with a watcher on critical checks
config:
```
{
  "type": "checks",
  "handler": "/home/imcom/consul/bin/rasalghul watch -name critical -region dc2",
  "datacenter": "dc2",
   "state": "critical"
 }
```
2) deploy a script check by adding a json file in Consul config dir and reload consul agent.

3) script checks output text/json formatted string to stdout and run every 30s or whatever interval.

4) check_update_interval set to "0s" to have output get synced each time check runs.
```
{
   "check_update_interval": "0s",
   ...
}
```

Then, from the input of watcher, I get empty string in `Output` field every time for the first run of checks and then this field sometimes will be never filled even though the checks keep running.

```
{"Node":"rdserver9","CheckID":"service:rdserver9.systembasic:systembasic:1","Name":"Service 'systembasic:systembasic' check","Status":"critical","Notes":"load","Output":"","ServiceID":"rdserver9.systembasic:systembasic","ServiceName":"systembasic:systembasic"}]
```

From watcher's perspective, the checks will be in critical status anyway and have no outputs by the first time watcher receives the checks, so I get critical checks by the time the checks are first loaded with output filed being empty. What's bothering here is that the Output field will not update afterwards, even though the checks keep running ...

I also noted that TTL checks do not have this behavior ... Output returns immediately each time

Any ideas?

**Comment by imcom** [comment] 2015-06-25 09:04
P.S.  I am using 0.5.0 for this testing

**Comment by imcom** [comment] 2015-06-25 09:22
This issue may turn into another question,

How often a service is synced among agents? And how often the checks of a service are synced?

after upgraded to 0.5.2, I can see logs from agent like below:

```
015/06/25 17:09:20 [INFO] agent: Synced service 'rdserver9.systembasic:systembasic'
2015/06/25 17:09:22 [WARN] agent: Check 'service:rdserver9.systembasic:systembasic:2' is now critical
2015/06/25 17:09:23 [WARN] agent: Check 'service:rdserver9.systembasic:systembasic:3' is now critical
2015/06/25 17:09:28 [WARN] agent: Check 'service:rdserver9.systembasic:systembasic:4' is now critical
2015/06/25 17:09:44 [WARN] agent: Check 'service:rdserver9.systembasic:systembasic:1' is now critical
2015/06/25 17:09:52 [WARN] agent: Check 'service:rdserver9.systembasic:systembasic:2' is now critical
2015/06/25 17:09:53 [WARN] agent: Check 'service:rdserver9.systembasic:systembasic:3' is now critical
2015/06/25 17:09:58 [WARN] agent: Check 'service:rdserver9.systembasic:systembasic:4' is now critical
2015/06/25 17:10:14 [WARN] agent: Check 'service:rdserver9.systembasic:systembasic:1' is now critical
2015/06/25 17:10:22 [WARN] agent: Check 'service:rdserver9.systembasic:systembasic:2' is now critical
2015/06/25 17:10:23 [WARN] agent: Check 'service:rdserver9.systembasic:systembasic:3' is now critical
2015/06/25 17:10:28 [WARN] agent: Check 'service:rdserver9.systembasic:systembasic:4' is now critical
2015/06/25 17:10:44 [WARN] agent: Check 'service:rdserver9.systembasic:systembasic:1' is now critical
2015/06/25 17:10:52 [WARN] agent: Check 'service:rdserver9.systembasic:systembasic:2' is now critical
2015/06/25 17:10:53 [WARN] agent: Check 'service:rdserver9.systembasic:systembasic:3' is now critical
2015/06/25 17:10:58 [WARN] agent: Check 'service:rdserver9.systembasic:systembasic:4' is now critical
2015/06/25 17:11:14 [WARN] agent: Check 'service:rdserver9.systembasic:systembasic:1' is now critical
2015/06/25 17:11:22 [WARN] agent: Check 'service:rdserver9.systembasic:systembasic:2' is now critical
2015/06/25 17:11:23 [WARN] agent: Check 'service:rdserver9.systembasic:systembasic:3' is now critical
2015/06/25 17:11:28 [WARN] agent: Check 'service:rdserver9.systembasic:systembasic:4' is now critical
2015/06/25 17:11:44 [WARN] agent: Check 'service:rdserver9.systembasic:systembasic:1' is now critical
2015/06/25 17:11:52 [WARN] agent: Check 'service:rdserver9.systembasic:systembasic:2' is now critical
2015/06/25 17:11:53 [WARN] agent: Check 'service:rdserver9.systembasic:systembasic:3' is now critical
2015/06/25 17:11:58 [WARN] agent: Check 'service:rdserver9.systembasic:systembasic:4' is now critical
2015/06/25 17:12:14 [WARN] agent: Check 'service:rdserver9.systembasic:systembasic:1' is now critical
2015/06/25 17:12:22 [WARN] agent: Check 'service:rdserver9.systembasic:systembasic:2' is now critical
2015/06/25 17:12:23 [WARN] agent: Check 'service:rdserver9.systembasic:systembasic:3' is now critical
2015/06/25 17:12:24 [INFO] agent: Synced check 'service:rdserver9.systembasic:systembasic:1'
2015/06/25 17:12:28 [WARN] agent: Check 'service:rdserver9.systembasic:systembasic:4' is now critical
2015/06/25 17:12:44 [WARN] agent: Check 'service:rdserver9.systembasic:systembasic:1' is now critical
2015/06/25 17:12:45 [INFO] agent: Synced check 'service:rdserver9.systembasic:systembasic:4'
2015/06/25 17:12:52 [WARN] agent: Check 'service:rdserver9.systembasic:systembasic:2' is now critical
2015/06/25 17:12:53 [WARN] agent: Check 'service:rdserver9.systembasic:systembasic:3' is now critical
2015/06/25 17:12:58 [WARN] agent: Check 'service:rdserver9.systembasic:systembasic:4' is now critical
2015/06/25 17:13:14 [WARN] agent: Check 'service:rdserver9.systembasic:systembasic:1' is now critical
2015/06/25 17:13:22 [WARN] agent: Check 'service:rdserver9.systembasic:systembasic:2' is now critical
2015/06/25 17:13:23 [WARN] agent: Check 'service:rdserver9.systembasic:systembasic:3' is now critical
2015/06/25 17:13:28 [INFO] agent: Synced check 'service:rdserver9.systembasic:systembasic:2'
```

So when I first added the service, I got:
```
2015/06/25 17:09:20 [INFO] agent: Synced service 'rdserver9.systembasic:systembasic'
2015/06/25 17:09:22 [WARN] agent: Check 'service:rdserver9.systembasic:systembasic:2' is now critical
2015/06/25 17:09:23 [WARN] agent: Check 'service:rdserver9.systembasic:systembasic:3' is now critical
2015/06/25 17:09:28 [WARN] agent: Check 'service:rdserver9.systembasic:systembasic:4' is now critical
2015/06/25 17:09:44 [WARN] agent: Check 'service:rdserver9.systembasic:systembasic:1' is now critical
```
By that time, I got four critical checks from my watcher and the `Output` field of all checks were empty.

Then with time went by, checks run every 30s so I got messages that those checks remained in critical status all the time.

Afterwards, around 3min later, I got this:
```
2015/06/25 17:12:24 [INFO] agent: Synced check 'service:rdserver9.systembasic:systembasic:1'
```
```
2015/06/25 17:12:45 [INFO] agent: Synced check 'service:rdserver9.systembasic:systembasic:4'
```
with those messages showed up, I got updated `Output` field in my watcher ....
However as said, I set check_update_interval to "0s" as instructed in the doc to have `Output` synced immediately with no defer, but clearly it seemed not working on my case .... and the interval before I got messages like `Synced check xxx` seemed random to me ...

**Comment by imcom** [comment] 2015-06-25 09:34
More info,

I opened debug log and can see that checks got output every time without problem, but just the output were not synced to checks watcher nor web UI ...

logs here:
```
2015/06/25 17:33:43 [DEBUG] agent: check 'service:rdserver9.systembasic:systembasic:1' script '/usr/lib/nagios/plugins/check_load -c 24,22,20 -w 18,16,14 ' output: /bin/bash: /usr/lib/nagios/plugins/check_load: No such file or directory
2015/06/25 17:33:43 [WARN] agent: Check 'service:rdserver9.systembasic:systembasic:1' is now critical
2015/06/25 17:33:48 [DEBUG] memberlist: Initiating push/pull sync with: 10.6.8.98:8301
2015/06/25 17:34:02 [DEBUG] agent: check 'service:rdserver9.systembasic:systembasic:2' script '/usr/lib/nagios/plugins/check_memory -w 5% -c 1% -u G' output: /bin/bash: /usr/lib/nagios/plugins/check_memory: No such file or directory
2015/06/25 17:34:02 [WARN] agent: Check 'service:rdserver9.systembasic:systembasic:2' is now critical
2015/06/25 17:34:04 [DEBUG] agent: check 'service:rdserver9.systembasic:systembasic:3' script '/usr/lib/nagios/plugins/check_disk -w 30% -c 10% ' output: /bin/bash: /usr/lib/nagios/plugins/check_disk: No such file or directory
2015/06/25 17:34:04 [WARN] agent: Check 'service:rdserver9.systembasic:systembasic:3' is now critical
2015/06/25 17:34:06 [DEBUG] agent: check 'service:rdserver9.systembasic:systembasic:4' script '/usr/bin/ruby /root/port_open.rb -n example.com -t 3 -a 127.0.0.1:80,127.0.0.1:8080 ' output: "{\"domain\":\"example.com\",\"checks\":[\"127.0.0.1:80:true\",\"127.0.0.1:8080:false\"],\"pass\":false}"
2015/06/25 17:34:06 [WARN] agent: Check 'service:rdserver9.systembasic:systembasic:4' is now critical
2015/06/25 17:34:13 [DEBUG] agent: check 'service:rdserver9.systembasic:systembasic:1' script '/usr/lib/nagios/plugins/check_load -c 24,22,20 -w 18,16,14 ' output: /bin/bash: /usr/lib/nagios/plugins/check_load: No such file or directory
2015/06/25 17:34:13 [WARN] agent: Check 'service:rdserver9.systembasic:systembasic:1' is now critical
```

**Comment by orivej** [comment] 2015-07-10 01:57
I have the same issue with consul from master.

**Comment by ryanuber** [comment] 2015-07-13 19:55
I can see how this is happening - since the output and status both never change after the initial sync, the anti-entropy never actually syncs the output to the servers. Marking as a bug, thanks for the report!

**Comment by achille-roussel** [comment] 2015-10-01 18:28
Hello guys, I'm running into what I think is the same issue where the output is not being updated when the status of a check doesn't change.

Are you seeking help to get it fixed or is there already work in progress?
I'm willing to give it a try but just wanna avoid duplicate effort.

Let me know.

**Comment by imcom** [comment] 2015-10-02 00:46
hi @achille-roussel I've not got time to dig into this issue and it seems like neither the Consul team ... I am looking forward to the 0.5.3 release (current master) since it fixes the UDP loss issue by using TCP heartbeat as a fallback.It is a great help in multiple IDCs with unstable links. In 0.5.3 they used a new protocol among agents for communication and maybe consensus, just to be sure that your work shall base on the new protocol.

Good luck

**Comment by imcom** [comment] 2015-10-30 04:10
Consul team! any updates on this bug??

**Comment by spinus** [comment] 2015-11-18 13:31
Same issue here.

**Comment by ariscn** [comment] 2015-12-15 20:32
+1, similar problem - TTL checks that change notes but not health status show null notes forever.

**Comment by ariscn** [comment] 2016-01-02 20:40
Bump, this is a real thorn in my side right now...

**Comment by fishtek** [comment] 2016-01-16 15:56
+1, It seems we are running into this issue (or a very similar one) as well.  We are experimenting with script checks.  And simply watching the output field will occasionally show an empty string, even though in the debug, log the script returns stdout every time.

I set up a small 3 node system with one check on each node (1 CPU, 1 Memory, and 1 Disk).  In the below example the memory check on node 3 seems to occasionally return an empty output, but the debug log shows the proper data every time.  After a couple minutes it'll populate the output, and then a few minutes more it'll return to the empty string.

```bash
 2016/01/16 15:46:52 [DEBUG] agent: Service 'consul' in sync
 2016/01/16 15:46:52 [DEBUG] agent: Check 'System memory' in sync
 2016/01/16 15:46:52 [DEBUG] agent: check 'System memory' script 'check_system.py mem 70 90' output: MEM OK: 34.0% memory used -- 0.0% swap used
 2016/01/16 15:46:52 [DEBUG] agent: Check 'System memory' is passing
 2016/01/16 15:46:53 [DEBUG] memberlist: Initiating push/pull sync with: 192.168.19.142:8301
 2016/01/16 15:47:12 [DEBUG] agent: check 'System memory' script 'check_system.py mem 70 90' output: MEM OK: 34.0% memory used -- 0.0% swap used
 2016/01/16 15:47:12 [DEBUG] agent: Check 'System memory' is passing
 2016/01/16 15:47:23 [DEBUG] memberlist: Initiating push/pull sync with: 192.168.19.148:8301
 2016/01/16 15:47:32 [DEBUG] agent: check 'System memory' script 'check_system.py mem 70 90' output: MEM OK: 34.1% memory used -- 0.0% swap used
 2016/01/16 15:47:32 [DEBUG] agent: Check 'System memory' is passing
 2016/01/16 15:47:38 [DEBUG] memberlist: Initiating push/pull sync with: 192.168.19.142:8302
 2016/01/16 15:47:51 [DEBUG] memberlist: TCP connection from=192.168.19.142:43558
```

curl http://192.168.19.142:8500/v1/health/state/any
```json
[{
    "Node": "consul-node1",
    "CheckID": "serfHealth",
    "Name": "Serf Health Status",
    "Status": "passing",
    "Notes": "",
    "Output": "Agent alive and reachable",
    "ServiceID": "",
    "ServiceName": "",
    "CreateIndex": 57697,
    "ModifyIndex": 57697
}, {
    "Node": "consul-node1",
    "CheckID": "System cpu",
    "Name": "System cpu",
    "Status": "passing",
    "Notes": "Critical 90%, warning 70%",
    "Output": "CPU OK: 1.2%\n",
    "ServiceID": "",
    "ServiceName": "",
    "CreateIndex": 60771,
    "ModifyIndex": 60998
}, {
    "Node": "consul-node2",
    "CheckID": "serfHealth",
    "Name": "Serf Health Status",
    "Status": "passing",
    "Notes": "",
    "Output": "Agent alive and reachable",
    "ServiceID": "",
    "ServiceName": "",
    "CreateIndex": 57697,
    "ModifyIndex": 57697
}, {
    "Node": "consul-node2",
    "CheckID": "System disks",
    "Name": "System disks",
    "Status": "passing",
    "Notes": "Critical 90%, Warning 70% used",
    "Output": "DISK OK: 7.8% used\n",
    "ServiceID": "",
    "ServiceName": "",
    "CreateIndex": 57697,
    "ModifyIndex": 60785
}, {
    "Node": "consul-node3",
    "CheckID": "serfHealth",
    "Name": "Serf Health Status",
    "Status": "passing",
    "Notes": "",
    "Output": "Agent alive and reachable",
    "ServiceID": "",
    "ServiceName": "",
    "CreateIndex": 57697,
    "ModifyIndex": 57697
}, {
    "Node": "consul-node3",
    "CheckID": "System memory",
    "Name": "System memory",
    "Status": "passing",
    "Notes": "Critical 90%, warning 70%",
    "Output": "",
    "ServiceID": "",
    "ServiceName": "",
    "CreateIndex": 57697,
    "ModifyIndex": 60981
}]
```

Is it something specific in my output that is causing it to behave so erratically?  
Also is there perhaps any sort of workaround someone can think of, until this issue is fixed?

**Comment by kisscool** [comment] 2016-01-25 19:39
+1
This exact issue is forcing me to keep my old Nagios on production. Please, any news of progress would be welcome.

**Comment by Blatwurst** [comment] 2016-02-01 03:31
I'm seeing this issue as well I think.  For me, the output occasionally shows up in the status record, but I can't pin down what triggers it to do so.  I'm only playing with health checks for the first time, so I have check_update_interval set to 5s and am just hand-tweaking a hard-coded script to cause it to return different status codes and print different output.

I've got just a single server node.  I've tried querying both the server itself and the one client node I've got in the cluster.

**Comment by kisscool** [comment] 2016-02-08 22:19
It might be related to the following lines of the function UpdateCheck from /command/agent/local.go : 

	// Do nothing if update is idempotent
	if check.Status == status && check.Output == output {
		return
	}

I cannot reproduce the issue once I comment those lines, but my test setup is quite small (3 nodes only) so it might just be blind luck. Could someone with a bigger test setup confirms it as a valid fix ?

**Comment by slackpad** [comment] 2016-02-17 04:09
@kisscool that's probably not a good fix because it will always sync the output so there will be a lot of churn in the cluster state to repeatedly sync the same output. I think we will either rate limit these so they eventually get synced, or we can do a check when we perform anti-entropy sync with the servers like we do for other values. We will get a fix in for the next Consul release.

**Comment by Blatwurst** [comment] 2016-03-22 07:03
I just upgraded to 0.6.4 and I'm still not consistently seeing the output of my health checks via the HTTP endpoints that return the "Output" value for a check, nor do I see them in the GUI.  Is this supposed to be fixed in 0.6.4, or did **slackpad**'s comment "We will get a fix in for the next Consul release." refer to 0.6.5.  We would really like to be able to consistently get the output of our checks without resorting to some wonky out of band method.

**Comment by slackpad** [comment] 2016-03-22 14:56
Hi @Blatwurst a fix for this did not make it in time for the 0.6.4 release - sorry about that. We will update this once we've got it fixed. Sorry about the delay as well, there's another issue #1069 in this area and we want to make sure we don't make that worse as part of this fix.

**Comment by slackpad** [comment] 2016-04-23 01:52
Need to re-open this one. This seems to still be an issue:

1. TTL check gets registered after a service is created (output will default to empty).
2. External process starts hitting the TTL check with non-empty output at a 5 second interval.
3. Check output doesn't update unless the state changes (remains blank).

Doing some tracing it looks like the check always has a deferred timer active, even well after it should have expired.

/cc @sean-

**Comment by slackpad** [comment] 2016-04-23 02:19
Figured out that the above is because the newly-registered check is forced to have an initial empty output, so it sees the first real output update as spammy since the status didn't change. A simple fix for this might be to accept all updates in the initial `CheckUpdateInterval` after the check is registered and then apply rate limiting after that. This lets us get start startup transients out of the way and then slow down in the steady state

**Comment by slackpad** [comment] 2016-04-23 05:03
A nice policy might be to allow unlimited output updates up to `CheckUpdateInterval` minutes after a state change - that'll let you get transients after any event, not just startup. I'll pursue that and see how it looks and then add a test to make sure there's no issue were if the output is always changing you never get an update.

**Comment by slackpad** [comment] 2016-04-24 17:24
Tracking open work under #1982.

**Closed by slackpad** 2016-04-24 17:24 UTC
Labels: bug

**Comment by nh2** [comment] 2017-10-10 16:10
I'd like to raise that this issue is a `bug` while #1982 is only an `enhancement` -- is this no longer considered a bug?

**Comment by slackpad** [comment] 2017-10-10 16:34
@nh2 the enhancement will fix the bug but I went ahead and added the bug label to #1982.

**Comment by kisscool** [comment] 2017-10-10 17:35
Is this enhancement planned on the roadmap ?
This bug is now 2 years old and it still prevents any Consul deployment at my company. At this point I don't even dare to suggest Consul for new projects anymore.

**Comment by slackpad** [comment] 2017-10-10 17:53
@kisscool sorry about that, we are working on a local state refactor in https://github.com/hashicorp/consul/pull/3391 that's underway, and will be a good basis from which we can fix this, so hopefully fairly soon for this one.
