### ISSUE TITLE
Consul member might get evicted and flaps if behind NAT due to source port not the same as serf listen port.

### ISSUE THREAD

**Issue by sam0737** [hashicorp/consul#1465] opened 2015-12-03 05:53 UTC
(I did comment my scenario here at #352 but I think it might not been reviewed, because I didn't aware the ticket was closed at that time)

Problem Description:
1. consul member stays behind an NAT (use case: a docker container)
2. It is configured with "advertise_addr": "PUBLIC_IP", "ports": { "serf_lan": 12345 }. And port 12345 is mapped accordingly. (say PUBLIC_IP:12345 -> PRIVATE_IP:12345 by iptables DNAT, both TCP/UDP). of course 12345 is just an example but is unique.
3. the problem is, although PUBLIC_IP:12345 -> PRIVATE_IP:12345 works, but when this PRIVATE_IP makes send "ping" to other hosts, the source port is not guaranteed to be :12345. It might be something else if the source port is used previously.  And some others peer might not recognize the member because the source port is different, and results in state flapping.

Scenario/Repro Step:
1. Put consul inside a docker container. when container is started, a port is picked (say 12345) and mapped, and consul is configured as described.
2. Things works perfectly at this stage. Outgoing communication is initiated from port 12345 and seen as 12345, and packets coming to 12345 is received by this container too.
3. stop, and start such container again.  The port number and configuration stays the same...
4. At this point, the container private ip is mostly likely changed, hence the NAT will now map outgoing packets from 12345 and this new private ip to another source port - say 1206, and this is not expected by the other members.  
5. Flapping or false negative health is resulted.

Consul version 0.5.2. Consul protocol 2.

**Comment by sam0737** [comment] 2015-12-09 02:38
`consul monitor` output

At step 2.

    2015/12/08 18:45:22 [INFO] serf: EventMemberJoin: w9vnge 10.88.43.165
    2015/12/08 18:45:22 [INFO] consul: member 'w9vnge' joined, marking health alive
    2015/12/08 18:50:45 [INFO] agent.rpc: Accepted client: 127.0.0.1:37479
    2015/12/08 18:51:59 [INFO] agent.rpc: Accepted client: 127.0.0.1:37488

After the container is stopped and restart. `tcpdump` shows that the source UDP port changed.

    2015/12/08 18:52:15 [INFO] serf: EventMemberLeave: w9vnge 10.88.43.165
    2015/12/08 18:52:15 [INFO] consul: member 'w9vnge' left, deregistering
    2015/12/08 18:52:33 [INFO] serf: EventMemberJoin: w9vnge 10.88.43.165
    2015/12/08 18:52:33 [INFO] consul: member 'w9vnge' joined, marking health alive
    2015/12/08 18:52:39 [WARN] memberlist: Was able to reach w9vnge via TCP but not UDP, network may be misconfigured and not allowing bidirectional UDP
    2015/12/08 18:52:43 [INFO] serf: EventMemberFailed: w9vnge 10.88.43.165
    2015/12/08 18:52:43 [INFO] consul: member 'w9vnge' failed, marking health critical
    2015/12/08 18:53:23 [INFO] serf: EventMemberJoin: w9vnge 10.88.43.165
    2015/12/08 18:53:23 [INFO] consul: member 'w9vnge' joined, marking health alive
    2015/12/08 18:53:24 [WARN] memberlist: Was able to reach w9vnge via TCP but not UDP, network may be misconfigured and not allowing bidirectional UDP
    2015/12/08 18:53:31 [WARN] memberlist: Was able to reach w9vnge via TCP but not UDP, network may be misconfigured and not allowing bidirectional UDP
    2015/12/08 18:53:32 [INFO] serf: EventMemberFailed: w9vnge 10.88.43.165
    2015/12/08 18:53:32 [INFO] consul: member 'w9vnge' failed, marking health critical
    2015/12/08 18:53:53 [INFO] serf: EventMemberJoin: w9vnge 10.88.43.165
    2015/12/08 18:53:53 [INFO] consul: member 'w9vnge' joined, marking health alive
    2015/12/08 18:53:59 [INFO] memberlist: Marking w9vnge as failed, suspect timeout reached
    2015/12/08 18:53:59 [INFO] serf: EventMemberFailed: w9vnge 10.88.43.165
    2015/12/08 18:53:59 [INFO] consul: member 'w9vnge' failed, marking health critical
    2015/12/08 18:54:02 [INFO] serf: EventMemberJoin: w9vnge 10.88.43.165
    2015/12/08 18:54:02 [INFO] consul: member 'w9vnge' joined, marking health alive
    2015/12/08 18:54:04 [WARN] memberlist: Was able to reach w9vnge via TCP but not UDP, network may be misconfigured and not allowing bidirectional UDP
    2015/12/08 18:54:08 [INFO] serf: EventMemberLeave: w9vnge 10.88.43.165
    2015/12/08 18:54:08 [INFO] consul: member 'w9vnge' left, deregistering
    2015/12/08 18:55:23 [INFO] serf: EventMemberJoin: w9vnge 10.88.43.165
    2015/12/08 18:55:23 [INFO] consul: member 'w9vnge' joined, marking health alive

**Comment by tayzlor** [comment] 2016-01-05 10:10
I'm receiving a similar issue after restarting consul (running as a docker container) on coreOS. 

```
 2016/01/05 10:08:07 [INFO] serf: EventMemberJoin: master2 172.31.1.12
    2016/01/05 10:08:07 [INFO] serf: EventMemberJoin: master1 172.31.1.11
    2016/01/05 10:08:07 [INFO] consul: adding server master3 (Addr: 172.31.1.13:8300) (DC: vagrant)
    2016/01/05 10:08:07 [INFO] consul: adding server master2 (Addr: 172.31.1.12:8300) (DC: vagrant)
    2016/01/05 10:08:07 [INFO] consul: adding server master1 (Addr: 172.31.1.11:8300) (DC: vagrant)
    2016/01/05 10:08:09 [WARN] memberlist: Was able to reach master3 via TCP but not UDP, network may be misconfigured and not allowing bidirectional UDP
    2016/01/05 10:08:10 [WARN] memberlist: Was able to reach master2 via TCP but not UDP, network may be misconfigured and not allowing bidirectional UDP
    2016/01/05 10:08:11 [WARN] memberlist: Was able to reach master1 via TCP but not UDP, network may be misconfigured and not allowing bidirectional UDP
```

Here's my consul config (for the agent) - 
```
{
  "datacenter": "vagrant",
  "advertise_addr": "172.31.1.14",
  "node_name": "slave1",
  "domain": "consul",
  "rejoin_after_leave": true,
  "client_addr": "0.0.0.0",
  "retry_join": [ "172.31.1.11", "172.31.1.12", "172.31.1.13" ],
  "leave_on_terminate": true,
  "dns_config": {
    "allow_stale": true,
    "max_stale": "1s"
  },
  "data_dir": "/var/lib/consul",
  "ui_dir": "/ui
```

and the output of docker inspect - 

```
[
{
    "Id": "691b02f10a4484ac61a8771736675db68e4e215ec91240e5298eb0451c11f197",
    "Created": "2016-01-05T10:07:06.734659749Z",
    "Path": "/bin/consul",
    "Args": [
        "agent",
        "-config-dir=/config"
    ],
    "State": {
        "Running": true,
        "Paused": false,
        "Restarting": false,
        "OOMKilled": false,
        "Dead": false,
        "Pid": 3107,
        "ExitCode": 0,
        "Error": "",
        "StartedAt": "2016-01-05T10:07:07.57918523Z",
        "FinishedAt": "0001-01-01T00:00:00Z"
    },
    "Image": "127df2235b9d9279b560d1322f30c9ee700874c09faf5543394a9cef4c719b77",
    "NetworkSettings": {
        "Bridge": "",
        "EndpointID": "fbbf643ec410fcd27a58573826c62738bd4df9da613acf14b5ac107e93d0b568",
        "Gateway": "172.17.42.1",
        "GlobalIPv6Address": "",
        "GlobalIPv6PrefixLen": 0,
        "HairpinMode": false,
        "IPAddress": "172.17.0.5",
        "IPPrefixLen": 16,
        "IPv6Gateway": "",
        "LinkLocalIPv6Address": "",
        "LinkLocalIPv6PrefixLen": 0,
        "MacAddress": "02:42:ac:11:00:05",
        "NetworkID": "62deade8d32381a2d045d89fee6e28269f0241a83b3a7bdc850786a7a4d2ba31",
        "PortMapping": null,
        "Ports": {
            "8300/tcp": [
                {
                    "HostIp": "0.0.0.0",
                    "HostPort": "8300"
                }
            ],
            "8301/tcp": [
                {
                    "HostIp": "0.0.0.0",
                    "HostPort": "8301"
                }
            ],
            "8301/udp": [
                {
                    "HostIp": "0.0.0.0",
                    "HostPort": "8301"
                }
            ],
            "8302/tcp": [
                {
                    "HostIp": "0.0.0.0",
                    "HostPort": "8302"
                }
            ],
            "8302/udp": [
                {
                    "HostIp": "0.0.0.0",
                    "HostPort": "8302"
                }
            ],
            "8400/tcp": [
                {
                    "HostIp": "0.0.0.0",
                    "HostPort": "8400"
                }
            ],
            "8500/tcp": [
                {
                    "HostIp": "0.0.0.0",
                    "HostPort": "8500"
                }
            ],
            "8600/tcp": null,
            "8600/udp": [
                {
                    "HostIp": "0.0.0.0",
                    "HostPort": "8600"
                }
            ]
        },
        "SandboxKey": "/var/run/docker/netns/691b02f10a44",
        "SecondaryIPAddresses": null,
        "SecondaryIPv6Addresses": null
    },
    "ResolvConfPath": "/var/lib/docker/containers/691b02f10a4484ac61a8771736675db68e4e215ec91240e5298eb0451c11f197/resolv.conf",
    "HostnamePath": "/var/lib/docker/containers/691b02f10a4484ac61a8771736675db68e4e215ec91240e5298eb0451c11f197/hostname",
    "HostsPath": "/var/lib/docker/containers/691b02f10a4484ac61a8771736675db68e4e215ec91240e5298eb0451c11f197/hosts",
    "LogPath": "/var/lib/docker/containers/691b02f10a4484ac61a8771736675db68e4e215ec91240e5298eb0451c11f197/691b02f10a4484ac61a8771736675db68e4e215ec91240e5298eb0451c11f197-json.log",
    "Name": "/consul",
    "RestartCount": 0,
    "Driver": "overlay",
    "ExecDriver": "native-0.2",
    "MountLabel": "",
    "ProcessLabel": "",
    "AppArmorProfile": "",
    "ExecIDs": null,
    "HostConfig": {
        "Binds": [
            "/var/lib/consul:/data",
            "/etc/consul.d:/config",
            "/var/run/docker.sock:/var/run/docker.sock"
        ],
        "ContainerIDFile": "",
        "LxcConf": [],
        "Memory": 0,
        "MemorySwap": 0,
        "CpuShares": 0,
        "CpuPeriod": 0,
        "CpusetCpus": "",
        "CpusetMems": "",
        "CpuQuota": 0,
        "BlkioWeight": 0,
        "OomKillDisable": false,
        "MemorySwappiness": -1,
        "Privileged": false,
        "PortBindings": {
            "8300/tcp": [
                {
                    "HostIp": "",
                    "HostPort": "8300"
                }
            ],
            "8301/tcp": [
                {
                    "HostIp": "",
                    "HostPort": "8301"
                }
            ],
            "8301/udp": [
                {
                    "HostIp": "",
                    "HostPort": "8301"
                }
            ],
            "8302/tcp": [
                {
                    "HostIp": "",
                    "HostPort": "8302"
                }
            ],
            "8302/udp": [
                {
                    "HostIp": "",
                    "HostPort": "8302"
                }
            ],
            "8400/tcp": [
                {
                    "HostIp": "",
                    "HostPort": "8400"
                }
            ],
            "8500/tcp": [
                {
                    "HostIp": "",
                    "HostPort": "8500"
                }
            ],
            "8600/udp": [
                {
                    "HostIp": "",
                    "HostPort": "8600"
                }
            ]
        },
        "Links": null,
        "PublishAllPorts": false,
        "Dns": null,
        "DnsSearch": null,
        "ExtraHosts": null,
        "VolumesFrom": null,
        "Devices": [],
        "NetworkMode": "default",
        "IpcMode": "",
        "PidMode": "",
        "UTSMode": "",
        "CapAdd": null,
        "CapDrop": null,
        "GroupAdd": null,
        "RestartPolicy": {
            "Name": "no",
            "MaximumRetryCount": 0
        },
        "SecurityOpt": null,
        "ReadonlyRootfs": false,
        "Ulimits": null,
        "LogConfig": {
            "Type": "json-file",
            "Config": {}
        },
        "CgroupParent": "",
        "ConsoleSize": [
            0,
            0
        ]
    },
    "GraphDriver": {
        "Name": "overlay",
        "Data": {
            "LowerDir": "/var/lib/docker/overlay/127df2235b9d9279b560d1322f30c9ee700874c09faf5543394a9cef4c719b77/root",
            "MergedDir": "/var/lib/docker/overlay/691b02f10a4484ac61a8771736675db68e4e215ec91240e5298eb0451c11f197/merged",
            "UpperDir": "/var/lib/docker/overlay/691b02f10a4484ac61a8771736675db68e4e215ec91240e5298eb0451c11f197/upper",
            "WorkDir": "/var/lib/docker/overlay/691b02f10a4484ac61a8771736675db68e4e215ec91240e5298eb0451c11f197/work"
        }
    },
    "Mounts": [
        {
            "Source": "/etc/consul.d",
            "Destination": "/config",
            "Mode": "",
            "RW": true
        },
        {
            "Source": "/var/run/docker.sock",
            "Destination": "/var/run/docker.sock",
            "Mode": "",
            "RW": true
        },
        {
            "Source": "/var/lib/consul",
            "Destination": "/data",
            "Mode": "",
            "RW": true
        }
    ],
    "Config": {
        "Hostname": "slave1",
        "Domainname": "",
        "User": "",
        "AttachStdin": false,
        "AttachStdout": true,
        "AttachStderr": true,
        "ExposedPorts": {
            "8300/tcp": {},
            "8301/tcp": {},
            "8301/udp": {},
            "8302/tcp": {},
            "8302/udp": {},
            "8400/tcp": {},
            "8500/tcp": {},
            "8600/tcp": {},
            "8600/udp": {}
        },
        "Tty": false,
        "OpenStdin": false,
        "StdinOnce": false,
        "Env": [
            "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
            "CONSUL_VERSION=0.6.0",
            "CONSUL_SHA256=307fa26ae32cb8732aed2b3320ed8daf02c28b50d952cbaae8faf67c79f78847",
            "DNS_RESOLVES=consul",
            "DNS_PORT=8600"
        ],
        "Cmd": null,
        "Image": "gliderlabs/consul-agent:0.6",
        "Volumes": null,
        "WorkingDir": "",
        "Entrypoint": [
            "/bin/consul",
            "agent",
            "-config-dir=/config"
        ],
        "OnBuild": null,
        "Labels": {}
    }
}```

**Comment by rojaro** [comment] 2016-01-29 13:05
I am having the same issue using Consul v0.6.3. After having restarted one of the cluster nodes the logs of the other two start filling up with messages like this one:
```
[WARN] memberlist: Was able to reach consul-coreos-ip-10-109-4-30 via TCP but not UDP, network may be misconfigured and not allowing bidirectional UDP
```

**Comment by anroots** [comment] 2016-02-03 15:31
Similar issue. `gliderlabs/consul` in Docker, ports published (both UDP and TCP), 3-node cluster. Redeployed one node, now the output is
```
2016/02/03 15:21:50 [WARN] memberlist: Was able to reach test via TCP but not UDP, network may be misconfigured and not allowing bidirectional UDP
```

**Comment by slackpad** [comment] 2016-03-29 06:49
Linking https://github.com/docker/docker/issues/8795 as related here, especially since the original description includes a container restart.

**Comment by asheshambasta** [comment] 2016-06-12 17:31
I ran into this without a container restart, and on EC2. I see some other issues speaking of this being a common occurrence on EC2 but that doesn't seem to make much sense. In my case, all the three hosts belong to the same VPC and are entirely reachable from one another (wide open SG setting).

Quite a show stopper for us, I'm afraid.

**Comment by CpuID** [comment] 2016-06-13 05:00
> Similar issue. gliderlabs/consul (0.6) in Docker, ports published (both UDP and TCP), 3-node cluster. Redeployed one node, now the output is
> 
> 2016/02/03 15:21:50 [WARN] memberlist: Was able to reach test via TCP but not UDP, network may be misconfigured and not allowing bidirectional UDP

I ended up just using net=host to resolve this warning, after trying to mess with a heap of other solutions. The original issue description [here](https://github.com/hashicorp/consul/issues/1465#issue-120099556) would make sense though, and explain the why.

**Comment by asheshambasta** [comment] 2016-06-13 07:05
@CpuID yeah that _seems_ to do the trick for me.

**Comment by sitano** [comment] 2016-08-11 16:38
We ran into the same issue @sam0737 with the Windows 2016 TP5 cross Azure boundaries. Will take a look into the heart-beating source code.

**Comment by sitano** [comment] 2016-09-12 16:22
I have extended `memberlist` package SWIM implementation to be able to trace exactly sources and dests of the membership protocol. Its exactly seen that the consul server receive UDP traffic not from advertised ports, but from NAT mapped randomly different ones (like :64123 instead of :8301).

To fix that, Docker `run` instruction must be provided with explicit TCP and UDP port mappings and a check that it succeeded w/o remapping dynamically. 

Under Windows Server TP5 mapping of the TCP and UDP port over the same source Port is not supported. (https://github.com/Microsoft/Virtualization-Documentation/issues/319). Thus, consul can't be setup in Windows environment for now.

Researching logs from the `memberlist`, I've got few thoughts on improving current situation:
- Consul/Memberlist(SWIM) implementation can detect and report port mismatch to make it easier to detect such kind of failures. It can be easily done when a Node `suspects` a node and then receives `alive` msg from the Node as a dead refuting response, it can compare source UDP port of the `alive` message with what it have in `stateNode` struct and report a [WARN] about ports mismatched and NATed misconfigured Node.
- Theoretically, Memberlist(SWIM) could support dynamic reconfiguration of advertised port. This is easy. When it sees refuting dead message response - fix the port if its a case.
- The main concern for now in Windows environment - Serf requires (if I am not wrong) to have TCP and UDP port to be the SAME. Is that the case? It would be helpful in some env to allow to use different ports via configuration.
- Memberlist(SWIM) could support the whole operation via TCP for hacking over complicated cases of UDP unavailability. 

What do you think?

**Comment by slackpad** [comment] 2016-09-21 02:58
@sitano that's a very interesting result. Is it possible for memberlist to become aware of the mapped ports by any direct means, or is that completely hidden because of the container wrapping? It would be nice if we could use some API to get this and configure accordingly without having to get feedback from peer nodes. TCP is possible for limited clusters, but won't scale well.

**Comment by sitano** [comment] 2016-09-29 11:06
@slackpad The question is about two things. 

> is that completely hidden because of the container wrapping?

I think this information is hidden from the environment of the guest (container), because this is exactly the point of the abstraction layer - transparent resource isolation. From the isolation standpoint, there is no sense to expose the information on how ports are mapped on a different level to the virtualized env.

> Is it possible for memberlist to become aware of the mapped ports by any direct means

Acquiring this information is possible, yet it is not very easy. The starter environment inside of the container may be organized by any means to obtain this information from the Docker daemon (requested mapping), host conntrack/nat configuration (Get-NewNATSession/StaticMapping) or any other way available; and then it should pass gathered info on mapped ports to the consul server agent start command line. And there are may exist other levels of indirection. Organizing all this is not very pleasant.

Personally, I would prefer MemberList to be able to detect miss-advertised ports automatically based on the stats of the incoming UDP traffic. The thing is the wrong port advertisement can be detected only from the outside of the container network host environment, so memberlist could reuse additional knowledge to at least detect such a cases.

**Comment by sitano** [comment] 2016-10-01 16:34
@slackpad I wanted to share another thought

This NAT issue is not a _BUG_. The bug is an error in implementation or environment. But a cause of this flapping behaviour is not an error, but wrong ports configuration. It's not a fault of the Consul, that it awaits properly declared ports to be available in advance. The fact of mismatching of advertised ports and mapped ports results into the situation where one side\or both of membership protocol does not see ping's acks.

Flapping behavior, in that case, is also normal, due to how MemberList is working. Suspect nodes can successfully refute its deadness. There is also a separation of MemberList operations between active and passive (ping ack is passive, refuting and resync is active).

Flapping is possible when behind a NAT, there is a still partial visibility (some ports are accessible and known, others dont) and is, due to the protocol best effort.

Maybe this issue (and all related) could be closed then, because the only way to organize valid networking for the Consul, is to know your ports, and not to advertise wrong ones. We run it on Linux docker like that:

```
/usr/bin/docker run \
    -p ${PUBLIC_IPV4}:8300:8300 \
    -p ${PUBLIC_IPV4}:8301:8301 \
    -p ${PUBLIC_IPV4}:8301:8301/udp \
    -p ${PUBLIC_IPV4}:8302:8302 \
    -p ${PUBLIC_IPV4}:8302:8302/udp \
    -p ${PRIVATE_IPV4}:8400:8400 \
    -p ${PRIVATE_IPV4}:8500:8500 \
    -p ${PRIVATE_IPV4}:53:53/udp \
    gliderlabs/consul:latest agent \
    ...
```

**Comment by slackpad** [comment] 2016-10-20 16:37
Agree with you it's not a bug :-) I don't like the idea of fixing up the ports based on feedback over the network as that breaks the abstraction as well. I'll keep this open to think about ways we can better report what's going on to operators since it can be hard to understand and diagnose what's going on.

**Comment by slackpad** [comment] 2017-05-18 01:06
I'm going to close this out as we've looked at some different options for reporting these kinds of errors but it really does come down to making sure the right ports are open.

**Closed by slackpad** 2017-05-18 01:06 UTC
Labels: docker, enhancement
