### ISSUE TITLE
UI xhr without token

### ISSUE THREAD

**Issue by FlowerWrong** [hashicorp/consul#2991] opened 2017-04-29 12:05 UTC
If you have a question, please direct it to the
[consul mailing list](https://www.consul.io/community.html) if it hasn't been
addressed in either the [FAQ](https://www.consul.io/docs/faq.html) or in one
of the [Consul Guides](https://www.consul.io/docs/guides/index.html).

When filing a bug, please include the following:

### `consul version` for both Client and Server
Client: `Consul v0.8.1`
Server: `Consul v0.8.1`

### `consul info` for both Client and Server
Client:
```
agent:
	check_monitors = 0
	check_ttls = 0
	checks = 0
	services = 1
build:
	prerelease = 
	revision = 'e9ca44d
	version = 0.8.1
consul:
	bootstrap = true
	known_datacenters = 1
	leader = true
	leader_addr = 127.0.0.1:8300
	server = true
raft:
	applied_index = 37
	commit_index = 37
	fsm_pending = 0
	last_contact = 0
	last_log_index = 37
	last_log_term = 3
	last_snapshot_index = 0
	last_snapshot_term = 0
	latest_configuration = [{Suffrage:Voter ID:127.0.0.1:8300 Address:127.0.0.1:8300}]
	latest_configuration_index = 1
	num_peers = 0
	protocol_version = 2
	protocol_version_max = 3
	protocol_version_min = 0
	snapshot_version_max = 1
	snapshot_version_min = 0
	state = Leader
	term = 3
runtime:
	arch = amd64
	cpu_count = 8
	goroutines = 74
	max_procs = 8
	os = linux
	version = go1.8.1
serf_lan:
	encrypted = false
	event_queue = 1
	event_time = 3
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 1
	members = 1
	query_queue = 0
	query_time = 1
serf_wan:
	encrypted = false
	event_queue = 0
	event_time = 1
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 1
	members = 1
	query_queue = 0
	query_time = 1
```

Server:
```
agent:
	check_monitors = 0
	check_ttls = 0
	checks = 0
	services = 1
build:
	prerelease = 
	revision = 'e9ca44d
	version = 0.8.1
consul:
	bootstrap = true
	known_datacenters = 1
	leader = true
	leader_addr = 127.0.0.1:8300
	server = true
raft:
	applied_index = 37
	commit_index = 37
	fsm_pending = 0
	last_contact = 0
	last_log_index = 37
	last_log_term = 3
	last_snapshot_index = 0
	last_snapshot_term = 0
	latest_configuration = [{Suffrage:Voter ID:127.0.0.1:8300 Address:127.0.0.1:8300}]
	latest_configuration_index = 1
	num_peers = 0
	protocol_version = 2
	protocol_version_max = 3
	protocol_version_min = 0
	snapshot_version_max = 1
	snapshot_version_min = 0
	state = Leader
	term = 3
runtime:
	arch = amd64
	cpu_count = 8
	goroutines = 74
	max_procs = 8
	os = linux
	version = go1.8.1
serf_lan:
	encrypted = false
	event_queue = 1
	event_time = 3
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 1
	members = 1
	query_queue = 0
	query_time = 1
serf_wan:
	encrypted = false
	event_queue = 0
	event_time = 1
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 1
	members = 1
	query_queue = 0
	query_time = 1
```

### Operating system and Environment details

archlinux

### Description of the Issue (and unexpected/desired result)

I am runing with `consul agent -server -bind=127.0.0.1 -client=0.0.0.0 -ui -config-file=development_config.json`, but the ui acl menu `Access Denied`. I see the chrome console. The xhr `http://127.0.0.1:8500/v1/acl/list?dc=dc1&token=` without token I set in url `http://127.0.0.1:8500/ui/?token=dev`.

### Log Fragments or Link to [gist](https://gist.github.com/)

Include appropriate Client or Server log fragments.  If the log is longer
than a few dozen lines, please include the URL to the
[gist](https://gist.github.com/).

TIP: Use `-log-level=TRACE` on the client and server to capture the maximum log detail.

**Comment by slackpad** [comment] 2017-05-01 22:26
Hi @FlowerWrong you actually need to set the token in the settings page of the UI, which puts it in local storage, though there's https://github.com/hashicorp/consul/issues/1655 which can make it difficult to do (see that issue for a workaround). Closing this as a duplicate of #1655.

**Closed by slackpad** 2017-05-01 22:26 UTC
