### ISSUE TITLE
No TRACE level logs are available

### ISSUE THREAD

**Issue by shpoont** [hashicorp/consul#1401] opened 2015-11-11 11:19 UTC
Despite the fact there is log_level option for "trace", there is no code generating logs of this level. This option should be removed, or, which is better, traces should be available according to configuration.

**Comment by slackpad** [comment] 2016-04-13 05:59
Closing this as a duplicate of https://github.com/hashicorp/consul/issues/1919 - we plan to convert DEBUG output that gets produced proportional to requests / usage to TRACE.

**Closed by slackpad** 2016-04-13 05:59 UTC
Labels: enhancement
