### ISSUE TITLE
Docs say one thing, consul does another.

### ISSUE THREAD

**Issue by withinboredom** [hashicorp/consul#2279] opened 2016-08-16 14:01 UTC
Docs here, [bind: Configuration page](https://www.consul.io/docs/agent/options.html#_bind) say it will bind to the first available private ip. They also say [under advertise](https://www.consul.io/docs/agent/options.html#_advertise) that it will use the `-bind` address, which should be the first private ip. However, if there are multiple private ips, this error is given:

Consul 0.6.4 (official docker image)
```
Error starting agent: Failed to get advertise address: Multiple private IPs found. Please configure one.
```

**Comment by withinboredom** [comment] 2016-08-16 14:03
Similar to #2234

**Comment by slackpad** [comment] 2016-09-16 22:41
Closing as a duplicate of #2234.

**Closed by slackpad** 2016-09-16 22:41 UTC
