### ISSUE TITLE
panic cannot free page 0 or 1: 0

### ISSUE THREAD

**Issue by kingeasternsun** [hashicorp/consul#6257] opened 2019-08-01 03:05 UTC
When filing a bug, please include the following headings if possible. Any example text in this template can be deleted.

#### Overview of the Issue

```
wdy@DESKTOP-6UVARRT:~$ consul agent -server -bootstrap-expect=1 -data-dir=/tmp/consul -node=agent-one -bind=10.10.4.118 -enable-script-checks=true -config-dir=/etc       /consul.d/ -ui
BootstrapExpect is set to 1; this is the same as Bootstrap mode.
bootstrap = true: do not enable unless necessary
==> Starting Consul agent...
           Version: 'v1.5.3'
           Node ID: '9f32ff5e-87e7-53c6-82d5-ccc7c996760f'
         Node name: 'agent-one'
        Datacenter: 'dc1' (Segment: '<all>')
            Server: true (Bootstrap: true)
       Client Addr: [127.0.0.1] (HTTP: 8500, HTTPS: -1, gRPC: -1, DNS: 8600)
      Cluster Addr: 10.10.4.118 (LAN: 8301, WAN: 8302)
           Encrypt: Gossip: false, TLS-Outgoing: false, TLS-Incoming: false, Auto-Encrypt-TLS: false

==> Log data will now stream in as it occurs:

    2019/08/01 09:56:24 [INFO]  raft: Initial configuration (index=1): [{Suffrage:Voter ID:9f32ff5e-87e7-53c6-82d5-ccc7c996760f Address:10.10.4.118:8300}]
    2019/08/01 09:56:24 [INFO]  raft: Node at 10.10.4.118:8300 [Follower] entering Follower state (Leader: "")
    2019/08/01 09:56:24 [INFO] serf: EventMemberJoin: agent-one.dc1 10.10.4.118
    2019/08/01 09:56:24 [WARN] serf: Failed to re-join any previously known node
    2019/08/01 09:56:24 [INFO] serf: EventMemberJoin: agent-one 10.10.4.118
    2019/08/01 09:56:24 [INFO] serf: Attempting re-join to previously known node: agent-two: 10.10.4.52:8301
    2019/08/01 09:56:24 [INFO] agent: Started DNS server 127.0.0.1:8600 (udp)
    2019/08/01 09:56:24 [INFO] consul: Handled member-join event for server "agent-one.dc1" in area "wan"
    2019/08/01 09:56:24 [INFO] consul: Adding LAN server agent-one (Addr: tcp/10.10.4.118:8300) (DC: dc1)
    2019/08/01 09:56:24 [INFO] agent: Started DNS server 127.0.0.1:8600 (tcp)
    2019/08/01 09:56:24 [INFO] agent: Started HTTP server on 127.0.0.1:8500 (tcp)
    2019/08/01 09:56:24 [INFO] agent: started state syncer
==> Consul agent running!
    2019/08/01 09:56:24 [INFO] serf: EventMemberJoin: agent-two 10.10.4.52
    2019/08/01 09:56:24 [INFO] serf: Re-joined to previously known node: agent-two: 10.10.4.52:8301
    2019/08/01 09:56:31 [WARN]  raft: Heartbeat timeout from "" reached, starting election
    2019/08/01 09:56:31 [INFO]  raft: Node at 10.10.4.118:8300 [Candidate] entering Candidate state in term 4
    2019/08/01 09:56:31 [INFO]  raft: Election won. Tally: 1
    2019/08/01 09:56:31 [INFO]  raft: Node at 10.10.4.118:8300 [Leader] entering Leader state
    2019/08/01 09:56:31 [INFO] consul: cluster leadership acquired
    2019/08/01 09:56:31 [INFO] consul: New leader elected: agent-one
    2019/08/01 09:56:31 [INFO] agent: Synced node info
    2019/08/01 09:59:44 [INFO] serf: EventMemberLeave: agent-two 10.10.4.52
    2019/08/01 09:59:44 [INFO] consul: member 'agent-two' left, deregistering
    2019/08/01 10:01:28 [INFO] serf: EventMemberJoin: agent-two 10.10.4.52
    2019/08/01 10:01:28 [INFO] consul: member 'agent-two' joined, marking health alive
panic: cannot free page 0 or 1: 0

goroutine 71 [running]:
github.com/boltdb/bolt.(*freelist).free(0xc000525500, 0xd5, 0x7fca7e880000)
        /go/pkg/mod/github.com/boltdb/bolt@v1.3.1/freelist.go:113 +0x336
github.com/boltdb/bolt.(*Tx).Commit(0xc00034e0e0, 0xc00070c1b8, 0x8)
        /go/pkg/mod/github.com/boltdb/bolt@v1.3.1/tx.go:176 +0x1b7
github.com/hashicorp/raft-boltdb.(*BoltStore).StoreLogs(0xc0000bbe60, 0xc0000e0030, 0x1, 0x1, 0x0, 0x0)
        /go/pkg/mod/github.com/hashicorp/raft-boltdb@v0.0.0-20171010151810-6e5ba93211ea/bolt_store.go:187 +0x23e
github.com/hashicorp/raft.(*LogCache).StoreLogs(0xc000489840, 0xc0000e0030, 0x1, 0x1, 0x3, 0xbf48b0a411f5f10c)
        /go/pkg/mod/github.com/hashicorp/raft@v1.1.1/log_cache.go:61 +0xec
github.com/hashicorp/raft.(*Raft).dispatchLogs(0xc0002aa300, 0xc0000b1b60, 0x1, 0x1)
        /go/pkg/mod/github.com/hashicorp/raft@v1.1.1/raft.go:1061 +0x2d8
github.com/hashicorp/raft.(*Raft).leaderLoop(0xc0002aa300)
        /go/pkg/mod/github.com/hashicorp/raft@v1.1.1/raft.go:746 +0x676
github.com/hashicorp/raft.(*Raft).runLeader(0xc0002aa300)
        /go/pkg/mod/github.com/hashicorp/raft@v1.1.1/raft.go:455 +0x209
github.com/hashicorp/raft.(*Raft).run(0xc0002aa300)
        /go/pkg/mod/github.com/hashicorp/raft@v1.1.1/raft.go:142 +0x66
github.com/hashicorp/raft.(*raftState).goFunc.func1(0xc0002aa300, 0xc000093af0)
        /go/pkg/mod/github.com/hashicorp/raft@v1.1.1/state.go:146 +0x53
created by github.com/hashicorp/raft.(*raftState).goFunc
        /go/pkg/mod/github.com/hashicorp/raft@v1.1.1/state.go:144 +0x66

```

#### Reproduction Steps

Steps to reproduce this issue, eg:

1. use the WSL-ubuntu18.04  of win10,  `consul agent -server -bootstrap-expect=1 -data-dir=/tmp/consul -node=agent-one -bind=10.10.4.118 -enable-script-checks=true -config-dir=/etc       /consul.d/ -ui`
2. another computer, ubuntu18.04.  `consul agent -data-dir=/tmp/consul -node=agent-two -bind=10.10.4.52 -enable-script-checks=true -config-dir=/etc/consul.d/`

### Consul info for both Client and Server

<details>
  <summary>Client info</summary>

```

agent:
        check_monitors = 2
        check_ttls = 0
        checks = 2
        services = 1
build:
        prerelease =
        revision = a42ded47
        version = 1.5.3
consul:
        acl = disabled
        known_servers = 1
        server = false
runtime:
        arch = amd64
        cpu_count = 4
        goroutines = 48
        max_procs = 4
        os = linux
        version = go1.12.1
serf_lan:
        coordinate_resets = 0
        encrypted = false
        event_queue = 0
        event_time = 5
        failed = 0
        health_score = 0
        intent_queue = 0
        left = 0
        member_time = 6
        members = 2
        query_queue = 0
        query_time = 1

```

</details>

<details>
  <summary>Server info</summary>

```
agent:
        check_monitors = 0
        check_ttls = 0
        checks = 0
        services = 0
build:
        prerelease =
        revision = a42ded47
        version = 1.5.3
consul:
        acl = disabled
        bootstrap = true
        known_datacenters = 1
        leader = true
        leader_addr = 10.10.4.118:8300
        server = true
raft:
        applied_index = 413
        commit_index = 413
        fsm_pending = 0
        last_contact = 0
        last_log_index = 413
        last_log_term = 5
        last_snapshot_index = 0
        last_snapshot_term = 0
        latest_configuration = [{Suffrage:Voter ID:9f32ff5e-87e7-53c6-82d5-ccc7c996760f Address:10.10.4.118:8300}]
        latest_configuration_index = 1
        num_peers = 0
        protocol_version = 3
        protocol_version_max = 3
        protocol_version_min = 0
        snapshot_version_max = 1
        snapshot_version_min = 0
        state = Leader
        term = 5
runtime:
        arch = amd64
        cpu_count = 8
        goroutines = 86
        max_procs = 8
        os = linux
        version = go1.12.1
serf_lan:
        coordinate_resets = 0
        encrypted = false
        event_queue = 0
        event_time = 5
        failed = 0
        health_score = 0
        intent_queue = 0
        left = 0
        member_time = 6
        members = 2
        query_queue = 0
        query_time = 1
serf_wan:
        coordinate_resets = 0
        encrypted = false
        event_queue = 0
        event_time = 1
        failed = 0
        health_score = 0
        intent_queue = 0
        left = 0
        member_time = 1
        members = 1
        query_queue = 0
        query_time = 1

```

</details>

### Operating system and Environment details

OS, Architecture, and any other information you can provide about the environment.

server consul: 
![win](https://user-images.githubusercontent.com/5291739/62262602-daeca700-b44b-11e9-9f8b-e15578c8a6f3.PNG)
and the WSL-ubuntu
```
lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.2 LTS
Release:        18.04
Codename:       bionic

```

client consul:
```
lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.2 LTS
Release:        18.04
Codename:       bionic
```

### Log Fragments

Include appropriate Client or Server log fragments. If the log is longer than a few dozen lines, please include the URL to the [gist](https://gist.github.com/) of the log instead of posting it in the issue. Use `-log-level=TRACE` on the client and server to capture the maximum log detail.

**Comment by Aestek** [comment] 2019-08-01 08:16
We've seen this as well when trying to run the tests on WSL

**Comment by mkeeler** [comment] 2019-08-01 14:11
Thanks for the report. Unfortunately this has been seen before and so far there is no fix. I am going to close this as a duplicate of: #3771

**Closed by mkeeler** 2019-08-01 14:11 UTC
