### ISSUE TITLE
Unpredictable X-Consul-Index changes by health/service method with blocking queries

### ISSUE THREAD

**Issue by WoZ** [hashicorp/consul#2216] opened 2016-07-27 17:05 UTC
I noticed strange behaviour with health/service API method with blocking queries. In example below I asked with index=3591901 and consul returns the list of services after 1 minute, as it should. Then I ran the same requests one more time and consul responded with new index=3592694. But the state of service didn't change. You may check CreateIndex and ModifyIndex of first and second responses to ensure that none of blocks changed. I've looked at docs but docs say nothing about unpredictable X-Consul-Index change that is not caused by ttl expiration of request. Is it specific to consul?

#### The first one request and response

```
# curl -i "http://127.0.0.1:8500/v1/health/service/vsscc?pretty&index=3591901&wait=1m"
HTTP/1.1 200 OK
Content-Type: application/json
X-Consul-Index: 3591901
X-Consul-Knownleader: true
X-Consul-Lastcontact: 0
Date: Wed, 27 Jul 2016 16:36:11 GMT
Content-Length: 1469

[
    {
        "Node": {
            "Node": "vsscc_app",
            "Address": "192.168.101.3",
            "CreateIndex": 2901006,
            "ModifyIndex": 3569565
        },
        "Service": {
            "ID": "vsscc.66",
            "Service": "vsscc",
            "Tags": [
                "vsscc"
            ],
            "Address": "192.168.101.3",
            "Port": 2912,
            "EnableTagOverride": false,
            "CreateIndex": 3242955,
            "ModifyIndex": 3242981
        },
        "Checks": [
            {
                "Node": "vsscc_app",
                "CheckID": "serfHealth",
                "Name": "Serf Health Status",
                "Status": "passing",
                "Notes": "",
                "Output": "Agent alive and reachable",
                "ServiceID": "",
                "ServiceName": "",
                "CreateIndex": 2901006,
                "ModifyIndex": 3569274
            },
            {
                "Node": "vsscc_app",
                "CheckID": "service:vsscc.66",
                "Name": "Service 'vsscc' check",
                "Status": "passing",
                "Notes": "",
                "Output": "HTTP GET http://192.168.101.3:2912/healthcheck: 200 OK Output: ",
                "ServiceID": "vsscc.66",
                "ServiceName": "vsscc",
                "CreateIndex": 3242955,
                "ModifyIndex": 3242981
            }
        ]
    }
]
```

#### Second request and response
```
# curl -i "http://127.0.0.1:8500/v1/health/service/vsscc?pretty&index=3591901&wait=1m"
HTTP/1.1 200 OK
Content-Type: application/json
X-Consul-Index: 3592694
X-Consul-Knownleader: true
X-Consul-Lastcontact: 0
Date: Wed, 27 Jul 2016 16:36:45 GMT
Content-Length: 1469

[
    {
        "Node": {
            "Node": "vsscc_app",
            "Address": "192.168.101.3",
            "CreateIndex": 2901006,
            "ModifyIndex": 3569565
        },
        "Service": {
            "ID": "vsscc.66",
            "Service": "vsscc",
            "Tags": [
                "vsscc"
            ],
            "Address": "192.168.101.3",
            "Port": 2912,
            "EnableTagOverride": false,
            "CreateIndex": 3242955,
            "ModifyIndex": 3242981
        },
        "Checks": [
            {
                "Node": "vsscc_app",
                "CheckID": "serfHealth",
                "Name": "Serf Health Status",
                "Status": "passing",
                "Notes": "",
                "Output": "Agent alive and reachable",
                "ServiceID": "",
                "ServiceName": "",
                "CreateIndex": 2901006,
                "ModifyIndex": 3569274
            },
            {
                "Node": "vsscc_app",
                "CheckID": "service:vsscc.66",
                "Name": "Service 'vsscc' check",
                "Status": "passing",
                "Notes": "",
                "Output": "HTTP GET http://192.168.101.3:2912/healthcheck: 200 OK Output: ",
                "ServiceID": "vsscc.66",
                "ServiceName": "vsscc",
                "CreateIndex": 3242955,
                "ModifyIndex": 3242981
            }
        ]
    }
]
```

#### `consul version`
Client: 0.6.3
Server: 0.6.3

#### `consul info`
Client:
```
agent:
        check_monitors = 0
        check_ttls = 0
        checks = 1
        services = 2
build:
        prerelease =
        revision = c933efde
        version = 0.6.3
consul:
        bootstrap = false
        known_datacenters = 1
        leader = false
        server = true
raft:
        applied_index = 3593512
        commit_index = 3593512
        fsm_pending = 0
        last_contact = 91.495114ms
        last_log_index = 3593512
        last_log_term = 48174
        last_snapshot_index = 3591199
        last_snapshot_term = 48174
        num_peers = 8
        state = Follower
        term = 48174
runtime:
        arch = amd64
        cpu_count = 4
        goroutines = 80
        max_procs = 2
        os = linux
        version = go1.5.3
serf_lan:
        encrypted = false
        event_queue = 0
        event_time = 221
        failed = 0
        intent_queue = 0
        left = 0
        member_time = 82
        members = 8
        query_queue = 0
        query_time = 1
serf_wan:
        encrypted = false
        event_queue = 0
        event_time = 1
        failed = 0
        intent_queue = 0
        left = 0
        member_time = 1
        members = 1
        query_queue = 0
        query_time = 1
```

**Comment by highlyunavailable** [comment] 2016-07-27 18:06
This sounds similar to the underlying cause in #1244.

**Comment by WoZ** [comment] 2016-07-29 12:41
@highlyunavailable yes, it's the same issue.

**Comment by slackpad** [comment] 2016-08-18 00:28
This definitely is #1244. In general, a blocking query can always wake up even if there were no changes to what you were blocking on, but in this case, a change to any service wakes them all up, so we need to make the tracking more fine grained. Sorry that's currently confusing.

Closing this as a duplicate of #1244.

**Closed by slackpad** 2016-08-18 00:28 UTC
