### ISSUE TITLE
Agent start fails with nil pointer dereference

### ISSUE THREAD

**Issue by pascaldekloe** [hashicorp/consul#2428] opened 2016-10-21 14:07 UTC
Current master branch: 104b12040a8fbe6153d1a4f1be1b73d37bf699e5

% ~/repo/consul/bin/consul agent -dev -advertise 127.0.0.1 -config-dir=etc/consul.d
==> Starting Consul agent...
==> Starting Consul agent RPC...
==> Consul agent running!
           Version: 'v0.7.0-111-g104b120-dev (104b120)'
         Node name: 'LM-AMS-14500281'
        Datacenter: 'dc1'
            Server: true (bootstrap: false)
       Client Addr: 127.0.0.1 (HTTP: 8500, HTTPS: -1, DNS: 8600, RPC: 8400)
      Cluster Addr: 127.0.0.1 (LAN: 8301, WAN: 8302)
    Gossip encrypt: false, RPC-TLS: false, TLS-Incoming: false
             Atlas: <disabled>

==> Log data will now stream in as it occurs:

```
2016/10/21 16:00:22 [INFO] raft: Initial configuration (index=1): [{Suffrage:Voter ID:127.0.0.1:8300 Address:127.0.0.1:8300}]
2016/10/21 16:00:22 [INFO] raft: Node at 127.0.0.1:8300 [Follower] entering Follower state (Leader: "")
2016/10/21 16:00:22 [INFO] serf: EventMemberJoin: LM-AMS-14500281 127.0.0.1
2016/10/21 16:00:22 [INFO] consul: Adding LAN server LM-AMS-14500281 (Addr: tcp/127.0.0.1:8300) (DC: dc1)
2016/10/21 16:00:22 [INFO] serf: EventMemberJoin: LM-AMS-14500281.dc1 127.0.0.1
2016/10/21 16:00:22 [INFO] consul: Adding WAN server LM-AMS-14500281.dc1 (Addr: tcp/127.0.0.1:8300) (DC: dc1)
2016/10/21 16:00:22 [DEBUG] agent: pausing 50.098827ms before first invocation of redis-cli -p 6379 ping || exit 1
2016/10/21 16:00:22 [DEBUG] agent: pausing 957.557913ms before first invocation of redis-cli -p 6381 ping || exit 1
2016/10/21 16:00:22 [DEBUG] agent: pausing 819.904891ms before first invocation of redis-cli -p 6380 ping || exit 1
```

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x140782]

goroutine 72 [running]:
panic(0x6f4720, 0xc420012100)
    /usr/local/go/src/runtime/panic.go:500 +0x1a1
sync.(_RWMutex).RLock(0x0)
    /usr/local/go/src/sync/rwmutex.go:41 +0x22
github.com/hashicorp/consul/command/agent.(_CheckMonitor).check(0xc42025c770)
    /Users/pdekloe/repo/consul/src/github.com/hashicorp/consul/command/agent/check.go:160 +0x62
github.com/hashicorp/consul/command/agent.(_CheckMonitor).run(0xc42025c770)
    /Users/pdekloe/repo/consul/src/github.com/hashicorp/consul/command/agent/check.go:147 +0x1d0
created by github.com/hashicorp/consul/command/agent.(_CheckMonitor).Start
    /Users/pdekloe/repo/consul/src/github.com/hashicorp/consul/command/agent/check.go:125 +0xbf
%

**Comment by zbintliff** [comment] 2016-11-01 20:56
I was able to track it down to the `-dev` flag.

**Comment by slackpad** [comment] 2016-11-01 22:32
Thanks for opening an issue - can you share any details about what kind of configs you have setup in "etc/consul.d"?

**Comment by zbintliff** [comment] 2016-11-02 13:42
I'm running the docker container with no extra configuration. The command that works is:
```
docker run agent -server -dc poc -bootstrap-expect 5 -bind 0.0.0.0 -advertise  %eth0 -retry-join %other_host
```

The command that fails is:

```
docker run agent -server -dc poc -dev -bootstrap-expect 5 -bind 0.0.0.0 -advertise  %eth0 -retry-join %other_host
```

Only difference is -dev flag. Error trace is here:

```
Nov  1 20:47:42 ip-10-195-74-59 docker/consul-server[4054]: ==> WARNING: Expect Mode enabled, expecting 5 servers
Nov  1 20:47:42 ip-10-195-74-59 docker/consul-server[4054]: ==> Starting Consul agent...
Nov  1 20:47:42 ip-10-195-74-59 docker/consul-server[4054]: ==> Starting Consul agent RPC...
Nov  1 20:47:42 ip-10-195-74-59 docker/consul-server[4054]: panic: runtime error: invalid memory address or nil pointer dereference
Nov  1 20:47:42 ip-10-195-74-59 docker/consul-server[4054]: [signal 0xb code=0x1 addr=0x0 pc=0x966b95]
Nov  1 20:47:42 ip-10-195-74-59 docker/consul-server[4054]:
Nov  1 20:47:42 ip-10-195-74-59 docker/consul-server[4054]: goroutine 39 [running]:
Nov  1 20:47:42 ip-10-195-74-59 docker/consul-server[4054]: panic(0xcb9ec0, 0xc820010060)
Nov  1 20:47:42 ip-10-195-74-59 docker/consul-server[4054]: #011/goroot/src/runtime/panic.go:464 +0x3e6
Nov  1 20:47:42 ip-10-195-74-59 docker/consul-server[4054]: github.com/hashicorp/consul/vendor/github.com/hashicorp/raft-boltdb.(*BoltStore).LastIndex(0x0, 0x0, 0x0, 0x0)
Nov  1 20:47:42 ip-10-195-74-59 docker/consul-server[4054]: #011/gopath/src/github.com/hashicorp/consul/vendor/github.com/hashicorp/raft-boltdb/bolt_store.go:101 +0x45
Nov  1 20:47:42 ip-10-195-74-59 docker/consul-server[4054]: github.com/hashicorp/consul/consul.(*Server).maybeBootstrap(0xc820170780)
Nov  1 20:47:42 ip-10-195-74-59 docker/consul-server[4054]: #011/gopath/src/github.com/hashicorp/consul/consul/serf.go:195 +0x5d
Nov  1 20:47:42 ip-10-195-74-59 docker/consul-server[4054]: github.com/hashicorp/consul/consul.(*Server).lanNodeJoin(0xc820170780, 0x0, 0xc82014e9b0, 0x1, 0x1)
Nov  1 20:47:42 ip-10-195-74-59 docker/consul-server[4054]: #011/gopath/src/github.com/hashicorp/consul/consul/serf.go:158 +0x332
Nov  1 20:47:42 ip-10-195-74-59 docker/consul-server[4054]: github.com/hashicorp/consul/consul.(*Server).lanEventHandler(0xc820170780)
Nov  1 20:47:42 ip-10-195-74-59 docker/consul-server[4054]: #011/gopath/src/github.com/hashicorp/consul/consul/serf.go:41 +0x1a2
Nov  1 20:47:42 ip-10-195-74-59 docker/consul-server[4054]: created by github.com/hashicorp/consul/consul.NewServer
Nov  1 20:47:42 ip-10-195-74-59 docker/consul-server[4054]: #011/gopath/src/github.com/hashicorp/consul/consul/server.go:261 +0xfd3
```

**Comment by slackpad** [comment] 2016-11-03 16:57
Should be fixed by #2484.

**Comment by pascaldekloe** [comment] 2016-11-09 17:20
Are you joking @slackpad? Please reopen this issue.

Something like the following causes the crash.
```json
{
  "services": [
    {
      "id":"cfp-redis-6379",
      "name":"redis",
      "address":"127.0.0.1",
      "tags": ["type-redis-cfp"],
      "port":6379,
      "check": {"script": "redis-cli -p 6379 ping || exit 1", "interval": "1s"}
    }
  ]
}
```

**Comment by slackpad** [comment] 2016-11-09 17:27
@pascaldekloe thanks for the JSON, now I can reproduce your crash locally.

**Closed** 2016-11-09 17:52 UTC
Labels: bug, crash

**Comment by slackpad** [comment] 2016-11-09 17:53
Thanks for the poke @pascaldekloe - I hadn't carefully compared the stack traces and thought we were fixing the same issue. I've also updated our test environment to exercise this since it runs its script checks over in a Docker container and didn't hit this path, and our unit tests were properly setting up the mutex. Should be good now - please let me know if that's not the case!
