### ISSUE TITLE
Add consul acl subcommand

### ISSUE THREAD

**Issue by c4milo** [hashicorp/consul#3755] opened 2017-12-17 02:26 UTC
Just like in Nomad:  https://www.nomadproject.io/docs/commands/acl.html

This will make ACL bootstrapping much simpler.

**Comment by slackpad** [comment] 2018-01-05 06:23
Closing as a duplicate of https://github.com/hashicorp/consul/issues/3208.

**Closed by slackpad** 2018-01-05 06:23 UTC
Labels: enhancement, theme/cli-cleanup
