### ISSUE TITLE
Some tags not showing in UI

### ISSUE THREAD

**Issue by mgresser** [hashicorp/consul#4884] opened 2018-11-01 16:41 UTC
On consul 1.2.2 some services are only showing one tag in the list despite multiple tags being applied to the service. For example I have a service named "foo" with tags of "alpha", "beta" and "prod". In the consul UI service view I see only the alpha tag listed for this service. If I click on the service name in the UI then I see the complete tag list.

### Consul info for both Client and Server

```
output from client 'consul info' command here
```

agent:
	check_monitors = 0
	check_ttls = 0
	checks = 8
	services = 9
build:
	prerelease =
	revision = e716d1b5
	version = 1.2.2
consul:
	known_servers = 3
	server = false
runtime:
	arch = amd64
	cpu_count = 8
	goroutines = 52
	max_procs = 8
	os = linux
	version = go1.10.1
serf_lan:
	coordinate_resets = 0
	encrypted = false
	event_queue = 0
	event_time = 83
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 30961
	members = 845
	query_queue = 0
	query_time = 1

```
output from server 'consul info' command here
```

agent:
	check_monitors = 0
	check_ttls = 0
	checks = 1
	services = 1
build:
	prerelease =
	revision = e716d1b5
	version = 1.2.2
consul:
	bootstrap = true
	known_datacenters = 2
	leader = true
	leader_addr = 10.70.80.61:8300
	server = true
raft:
	applied_index = 1637744
	commit_index = 1637744
	fsm_pending = 0
	last_contact = 0
	last_log_index = 1637744
	last_log_term = 509
	last_snapshot_index = 1623482
	last_snapshot_term = 509
	latest_configuration = [{Suffrage:Voter ID:ef526f71-ed58-5d22-7bcb-9df02fb610a3 Address:10.70.80.61:8300} {Suffrage:Voter ID:ad6dc351-956f-90be-2ba6-46fc3c469dba Address:10.70.80.62:8300} {Suffrage:Voter ID:6e6410f6-ea46-3ec6-7380-754efbde2a0a Address:10.70.80.63:8300}]
	latest_configuration_index = 2128
	num_peers = 2
	protocol_version = 3
	protocol_version_max = 3
	protocol_version_min = 0
	snapshot_version_max = 1
	snapshot_version_min = 0
	state = Leader
	term = 509
runtime:
	arch = amd64
	cpu_count = 8
	goroutines = 2393
	max_procs = 8
	os = linux
	version = go1.10.1
serf_lan:
	coordinate_resets = 0
	encrypted = false
	event_queue = 0
	event_time = 83
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 30961
	members = 845
	query_queue = 0
	query_time = 1
serf_wan:
	coordinate_resets = 0
	encrypted = false
	event_queue = 0
	event_time = 1
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 220
	members = 6
	query_queue = 0
	query_time = 1

### Operating system and Environment details

CentOS 7

**Comment by pearkes** [comment] 2018-11-01 19:13
I believe this is caused by this bug, so I'm going to close this. Thank you for reporting!

https://github.com/hashicorp/consul/issues/4222

**Closed by pearkes** 2018-11-01 19:13 UTC

**Comment by mgresser** [comment] 2018-11-01 19:22
Seems possible. I would note that some of my services show multiple tags although I'm not sure any show every tag. Thanks for looking!

**Comment by pearkes** [comment] 2018-11-01 19:23
You might be seeing multiple tags when it is using different endpoints -- the outer list view would be the one that is wrong with that bug.

**Comment by pearkes** [comment] 2018-11-01 19:28
No problem thanks for reporting.
