### ISSUE TITLE
Updating a Service definition via the API does not update Checks

### ISSUE THREAD

**Issue by dantoml** [hashicorp/consul#5631] opened 2019-04-10 08:20 UTC
👋  hey folks

#### Overview of the Issue

When registering a Service with Consul, and then registering checks against that service, the Check is stored with a de-normalized version of a subset of the service state, specifically, the Service Tags.

If a Service is then updated (via a second) registration call, the checks do not then get updated, and the API returns stale data for the Checks. As far as I am aware, it's not possible to trigger an update to the check without affecting its status.

This shouldn't effect any Consul functionality afaik, but could be a UX issue when consul service registrations are managed by an orchestration tool (e.g Nomad).

#### Reproduction Steps

Steps to reproduce this issue:

1) Start a consul dev agent (or use an existing cluster of any size)
2) Register a Service that has ServiceTags with Consul using the API
3) Register a Check against the Service
4) Re-register the Service with different, or no ServiceTags
5) Observe that `curl http://127.0.0.1:8500/v1/health/service/{service-name} | jq '.[].Checks'` still returns outdated tags for the service

Let me know if you need an easier to run test case, and I can spend some time writing one up with the go sdk.

**Comment by pierresouchay** [comment] 2019-04-10 08:29
I think this is a duplicate of https://github.com/hashicorp/consul/issues/3869

For which I already proposed a fix: https://github.com/hashicorp/consul/pull/3965

**Comment by pearkes** [comment] 2019-04-11 02:04
I believe @pierresouchay is right that we can close this as a duplicate of #3869 and keep the conversation going there. 

Unfortunately as described by @preetapan in https://github.com/hashicorp/consul/pull/3965#issuecomment-374419145 there isn't a simple solution for this. We could definitely brainstorm alternatives for Nomad's use-case, or try to dig into the larger fix, but wanted to highlight that.

**Closed by pearkes** 2019-04-11 02:04 UTC
