### ISSUE TITLE
Non-blocking queries blocking unexpectedly

### ISSUE THREAD

**Issue by hottea773** [hashicorp/consul#12568] opened 2022-03-16 17:15 UTC
#### Overview of the Issue

If a blocking query to `v1/agent/connect/ca/leaf/machine?index=<index>` is cancelled, future requests with either no index, or `index=0` take 10 minutes to complete. 

#### Reproduction Steps

- Start a Consul cluster going using the docker image:
`docker run --network host -it -e CONSUL_BIND_INTERFACE=eth0 consul:1.11.4`
- Find the `X-Consul-Index` by doing a query to `localhost:8500/v1/agent/connect/ca/leaf/machine` (this will complete immediately).
- Make a request to `curl -v localhost:8500/v1/agent/connect/ca/leaf/machine?index=<X-Consul-Index>` this will block as expected.
- Cancel that query.
- Later requests to either `localhost:8500/v1/agent/connect/ca/leaf/machine` or `localhost:8500/v1/agent/connect/ca/leaf/machine?index=0` will block. 

### Consul info for both Client and Server

All I'm using is the standard `consul:1.11.4` docker image.

### Log Fragments

Log from consul image:
```
$ docker run --network host -it -e CONSUL_BIND_INTERFACE=eth0 consul:1.11.4
==> Found address '172.17.93.39' for interface 'eth0', setting bind option...
==> Starting Consul agent...
           Version: '1.11.4'
           Node ID: '100c9dfb-52ca-1987-8e86-5c9cbe68c684'
         Node name: 'DESKTOP-6JL1A0K'
        Datacenter: 'dc1' (Segment: '<all>')
            Server: true (Bootstrap: false)
       Client Addr: [0.0.0.0] (HTTP: 8500, HTTPS: -1, gRPC: 8502, DNS: 8600)
      Cluster Addr: 172.17.93.39 (LAN: 8301, WAN: 8302)
           Encrypt: Gossip: false, TLS-Outgoing: false, TLS-Incoming: false, Auto-Encrypt-TLS: false

==> Log data will now stream in as it occurs:

2022-03-16T17:00:25.881Z [INFO]  agent.server.raft: initial configuration: index=1 servers="[{Suffrage:Voter ID:100c9dfb-52ca-1987-8e86-5c9cbe68c684 Address:172.17.93.39:8300}]"
2022-03-16T17:00:25.881Z [INFO]  agent.server.raft: entering follower state: follower="Node at 172.17.93.39:8300 [Follower]" leader=
2022-03-16T17:00:25.881Z [INFO]  agent.server.serf.wan: serf: EventMemberJoin: DESKTOP-6JL1A0K.dc1 172.17.93.39
2022-03-16T17:00:25.882Z [INFO]  agent.server.serf.lan: serf: EventMemberJoin: DESKTOP-6JL1A0K 172.17.93.39
2022-03-16T17:00:25.882Z [INFO]  agent.router: Initializing LAN area manager
2022-03-16T17:00:25.882Z [INFO]  agent.server: Adding LAN server: server="DESKTOP-6JL1A0K (Addr: tcp/172.17.93.39:8300) (DC: dc1)"
2022-03-16T17:00:25.882Z [WARN]  agent: grpc: addrConn.createTransport failed to connect to {dc1-172.17.93.39:8300 0 DESKTOP-6JL1A0K <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp 172.17.93.39:0->172.17.93.39:8300: operation was canceled". Reconnecting...
2022-03-16T17:00:25.882Z [INFO]  agent.server: Handled event for server in area: event=member-join server=DESKTOP-6JL1A0K.dc1 area=wan
2022-03-16T17:00:25.882Z [INFO]  agent: Started DNS server: address=0.0.0.0:8600 network=udp
2022-03-16T17:00:25.882Z [INFO]  agent: Started DNS server: address=0.0.0.0:8600 network=tcp
2022-03-16T17:00:25.883Z [INFO]  agent: Starting server: address=[::]:8500 network=tcp protocol=http
2022-03-16T17:00:25.883Z [WARN]  agent: DEPRECATED Backwards compatibility with pre-1.9 metrics enabled. These metrics will be removed in a future version of Consul. Set `telemetry { disable_compat_1.9 = true }` to disable them.
2022-03-16T17:00:25.883Z [INFO]  agent: Started gRPC server: address=[::]:8502 network=tcp
2022-03-16T17:00:25.883Z [INFO]  agent: started state syncer
2022-03-16T17:00:25.883Z [INFO]  agent: Consul agent running!
2022-03-16T17:00:25.929Z [WARN]  agent.server.raft: heartbeat timeout reached, starting election: last-leader=
2022-03-16T17:00:25.929Z [INFO]  agent.server.raft: entering candidate state: node="Node at 172.17.93.39:8300 [Candidate]" term=2
2022-03-16T17:00:25.929Z [DEBUG] agent.server.raft: votes: needed=1
2022-03-16T17:00:25.929Z [DEBUG] agent.server.raft: vote granted: from=100c9dfb-52ca-1987-8e86-5c9cbe68c684 term=2 tally=1
2022-03-16T17:00:25.929Z [INFO]  agent.server.raft: election won: tally=1
2022-03-16T17:00:25.929Z [INFO]  agent.server.raft: entering leader state: leader="Node at 172.17.93.39:8300 [Leader]"
2022-03-16T17:00:25.929Z [INFO]  agent.server: cluster leadership acquired
2022-03-16T17:00:25.930Z [INFO]  agent.server: New leader elected: payload=DESKTOP-6JL1A0K
2022-03-16T17:00:25.932Z [INFO]  agent.leader: started routine: routine="federation state anti-entropy"
2022-03-16T17:00:25.932Z [INFO]  agent.leader: started routine: routine="federation state pruning"
2022-03-16T17:00:25.932Z [DEBUG] agent.server.autopilot: autopilot is now running
2022-03-16T17:00:25.932Z [DEBUG] agent.server.autopilot: state update routine is now running
2022-03-16T17:00:25.933Z [DEBUG] connect.ca.consul: consul CA provider configured: id=fb:50:9b:45:1a:65:15:c1:68:57:73:5f:da:cd:b8:0d:0f:e2:26:eb:68:66:43:11:85:9d:67:a9:7a:56:9c:b9 is_primary=true
2022-03-16T17:00:25.939Z [INFO]  connect.ca: initialized primary datacenter CA with provider: provider=consul
2022-03-16T17:00:25.939Z [INFO]  agent.leader: started routine: routine="intermediate cert renew watch"
2022-03-16T17:00:25.940Z [INFO]  agent.leader: started routine: routine="CA root pruning"
2022-03-16T17:00:25.940Z [INFO]  agent.leader: started routine: routine="CA root expiration metric"
2022-03-16T17:00:25.940Z [INFO]  agent.leader: started routine: routine="CA signing expiration metric"
2022-03-16T17:00:25.940Z [INFO]  agent.leader: started routine: routine="virtual IP version check"
2022-03-16T17:00:25.940Z [DEBUG] agent.server: successfully established leadership: duration=10.429795ms
2022-03-16T17:00:25.940Z [INFO]  agent.server: member joined, marking health alive: member=DESKTOP-6JL1A0K partition=default
2022-03-16T17:00:25.941Z [DEBUG] agent.leader: stopping routine: routine="virtual IP version check"
2022-03-16T17:00:25.941Z [DEBUG] agent.leader: stopped routine: routine="virtual IP version check"
2022-03-16T17:00:25.995Z [DEBUG] agent: Skipping remote check since it is managed automatically: check=serfHealth
2022-03-16T17:00:25.996Z [INFO]  agent: Synced node info
2022-03-16T17:00:25.996Z [DEBUG] agent: Node info in sync
2022-03-16T17:00:26.069Z [INFO]  agent.server: federation state anti-entropy synced
2022-03-16T17:00:26.414Z [DEBUG] agent: Skipping remote check since it is managed automatically: check=serfHealth
2022-03-16T17:00:26.414Z [DEBUG] agent: Node info in sync
2022-03-16T17:00:35.240Z [DEBUG] agent.http: Request finished: method=GET url=/v1/agent/connect/ca/leaf/machine from=127.0.0.1:37108 latency=1.35819ms
2022-03-16T17:00:47.598Z [INFO]  agent.http: Request cancelled: method=GET url=/v1/agent/connect/ca/leaf/machine?index=17 from=127.0.0.1:37200 error="context canceled"
2022-03-16T17:00:47.598Z [DEBUG] agent.http: Request finished: method=GET url=/v1/agent/connect/ca/leaf/machine?index=17 from=127.0.0.1:37200 latency=2.309456719s
2022-03-16T17:01:43.127Z [DEBUG] agent: Skipping remote check since it is managed automatically: check=serfHealth
2022-03-16T17:01:43.127Z [DEBUG] agent: Node info in sync
2022-03-16T17:02:25.884Z [DEBUG] agent.router.manager: Rebalanced servers, new active server: number_of_servers=1 active_server="DESKTOP-6JL1A0K.dc1 (Addr: tcp/172.17.93.39:8300) (DC: dc1)"
2022-03-16T17:02:25.885Z [DEBUG] agent.router.manager: Rebalanced servers, new active server: number_of_servers=1 active_server="DESKTOP-6JL1A0K (Addr: tcp/172.17.93.39:8300) (DC: dc1)"
2022-03-16T17:02:58.212Z [DEBUG] agent: Skipping remote check since it is managed automatically: check=serfHealth
2022-03-16T17:02:58.212Z [DEBUG] agent: Node info in sync
2022-03-16T17:04:27.115Z [DEBUG] agent.router.manager: Rebalanced servers, new active server: number_of_servers=1 active_server="DESKTOP-6JL1A0K.dc1 (Addr: tcp/172.17.93.39:8300) (DC: dc1)"
2022-03-16T17:04:37.695Z [DEBUG] agent: Skipping remote check since it is managed automatically: check=serfHealth
2022-03-16T17:04:37.695Z [DEBUG] agent: Node info in sync
2022-03-16T17:04:52.646Z [DEBUG] agent.router.manager: Rebalanced servers, new active server: number_of_servers=1 active_server="DESKTOP-6JL1A0K (Addr: tcp/172.17.93.39:8300) (DC: dc1)"
2022-03-16T17:05:56.988Z [DEBUG] agent: Skipping remote check since it is managed automatically: check=serfHealth
2022-03-16T17:05:56.988Z [DEBUG] agent: Node info in sync
2022-03-16T17:06:33.115Z [DEBUG] agent.router.manager: Rebalanced servers, new active server: number_of_servers=1 active_server="DESKTOP-6JL1A0K.dc1 (Addr: tcp/172.17.93.39:8300) (DC: dc1)"
2022-03-16T17:07:33.561Z [DEBUG] agent.router.manager: Rebalanced servers, new active server: number_of_servers=1 active_server="DESKTOP-6JL1A0K (Addr: tcp/172.17.93.39:8300) (DC: dc1)"
2022-03-16T17:07:35.282Z [DEBUG] agent: Skipping remote check since it is managed automatically: check=serfHealth
2022-03-16T17:07:35.282Z [DEBUG] agent: Node info in sync
2022-03-16T17:08:43.066Z [DEBUG] agent.router.manager: Rebalanced servers, new active server: number_of_servers=1 active_server="DESKTOP-6JL1A0K.dc1 (Addr: tcp/172.17.93.39:8300) (DC: dc1)"
2022-03-16T17:08:44.101Z [DEBUG] agent: Skipping remote check since it is managed automatically: check=serfHealth
2022-03-16T17:08:44.101Z [DEBUG] agent: Node info in sync
2022-03-16T17:10:17.479Z [DEBUG] agent.router.manager: Rebalanced servers, new active server: number_of_servers=1 active_server="DESKTOP-6JL1A0K (Addr: tcp/172.17.93.39:8300) (DC: dc1)"
2022-03-16T17:10:43.151Z [DEBUG] agent: Skipping remote check since it is managed automatically: check=serfHealth
2022-03-16T17:10:43.151Z [DEBUG] agent: Node info in sync
2022-03-16T17:10:45.289Z [DEBUG] agent.http: Request finished: method=GET url=/v1/agent/connect/ca/leaf/machine from=127.0.0.1:37284 latency=9m53.365815018s
```
Log from queries:
```
$ time curl -v localhost:8500/v1/agent/connect/ca/leaf/machine
*   Trying 127.0.0.1:8500...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8500 (#0)
> GET /v1/agent/connect/ca/leaf/machine HTTP/1.1
> Host: localhost:8500
> User-Agent: curl/7.68.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Content-Type: application/json
< Vary: Accept-Encoding
< X-Cache: MISS
< X-Consul-Default-Acl-Policy: allow
< X-Consul-Index: 17
< Date: Wed, 16 Mar 2022 17:00:35 GMT
< Content-Length: 1370
<
{
    "SerialNumber": "08",
    "CertPEM": "-----BEGIN CERTIFICATE-----<CERT_PEM>-----END CERTIFICATE-----\n",
    "PrivateKeyPEM": "-----BEGIN EC PRIVATE KEY-----<KEY>-----END EC PRIVATE KEY-----\n",
    "Service": "machine",
    "ServiceURI": "spiffe://c264aa4e-f84b-0313-fa7e-7d98ab7d28f4.consul/ns/default/dc/dc1/svc/machine",
    "ValidAfter": "2022-03-16T16:59:35Z",
    "ValidBefore": "2022-03-19T16:59:35Z",
    "CreateIndex": 17,
    "ModifyIndex": 17
}
* Connection #0 to host localhost left intact

real    0m0.010s
user    0m0.007s
sys     0m0.000s
$ time curl -v localhost:8500/v1/agent/connect/ca/leaf/machine?index=17
*   Trying 127.0.0.1:8500...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8500 (#0)
> GET /v1/agent/connect/ca/leaf/machine?index=17 HTTP/1.1
> Host: localhost:8500
> User-Agent: curl/7.68.0
> Accept: */*
>
^C

real    0m2.324s
user    0m0.007s
sys     0m0.007s
$ time curl -v localhost:8500/v1/agent/connect/ca/leaf/machine
*   Trying 127.0.0.1:8500...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8500 (#0)
> GET /v1/agent/connect/ca/leaf/machine HTTP/1.1
> Host: localhost:8500
> User-Agent: curl/7.68.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Content-Type: application/json
< Vary: Accept-Encoding
< X-Cache: MISS
< X-Consul-Default-Acl-Policy: allow
< X-Consul-Index: 17
< Date: Wed, 16 Mar 2022 17:10:45 GMT
< Content-Length: 1370
<
{
    "SerialNumber": "08",
    "CertPEM": "-----BEGIN CERTIFICATE-----<CERT_PEM>-----END CERTIFICATE-----\n",
    "PrivateKeyPEM": "-----BEGIN EC PRIVATE KEY-----<KEY>-----END EC PRIVATE KEY-----\n",
    "Service": "machine",
    "ServiceURI": "spiffe://c264aa4e-f84b-0313-fa7e-7d98ab7d28f4.consul/ns/default/dc/dc1/svc/machine",
    "ValidAfter": "2022-03-16T16:59:35Z",
    "ValidBefore": "2022-03-19T16:59:35Z",
    "CreateIndex": 17,
    "ModifyIndex": 17
}
* Connection #0 to host localhost left intact

real    9m53.387s
user    0m0.049s
sys     0m0.000s

**Comment by hottea773** [comment] 2022-03-16 17:51
FWIW I've done a binary chop and this seems to have been introduced between `1.10.6` and `1.10.7`

**Comment by Amier3** [comment] 2022-03-16 18:28
Hey @hottea773 

I see this is your first post here so welcome to the consul community 🎊 

Glancing at the changelog, looks like this could be related to this change in 1.10.7: 

> ca: fixes a bug that caused non blocking leaf cert queries to return the same cached response regardless of ca rotation or leaf cert expiry

We'll investigate this further as a possible regression and get back to you with what we find. Thank you for bringing this to our attention!

**Comment by kisunji** [comment] 2022-03-16 19:15
Duplicate of https://github.com/hashicorp/consul/issues/12048

**Comment by Amier3** [comment] 2022-03-16 21:30
Thanks for pointing that out @kisunji , going to close this one out in favor of #12048 since it has an associated PR that's in draft 👍

**Closed by Amier3** 2022-03-16 21:30 UTC
Labels: type/bug, theme/connect, theme/certificates
