### ISSUE TITLE
Panic: log not found error when starting consul agent

### ISSUE THREAD

**Issue by harika224121** [hashicorp/consul#5190] opened 2019-01-04 19:17 UTC
Hi, 
 We are currently running our consul server with version 0.8.4. Now, we are testing upgrade of consul version from 0.8.4 to 1.3.0. As part of this, We have upgraded our consul server version from 0.8.4 to 1.3.0 and we also wanted to test whether we can downgrade the version back to 0.8.4. So, when we tried to downgrade it we are getting the error Panic: log not found.

![consul-error-downgrade](https://user-images.githubusercontent.com/9380139/50705724-97929d00-1010-11e9-8831-35e719deca11.PNG)

I found that the solution for this error is to delete the raft.db file under the data directory but we are not willing to delete the raft file since we might lose all the data regarding the cluster state, Services registered, KV pairs etc., so, can anyone please help us with an alternative for this issue.

**Comment by pearkes** [comment] 2019-01-04 19:20
Sorry about this. I think this is a duplicate of https://github.com/hashicorp/consul/issues/2933. Can you try snapshotting and recovering after removal of that file? 

https://www.consul.io/docs/guides/backup.html

Otherwise that issue is the right place to discuss this bug.

**Closed by pearkes** 2019-01-04 19:20 UTC
