### ISSUE TITLE
DNS Query response customization

### ISSUE THREAD

**Issue by VaradDeolankar** [hashicorp/consul#1089] opened 2015-07-07 13:44 UTC
The HTTP API provides a JSON response which contains service specific labels as well. So you get the information, that you registered the service with back again. Is it possible to retrieve that information back again by querying using the DNS interface.? SRV record returns only port and host. what about the Tags? can i retrieve them using a DNS query?

**Comment by ryanuber** [comment] 2015-07-07 15:23
@VaradDeolankar you cannot retrieve the tags using the DNS interface, but you can filter results by them. Take a look [here](https://consul.io/docs/agent/dns.html), specifically the "standard lookup" section. It might not be exactly what you were looking for. If you really need to retrieve the tags for a given service, you can use the HTTP API to do that.

**Comment by VaradDeolankar** [comment] 2015-07-08 04:27
But unlike the DNS interface, the HTTP API does not provide load balancing through randomization or any other method Right? We wanted to make use of that feature as well. Hence, we had decided to use the DNS interface in the first place. So any suggestions?

**Comment by ryanuber** [comment] 2015-07-08 05:43
@VaradDeolankar the randomization in the DNS responses is in no way special. You can pick any random entry you receive from the API response if you query the /v1/health/service endpoint and use the `?passing` flag to filter the result down to only healthy nodes. If your requirement is to retrieve tag values, then currently the only way to do this is using the HTTP API, and as far as I know, we don't have any plans to support returning them from the DNS interface.

**Comment by VaradDeolankar** [comment] 2015-07-08 07:41
A service discovery solution that leverages DNS must allow users to configure and retrieve following :
•	PTR - used to map service types to named service instances.
•	SRV - used to provide location and port for service instances.
•	TXT - used to provide additional meta data about service instances.


But, Consul only supports “A” record that merely returns the address and SRV record, that returns the host and port.
So, there are no plans regarding this?

**Comment by ryanuber** [comment] 2015-07-14 00:21
Sorry, what I meant was more that we just don't support it currently, and hadn't really planned the feature. It's possible that we could return each service tag as a separate TXT record. I'll mark this as an enhancement for now.

**Comment by VaradDeolankar** [comment] 2015-07-14 09:52
Thanks a lot :)

**Comment by sodre** [comment] 2017-01-30 17:04
@ryanuber 
I would also like to see the option to attach a custom TXT record and support RFC 2782 at the *domain* level, i.e. answer to look-ups of _<service>._<protocol>[.service][.datacenter][.domain] for SVR and _<service>[.service][.datacenter][.domain] for TXT.

The use case in mind is for a [kerberized cluster using only DNS](http://web.mit.edu/Kerberos/krb5-1.5/krb5-1.5.4/doc/krb5-install/Hostnames-for-the-Master-and-Slave-KDCs.html) for realm and service discovery.

**Comment by sodre** [comment] 2017-01-30 18:58
PR #2690 adds support for SRV queries at the datacenter level. @ryanuber, can you review is and see if it is okay?

**Comment by slackpad** [comment] 2017-05-02 22:37
I'm going to close this as a duplicate of #2709 since there's some more recent discussion over there.

**Closed by slackpad** 2017-05-02 22:37 UTC
Labels: enhancement, post-0.9
