### ISSUE TITLE
DNS Result Inconsistencies

### ISSUE THREAD

**Issue by krushmike** [hashicorp/consul#4192] opened 2018-06-04 18:37 UTC
We are currently using Consul v1.0.6.  Our servers are setup to use a Consul VIP (with five Consul nodes underneath) as the first hop for DNS.  Anything not resolved locally in Consol gets forwarded out to Windows DNS servers.  When trying to resolve a service name, such as `consul.service.consul`, sometimes we get Consul cluster members from the local cluster and other times from another Cluster in another Consul data center.  The two data centers are federated, but I am not sure why `consul.service.consul` would bring back Consul nodes from the other data center and not the data center the agent is a part of?

```
2018/06/04 11:04:15 [DEBUG] dns: recurse RTT for {consul.service.consul.[removed].[removed]. 1 1} (1.084ms)
2018/06/04 11:04:15 [DEBUG] dns: request for {consul.service.consul.[removed].[removed]. 1 1} (udp) (10.2905ms) from client 10.70.185.21:27096 (udp)
2018/06/04 11:04:15 [DEBUG] dns: recurse RTT for {consul.service.consul.[removed].[removed]. 28 1} (1.1417ms)
2018/06/04 11:04:15 [DEBUG] dns: request for {consul.service.consul.[removed].[removed]. 28 1} (udp) (1.9034ms) from client 10.70.184.21:23344 (udp)
2018/06/04 11:04:15 [DEBUG] dns: request for {consul.service.consul. 28 1} (3.033ms) from client 10.70.185.21:35398 (udp)
```
You can see where it went to the primary data center first, 10.70.184.21:23344 and then went to the second data center second, 10.70.185.21:35398.  Sometimes we get the correct group of Consul servers for the associated data center and other times not for the queried service.  Is Federation causing this or is this the expected behavior?  I would think Consul DNS should **always** return the IP's for the local service first before going to another data center.

**Comment by krushmike** [comment] 2018-06-04 19:01
If I specify the data center specifically in the name, I get the correct IP's back:

Name:    consul.service.phx2.consul
Addresses:  10.70.185.32
          10.70.185.34
          10.70.185.30

And:

Name:    consul.service.phx1.consul
Addresses:  10.70.184.34
          10.70.184.32
          10.70.184.33

If I query without the data center (consul.service.consul), I get inconsistent results mixing between phx1 and phx2.  Shouldn't Consul return the closest result instead of a mix between two data centers?

**Comment by krushmike** [comment] 2018-06-04 19:06
Found this in the docs as well:

`The datacenter is an optional part of the FQDN: if not provided, it defaults to the datacenter of the agent.`

This does not appear to be happening.

**Comment by krushmike** [comment] 2018-06-04 19:28
Think we may have it figured out.  Both PHX1 and PHX2 are on /23 networks with the same gateway.  Guessing this is causing issue when routing properly out of the NetScaler.

**Comment by mkeeler** [comment] 2018-06-04 19:37
@krushmike I am going to go ahead and close the issue since it looks like you figured it out. I did double check a few things and if no datacenter is specified Consul will default it to the datacenter of the agent handling the DNS request.

Also you shouldn't see the logs for "...recurse RTT..." except for queries that need to be recursively handled. It looks like your Consul instances are not configured with an alternative domain but some of your queries seem to be for alternative domains "consul.service.consul.[removed].[removed]". These queries are not being handled by Consul but are forwarded to your upstream recursors.

**Comment by krushmike** [comment] 2018-06-04 19:49
I am not entirely sold this is the issue to be honest, so I am not sure we should close quite yet.  It seems as if Consul is not defaulting to the datacenter of the agent.  

An alternate domain has not been specified, so I am assuming Consul is defaulting to the Windows domain in which the server is on which is where `.[removed].[removed]` comes from.  It seems as if Consul is traversing through other names before resolving `consul.service.consul`.  What would cause Consul to switch between the two below from the same source machine?

2018/06/04 11:44:56 [DEBUG] dns: request for {consul.service.consul. 28 1} (0s) from client **10.70.185.21**:55655 (udp)

And 

2018/06/04 11:49:11 [DEBUG] dns: request for {consul.service.consul. 28 1} (0s) from client **10.70.184.21**:16692 (udp)

**Comment by mkeeler** [comment] 2018-06-04 20:01
@krushmike The "client" in those logs is the IP of the system issuing the DNS requests. Not the result of the query. So it would seem you have both the 10.70.185.21 and 10.70.184.21 systems configured to use that one consul agent for DNS resolution.

**Comment by krushmike** [comment] 2018-06-04 20:14
The 10.70.185.21 and 10.70.184.21 are the SNIP's on the NetScaler or the subnet IP for the corresponding networks on the NetScaler.  Since this is a /23, which combines both 10.70.184.x and 10.70.185.x, I am concerned this may be causing an issue.  However, if I remove all Consul nodes but one and trace Consul, I can see where 184 and 185 are responding to DNS which is odd.  I would generally expect to only see 184, but I am doing further testing.  

Will keep you updated and thanks for the quick response!

**Comment by krushmike** [comment] 2018-06-04 20:41
You can see the network for 10.70.184.20 is returning Consul nodes for the query `consul.service.consul` of the incorrect IP's.  Those should be 10.70.184.x addresses.

4618	12.109338352	10.73.36.36	10.70.184.20	DNS	116	Standard query 0x0004 A consul.service.consul

4619	12.109346100	10.70.184.20	10.73.36.36	DNS	164	Standard query response 0x0004 A consul.service.consul A **10.70.185.32 A 10.70.185.31 A 10.70.185.33**

Now, I put one Consul node on native port 53 so I could get to it via nslookup from another box.  Doing this and bypassing the NetScaler, I get the correct IP's back every time.  So, I am very suspicious of the NetScaler configuration at this point.

**Comment by mkeeler** [comment] 2018-06-04 20:46
Yeah, it sounds like the DNS query could be going to the wrong agent. When you do a few queries and get different results did you correlate each query to a log message one one of the consul agents?

**Comment by krushmike** [comment] 2018-06-05 13:25
It appears the default DNS policy on our NetScalers is to cache.  This was disabled and now all machines appear to be resolving the service name properly now.  Question is, how did records from the other datacenter get cached.  At one point, we had some cross-pollination issues between our two datacenters which may have inadvertently introduced cluster IP's from the other datacenter in to the DNS records.  Simply a guess at this point, but I _think_ we are in good shape.

If this creeps up again, a deeper dive will be necessary.  Thank you for your assistance @mkeeler!

**Comment by mkeeler** [comment] 2018-06-05 16:19
@krushmike Not knowing much about NetScalers and how they handle DNS its hard to say what the root cause would be. I guess the two possibilities are that the 1) Consul agent in one DC was serving out records for IPs that were supposed to be in a different DC (cross polination issues) or 2) that the NetScaler queried and agent in the second DC at some point and cached its results. 

One thing you may want to think about is that the NetScaler hopefully shouldn't cache for longer than the TTL in the DNS response. Unless you configured the DNS TTLs for Consul they should be defaulting to having a 0 TTL and prevent caching. Maybe the 0 TTL could be tripping up the NetScaler? Again I have no experience with NetScalers so these are all shots in the dark.

**Closed** 2018-06-06 13:38 UTC
