### ISSUE TITLE
consul nested key isn't created properly 

### ISSUE THREAD

**Issue by arnoldyahad** [hashicorp/consul#5124] opened 2018-12-20 13:39 UTC
#### Overview of the Issue

when creating a nested key the prefix doesnt get a null value
its a problem with most clients ( ruby client, python-consul , CURL) 

#### Reproduction Steps
using consul 1.4.0 

using the UI : 
create a new prefix+nested key in the ui:
test/example

( and now when you try to 
curl http://127.0.0.1:8500/v1/kv/consul-template/test/ )
it wont appear. 

only if you create
test/ 
it will appear 

### Consul info for both Client and Server

<details>
  <summary>Client info</summary>

```
agent:
	check_monitors = 0
	check_ttls = 3
	checks = 3
	services = 3
build:
	prerelease =
	revision = 48d287ef
	version = 1.2.3
consul:
	known_servers = 3
	server = false
runtime:
	arch = amd64
	cpu_count = 2
	goroutines = 58
	max_procs = 2
	os = linux
	version = go1.10.1
serf_lan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 5
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 36
	member_time = 12338
	members = 71
	query_queue = 0
	query_time = 1
```

</details>

<details>
  <summary>Server info</summary>

```
agent:
	check_monitors = 0
	check_ttls = 0
	checks = 0
	services = 0
build:
	prerelease =
	revision = 0bddfa23
	version = 1.4.0
consul:
	acl = disabled
	bootstrap = false
	known_datacenters = 1
	leader = false
	leader_addr = 10.195.8.31:8300
	server = true
raft:
	applied_index = 1439960
	commit_index = 1439960
	fsm_pending = 0
	last_contact = 25.620226ms
	last_log_index = 1439960
	last_log_term = 5
	last_snapshot_index = 1433761
	last_snapshot_term = 5
	latest_configuration = [{Suffrage:Voter ID:7fb1fce7-5439-c61b-fab6-4e6c84f2f921 Address:10.195.1.50:8300} {Suffrage:Voter ID:9c054f2e-408a-5802-ede5-02263bc2215e Address:10.195.8.31:8300} {Suffrage:Voter ID:97533334-a890-a6c4-61c6-80b5c70a7ecd Address:10.195.6.136:8300}]
	latest_configuration_index = 35928
	num_peers = 2
	protocol_version = 3
	protocol_version_max = 3
	protocol_version_min = 0
	snapshot_version_max = 1
	snapshot_version_min = 0
	state = Follower
	term = 5
runtime:
	arch = amd64
	cpu_count = 4
	goroutines = 194
	max_procs = 4
	os = linux
	version = go1.11.1
serf_lan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 5
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 36
	member_time = 12338
	members = 71
	query_queue = 0
	query_time = 1
serf_wan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 1
	failed = 2
	health_score = 7
	intent_queue = 0
	left = 0
	member_time = 19
	members = 3
	query_queue = 0
	query_time = 1
```

</details>

**Comment by johncowen** [comment] 2019-01-14 12:48
Hi @arnoldyahad 

I'm going to close this issue, but please feel free to reopen if you feel we should look further.

Related to this, I'll add a link to one of our resources here which goes into more detail on the KV store.

https://learn.hashicorp.com/consul/getting-started/kv

I'm also going to mention this to our education team to see if we can add more detail relating to this specific issue there.

Thanks,

John

**Closed by johncowen** 2019-01-14 12:48 UTC
Labels: ui, waiting-reply

**Comment by banks** [comment] 2019-01-14 14:34
To clarify. Consul KV treats keys as opaque strings just like S3. Many people use `/` as a delimiter to organise them and we have a prefix-delimited list API that allows you to efficiently iterate lots of keys using _any delimiter_ as a separator (`/` is the default choice).

But since Each KV pair is totally unrelated and there is actually no hierarchy in Consul itself, the existence of a key named `/foo/bar/baz` _does not imply_ that `/foo/bar` exists. The listing API is listing partial-prefixes at which actual keys exist not real "folders".

As John mentioned, we can see that our KV intro docs could maybe make this a bit more explicit but it's working as intended!

Hope that helps!
