### ISSUE TITLE
loki -> consul -> panic: leave after shutdown

### ISSUE THREAD

**Issue by jsoref** [hashicorp/consul#10971] opened 2021-09-01 17:09 UTC
When filing a bug, please include the following headings if possible. Any example text in this template can be deleted.

#### Overview of the Issue

We've been running loki w/ consul for months and Google Cloud Error monitoring just reported this error to us this week.

#### Reproduction Steps

Steps to reproduce this issue, eg:

1. Set up loki in a modular configuration: https://github.com/GarnerCorp/modular-loki-helm
2. Leave it alone for months
3. Get an error notification from Google Cloud Platform - Error Reporting
4. Switch to the Google Cloud Platform - Logs Explorer to get a more detailed view of the sequence of events.

### Consul info for both Client and Server

<details>
  <summary>Client info</summary>

```
```

Afaiu, this is the main consul instance, so the information would be identical to the information below

</details>

<details>
  <summary>Server info</summary>

```
agent:
	check_monitors = 0
	check_ttls = 0
	checks = 0
	services = 0
build:
	prerelease =
	revision = a42ded47
	version = 1.5.3
consul:
	acl = disabled
	bootstrap = true
	known_datacenters = 1
	leader = true
	leader_addr = 10.4.8.5:8300
	server = true
raft:
	applied_index = 34734
	commit_index = 34734
	fsm_pending = 0
	last_contact = 0
	last_log_index = 34734
	last_log_term = 2
	last_snapshot_index = 32831
	last_snapshot_term = 2
	latest_configuration = [{Suffrage:Voter ID:f7d3b7d1-f978-32ef-57fc-120bdce5dfed Address:10.4.8.5:8300}]
	latest_configuration_index = 1
	num_peers = 0
	protocol_version = 3
	protocol_version_max = 3
	protocol_version_min = 0
	snapshot_version_max = 1
	snapshot_version_min = 0
	state = Leader
	term = 2
runtime:
	arch = amd64
	cpu_count = 4
	goroutines = 105
	max_procs = 4
	os = linux
	version = go1.12.1
serf_lan:
	coordinate_resets = 0
	encrypted = false
	event_queue = 1
	event_time = 2
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 1
	members = 1
	query_queue = 0
	query_time = 1
serf_wan:
	coordinate_resets = 0
	encrypted = false
	event_queue = 0
	event_time = 1
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 1
	members = 1
	query_queue = 0
	query_time = 1
```

Note that this information was captured as I created this bug report, not at the time of the event, as at that time, the pod was dying.

</details>

### Operating system and Environment details

`Linux loki-modular-loki-consul-579c44dc78-h2w6h 5.4.120+ #1 SMP Tue Jun 22 14:53:20 PDT 2021 x86_64 Linux`

Yes, this pod is a different pod, but the configuration is roughly equivalent as the specs are controlled by a helm chart that hasn't changed.

Pods all live together in a single namespace in a single GKE regional cluster.

### Log Fragments

|Severity|Time|Monitoring|Event|
-|-|-|-
|Error|2021-09-01 04:55:36.771 EDT|sidekick|2021/09/01 08:55:36 Cannot access ReplicaSet (metrics/loki-modular-loki-consul-579c44dc78)
|Info|2021-09-01 04:55:37.000 EDT|loki-modular-loki-consul-579c44dc78-j5plk|"Stopping container statsd-exporter"
|Info|2021-09-01 04:55:37.000 EDT|loki-modular-loki-consul-579c44dc78-j5plk|"Stopping container sidekick"
|Info|2021-09-01 04:55:37.000 EDT|loki-modular-loki-consul-579c44dc78-j5plk|"Stopping container consul"
|Info|2021-09-01 04:55:37.000 EDT|loki-modular-loki-consul-579c44dc78-j5plk|"Stopping container consul-exporter"
|Info|2021-09-01 04:55:37.643 EDT|consul| 2021/09/01 08:55:37 [INFO] agent: Caught signal: terminated
|Info|2021-09-01 04:55:37.644 EDT|consul| 2021/09/01 08:55:37 [INFO] agent: Gracefully shutting down agent...
|Info|2021-09-01 04:55:37.662 EDT|consul| 2021/09/01 08:55:37 [INFO] agent: Caught second signal terminated. Exiting
|Info|2021-09-01 04:55:37.662 EDT|consul| 2021/09/01 08:55:37 [INFO] agent: Requesting shutdown
|Info|2021-09-01 04:55:37.779 EDT|consul| 2021/09/01 08:55:37 [INFO] consul: server starting leave
|Info|2021-09-01 04:55:37.800 EDT|consul| 2021/09/01 08:55:37 [INFO] consul: shutting down server
|Info|2021-09-01 04:55:37.801 EDT|consul| 2021/09/01 08:55:37 [WARN] serf: Shutdown without a Leave
|Info|2021-09-01 04:55:37.801 EDT|consul| 2021/09/01 08:55:37 [WARN] serf: Shutdown without a Leave
|Error|2021-09-01 04:55:37.815 EDT|consul|panic: leave after shutdown goroutine 28065700 [running]: github.com/hashicorp/memberlist.(*Memberlist).Leave(0xc0005a9680, 0x12a05f200, 0x0, 0x0) /go/pkg/mod/github.com/hashicorp/memberlist@v0.1.4/memberlist.go:568 +0x42e github.com/hashicorp/serf/serf.(*Serf).Leave(0xc000486c00, 0xc0003883e0, 0xe) /go/pkg/mod/github.com/hashicorp/serf@v0.8.2/serf/serf.go:689 +0x1fc github.com/hashicorp/consul/agent/consul.(*Server).Leave(0xc0006f4700, 0x329e201, 0xc000eb5130) /home/circleci/project/consul/agent/consul/server.go:885 +0x65b github.com/hashicorp/consul/agent.(*Agent).Leave(...) /home/circleci/project/consul/agent/agent.go:1615 github.com/hashicorp/consul/command/agent.(*cmd).run.func2(0xc0003e2240, 0xc00004f500, 0xc0014daf00) /home/circleci/project/consul/command/agent/agent.go:370 +0x39 created by github.com/hashicorp/consul/command/agent.(*cmd).run /home/circleci/project/consul/command/agent/agent.go:369 +0x1809|

```
insertId: "pyz7u4k44m93hz5r"
labels: {
compute.googleapis.com/resource_name: "gke-default-cluster-default-pool-cbfd1660-plpv"
k8s-pod/app_kubernetes_io/component: "consul"
k8s-pod/app_kubernetes_io/instance: "loki"
k8s-pod/app_kubernetes_io/managed-by: "Helm"
k8s-pod/app_kubernetes_io/name: "modular-loki"
k8s-pod/app_kubernetes_io/version: "1.6.1"
k8s-pod/helm_sh/chart: "modular-loki-1.0.3"
k8s-pod/pod-template-hash: "579c44dc78"
}
logName: "projects/.../logs/stderr"
receiveTimestamp: "2021-09-01T08:55:55.901700006Z"
resource: {
labels: {
cluster_name: "default-cluster"
container_name: "consul"
location: "northamerica-northeast1"
namespace_name: "metrics"
pod_name: "loki-modular-loki-consul-579c44dc78-j5plk"
project_id: "..."
}
type: "k8s_container"
}
severity: "ERROR"
textPayload: "panic: leave after shutdown

goroutine 28065700 [running]:
github.com/hashicorp/memberlist.(*Memberlist).Leave(0xc0005a9680, 0x12a05f200, 0x0, 0x0)
	/go/pkg/mod/github.com/hashicorp/memberlist@v0.1.4/memberlist.go:568 +0x42e
github.com/hashicorp/serf/serf.(*Serf).Leave(0xc000486c00, 0xc0003883e0, 0xe)
	/go/pkg/mod/github.com/hashicorp/serf@v0.8.2/serf/serf.go:689 +0x1fc
github.com/hashicorp/consul/agent/consul.(*Server).Leave(0xc0006f4700, 0x329e201, 0xc000eb5130)
	/home/circleci/project/consul/agent/consul/server.go:885 +0x65b
github.com/hashicorp/consul/agent.(*Agent).Leave(...)
	/home/circleci/project/consul/agent/agent.go:1615
github.com/hashicorp/consul/command/agent.(*cmd).run.func2(0xc0003e2240, 0xc00004f500, 0xc0014daf00)
	/home/circleci/project/consul/command/agent/agent.go:370 +0x39
created by github.com/hashicorp/consul/command/agent.(*cmd).run
	/home/circleci/project/consul/command/agent/agent.go:369 +0x1809"
timestamp: "2021-09-01T08:55:37.815463418Z"
```

**Comment by dnephin** [comment] 2021-09-01 17:27
Thank you for the bug report! I notice the Consul version is 1.5.3. That version is quite old now. We only release bug fixes for the last 3 "major" versions, which is currently 1.10.x, 1.9.x, and 1.8x. 

It looks like the `values.yaml` has a field for the Consul version. Would it be possible to set that to use a newer version?

I wasn't able to find other reports of this problem, so I'm not sure if it's fixed, but it does appear to be a rare. If you are able to reproduce the problem on a more recent version I can take a closer look.

I did also notice this in the logs you provided:

```
Info | 2021-09-01 04:55:37.643 EDT | consul | 2021/09/01 08:55:37 [INFO] agent: Caught signal: terminated
Info | 2021-09-01 04:55:37.644 EDT | consul | 2021/09/01 08:55:37 [INFO] agent: Gracefully shutting down agent...
Info | 2021-09-01 04:55:37.662 EDT | consul | 2021/09/01 08:55:37 [INFO] agent: Caught second signal terminated. Exiting
```

It seems like kubernetes is only giving Consul a few milliseconds to gracefully shutdown. Is there an option to give it more time? I wonder if that second forceful shutdown causes some defer to fire which leads to the "leave after shutdown" problem.

**Comment by jkirschner-hashicorp** [comment] 2021-09-02 19:45
@jsoref: it might be worth posting on the loki repository, to see if anyone there has encountered something similar (I didn't see anything obvious looking through their issue history).

Regarding the fast shutdown time, it might be worth looking at [loki's `graceful_shutdown_timeout` configuration](graceful_shutdown_timeout) or [k8s's `terminationGracePeriodSeconds` pod configuration](https://cloud.google.com/blog/products/containers-kubernetes/kubernetes-best-practices-terminating-with-grace).

**Comment by jsoref** [comment] 2021-09-02 19:58
@jkirschner-hashicorp: I think your first link is broken?

**Comment by jkirschner-hashicorp** [comment] 2021-09-02 20:01
Fixed. Not sure how that happened!

**Comment by jsoref** [comment] 2021-09-02 20:22
I might post there, since we've forked the helm chart, and I didn't see anything obvious in their repository issues either, it didn't seem to make much sense. (We're also almost certainly behind wrt the loki stack as well...)

I'll see about both trying to upgrade consul and bumping `terminationGracePeriodSeconds` a bit. I'm not sure if we'll look at the `graceful_shutdown_timeout` option (the documentation doesn't seem to be particularly helpful, so, we'd have to talk to a human, and I'm not sure it's worth it).

Not sure when we'll be able to provide more feedback. It was a pretty odd thing to suddenly happen after running silently for a fairly long time. (Hopefully we'll at least update this ticket when we've successfully deployed a newer version of consul.)

**Comment by jkirschner-hashicorp** [comment] 2021-09-13 21:01
Hi @jsoref,

> Not sure when we'll be able to provide more feedback. It was a pretty odd thing to suddenly happen after running silently for a fairly long time. (Hopefully we'll at least update this ticket when we've successfully deployed a newer version of consul.)

I'm going to close this for now, but please reopen if it reoccurs in a newer version of Consul (ideally 1.9+) or you discover reproduction steps. Thanks!

**Closed by jkirschner-hashicorp** 2021-09-13 21:01 UTC
Labels: type/bug, type/crash
