### ISSUE TITLE
Cannot access consul web-ui from other http-base location

### ISSUE THREAD

**Issue by megastallman** [hashicorp/consul#4122] opened 2018-05-14 14:39 UTC
#### Overview of the Issue

I can successfully use Consul web-ui when binding it to kubernetes hostPort, accessing it the way like:
```
http://host:8500
```
But cannot reach consul when wrapping it with a service and an ingress controller as follows:
```
http://ingresshost/consul
``` 
The Chrome devtools show 200 and 404.

### Operating system and Environment details

Kubernetes, Openshift. HA-Proxy-based ingress-controller.

**Comment by megastallman** [comment] 2018-05-14 14:59
I've just tried to overwrite the base path with nginx-pod like this:
```
    server {
      listen 80;
      root /usr/share/nginx/www;
      index index.html index.htm;
      location /consul/ {
        rewrite ^/consul/(.*) /$1 break;
        proxy_pass http://consul:8500/;
        proxy_set_header   Host $host;
      }
    }

```
And got the /ui redirect which does not exist on my ingress controller. It should be /consul/ui instead.

**Comment by pearkes** [comment] 2018-07-26 21:12
Looks like this is a duplicate of https://github.com/hashicorp/consul/issues/1382 and https://github.com/hashicorp/consul/issues/1930. Please see those issues for more information.

**Closed by pearkes** 2018-07-26 21:12 UTC
Labels: question
