### ISSUE TITLE
io Discard in API

### ISSUE THREAD

**Issue by renanbastos93tc** [hashicorp/consul#10524] opened 2021-06-29 19:11 UTC
#### Overview of the Issue

I updated the package to 1.9.x, but my old version was 1.8.1 then the change was in this line https://github.com/hashicorp/consul/commit/e72a703041dc265bd017da0a5ee7807647f803b0#diff-bf98d5fab5bcfabded9769069e7318683f549ec91cff84c5f87a9ae3a3ca3d8dR1072

#### Reproduction Steps

```bash
go get -u github.com/hashicorp/consul
go mod tidy
...
# output: /go/pkg/mod/github.com/hashicorp/consul/api@v1.9.0/api.go:1072:17: undefined: io.Discard
# script returned exit code 2
```

**Comment by dnephin** [comment] 2021-06-29 19:20
Thanks for reporting this issue! I believe this is a duplicate of #10470.

We'll be tagging a v1.9.1 release of the `api` module today.

**Comment by dnephin** [comment] 2021-06-29 20:24
v1.9.1 has been tagged: we have tagged v1.9.1 for the api: https://github.com/hashicorp/consul/releases/tag/api%2Fv1.9.1

**Closed by dnephin** 2021-06-29 20:24 UTC
