### ISSUE TITLE
Can consul high i/o rate cause Too many open files error?

### ISSUE THREAD

**Issue by igal-stratoscale** [hashicorp/consul#2086] opened 2016-06-02 15:40 UTC
We have a consul cluster (0.6.4) with 3 servers.
Consul uses HDD as storage device and we notice it has high I/O rate (4M/s displayed by iotop). 

At certain point, seems like consul loosing a leader, and then it fails with too many open files error.
And we see that the disk is at 100% busy and high latency.
How can we know what causes such high i/o rate, and can it really cause to the mentioned above error?

Consul info:
 agent:
    check_monitors = 4
    check_ttls = 29
    checks = 33
    services = 33
build:
    prerelease = 
    revision = 26a0ef8c
    version = 0.6.4
consul:
    known_servers = 3
    server = false
runtime:
    arch = amd64
    cpu_count = 12
    goroutines = 190
    max_procs = 12
    os = linux
    version = go1.6
serf_lan:
    encrypted = false
    event_queue = 0
    event_time = 21
    failed = 0
    intent_queue = 0
    left = 0
    member_time = 8
    members = 8
    query_queue = 0
    query_time = 1

**Comment by slackpad** [comment] 2016-06-02 15:57
Hi @igal-stratoscale servers sync the disk when committing new write log entries through Raft, so a heavy write load to Consul can cause a lot of disk i/o. That write rate seems fairly high. If you pull [telemetry](https://www.consul.io/docs/agent/telemetry.html) there might be some insight there. Look for telemetry with names including "consul.fsm" and the counts there will give you how many of each log type are being committed in that interval, which may point to something that's churning rapidly in the cluster. Consul stores all its data in RAM as well, so you'll also want to make sure you have enough RAM and aren't swapping.

The high disk i/o doesn't seem like it should be related to file descriptors. Running something like `sudo lsof -n -P` should shed light on what's happening there. That's usually caused by a client rapidly making HTTP connections and not closing them, as could happen with earlier versions of the Go API client, for example.

**Comment by slackpad** [comment] 2016-06-02 18:27
@igal-stratoscale there's also https://github.com/hashicorp/consul/issues/907, which could be related.

**Comment by slackpad** [comment] 2016-06-02 18:28
If you are hitting that it might be a feedback loop where the disk i/o leads to slowdown handling incoming connections which leads to exhausting fds, hitting that bug.

**Comment by rom-stratoscale** [comment] 2016-06-02 20:04
@slackpad what is the expected i/o rate for consul from your experience?
The base is 4 nodes cluster, with 3 servers.

**Comment by slackpad** [comment] 2016-06-02 20:10
It all depends on what's happening with the cluster. There's very little steady state churn if things like service health isn't changing and KV writes aren't occurring so if the cluster is quiet I'd expect a tiny fraction 4M/s. It seems like you might have something rapidly sending requests. Or, if you hit the fd issue in #907 then you might just be logging output very rapidly and it doesn't have anything to do with cluster load / Raft log writes.

**Comment by slackpad** [comment] 2017-05-25 01:06
Closing this out as this continued over on https://groups.google.com/d/msg/consul-tool/3XvE4lUARrY/HJwG-K5_AQAJ.

**Closed by slackpad** 2017-05-25 01:06 UTC
