### ISSUE TITLE
Consul Leader Election Not Taking Place

### ISSUE THREAD

**Issue by MaxFlanders** [hashicorp/consul#3960] opened 2018-03-12 18:25 UTC
### Description of the Issue (and unexpected/desired result)
The leader of our consul cluster occasionally crashes (not certain as to why yet), and rejoins the cluster 15-30 seconds later. During this period, no leader election on the other two nodes takes place, and the cluster is left leaderless and unavailable until the original leader node re-joins.

The moment that the leader node leaves the cluster, shouldnt the remaining two nodes hold an election and elect one of them as the new leader??

At this point, I am almost tempted to simply attempt a rolling upgrade to the newest version, but I'd like to see if there is anything obvious that I am missing before we start to devoting a lot of time to something we dont KNOW will fix the issue.

Thank you!

### Reproduction steps
This is only happening on our production cluster, uncertain how to reproduce as of right now.

### `consul version` for both Client and Server
Client: `0.5.2`
Server: `0.5.2`

### `consul.json` for server
The config on all 3 server nodes looks like this:
```
{
	"data_dir": "/data",
	"ui_dir": "/ui",
	"client_addr": "0.0.0.0",
	"ports": {
		"dns": 53
	},
	"recursor": "8.8.8.8",
	"disable_update_check": true
}
```

### `consul info` for both Client and Server
server1:
```
WARNING: It is highly recommended to set GOMAXPROCS higher than 1

agent:
	check_monitors = 0
	check_ttls = 0
	checks = 0
	services = 1
build:
	prerelease =
	revision = 9a9cc934
	version = 0.5.2
consul:
	bootstrap = false
	known_datacenters = 1
	leader = false
	server = true
raft:
	applied_index = 15104671
	commit_index = 15104671
	fsm_pending = 0
	last_contact = 2.097855ms
	last_log_index = 15104672
	last_log_term = 2
	last_snapshot_index = 15103953
	last_snapshot_term = 2
	num_peers = 2
	state = Follower
	term = 2
runtime:
	arch = amd64
	cpu_count = 2
	goroutines = 133
	max_procs = 1
	os = linux
	version = go1.4.2
serf_lan:
	encrypted = false
	event_queue = 0
	event_time = 5
	failed = 1
	intent_queue = 0
	left = 0
	member_time = 49
	members = 41
	query_queue = 0
	query_time = 1
serf_wan:
	encrypted = false
	event_queue = 0
	event_time = 1
	failed = 0
	intent_queue = 0
	left = 0
	member_time = 1
	members = 1
	query_queue = 0
	query_time = 1
```

server2:
```
WARNING: It is highly recommended to set GOMAXPROCS higher than 1

agent:
	check_monitors = 0
	check_ttls = 0
	checks = 0
	services = 1
build:
	prerelease =
	revision = 9a9cc934
	version = 0.5.2
consul:
	bootstrap = false
	known_datacenters = 1
	leader = false
	server = true
raft:
	applied_index = 15105007
	commit_index = 15105007
	fsm_pending = 0
	last_contact = 2.302506ms
	last_log_index = 15105007
	last_log_term = 2
	last_snapshot_index = 15100159
	last_snapshot_term = 2
	num_peers = 2
	state = Follower
	term = 2
runtime:
	arch = amd64
	cpu_count = 2
	goroutines = 248
	max_procs = 1
	os = linux
	version = go1.4.2
serf_lan:
	encrypted = false
	event_queue = 0
	event_time = 5
	failed = 2
	intent_queue = 0
	left = 0
	member_time = 49
	members = 41
	query_queue = 0
	query_time = 1
serf_wan:
	encrypted = false
	event_queue = 0
	event_time = 1
	failed = 0
	intent_queue = 0
	left = 0
	member_time = 1
	members = 1
	query_queue = 0
	query_time = 1
```

server3:
```
WARNING: It is highly recommended to set GOMAXPROCS higher than 1

agent:
	check_monitors = 0
	check_ttls = 0
	checks = 0
	services = 1
build:
	prerelease =
	revision = 9a9cc934
	version = 0.5.2
consul:
	bootstrap = false
	known_datacenters = 1
	leader = true
	server = true
raft:
	applied_index = 15105216
	commit_index = 15105216
	fsm_pending = 0
	last_contact = 0
	last_log_index = 15105217
	last_log_term = 2
	last_snapshot_index = 15104009
	last_snapshot_term = 2
	num_peers = 2
	state = Leader
	term = 2
runtime:
	arch = amd64
	cpu_count = 2
	goroutines = 362
	max_procs = 1
	os = linux
	version = go1.4.2
serf_lan:
	encrypted = false
	event_queue = 0
	event_time = 5
	failed = 1
	intent_queue = 0
	left = 0
	member_time = 49
	members = 41
	query_queue = 0
	query_time = 1
serf_wan:
	encrypted = false
	event_queue = 0
	event_time = 1
	failed = 0
	intent_queue = 0
	left = 0
	member_time = 1
	members = 1
	query_queue = 0
	query_time = 1
```

### Operating system and Environment details
These consul servers are running the progrium/consul image on an ubuntu 16.04 system.

### Log Fragments or Link to [gist](https://gist.github.com/)
Server logs from one such outage.
Starts with the leader leaving the cluster, followed by a series of errors until it re-joins the cluster.
https://gist.github.com/MaxFlanders/82071b7df8fcf2ea08d093532be59237

**Comment by banks** [comment] 2018-03-12 20:20
0.5.2 is pretty old - there have been a lot of changes that affect stability and performance since then so I'm not sure how much we can do unless you can reproduce this on a recent version.

A few things though:

> WARNING: It is highly recommended to set GOMAXPROCS higher than 1

Raft protocol relies on timely processing of heartbeat messages. If you only have one thread then it can cause instability since the leader can get stuck handling other work and not processing heartbeats in a timely way. I don't know that that is directly relevant to what you see but it's a warning sign that your config might not be well tuned for production stability.

https://www.consul.io/docs/guides/performance.html

Has more info on that but also note that as of Consul 0.7 we ship with default performance parameters that are more suitable for stability on low-spec VMs at expense of slow leader elections.

Especially take note that there are now tunables around how long we wait before triggering elections. I don't think any of that existed in 0.5.2 though and don't recall what the default times were.

Does this help at all? Overall I agree with you that an upgrade might make most sense rather than chasing down issues in such an old and different codebase. There are a quite a few significant changes in versions since 0.5 though so check the changelog notes!

**Comment by MaxFlanders** [comment] 2018-03-28 19:36
We have opted to upgrade our server nodes to 1.0.2. Thank you!

**Comment by pearkes** [comment] 2018-04-18 23:57
@MaxFlanders given you'll be upgrading I'm going to close this out! Feel free to let us know if you have other issues.

**Closed by pearkes** 2018-04-18 23:57 UTC
