### ISSUE TITLE
Re Registration of Consul Health Checks with the same Name and ID and Content causes the health check to fail momentarily

### ISSUE THREAD

**Issue by glakshmeepathi** [hashicorp/consul#5114] opened 2018-12-19 09:48 UTC
Version: 1.0.6 and 1.2.1

**Re Registration of Consul Health Checks with the same 1) Name 2) ID and 3) Content (and other params as well like Interval ) causes the check to fail momentarily.**

We maintain the required set of health checks that has to be applied to a certain set of nodes ( a cluster ). When new nodes are created in the cluster, we apply/sync/update this required set of health checks to the entire cluster again ( because of this the, health checks get applied/registered again to the already available nodes + same health checks gets registered for the first time in the new set of nodes.)

**When the health checks are registered again, Consul Server shows the health checks as "FAIL" momentarily for about 5s and returns to "PASS" state**. During that short interval if our Consul Monitoring Tool is triggered, it reports failing health checks.

Why the momentary failure ? Is that expected ? Or is it a bug ?

Workaround: Before re-registering, it can be checked whether the health check is already available and if not, only then register. But I did not want to have the overhead of comparing and then registering.

**Comment by glakshmeepathi** [comment] 2018-12-19 10:33
@pierresouchay Cool. 👍 

I have a question. Say the check is changed from "timeout 5s docker ps" to "timeout 10s docker ps". Still there is a slight change will it fail for some time ?

If so, why not "fail" only if the health check actually fails ?

**Comment by glakshmeepathi** [comment] 2018-12-19 11:34
@pierresouchay Thanks. :) 

But 4903 says "if a check already exists and is **not modified** do not change the current status of the check."

So my question is that even after the fix, if there is a slight change in the check's content like I gave above, will it fail for some time or the fix addresses this scenario as well ?

**Comment by pierresouchay** [comment] 2018-12-24 09:43
@glakshmeepathi yes, it should work with #4904 as long as Id of check does not change

**Comment by pearkes** [comment] 2019-01-03 23:13
Closing as a duplicate of #4903 thanks for reporting.

**Closed by pearkes** 2019-01-03 23:13 UTC
