### ISSUE TITLE
Feature request: Cache results of service nodes when stale read is allowed

### ISSUE THREAD

**Issue by tesseract2048** [hashicorp/consul#1604] opened 2016-01-14 09:33 UTC

**Comment by hesamg** [comment] 2016-01-22 00:39
This will be very useful feature.  We have an issue where we reboot a node (not the leader) within the cluster, and we don't get any DNS response for a few seconds.  We have turned on allow_stale, but that does not solve this issue.

**Comment by slackpad** [comment] 2016-02-02 03:16
There's a lot of complexity adding a full cache capability that should be handled by other DNS tools. I'm going to close this in favor of fixing the root cause of the outage (see https://github.com/hashicorp/consul/issues/1554#issuecomment-178338209). If that isn't sufficient we can open this one again.

**Closed by slackpad** 2016-02-02 03:16 UTC
Labels: enhancement
