### ISSUE TITLE
queries for multiple tags

### ISSUE THREAD

**Issue by carlivar** [hashicorp/consul#294] opened 2014-08-20 01:19 UTC
We would like the ability to query multiple tags via DNS and HTTP.

An example of this would be using environment name as a tag, but also needing additional tag functionality such as master/slave. For example to get the master mysql server in the qa environment, we'd like the service to publish both those tags and allow a DNS query such as:

```dig @127.0.0.1 -p 8600 master.qa.mysql.service.consul. ANY```

Or for HTTP:

```curl 'http://localhost:8500/v1/catalog/service/mysql?tag=master&tag=qa```

Or whatever HTTP param syntax is sensible (I suppose multiple params named the same would not work. Perhaps an array syntax is needed).

For DNS, I'm not sure how easy it would be to support multiple tags in the format I suggested, so a delimiter could also work. Perhaps ```master_qa.mysql.service.consul``` using underscore as a delimiter. Although this would remove the ability to put underscore in tags.

This is somewhat related to #290 since it solves the multiple environments problem for those that are willing to use tags. After much internal discussion, we are.

**Comment by xakraz** [comment] 2015-01-21 13:32
:+1:

**Comment by mdhelgen** [comment] 2015-02-03 23:40
:+1:

**Comment by mfischer-zd** [comment] 2015-03-02 23:38
Any idea when the HTTP tag intersection behavior might be released?  I'm sort of surprised that it didn't end up in 0.5.0.

**Comment by armon** [comment] 2015-03-03 02:26
No idea currently. Part of the issue is simultaneously migrating tags from a flag list of strings into a richer K/V representation. That complicates the syntax as it's no longer flat.

**Comment by breedx** [comment] 2015-04-02 15:37
+1

**Comment by blacked** [comment] 2015-05-04 21:46
```
'http://localhost:8500/v1/catalog/service/mysql?tag=[master,qa]
```
why not just add something like that? no need make tags overcomplicated, they need just for filtering. And not have ability to filter by multiple parameters that's... i was very frustrated.

**Comment by mfischer-zd** [comment] 2015-05-04 21:47
@blacked, because that's not how you specify multiple options for a value in HTTP request parameters.  See the relevant RFCs.  The correct form is `?tag=master&tag=qa`.

**Comment by sfncook** [comment] 2015-05-22 20:31
:+1:

**Comment by rodrigopr** [comment] 2015-05-26 00:33
+1 for multiple tags

**Comment by ybogdanov** [comment] 2015-06-02 13:38
any progress on this?

**Comment by PM-Andrey-Kupreychik** [comment] 2015-06-11 06:34
+1 for multiple tags search over DNS with '.' prohobited in tag

**Comment by loicalbertin** [comment] 2015-06-19 13:11
:+1: with dns search support.

**Comment by ninthnails** [comment] 2015-08-18 18:06
+1

**Comment by cleung2010** [comment] 2015-09-01 18:40
+1 for this feature. It would be nice for multi-environment teams that are using/hosting the same services.

**Comment by nickwales** [comment] 2015-10-09 22:06
Related to this topic, I was trying to provide some extra DNS information without using tags. So I can create a service called test.app which the API lets me query but not DNS. I can't see any specific documentation for what the name of the service should include but it appears periods are not supported for DNS resolution. 

e.g. 
    curl consul/v1/catalog/service/test.app  <-- works
    dig @consul -p8600 test.app.service.datacenter.consul <-- doesn't return anything

**Comment by endzyme** [comment] 2015-10-14 13:11
+1 for the multi-tag filtering

**Comment by isegal** [comment] 2015-11-05 02:12
+1 yes this would be extremely useful. For example, a mysql sever could be staging or production, but it could also be master or slave. Allowing multi-tag filtering would keep the number of service name definitions down to a minimum.
A potential disadvantage would be the order of tags, from DNS perspective production.master.mysql.service.consul and master.production.mysql.service.consul are supposed to be separate hosts, but for service discovery it would be the same. A small price to pay I presume.

**Comment by rgarver** [comment] 2015-12-16 18:30
:+1: for this. Seems like the DNS complications could be managed with a canonical ordering of tags (eg: alphabetical) and CNAME non-canonical versions to the canonical version. That's if we really care that `production.primary.mysql.service.consul` and `primary.production.mysql.service.consul` are the same. Personally I think that's a non-issue that only affects DNS caching and frankly not in anyway that seems important given the context.

**Comment by nivan22** [comment] 2015-12-16 18:42
Allowing multi-tag filtering would keep the number of service name definitions down to a minimum.
A potential disadvantage would be the order of tags, from DNS perspective  DNS caching and frankly not??

**Comment by slackpad** [comment] 2016-01-09 01:46
Prepared queries (released in Consul 0.6.0) provides a solution for this - https://www.consul.io/docs/agent/http/query.html.

You can register a query that filters with multiple tags (in addition to several more features) and execute that query via DNS or HTTP request.

**Comment by chatu** [comment] 2016-02-03 23:15
:+1:

**Comment by slackpad** [comment] 2016-02-13 04:28
Closing this out now that prepared queries are available and allow queries using multiple tags via DNS and HTTP.

**Closed by slackpad** 2016-02-13 04:28 UTC
Labels: thinking

**Comment by rogeralsing** [comment] 2016-08-19 07:19
Is this really a viable replacement for the actual request?

Prepared queries have a name, you can not pass any arguments to it.
Thus you cannot really use it for dynamic queries.

e.g. say I want to find a service with the name Customer and the tags VIP and Sweden.
Then I would be forced to have one Query for VipSweden and then another for VipNorway etc etc.
No?

If it was possible to use multiple tags in the API directly, one could do what the OP suggested:

`curl 'http://localhost:8500/v1/catalog/service/mysql?tag=VIP&tag=Sweden`

Currently the only option for building context aware service discovery is to query for all healthy instances and then filter it on the client.

**Comment by slackpad** [comment] 2016-08-19 07:37
@rogeralsing [prepared query templates](https://www.consul.io/docs/agent/http/query.html#templates) would let you parameterize to let you make a single query that can handle "vip" + "something else". We opened #1781 for a solution to ad-hoc queries with multiple tags as PQs still need to be created before they can be executed.

**Comment by rogeralsing** [comment] 2016-08-19 07:50
Perfect, I added a querstion about prepared query templates here https://groups.google.com/forum/#!topic/consul-tool/iaPwF9gLT0w

I get that I can use regex to extract parts of the name, but how would one go about to extract multiple tags? e.g. should that match contain a comma separated list when it is inserted into the template?
That is, how do I make this multiple matches? 
` "Tags": ["${match(2)}"]`
