### ISSUE TITLE
Please give a adapter M1 version of the consul

### ISSUE THREAD

**Issue by junchaogg996** [hashicorp/consul#9484] opened 2021-01-04 10:06 UTC
Please search the existing issues for relevant feature requests, and use the reaction feature (https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to add upvotes to pre-existing requests.

#### Feature Description

A written overview of the feature.

#### Use Case(s)

Any relevant use-cases that you see.

**Comment by mikemorris** [comment] 2021-01-04 20:27
Dupe of #9476

**Closed by mikemorris** 2021-01-04 20:27 UTC
