### ISSUE TITLE
shutdown leader in 3 node cluster cause one of the two remaining server lost new leader

### ISSUE THREAD

**Issue by ycheng-gh** [hashicorp/consul#2513] opened 2016-11-17 01:24 UTC
### `consul version` for both Client and Server
Server: `Consul v0.7.0`

### `consul info` for both Client and Server
Server:
```
[root@wf-500-117 ~]# consul info
agent:
	check_monitors = 0
	check_ttls = 0
	checks = 0
	services = 8
build:
	prerelease = 
	revision = 'a189091
	version = 0.7.0
consul:
	bootstrap = false
	known_datacenters = 1
	leader = false
	leader_addr = 192.168.1.118:8300
	server = true
raft:
	applied_index = 30126
	commit_index = 30126
	fsm_pending = 0
	last_contact = 8.475242ms
	last_log_index = 30126
	last_log_term = 4
	last_snapshot_index = 24737
	last_snapshot_term = 4
	latest_configuration = [{Suffrage:Voter ID:192.168.1.116:8300 Address:192.168.1.116:8300} {Suffrage:Voter ID:192.168.1.117:8300 Address:192.168.1.117:8300} {Suffrage:Voter ID:192.168.1.118:8300 Address:192.168.1.118:8300}]
	latest_configuration_index = 133
	num_peers = 2
	protocol_version = 1
	protocol_version_max = 3
	protocol_version_min = 0
	snapshot_version_max = 1
	snapshot_version_min = 0
	state = Follower
	term = 4
runtime:
	arch = amd64
	cpu_count = 24
	goroutines = 254
	max_procs = 24
	os = linux
	version = go1.7.3
serf_lan:
	encrypted = false
	event_queue = 0
	event_time = 20071
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 4
	members = 3
	query_queue = 0
	query_time = 1
serf_wan:
	encrypted = false
	event_queue = 0
	event_time = 1
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 1
	members = 1
	query_queue = 0
	query_time = 1
```

### Operating system and Environment details
Linux 3.10.88  x86_64

### Description of the Issue (and unexpected/desired result)
The consul cluster has 3 nodes, all of them are servers.
Gracefully shutdown the leader (116) to prepare for reboot.
The remaining two servers held an election, one of them (118) became new leader.
But the non-leader node (117) goes into "lost leader" mode and cannot recover, 
even after the rebooted node joins back again.
It only recovered after gracefully restart.

### Reproduction steps
see above

############# on 116 (the old leader got shutdown)
==> Caught signal: terminated
    2016/11/15 15:27:04 [INFO] agent: requesting shutdown
    2016/11/15 15:27:04 [INFO] consul: shutting down server
    2016/11/15 15:27:04 [WARN] serf: Shutdown without a Leave
    2016/11/15 15:27:04 [ERR] dns: error starting tcp server: accept tcp 127.0.0.1:8600: use of closed network connection
    2016/11/15 15:27:04 [ERR] agent: Failed to invoke watch handler '/sbin/consul_task_svr notify_engine': signal: terminated
    2016/11/15 15:27:04 [ERR] agent: Failed to invoke watch handler '/sbin/consul_task_client': signal: terminated
    2016/11/15 15:27:04 [WARN] serf: Shutdown without a Leave
    2016/11/15 15:27:04 [INFO] raft: aborting pipeline replication to peer {Voter 192.168.1.117:8300 192.168.1.117:8300}
    2016/11/15 15:27:04 [INFO] raft: aborting pipeline replication to peer {Voter 192.168.1.118:8300 192.168.1.118:8300}
    2016/11/15 15:27:04 [INFO] agent: shutdown complete

############# on 117 (the one failed)
    2016/11/15 15:27:09 consul.watch: Watch (type: keyprefix) errored: Unexpected response code: 500, retry in 20s
    2016/11/15 15:27:11 [INFO] memberlist: Marking wfpc-1234ABC6-internal as failed, suspect timeout reached (0 peer confirmations)
    2016/11/15 15:27:11 [INFO] serf: EventMemberFailed: wfpc-1234ABC6-internal 192.168.1.116
    2016/11/15 15:27:11 [INFO] consul: Removing LAN server wfpc-1234ABC6-internal (Addr: tcp/192.168.1.116:8300) (DC: trs-cluster)
    2016/11/15 15:27:12 [INFO] memberlist: Suspect wfpc-1234ABC6-internal has failed, no acks received
    2016/11/15 15:27:15 [WARN] raft: Heartbeat timeout from "192.168.1.116:8300" reached, starting election
    2016/11/15 15:27:15 [INFO] raft: Node at 192.168.1.117:8300 [Candidate] entering Candidate state in term 3
    2016/11/15 15:27:15 [ERR] raft: Failed to make RequestVote RPC to {Voter 192.168.1.116:8300 192.168.1.116:8300}: dial tcp 192.168.1.116:8300: getsockopt: connection refused
    2016/11/15 15:27:17 [INFO] raft: Duplicate RequestVote for same term: 3
    2016/11/15 15:27:22 [INFO] raft: Node at 192.168.1.117:8300 [Follower] entering Follower state (Leader: "")
    2016/11/15 15:27:22 [INFO] consul: New leader elected: wfpc-1234ABC1-internal
    2016/11/15 15:27:23 [ERR] http: Request GET /v1/kv/status/kv, error: No cluster leader from=127.0.0.1:46176
    2016/11/15 15:27:28 [ERR] http: Request GET /v1/kv/status/kv?consistent=1, error: No cluster leader from=127.0.0.1:46184
    2016/11/15 15:27:28 [INFO] agent: (LAN) joining: [192.168.1.116]
    2016/11/15 15:27:28 [INFO] agent: (LAN) joined: 0 Err: 1 error(s) occurred:

* Failed to join 192.168.1.116: dial tcp 192.168.1.116:8301: getsockopt: connection refused
    2016/11/15 15:27:28 [ERR] http: Request GET /v1/agent/join/192.168.1.116, error: 1 error(s) occurred:

* Failed to join 192.168.1.116: dial tcp 192.168.1.116:8301: getsockopt: connection refused from=127.0.0.1:46198
    2016/11/15 15:27:33 [ERR] agent: coordinate update error: No cluster leader

############# on 118 (the new leader)
    2016/11/15 15:25:43 [INFO] memberlist: Suspect wfpc-1234ABC6-internal has failed, no acks received
    2016/11/15 15:25:44 [INFO] serf: EventMemberFailed: wfpc-1234ABC6-internal 192.168.1.116
    2016/11/15 15:25:44 [INFO] consul: Removing LAN server wfpc-1234ABC6-internal (Addr: tcp/192.168.1.116:8300) (DC: trs-cluster)
    2016/11/15 15:25:48 [WARN] raft: Rejecting vote request from 192.168.1.117:8300 since we have a leader: 192.168.1.116:8300
    2016/11/15 15:25:49 [WARN] raft: Heartbeat timeout from "192.168.1.116:8300" reached, starting election
    2016/11/15 15:25:49 [INFO] raft: Node at 192.168.1.118:8300 [Candidate] entering Candidate state in term 3
    2016/11/15 15:25:49 [ERR] raft: Failed to make RequestVote RPC to {Voter 192.168.1.116:8300 192.168.1.116:8300}: dial tcp 192.168.1.116:8300: getsockopt: connection refused
    2016/11/15 15:25:53 [ERR] http: Request GET /v1/kv/status/kv, error: No cluster leader from=127.0.0.1:59016
    2016/11/15 15:25:55 [WARN] raft: Election timeout reached, restarting election
    2016/11/15 15:25:55 [INFO] raft: Node at 192.168.1.118:8300 [Candidate] entering Candidate state in term 4
    2016/11/15 15:25:55 [ERR] raft: Failed to make RequestVote RPC to {Voter 192.168.1.116:8300 192.168.1.116:8300}: dial tcp 192.168.1.116:8300: getsockopt: connection refused
    2016/11/15 15:25:55 [INFO] raft: Election won. Tally: 2
    2016/11/15 15:25:55 [INFO] raft: Node at 192.168.1.118:8300 [Leader] entering Leader state
    2016/11/15 15:25:55 [INFO] raft: Added peer 192.168.1.116:8300, starting replication
    2016/11/15 15:25:55 [INFO] raft: Added peer 192.168.1.117:8300, starting replication
    2016/11/15 15:25:55 [INFO] consul: cluster leadership acquired
    2016/11/15 15:25:55 [INFO] consul: New leader elected: wfpc-1234ABC1-internal
    2016/11/15 15:25:55 [ERR] raft: Failed to AppendEntries to {Voter 192.168.1.116:8300 192.168.1.116:8300}: dial tcp 192.168.1.116:8300: getsockopt: connection refused
    2016/11/15 15:25:55 [INFO] raft: pipelining replication to peer {Voter 192.168.1.117:8300 192.168.1.117:8300}
    2016/11/15 15:25:55 [INFO] consul: member 'wfpc-1234ABC6-internal' failed, marking health critical

**Comment by ycheng-gh** [comment] 2016-11-28 18:37
Just wondering anyone else also encountered this?

**Comment by slackpad** [comment] 2016-12-20 03:09
Hi @ycheng-gh this is an odd one - I can't explain what was happening here. So rebooting 117 got things working again? It looks like 118 was able to connect to 117 - were there any logs on 118 related to 117 after those shown above (anything related to failed replication)?

**Comment by slackpad** [comment] 2017-05-02 00:35
Closing this as we never heard back. Please let us know if you still need help.

**Closed by slackpad** 2017-05-02 00:35 UTC

**Comment by kirankumar1991** [comment] 2018-05-07 22:59
@slackpad, We've run into the same issue in a six node cluster (5 servers and 1 client). We're using Consul v0.7.5 

When the leader was killed, the other servers knew that the leader is down and started an election. All the members got to know, who the new leader is. But two of the servers are complaining that there's no leader and operations are failing, even though the two servers logged who the new leader is in their respective log files.

I could see from the leader log file, that it was pipelining the replication to the IP address of these servers. Everything seems fine in the leader's log file. We have the servers in this state for the past few days and have not restarted consul. Do you need any other info that would help in debugging this issue?

**Comment by kirankumar1991** [comment] 2018-05-08 18:50
There are two possible workarounds and I tested them on each of the affected nodes.

1. Restart the affected nodes. Consul when it is restarted asks for who the leader is and it recovers.
2. Restart the cluster leader. The affected nodes detect that the leader is down, since the heartbeat fails. This triggers an election and the nodes recover.

Interesting observations:

- When I restarted the leader, the affected node detected that the leader is down. So this confirms again that it knew who the leader was. It participated in the election and recovered, when the new leader was elected.
- When I restarted one of the affected nodes, the leader detected that the affected node went down as heartbeat failed. 
- Based on the above two points, heartbeat was successful from both leader to affected nodes and from affected nodes to leader

**Comment by kirankumar1991** [comment] 2018-05-22 23:38
We hit this bug in 0.6.4 as well. We do know that v0.6.4 and v0.7.5 are pretty old. But it would be helpful, if we could understand the root cause of this bug and know if this issue still exists in the latest version.

@slackpad / @preetapan / @magiconair could we please reopen this bug?
