### ISSUE TITLE
[Feature request] make transaction limits configurable

### ISSUE THREAD

**Issue by Adidishen** [hashicorp/consul#3917] opened 2018-02-26 12:34 UTC
Currently, transactions are limited to 64 operations. [This value is hardcoded](https://github.com/hashicorp/consul/blob/master/agent/txn_endpoint.go#L17).

I'm writing a wrapper around Consul's KV store to read/write service configurations. Each key in the KV is a single configuration value. This means I'm currently limited to 63 configuration values to Consul (one `delete-subtree` and 63 `set` operations).

I've read somewhere that the limit was imposed to prevent abuse of the transaction endpoint. However it would make much more sense if this limit could be configured by the cluster admins instead.

**Comment by kyhavlov** [comment] 2018-02-27 18:33
Closing as a duplicate of #2921 (also about increasing the transaction operation limit).

**Closed by kyhavlov** 2018-02-27 18:33 UTC
