### ISSUE TITLE
Does Consul offer automated Health Notice/Advisory when agents failed in the cluster

### ISSUE THREAD

**Issue by achenand** [hashicorp/consul#5491] opened 2019-03-14 19:35 UTC
We have a three-server Consul cluster running on Linux and would like to get notified if one of the Consul server agents failed. I couldn't find anything in the existing documentation and issues. 

Could you let me know what is the best way to receive Health failure events from Consul cluster if one of the agents fails or stopped working.

**Comment by achenand** [comment] 2019-03-14 19:40
By reading this issue https://github.com/hashicorp/consul/issues/1790, it mentioned " agent's node-level serfHealth check as failed". Is there a way to get notified of this serfHealth check failing event ? thanks.

**Comment by pearkes** [comment] 2019-04-03 23:26
I think this is a duplicate of #3724, some good ideas in there.

**Closed by pearkes** 2019-04-03 23:26 UTC
