### ISSUE TITLE
healthcheck always return DOWN

### ISSUE THREAD

**Issue by jackwangyubo** [hashicorp/consul#3772] opened 2017-12-29 08:01 UTC
If you have a question, please direct it to the
[consul mailing list](https://www.consul.io/community.html) if it hasn't been
addressed in either the [FAQ](https://www.consul.io/docs/faq.html) or in one
of the [Consul Guides](https://www.consul.io/docs/guides/index.html).

When filing a bug, please include the following:

### `consul version` for both Client and Server
Client: `spring-cloud-consul-dependencies 1.0.1.RELEASE`
Server: `last`

### `consul info` for both Client and Server
Client:
```
[Client `consul info` here]
```

Server:
```
[Server `consul info` here]
```

### Description of the Issue (and unexpected/desired result)
the healthcheck api always return this：
"consul": {
        "status": "DOWN",
        "services": {
            "consul": [],
            "engine-core": [
                "dev"
            ]
        },
        "error": "java.lang.IllegalArgumentException: Value must not be null"
    }
engine-core is my service

### Log Fragments or Link to [gist](https://gist.github.com/)

Include appropriate Client or Server log fragments.  If the log is longer
than a few dozen lines, please include the URL to the
[gist](https://gist.github.com/).

TIP: Use `-log-level=TRACE` on the client and server to capture the maximum log detail.

**Comment by alxark** [comment] 2018-01-01 10:34
Well it looks like problem is with your service. 
I think it will be better to attach curl -v <HEALTHCHECK_URL> here

**Comment by slackpad** [comment] 2018-01-03 21:40
Closing this as a duplicate of https://github.com/hashicorp/consul/issues/3635, which I believe is fixed now on the Spring Cloud side.

**Closed by slackpad** 2018-01-03 21:40 UTC
