### ISSUE TITLE
False Information Provided by /health/service Endpoint 

### ISSUE THREAD

**Issue by orarnon** [hashicorp/consul#4629] opened 2018-09-04 16:28 UTC
#### Overview of the Issue
Consul catalog consists of nodes that do not longer exist. Their serf check is gone but their service checks are still passing.
It seems that the nodes that exist without any serf check but with a passing health-checks, are missing their node ID. None of them were registered externally. 
### Consul info for both Client and Server
</details>

<details>
  <summary>Server info</summary>

```
agent:
	check_monitors = 0
	check_ttls = 3
	checks = 3
	services = 4
build:
	prerelease =
	revision = e716d1b5
	version = 1.2.2
consul:
	bootstrap = false
	known_datacenters = 1
	leader = true
	leader_addr = 10.200.4.70:8300
	server = true
raft:
	applied_index = 396839672
	commit_index = 396839672
	fsm_pending = 0
	last_contact = 0
	last_log_index = 396839672
	last_log_term = 68547
	last_snapshot_index = 396832392
	last_snapshot_term = 68546
	latest_configuration = [{Suffrage:Voter ID:673e0ff3-815a-4c56-0b5b-1ccf17d7a7d1 Address:10.200.1.154:8300} {Suffrage:Voter ID:082aa7eb-3692-0d7b-b4fe-7efd1ab5b42e Address:10.200.4.70:8300} {Suffrage:Voter ID:6568e22c-2660-bdb8-8d47-5ffc65c1601d Address:10.200.10.157:8300}]
	latest_configuration_index = 396615574
	num_peers = 2
	protocol_version = 3
	protocol_version_max = 3
	protocol_version_min = 0
	snapshot_version_max = 1
	snapshot_version_min = 0
	state = Leader
	term = 68547
runtime:
	arch = amd64
	cpu_count = 8
	goroutines = 22040
	max_procs = 4
	os = linux
	version = go1.10.1
serf_lan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 4773
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 99
	member_time = 1608321
	members = 1288
	query_queue = 0
	query_time = 245
serf_wan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 1
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 3478
	members = 1
	query_queue = 0
	query_time = 1
```

</details>

### Operating system and Environment details
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty

### Querying /health/service 
Using: 
curl http://consul1.sonic-us.us-east-1.ec2ssa.info:8500/v1/health/service/es-logstash | jq .
<details>
  <summary>Returned JSON</summary>

```

    "Node": {
      "ID": "",
      "Node": "es-logstash-i-0026f8411964c691d.d.sonic-us.us-east-1",
      "Address": "<pvt_ip>",
      "Datacenter": "",
      "TaggedAddresses": {
        "lan": "<pvt_ip>",
        "wan": "<public_ip>"
      },
      "Meta": null,
      "CreateIndex": 396601352,
      "ModifyIndex": 396601352
    },
    "Service": {
      "ID": "es-logstash",
      "Service": "es-logstash",
      "Tags": [
        "prod_us",
        "es-logstash"
      ],
      "Address": "",
      "Meta": null,
      "Port": 9200,
      "EnableTagOverride": false,
      "ProxyDestination": "",
      "Connect": {
        "Native": false,
        "Proxy": null
      },
      "CreateIndex": 396601352,
      "ModifyIndex": 396601352
    },
    "Checks": [
      {
        "Node": "es-logstash-i-0026f8411964c691d.d.sonic-us.us-east-1",
        "CheckID": "es-logstash__es_agent",
        "Name": "Elastic Search agent on port 9200",
        "Status": "passing",
        "Notes": "",
        "Output": "HTTP GET http://localhost:9200/: 200 OK Output: {\n  \"name\" : \"es-logstash-i-0026f8411964c691d.d.sonic-us.us-east-1\",\n  \"cluster_name\" : \"prod_us-es.sonic-us\",\n  \"cluster_uuid\" : \"z4Zw2HjiRJ2zIM2ggU1kFQ\",\n  \"version\" : {\n    \"number\" : \"5.3.0\",\n    \"build_hash\" : \"3adb13b\",\n    \"build_date\" : \"2017-03-23T03:31:50.652Z\",\n    \"build_snapshot\" : false,\n    \"lucene_version\" : \"6.4.1\"\n  },\n  \"tagline\" : \"You Know, for Search\"\n}\n",
        "ServiceID": "",
        "ServiceName": "",
        "ServiceTags": [],
        "Definition": {},
        "CreateIndex": 396601352,
        "ModifyIndex": 396601352
      },
      {
        "Node": "es-logstash-i-0026f8411964c691d.d.sonic-us.us-east-1",
        "CheckID": "es-logstash__port9600",
        "Name": "Logstash service on port 9600",
        "Status": "passing",
        "Notes": "",
        "Output": "HTTP GET http://localhost:9600/_node?pretty: 200 OK Output: {\n  \"host\" : \"es-logstash-i-0026f8411964c691d.d.sonic-us.us-east-1\",\n  \"version\" : \"5.3.2\",\n  \"http_address\" : \"0.0.0.0:9600\",\n  \"id\" : \"c9e82bb4-f829-40d0-8f49-603b2871e844\",\n  \"name\" : \"es-logstash-i-0026f8411964c691d.d.sonic-us.us-east-1\",\n  \"pipeline\" : {\n    \"workers\" : 4,\n    \"batch_size\" : 1000,\n    \"batch_delay\" : 5,\n    \"config_reload_automatic\" : true,\n    \"config_reload_interval\" : 3,\n    \"id\" : \"main\"\n  },\n  \"os\" : {\n    \"name\" : \"Linux\",\n    \"arch\" : \"amd64\",\n    \"version\" : \"4.4.0-96-generic\",\n    \"available_processors\" : 4\n  },\n  \"jvm\" : {\n    \"pid\" : 1,\n    \"version\" : \"1.8.0_121\",\n    \"vm_name\" : \"OpenJDK 64-Bit Server VM\",\n    \"vm_version\" : \"1.8.0_121\",\n    \"vm_vendor\" : \"Oracle Corporation\",\n    \"start_time_in_millis\" : 1535309613248,\n    \"mem\" : {\n      \"heap_init_in_bytes\" : 4001366016,\n      \"heap_max_in_bytes\" : 3966500864,\n      \"non_heap_init_in_bytes\" : 2555904,\n      \"non_heap_max_in_bytes\" : 0\n    },\n    \"gc_collectors\" : [ \"ParNew\", \"ConcurrentMarkSweep\" ]\n  }\n}",
        "ServiceID": "",
        "ServiceName": "",
        "ServiceTags": [],
        "Definition": {},
        "CreateIndex": 396601352,
        "ModifyIndex": 396601352
      }
    ]
  }

```
</details>

**Comment by pierresouchay** [comment] 2018-09-06 07:49
@orarnon As we discussed it privately already, a few things:
* Having ID:"" for node seems to indicate something very weird, service might have been registered manually, or might be a bug in a old Consul version
* other possible issue: ACLs. It might be possible this node could not un-register its services while leaving the cluster and for some reason. You should check if the ACLs applied for the token of you agent have rights to register/unregister Checks starting with `Logstash` and `Elastic` since those checks are not tied to a specific service (since `"ServiceID": "",`), but to the node itself (which is weird)

**Comment by giladsh1** [comment] 2018-09-06 13:04
Hi @pierresouchay, 
I've suffering from the same zombie nodes issue, using the same Consul (1.2.2) version on centos 7.
no manual registration took place, and we're not using ACLs.

This issue did not occur in version 1.2.0, which I previously used.
It seems like in some cases Consul does not reap bad nodes with no Serf check.
The node has an empty ID when querying catalog/nodes, but is still registered to Consul, with no Serf health check.

```
{
    "ID": "",
    "Node": "abahat1-mng-i-0f245f4f1c0aeddd1",
    "Address": "10.251.152.187",
    "Datacenter": "",
    "TaggedAddresses": {
      "lan": "10.251.152.187",
      "wan": "10.251.152.187"
    },
    "Meta": null,
    "CreateIndex": 2068484,
    "ModifyIndex": 2068484
  },
```

```
➜  git:(master) curl -s <consul>:8500/v1/health/node/abahat1-mng-i-0f245f4f1c0aeddd1 | jq .

[
  {
    "Node": "abahat1-mng-i-0f245f4f1c0aeddd1",
    "CheckID": "service:mng:1",
    "Name": "Service 'mng' check",
    "Status": "critical",
    "Notes": "",
    "Output": "python: can't open file '/usr/local/cloud_bin/check_instance_health.py': [Errno 2] No such file or directory\n",
    "ServiceID": "mng",
    "ServiceName": "mng",
    "ServiceTags": [
      "abahat1"
    ],
    "Definition": {},
    "CreateIndex": 2068484,
    "ModifyIndex": 2068484
  },
  {
    "Node": "abahat1-mng-i-0f245f4f1c0aeddd1",
    "CheckID": "service:mng:2",
    "Name": "show application version",
    "Status": "warning",
    "Notes": "",
    "Output": "cat: /usr/local/cloud_bin/version.txt: No such file or directory\n",
    "ServiceID": "mng",
    "ServiceName": "mng",
    "ServiceTags": [
      "abahat1"
    ],
    "Definition": {},
    "CreateIndex": 2068484,
    "ModifyIndex": 2068484
  }
]
```

**Comment by pearkes** [comment] 2018-10-26 18:44
@giladsh1 I believe you're showing a slightly different scenario, querying the `/v1/health/node/` endpoint, which will not filter out non-passing checks (https://www.consul.io/api/health.html#list-checks-for-node).

Unfortunately the API appears to be doing the right thing here. Because there is no `serfHealthCheck` present on the service, it will return as the other checks are passing. The catalog does need to support services with no `serfHealthCheck`, for example the "external services" use-case.

I'm going to close this as I don't actually believe the issue is with the endpoint, but rather the scenario that resulted in that data being in the catalog. I don't think this is "fixed" but unfortunately it doesn't directly lead us to a scenario where we can make a change.

**Closed by pearkes** 2018-10-26 18:44 UTC
Labels: needs-investigation
