### ISSUE TITLE
Registering service and checks with a given ID

### ISSUE THREAD

**Issue by Tborra** [hashicorp/consul#760] opened 2015-03-05 09:49 UTC
I am using consul 5.0. I am trying to register a service with checks that have a specified id and name.
I can register the service and the checks. The checks however are not registered with the specified id and name. I tried using the config files and the api.

This is the same for script, ttl, and http checks. This is a problem because you need the checkId to do a call to the TTL checks. 

**my service config file:**
{
"service":
 {
   "name": "apache",
   "tags": ["apache, www"],
   "port": 80,
   "checks": [
                {
                  "id": "apache1",
                  "name": "index",
                  "http": "http://localhost:80",
                  "interval": "20s",
                  "timeout": "2s"
                },
                {
                  "id": "apache2",
                  "name": "testpage",
                  "http": "http://localhost:80/testpage.html",
                  "interval": "20s",
                  "timeout": "2s"
                }]}}

**or through the api:**

curl -H  'Content-Type: application/json'  -X PUT -d '{"name":"apache","tags":["apache","www"],"port":80,"checks":[{"id":"apache1","name":"index","http":"http://localhost:80","interval":"20s","timeout":"2s"},{"timeout":"2s","interval":"20s","http":"http://localhost:80/testpage.html","name":"testpage","id":"apache2"}]}' http://localhost:8500/v1/agent/service/register

**result (different name and id has been set by consul):**

curl http://localhost:8500/v1/agent/checks?pretty
{
    "service:apache:1": {
        "Node": "consulserver1.test.lan",
        "CheckID": "service:apache:1",
        "Name": "Service 'apache' check",
        "Status": "passing",
        "Notes": "",
        "Output": "HTTP GET http://localhost:80: 200 OK Output: \n",
        "ServiceID": "apache",
        "ServiceName": "apache"
    },
    "service:apache:2": {
        "Node": "consulserver1.test.lan",
        "CheckID": "service:apache:2",
        "Name": "Service 'apache' check",
        "Status": "passing",
        "Notes": "",
        "Output": "HTTP GET http://localhost:80/testpage.html: 200 OK Output: ",
        "ServiceID": "apache",
        "ServiceName": "apache"
    }
}

**Comment by ryanuber** [comment] 2015-03-05 16:53
Thanks for reporting this. I think that checks embedded into service definitions have a few limitations, though we plan to fix that. I'll take a look at this today, as it's likely something simple.

**Comment by ryanuber** [comment] 2015-03-05 18:53
This is actually a dupe of #740. I'm going to close this to track the issue there. Thanks!

**Closed by ryanuber** 2015-03-05 18:53 UTC
Labels: bug
