### ISSUE TITLE
raft: Failed to heartbeat to IP even if its allotted to an interface

### ISSUE THREAD

**Issue by prashantabkari** [hashicorp/consul#1829] opened 2016-03-14 06:01 UTC
Hi - I am running a ubuntu and have installed consul on it. I have started consul in the following way 

sudo  consul agent -server -bootstrap  -data-dir consul-agent/ -config-dir=/etc/consul.d -bind 10.X.X.X (hiding the IP )
Where 10.X.X.X  corresponds to eth0 interface 

This is the only member of the cluster with no client

On running the netstat i found that HTTP service is running on localhost/loopback ip on port 8500 and not on 10.X.X.X series. This is applicable for 172.x.x.x series

**The reason why its affecting is because i want to query the consul from a docker container and localhost from the docker is not possible**

Apologies for pasting the log. Didn't know if its logged on the system somewhere. 

Also following log statement could be found 
2016/03/14 11:04:21 [INFO] serf: EventMemberJoin: ubuntu 10.143.219.73
    2016/03/14 11:04:21 [INFO] raft: Node at 10.143.219.73:8300 [Follower] entering Follower state
    2016/03/14 11:04:21 [INFO] consul: adding LAN server ubuntu (Addr: 10.143.219.73:8300) (DC: dc1)
    2016/03/14 11:04:21 [WARN] serf: Unrecognized snapshot line: alive: ubuntu.dc1 172.17.0.1:8302
    2016/03/14 11:04:21 [WARN] serf: Unrecognized snapshot line: alive: ubuntu.dc1 172.17.0.1:8302
    2016/03/14 11:04:21 [INFO] serf: EventMemberJoin: ubuntu.dc1 10.143.219.73
    2016/03/14 11:04:21 [INFO] consul: adding WAN server ubuntu.dc1 (Addr: 10.143.219.73:8300) (DC: dc1)
    2016/03/14 11:04:21 [ERR] agent: failed to sync remote state: No cluster leader
    2016/03/14 11:04:22 [WARN] raft: Heartbeat timeout reached, starting election
    2016/03/14 11:04:22 [INFO] raft: Node at 10.143.219.73:8300 [Candidate] entering Candidate state
    2016/03/14 11:04:23 [INFO] raft: Election won. Tally: 1
    2016/03/14 11:04:23 [INFO] raft: Node at 10.143.219.73:8300 [Leader] entering Leader state
    2016/03/14 11:04:23 [INFO] consul: cluster leadership acquired
    2016/03/14 11:04:23 [INFO] consul: New leader elected: ubuntu
    2016/03/14 11:04:23 [INFO] raft: Disabling EnableSingleNode (bootstrap)
    2016/03/14 11:04:23 [INFO] raft: Added peer 192.168.135.3:8300, starting replication
    2016/03/14 11:04:23 [INFO] consul.fsm: EnsureRegistration failed: failed inserting service: failed inserting service: object missing primary index
    2016/03/14 11:04:23 [INFO] raft: Added peer 127.0.0.1:8300, starting replication
    2016/03/14 11:04:23 [INFO] raft: Removed peer 192.168.135.3:8300, stopping replication (Index: 124)
    2016/03/14 11:04:23 [ERR] raft: Failed to AppendEntries to 127.0.0.1:8300: dial tcp 127.0.0.1:8300: getsockopt: connection refused
    2016/03/14 11:04:23 [INFO] raft: Added peer 172.17.0.1:8300, starting replication
    2016/03/14 11:04:23 [INFO] raft: Removed peer 127.0.0.1:8300, stopping replication (Index: 126)
     ......  
   2016/03/14 11:04:23 [INFO] raft: Added peer 172.17.0.2:8300, starting replication
    2016/03/14 11:04:23 [ERR] raft: Failed to AppendEntries to 172.17.0.2:8300: dial tcp 172.17.0.2:8300: getsockopt: connection refused
    2016/03/14 11:04:24 [ERR] raft: Failed to heartbeat to 172.17.0.1:8300: dial tcp 172.17.0.1:8300: getsockopt: connection refused
    2016/03/14 11:04:24 [INFO] raft: Added peer 10.143.218.17:8300, starting replication
    2016/03/14 11:04:24 [INFO] raft: Removed peer 172.17.0.1:8300, stopping replication (Index: 3370)
    2016/03/14 11:04:24 [INFO] raft: Removed peer 172.17.0.2:8300, stopping replication (Index: 3370)
    2016/03/14 11:04:24 [ERR] raft: Failed to AppendEntries to 172.17.0.1:8300: dial tcp 172.17.0.1:8300: getsockopt: connection refused
    2016/03/14 11:04:24 [INFO] raft: Removed peer 10.143.218.17:8300, stopping replication (Index: 3404)
    2016/03/14 11:04:24 [INFO] raft: Added peer 172.17.0.1:8300, starting replication
    2016/03/14 11:04:24 [INFO] raft: Removed peer 172.17.0.1:8300, stopping replication (Index: 3488)
    2016/03/14 11:04:24 [ERR] raft: Failed to AppendEntries to 172.17.0.2:8300: dial tcp 172.17.0.2:8300: getsockopt: connection refused
    2016/03/14 11:04:24 [ERR] raft: Failed to heartbeat to 172.17.0.2:8300: dial tcp 172.17.0.2:8300: getsockopt: connection refused
    2016/03/14 11:04:24 [ERR] raft: Failed to AppendEntries to 172.17.0.1:8300: dial tcp 172.17.0.1:8300: getsockopt: connection refused
    2016/03/14 11:04:24 [ERR] raft: Failed to AppendEntries to 172.17.0.1:8300: dial tcp 172.17.0.1:8300: getsockopt: connection refused
    2016/03/14 11:04:24 [ERR] raft: Failed to AppendEntries to 172.17.0.2:8300: dial tcp 172.17.0.2:8300: getsockopt: connection refused
    2016/03/14 11:04:24 [ERR] raft: Failed to AppendEntries to 172.17.0.1:8300: dial tcp 172.17.0.1:8300: getsockopt: connection refused
    2016/03/14 11:04:27 [ERR] raft: Failed to heartbeat to 10.143.218.17:8300: dial tcp 10.143.218.17:8300: getsockopt: no route to host
    2016/03/14 11:04:27 [ERR] raft: Failed to AppendEntries to 10.143.218.17:8300: dial tcp 10.143.218.17:8300: getsockopt: no route to host
    2016/03/14 11:04:30 [ERR] raft: Failed to heartbeat to 10.143.218.17:8300: dial tcp 10.143.218.17:8300: getsockopt: no route to host
    2016/03/14 11:04:30 [ERR] raft: Failed to AppendEntries to 10.143.218.17:8300: dial tcp 10.143.218.17:8300: getsockopt: no route to host
    2016/03/14 11:04:33 [ERR] raft: Failed to AppendEntries to 192.168.135.3:8300: dial tcp 192.168.135.3:8300: i/o timeout

**Comment by slackpad** [comment] 2016-03-21 22:56
Hi @prashantabkari the [`-client`](https://www.consul.io/docs/agent/options.html#_client) option is what you set in order to get the HTTP (and DNS and RPC) sockets to bind to another interface. Currently, they default to loopback which I think is what you are seeing here. Note its generally a bad idea to bind these to an external interface from a security perspective. If you used `--net=host` for your Consul container I believe that would probably work better and allow you to keep these on loopback.

I noticed this in your log:

```
2016/03/14 11:04:23 [INFO] consul.fsm: EnsureRegistration failed: failed inserting service: failed inserting service: object missing primary index
```

It would be interesting to trace that down and see what service registration is leading to that. It shouldn't be possible to get that message because the service should fail the validation much earlier than that point.

**Comment by cshabi** [comment] 2017-02-16 11:32
Hi @slackpad ,

Im also seeing this message in my log:
consul.fsm: EnsureRegistration failed: failed inserting check: Missing service registration

What do you mean by tracing that down? how do I find which service is responsible for this message?

Thanks

**Comment by slackpad** [comment] 2017-04-12 01:18
> What do you mean by tracing that down? how do I find which service is responsible for this message?

That's a pretty weird low-level error so might need some instrumentation to fix. Can you reproduce getting Consul to emit that?

**Comment by slackpad** [comment] 2017-05-18 01:17
Closing this as we never heard back - please let us know if you are still seeing issues.

**Closed by slackpad** 2017-05-18 01:17 UTC
