### ISSUE TITLE
Consul > 1.4.0 returns NXDOMAIN for [tag].[service].service.consul

### ISSUE THREAD

**Issue by michaelgrosstarget** [hashicorp/consul#5599] opened 2019-04-03 16:50 UTC
Hello all,

I'm working to upgrade our consul clusters from 1.0.7 to 1.4.4 but have run into a problem with consul dns resolution.  Upgrading the agent to 1.4.1 or later causes dns requests for `[tag].[service].service.consul` (for example `active.vault.service.consul`) to return NXDOMAIN while just `[service].service.consul` (for example `vault.service.consul`) responds correctly.  If I try consul v1.4.0 then `[tag].[service].service.consul` resolves properly so it's something that changed between those 1.4.0 and 1.4.1.  Any suggestions on where to look or how to get more details?  Trace logging only shows that a request was processed.

Thank you,
Mike

With version 1.4.1:
```
# dig active.vault.service.consul  @127.0.0.1 -p 8600

; <<>> DiG 9.9.4-RedHat-9.9.4-73.el7_6 <<>> active.vault.service.consul @127.0.0.1 -p 8600
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 16167
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;active.vault.service.consul. IN    A

;; AUTHORITY SECTION:
consul.    0 IN SOA ns.consul. hostmaster.consul. 1554237212 3600 600 86400 0

;; Query time: 3 msec
;; SERVER: 127.0.0.1#8600(127.0.0.1)
;; WHEN: Tue Apr 02 20:33:32 UTC 2019
;; MSG SIZE  rcvd: 138
```

and from 1.4.0:
```
# dig active.vault.service.consul @127.0.0.1 -p 8600

; <<>> DiG 9.9.4-RedHat-9.9.4-73.el7_6 <<>> active.vault.service.consul @127.0.0.1 -p 8600
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 35366
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 2

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;active.vault.service.consul. IN    A

;; ANSWER SECTION:
active.vault.service.consul. 30    IN A 10.49.40.89

;; ADDITIONAL SECTION:
active.vault.service.consul. 30    IN TXT "consul-network-segment="

;; Query time: 2 msec
;; SERVER: 127.0.0.1#8600(127.0.0.1)
;; WHEN: Tue Apr 02 19:22:06 UTC 2019
;; MSG SIZE  rcvd: 140
```

**Comment by pearkes** [comment] 2019-04-03 22:31
To rule out issues with the data in the catalog, could you return the results of `consul catalog services -tags` in both setups? It could be that how the DNS response is sent has not changed but that the service is not registering correctly (with the right tags), causing this error. Also, because you're using Vault as the example, it may not be active during this query. You may want to try to reproduce with Vault out of the equation.

**Comment by michaelgrosstarget** [comment] 2019-04-04 07:11
Thank you for the response!  The tags are registered properly (`vault                               active,standby` from running `consul catalog services -tags | grep vault`)and the same issue is shown with other tagged services besides vault.

It looks like as long as I upgrade the servers first (to 1.4.4) then the new clients do not exhibit this behavior.  Below is the breakdown of when this issue occurs.
```
ability for clients to resolve [tag].[service].service.consul dns records:

                          server 1.0.7       server 1.4.4
client 1.0.7        successful        successful
client 1.4.4        failure               successful
```

I'm not sure if I overlooked a piece of documentation or if this falls under "don't jump so many versions at a time" :-)  I didn't test incremental server upgrades to see what the earliest version I could run without experiencing this as for us just getting the servers on latest before rolling it out to clients is sufficient.  Of note though is that I'm querying the dns resolver from the local consul agent, so I'm not sure what calls are made to the server that may not be getting the tag information or if it's even a concern given how many versions we're trying to upgrade at a time.

**Comment by mkeeler** [comment] 2019-04-04 14:16
@michaelgrosstarget I responded in the google group as well but for those who come here first I will reiterate a few things.

The general expectation is that version of Consul running the server agents will be at least as new as the version running on the client agents. We strive to ensure that older client agents when making requests to new server agents will produce correct results. The same cannot be said for newer clients talking to older servers.

In this particular case the client agents are sending somewhat modified RPC requests that can potentially use multiple tags for filtering instead of just one. The older server agent isn't looking for or recognizing the newer field and so the RPC isn't returning the desired results.

Jumping from 1.0.7 to 1.4.4 should be fine so long as the servers are upgraded first and then clients.

The standard upgrade procedures are documented here: https://www.consul.io/docs/upgrading.html#standard-upgrades

I will go ahead and close this issue as its expected behavior but if you run into any other issues or think that there is something else going on you can open a new issue (or I could reopen this one).

**Closed by mkeeler** 2019-04-04 14:16 UTC
Labels: needs-investigation, waiting-reply
