### ISSUE TITLE
Add logging of health-check status change

### ISSUE THREAD

**Issue by simonvanderveldt** [hashicorp/consul#2598] opened 2016-12-15 16:06 UTC
Currently Consul agent doesn't log any change in the health check status it's constantly performing. I was wondering if there's any particular reason this doesn't happen and if it can be added.

**Comment by mfischer-zd** [comment] 2016-12-20 20:49
I see it in my agent log.  I started with the following check JSON:

```json
{
  "ID": "test",
  "Name": "Test check",
  "Notes": "Always return true",
  "DeregisterCriticalServiceAfter": "90m",
  "Script": "test -f /tmp/yes",
  "Interval": "10s"
}
```

I then `touch /tmp/yes` and see the following:

```
    2016/12/20 12:48:28 [DEBUG] agent: check 'test' script 'test -f /tmp/yes' output: 
    2016/12/20 12:48:28 [DEBUG] agent: Check 'test' is passing
```

I then `rm /tmp/yes` and see the following:

```
    2016/12/20 12:49:18 [DEBUG] agent: check 'test' script 'test -f /tmp/yes' output: 
    2016/12/20 12:49:18 [WARN] agent: Check 'test' is now warning
```

**Comment by slackpad** [comment] 2017-05-02 00:31
Closing this as a duplicate of https://github.com/hashicorp/consul/issues/461.

**Closed by slackpad** 2017-05-02 00:31 UTC
