### ISSUE TITLE
Consul Go API accepts only a single node address

### ISSUE THREAD

**Issue by anoopengineer** [hashicorp/consul#1232] opened 2015-09-10 20:56 UTC
It would be good if we could provide multiple node address and the API was intelligent to select the best nodes and handle node failures internally. 

```go
// Config is used to configure the creation of a client
type Config struct {
	// Address is the address of the Consul server
	Address string

	// Scheme is the URI scheme for the Consul server
	Scheme string

	...
}
```

**Comment by armon** [comment] 2015-09-11 00:37
@anoopengineer The Consul model is that the agent handles that for you. You just communicate with the local agent, and it manages routing to healthy servers transparently.

**Comment by anoopengineer** [comment] 2015-09-11 01:48
What about scenario were agent goes down? If the API supported having a
list of servers/agents rather than a single hostname, we can afford
downtime of a few nodes without bringing down the entire application that
depends on consul.

-Anoop

**Comment by highlyunavailable** [comment] 2015-09-11 05:32
To expand on what @armon said, tn the vast majority of cases, there's a Consul agent on the same host as your code that will communicate with the Consul servers on your application's behalf. This means that usually, the scenario where the "agent goes down" means that the specific host that is running the code that created the Client is also down. Further, some of the calls in the client API are agent-specific (everything in `Client.Agent()`, e.g. the list of services on the local agent) so it would be bad API semantics in my opinionto have some sort of "fallback" agent that might return a completely different set of services, health checks, etc.

If you want to have a fallback Client if for some reason you cannot run a Consul agent on the same server as your application, I'd suggest creating a slice or map of Clients and handling failover between them in your application logic - this will ensure that you can handle any edge cases caused by calling Agent APIs against a remote agent in an appropriate way.

**Comment by anoopengineer** [comment] 2015-09-11 15:15
> To expand on what @armon said, in the vast majority of cases, there's a Consul agent on the same host as your code that will communicate with the Consul servers on your application's behalf.

I don't think having an agent on the same (and every) host where your app is running is a realistic architecture in most places. Even if it were, there is no way I can have rolling upgrade of Consul servers without bringing my entire application down. At least won't be able to bring down the consul agent without bringing down the application on that node.

>If you want to have a fallback Client if for some reason you cannot run a Consul agent on the same server as your application, I'd suggest creating a slice or map of Clients and handling failover between them in your application logic

Yes - this is definitely possible at the application side. But I believe for a critical system like consul which is used often as the infrastructure backbone and should be having high availability, it makes sense to have this made available in the standard API itself.

**Comment by highlyunavailable** [comment] 2015-09-11 17:09
> I don't think having an agent on the same (and every) host where your app is running is a realistic architecture in most places. Even if it were, there is no way I can have rolling upgrade of Consul servers without bringing my entire application down. At least won't be able to bring down the consul agent without bringing down the application on that node.

Why would you assume that a Consul Agent (in client mode) wouldn't be a good idea on every host? This is actually how Consul is [designed to be deployed](https://www.consul.io/docs/agent/basics.html).

Also, you can absolutely do a rolling upgrade of the Consul servers without bringing down your application - I've done it twice in production, in four different environments each time, from 0.4.0 to 0.5.0, then from 0.5.0 to 0.5.2. This is a supported upgrade method, see the [upgrade](https://www.consul.io/docs/upgrading.html) documentation.

You can either reuse the existing servers (as shown in the upgrade docs), or do what I did and bring up new VMs. Since Consul servers run in a quorum, all you need to do is upgrade them one at a time (though technically n/2-1 would be fine too, where n is quorum size). My method was: Bring up (n) more servers (say your cluster size is 3, so bring up 3 more servers with the new build), then join them to the same Consul cluster as your old servers before using a Graceful Leave (consul leave) on each of the old servers to remove them from the topology. You'll also need to update the start_join IPs on each agent if you don't reuse IPs from the old servers.

> Yes - this is definitely possible at the application side. But I believe for a critical system like consul which is used often as the infrastructure backbone and should be having high availability, it makes sense to have this made available in the standard API itself.

As I said previously, since Clients have agent-specific data returned based on what agent endpoint you hit, it would in my opinion be bad API semantics to have failover in the Client object itself due to the fact that two calls to the same Client object could return wildly different data - e.g. calling client.Agent().NodeName() could return two different values depending on which endpoint was hit.

**Comment by apparentlymart** [comment] 2015-09-14 22:38
In our Consul deployment we have some actions that are taken by hosts that are not considered "part of the cluster" and thus either don't have local Consul agents or have Consul agents that are members of a different cluster entirely.

For these cases where an outside agent is acting on the cluster, we've put an Amazon ELB in front of all of the Consul servers, so the external clients can connect to the ELB rather than to the servers directly. This is used only for ad-hoc API access (like reading keys with Terraform, for example) and isn't used to have nodes join the cluster.

Our current deployment takes this one step further by nominating one datacenter as what we call the "admin datacenter", which is where we run ``consul-replicate`` to push certain global key/value data out to other datacenters. We then adjusted our ELB to use only the servers from that datacenter, so external API clients can retrieve the "global" data without needing to worry about the idea of datacenters.

When it comes to having nodes actually *join* the cluster, we use the ELB as a "rally point" so that nodes can use the Consul registry to find the consul servers for a particular datacenter, as long as the admin datacenter remains up. They then ``consul join`` each of the discovered servers directly, and then henceforth the app uses the local Consul agent to interact with the server.

This seems to be working out okay for us so far. We can tolerate the loss of a single Consul server in the admin datacenter. If the "admin datacenter" is down for some reason then we'll need to do certain deployment steps manually, but we're expecting that to be rare enough (compared to the loss of a particular single Consul server) that we're willing to suffer through it in that event. Our apps themselves are proper members of the cluster and run their own Consul agents, and so once they are booted up they depend only on the health of the whole Consul cluster within their own DC.

**Comment by slackpad** [comment] 2016-04-13 05:45
Closing this out as the recommended way to talk to Consul is using a local agent, and other implementations likely use some kind of proxy or LB in front of the servers, so it would add confusion and complexity to make the API aware of multiple Consul endpoints.

**Closed by slackpad** 2016-04-13 05:45 UTC
