### ISSUE TITLE
Is there a consul agent reaping property?

### ISSUE THREAD

**Issue by vigneshsenapathy** [hashicorp/consul#3818] opened 2018-01-19 18:55 UTC
If you have a question, please direct it to the
[consul mailing list](https://www.consul.io/community.html) if it hasn't been
addressed in either the [FAQ](https://www.consul.io/docs/faq.html) or in one
of the [Consul Guides](https://www.consul.io/docs/guides/index.html).

When filing a bug, please include the following:

### Description of the Issue (and unexpected/desired result)
Consul agent is not reaping quickly. Want it to reap quickly when instance dies

### Reproduction steps
Node which has consul agent dies, so the perf health check goes to not passing
But the reaping on the agent/instance doesnt happen for around 8 hours or more. 
Is there any way this is configurable for changing the reaping to be lower

### `consul version` for both Client and Server
Client: `0.8.5`
Server: `0.8.5`

### `consul info` for both Client and Server
Client:
```
agent:
	check_monitors = 0
	check_ttls = 0
	checks = 2
	services = 2
build:
	prerelease =
	revision = 2c77151
	version = 0.8.5
consul:
	known_servers = 3
	server = false
runtime:
	arch = amd64
	cpu_count = 8
	goroutines = 57
	max_procs = 8
	os = linux
	version = go1.8.3
serf_lan:
	coordinate_resets = 0
	encrypted = false
	event_queue = 0
	event_time = 8
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 6
	member_time = 1908
	members = 41
	query_queue = 0
	query_time = 1
```

Server:
```
agent:
	check_monitors = 0
	check_ttls = 1
	checks = 3
	services = 4
build:
	prerelease =
	revision = 2c77151
	version = 0.8.5
consul:
	bootstrap = false
	known_datacenters = 1
	leader = true
	leader_addr = 
	server = true
raft:
	applied_index = 17585447
	commit_index = 17585447
	fsm_pending = 0
	last_contact = 0
	last_log_index = 17585447
	last_log_term = 22
	last_snapshot_index = 17584147
	last_snapshot_term = 22
	latest_configuration = []
	latest_configuration_index = 1
	num_peers = 2
	protocol_version = 2
	protocol_version_max = 3
	protocol_version_min = 0
	snapshot_version_max = 1
	snapshot_version_min = 0
	state = Leader
	term = 22
runtime:
	arch = amd64
	cpu_count = 2
	goroutines = 294
	max_procs = 2
	os = linux
	version = go1.8.3
serf_lan:
	coordinate_resets = 0
	encrypted = false
	event_queue = 0
	event_time = 8
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 6
	member_time = 1908
	members = 41
	query_queue = 0
	query_time = 1
serf_wan:
	coordinate_resets = 0
	encrypted = false
	event_queue = 0
	event_time = 1
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 27
	members = 3
	query_queue = 0
	query_time = 1
```

### Operating system and Environment details
docker image

**Comment by slackpad** [comment] 2018-01-25 02:16
Hi @vigneshsenapathy you currently can't lower that below 8 hours, but we've got https://github.com/hashicorp/consul/issues/2982 open to make it configurable per-agent. Closing this as a duplicate of that issue, since I think that would fit your use case.

**Closed by slackpad** 2018-01-25 02:16 UTC
