### ISSUE TITLE
Missing nodes get reaped immediately on next cluster bootup - in case of full cluster shutdown

### ISSUE THREAD

**Issue by mainframe** [hashicorp/consul#924] opened 2015-05-10 05:33 UTC
Not sure if its the bug or intended behaviour. If its intended behaviour it might need some explanation why is it made so.

Description:
I have 3-node consul cluster - when pulling power on 3rd node - it goes to failed status in consul member list - as it should. Now also powering down or crashing nodes 1-2 - for full cluster shutdown. Then booting up nodes 1-2 again - and once they form cluster quorum - 3rd node (which is still in shutdown) gets reaped immediately for some reason - and wont be shown in members list anymore. My expectation is that after full cluster shutdown/crash and partial bootup I will see remaining nodes in members list in failed status - until they get reaped after 72h or I issue force-remove manually. Currently Im losing member information after full cluster shutdown/crash. Interestingly RAFT peers.json will still contain full members list at all times (even after reaping event) - just 3rd node wont be seen in consul members list anymore. 

Steps to reproduce:
1. Crash or gracefully poweroff some cluster nodes - without loosing quorum
2. Crash or gracefully poweroff all remaining cluster nodes
3. Bootup enough cluster nodes in order to form quorum
4. Once leader is elected - all remaining nodes in powerdown get reaped immediately (event seen in log)

Example log with reaping event:

```
[root@nf-dev1 ~]# docker logs nf-consul
 2015/05/09 14:35:53 [INFO] serf: EventMemberJoin: nf-dev2.nf.int 10.211.55.69
    2015/05/09 14:35:53 [INFO] consul: adding server nf-dev2.nf.int (Addr: 10.211.55.69:8300) (DC: dc1)
    2015/05/09 14:35:53 [INFO] serf: EventMemberJoin: nf-dev2.nf.int.dc1 10.211.55.69
    2015/05/09 14:35:53 [INFO] consul: adding server nf-dev2.nf.int.dc1 (Addr: 10.211.55.69:8300) (DC: dc1)
    2015/05/09 14:35:53 [WARN] raft: Election timeout reached, restarting election
    2015/05/09 14:35:53 [INFO] raft: Node at 10.211.55.66:8300 [Candidate] entering Candidate state
    2015/05/09 14:35:53 [INFO] raft: Election won. Tally: 2
    2015/05/09 14:35:53 [INFO] raft: Node at 10.211.55.66:8300 [Leader] entering Leader state
    2015/05/09 14:35:53 [INFO] consul: cluster leadership acquired
    2015/05/09 14:35:53 [INFO] consul: New leader elected: nf-dev1.nf.int
    2015/05/09 14:35:53 [INFO] raft: pipelining replication to peer 10.211.55.69:8300
    2015/05/09 14:35:53 [INFO] consul: member 'nf-dev3.nf.int' reaped, deregistering
    2015/05/09 14:35:53 [WARN] raft: Failed to contact 10.211.55.70:8300 in 505.540584ms
    2015/05/09 14:35:54 [WARN] raft: Failed to contact 10.211.55.70:8300 in 936.931625ms
    2015/05/09 14:35:54 [WARN] raft: Failed to contact 10.211.55.70:8300 in 1.389435662s
    2015/05/09 14:35:55 [ERR] raft: Failed to heartbeat to 10.211.55.70:8300: dial tcp 10.211.55.70:8300: no route to host
    2015/05/09 14:35:55 [ERR] raft: Failed to AppendEntries to 10.211.55.70:8300: dial tcp 10.211.55.70:8300: no route to host
```

**Comment by mainframe** [comment] 2015-06-03 22:06
Any comments on this?

**Comment by ryanuber** [comment] 2015-06-03 23:43
@mainframe thanks for reporting this. This is happening in the gossip layer. After reading the code, it appears this is intentional. The gossip layer uses logical time only in its state which makes it more resilient to clock differences between the agents. My best guess at why the timers aren't restored is to avoid writing the local system time into the agent state to make this behavior more predictable. @armon can probably clarify here for us.

As for the peers.json file, that is intentionally left populated. You can read more about these types of failure scenarios in [this guide](https://consul.io/docs/guides/outage.html). Of particular interest here is the section on failed servers, which explains how this scenario may be recovered from.

I think the TL;DR is that this is working as intended, but I'll leave this open for now in case I missed something.

**Comment by mainframe** [comment] 2015-06-04 06:04
@ryanuber - correct me if Im wrong - but outage guide deals with recovering consul cluster and restoring the quorum after full outage. I have no problem with restoring the quorum and getting consul cluster working again - once enough nodes for quorum are up again. I have a problem that consul cluster members list is changed/reduced after outage recovery - when not all nodes are back up again. 

But let me illustrate the problem with the real use case - and why Im thinking its a problem:

1) Lets say we have 3 node consul cluster
```
Node            Address            Status  Type    Build  Protocol  DC
nf-dev1.nf.int  10.211.55.66:8301  alive   server  0.5.2  2         dc1
nf-dev2.nf.int  10.211.55.69:8301  alive   server  0.5.2  2         dc1
nf-dev3.nf.int  10.211.55.70:8301  alive   server  0.5.2  2         dc1
```
2) Now the full poweroff / outage happened
3) Lets say that after outage we manage to boot-up / recover nodes 1 and 2 - and node3 still stays down
4) Consul cluster forms with nodes 1 and 2 - quorum reached and cluster is operable - BUT nodelist is reduced/changed now to this (after reaping the node3 when node1-2 form the quorum):
```
Node            Address            Status  Type    Build  Protocol  DC
nf-dev1.nf.int  10.211.55.66:8301  alive   server  0.5.2  2         dc1
nf-dev2.nf.int  10.211.55.69:8301  alive   server  0.5.2  2         dc1
```
5) Our problem is that we are running Ceph cluster on top of consul cluster - and we are using consul member list in order to provide local host resolution (and generated configuration) to it. There would be no problem if after outage consul cluster would recover with nodes 1 and 2 up only - and members list would look like this (providing correct status overview of a cluster - with the member list as it was before outage):
```
Node            Address            Status  Type    Build  Protocol  DC
nf-dev1.nf.int  10.211.55.66:8301  alive   server  0.5.2  2         dc1
nf-dev2.nf.int  10.211.55.69:8301  alive   server  0.5.2  2         dc1
nf-dev3.nf.int  10.211.55.70:8301  failed  server  0.5.2  2         dc1
```
6) Ceph cluster would recover perfectly when node3 is still down yet present in members list (in failed state) - but it fails to recover when we are loosing node3 from nodelist/host resolution.

You could say that coupling local host resolution and ceph with consul members list is our problem :) But why Im thinking its a more generic problem for everyone? Because currently after outage and consul cluster auto-recovery you will end up with totally NEW cluster (changed member list) - in case enough nodes for quorum are up - but not all previous server nodes are up. I would expect that I will get OLD cluster status with failed nodes after outage - like it is also normally presented in case of node(s) failure (when still having quorum) - ie after outage I would expect to see this as members list (if node3 is still down):
```
Node            Address            Status  Type    Build  Protocol  DC
nf-dev1.nf.int  10.211.55.66:8301  alive   server  0.5.2  2         dc1
nf-dev2.nf.int  10.211.55.69:8301  alive   server  0.5.2  2         dc1
nf-dev3.nf.int  10.211.55.70:8301  failed  server  0.5.2  2         dc1
```

**Comment by mainframe** [comment] 2015-06-04 07:03
Interestingly this problem does not happen in the scenario when cluster quorum is lost - but there is still one node standing. Then it behaves as expected - ie keeps memberlist intact and lists failed members after partial recovery.

**Comment by armon** [comment] 2015-06-04 09:12
@mainframe I think the problem is that the node reaping is "best effort" in Serf. We do not persist the failed nodes, and their 72h grace period is only in memory. This means during a full cluster shut down, that state is lost. When the cluster comes back online the "failed" nodes are gone and so they are immediately reaped.

**Comment by mainframe** [comment] 2015-06-04 09:18
Thank you for explanation @armon. Would it be possible to make it persistent in the future releases or its by design?

**Comment by armon** [comment] 2015-06-04 09:37
It would be possible, it's just a deep change and rather low priority due to the edge case in which it is experienced. A full cluster outage is an atypical event.

**Comment by mainframe** [comment] 2015-06-04 09:53
For A-class datacenters power and service outages might be atypical - yes :)  Im more worried about manual full shutdown and auto-recovery ability. Is there any workaround to push/register missing nodes back to members list after new bootstrap - without these nodes being up and doing join?

**Comment by cbarbour** [comment] 2016-09-13 20:03
I just ran into this issue.

A full cluster outage is something that's actually fairly typical in small ephemeral environments. I'm using Consul to help build small self-service research compute clusters. For this use case, HA isn't really a requirement, the cluster will occasionally be shut-down for periods of time, and I really only want a single server node.

The clusters are built using Terraform, and services are registered using the Terraform Consul provider. Simply restarting Consul on the master node causes a full cluster outage.

The end result is that all the nodes are purged, and all the service data is lost until terraform re-applies its configuration.

**Comment by cornfeedhobo** [comment] 2017-04-28 21:01
Honestly, this is the only thing saving me right now. Check out #2981 for details.

**Comment by justinhenning** [comment] 2020-04-15 15:25
I see this is still open, anyone aware if this is still happening in latest versions? Can recreate with 3 nodes, 1 server, 2 client. Rebooting server nodes causes client nodes to be reaped and deregistered until manually restart on client.

**Comment by cornfeedhobo** [comment] 2020-04-15 19:39
@armon I'm returning to this ticket several years and companies later. Still running into this problem. Whole cluster outages *are* typical. A/B deployments, testing clusters, etc. Please reconsider your position here.

**Comment by crhino** [comment] 2020-04-16 15:38
HI @justinhenning and @cornfeedhobo,

I tried reproducing this myself with 2 scenarios:
### 1 Server, 2 Clients
Steps:
1. Shutdown the server node
2. Reboot server node
3. Check `consul members` to see if the client nodes were reaped.

In this scenario I see that the 2 client nodes ended up rejoining with the rebooted server.

### 3 Servers
Steps:
1. Kill 1 server node, wait for the other 2 nodes to re-elect a leader
2. Send `kill -STOP <consul-pid>` to the remaining 2 server nodes to simulate an immediate crash
3. Send `kill -CONT <consul-pid>` to the 2 server nodes to simulate the reboot
4. Check `consul members` to see whether the still down server node is reaped.

In this scenario I see the `consul-dc1-srv0` node is still in the members output and hasn't been reaped:
```
Node                Address          Status  Type    Build     Protocol  DC      Segment
consul-dc1-srv0     172.31.0.3:8301  left    server  1.7.0dev  2         chris1  <all>
consul-dc1-srv1     172.31.0.2:8301  alive   server  1.7.0dev  2         chris1  <all>
consul-dc1-srv2     172.31.0.5:8301  alive   server  1.7.0dev  2         chris1  <all>
consul-dc1-client0  172.31.0.6:8301  alive   client  1.7.0dev  2         chris1  <default>
consul-dc1-client1  172.31.0.4:8301  alive   client  1.7.0dev  2         chris1  <default>
```

I believe these scenarios cover the 2 cases mentioned in this ticket, but definitely let me know if something is different when you reproduce this.

In addition, I would like to know the following:
1. What version of Consul are you running and seeing this situation occur?
2. Are there any differences in your reproductions, e.g. Node IP changes, ephemeral disks being replaced, etc?

Thanks!

**Comment by ChipV223** [comment] 2021-04-07 18:17
HI @justinhenning and @cornfeedhobo!

Since it's been nearly a year since the last comment on this item and we have not been able to reproduce this on our end, I'll go ahead and close this. But if you have been able to reproduce this on your respective or have responses to the questions posed by @crhino in his last comment, feel free to respond!

**Closed by ChipV223** 2021-04-07 18:17 UTC
Labels: theme/operator-usability, type/enhancement, waiting-reply

**Comment by cornfeedhobo** [comment] 2021-04-07 18:40
I don't use consul anymore, but thanks for the heads up.
