### ISSUE TITLE
Clock drift on Windows with Consul >= 0.9.3

### ISSUE THREAD

**Issue by dennisdupont** [hashicorp/consul#3925] opened 2018-03-02 00:56 UTC
### Description of the Issue (and unexpected/desired result)
Experiencing excessive clock drift on Windows systems when consul >= 0.9.3 is running *and* connected to the cluster. 

We have a mixed cluster with all Linux servers, some Linux clients and some Windows clients.  Only the Windows systems experience the drift, Linux clients do not.  The clock drift begins as soon as consul is started with an initial drift of 100ms/sec.  Anecdotally this maxes out at 180 seconds off at which point NTP may be trying to adjust it back (but not completely understood yet).

Some observations:
- Tested the latest consul version 1.06 and still experienced the issue
- Tested 0.7.0, 0.8.0, 0.90, 0.9.1 and 0.9.2 and none of these experienced the issue

Desired result is that the system clock stays stable relative to the NTP source.

### Reproduction steps
I am downgrading my cluster, but I can reproduce this any time by running 0.9.3, so let me know if there is any issue reproducing.

Run consul >= v0.9.3 on a Windows system with either Win2003 or Win2008R2 (not yet tested on Win2012 or Win2016) attached to a domain.  
W32Time running as the (S)NTP client with a domain controller as the NTP source (not yet tested under other NTP clients or sources).
Compare time to the source (we used w32tm):
>w32tm /stripchart /computer:x.x.x.x /dataonly /samples:10
Tracking x.x.x.x [x.x.x.x:123].
Collecting 10 samples.
The current time is 2/28/2018 6:18:50 PM.
18:18:50, -113.1472053s
18:18:51, -112.7045555s
18:18:53, -112.2945822s
18:18:54, -111.8998771s
18:18:56, -111.5200829s

### `consul version` for both Client and Server
Client (Linux): Consul v0.9.3
Protocol 2 spoken by default, understands 2 to 3 (agent will automatically use protocol >2 when speaking to compatible agents)

Client (Windows):Consul v0.9.3
Protocol 2 spoken by default, understands 2 to 3 (agent will automatically use protocol >2 when speaking to compatible agents)

Server: Consul v0.9.3
Protocol 2 spoken by default, understands 2 to 3 (agent will automatically use protocol >2 when speaking to compatible agents)

### `consul info` for both Client and Server
Client:
```
agent:
        check_monitors = 0
        check_ttls = 0
        checks = 0
        services = 6
build:
        prerelease =
        revision = 112c060
        version = 0.9.3
consul:
        known_servers = 7
        server = false
runtime:
        arch = amd64
        cpu_count = 4
        goroutines = 39
        max_procs = 4
        os = windows
        version = go1.9
serf_lan:
        coordinate_resets = 0
        encrypted = false
        event_queue = 0
        event_time = 120
        failed = 0
        health_score = 0
        intent_queue = 0
        left = 0
        member_time = 137796
        members = 24
        query_queue = 0
        query_time = 1

```

Server:
```
agent:
        check_monitors = 0
        check_ttls = 0
        checks = 0
        services = 0
build:
        prerelease =
        revision = 112c060
        version = 0.9.3
consul:
        bootstrap = false
        known_datacenters = 1
        leader = false
        leader_addr = 10.200.2.162:8300
        server = true
raft:
        applied_index = 11339377
        commit_index = 11339377
        fsm_pending = 0
        last_contact = 37.0276ms
        last_log_index = 11339377
        last_log_term = 422005
        last_snapshot_index = 11335794
        last_snapshot_term = 422005
        latest_configuration = [{Suffrage:Voter ID:x.x.x.x:8300 Address:x.x.x.x:8300} {Suffrage:Voter ID:x.x.x.x:8300 Address:x.x.x.x:8300}
 {Suffrage:Voter ID:x.x.x.x:8300 Address:x.x.x.x:8300} {Suffrage:Voter ID:x.x.x.x:8300 Address:x.x.x.x:8300} {Suffrage:Voter ID:x.x.x.x:8300 Address:x.x.x.x:8300} {Suffrage:Voter ID:x.x.x.x:8300 Address:x.x.x.x:8300} {Suffrage:Voter ID:x.x.x.x:8300 Address:x.x.x.x:8300}]
        latest_configuration_index = 10813000
        num_peers = 6
        protocol_version = 1
        protocol_version_max = 3
        protocol_version_min = 0
        snapshot_version_max = 1
        snapshot_version_min = 0
        state = Follower
        term = 422005
runtime:
        arch = amd64
        cpu_count = 1
        goroutines = 143
        max_procs = 2
        os = linux
        version = go1.9
serf_lan:
        coordinate_resets = 0
        encrypted = false
        event_queue = 0
        event_time = 120
        failed = 0
        health_score = 0
        intent_queue = 0
        left = 0
        member_time = 137796
        members = 24
        query_queue = 0
        query_time = 1
serf_wan:
        coordinate_resets = 0
        encrypted = false
        event_queue = 0
        event_time = 1
        failed = 0
        health_score = 0
        intent_queue = 0
        left = 0
        member_time = 69
        members = 7
        query_queue = 0
        query_time = 1
```

### Operating system and Environment details
Clients: Windows 2003, 2008R2, Centos 6.6, Centos 7.4 (no issue on Centos systems)
Servers: Centos 7.4

### Log Fragments or Link to [gist](https://gist.github.com/)
I would need assistance to even decide what logs are appropriate.   Let me know and I will collect whatever is needed.

**Comment by dennisdupont** [comment] 2018-03-12 05:03
I have had to downgrade all of my Windows systems to get around this.  I would prefer to get onto the latest version.  Is there any suggestion on how to further investigate?  

I know Windows should not be used as servers (and we are not), but surely there would be others using Windows for clients.  We must be doing something wrong or others would surely have experienced/reported this.

**Comment by banks** [comment] 2018-03-13 15:09
Wow this is wild. I don't think Consul does anything with time other than read it using regular Golang standard library for getting the time.

Do any other applications affect the time on those hosts? It seems hard to know how it could be Consul specifically yet seems like you only see the issue when Consul is running?

If you stop Consul do the servers get back to no offset again? My limited understanding of Windows is that it won't just ping back but will gradually be drifted back into sync again.

Sanity check: what ports are you using for Consul and for NTP?

I'll see if anyone else knows more about Windows time than I do to have better guidance. We can try to reproduce although we know of a lot of people running new releases on windows without issue.

I note that Windows Server 2016 boasts about "much improved time sync" but how your problem can apparently be affected by different versions of Consul is pretty baffling!

**Comment by banks** [comment] 2018-03-13 15:19
Oh one more question: is there any virtualisation involved? If so are the above from the guest or hypervisor OS?

There are some painful known issues with HyperV for example as described here: https://blogs.msdn.microsoft.com/virtual_pc_guy/2010/11/19/time-synchronization-in-hyper-v/

**Comment by dennisdupont** [comment] 2018-03-14 00:28
Wild is definitely one way to put it.  

I heard from one person on Google Groups that mentions he is not having this issue but only runs win2012 or win2016.  We are on win2008r2 and some win2003, so maybe it is an OS interaction issue,

> Do any other applications affect the time on those hosts? It seems hard to know how it could be Consul specifically yet seems like you only see the issue when Consul is running (and only specific versions)?

We are running IIS and node along with consul (and of course the usual background OS tasks).  We are running a zabbix agent (a network management tool).  No other process seems to cause this issue (and again, as soon as we downgraded to 0.9.2, it all went away).  

> If you stop Consul do the servers get back to no offset again? My limited understanding of Windows is that it won't just ping back but will gradually be drifted back into sync again.

That's correct, the clock moves slowly back to perfect sync and stays there.  AFAIK that is standard NTP behavior, you don't want a quick clock jump.

> Sanity check: what ports are you using for Consul and for NTP?

I will check on ports from other apps, but I am sure there is no overlap of consul and "NTP" (we use windows time client which is really SNTP from what I gather).  And we use the same ports for the various versions of consul

> Oh one more question: is there any virtualisation involved? If so are the above from the guest or hypervisor OS?

All of our servers are VMs on Hyper-V.  That said, we have made sure to accommodate the nuances of time on Hyper-V VMs.  All run the (S)NTP service back to a domain controller and do not use the local timing.  Besides, if this was related we would have a problem even if consul was not running.

One more thing to keep in mind, that consul itself does not cause the problem, only if it is joined to the cluster.  Running it locally in dev mode does not cause the drift.

Thanks for the feedback!

**Comment by dennisdupont** [comment] 2018-03-14 00:48
Looking at the changelog for 0.9.3 one thing that is a remote possibility is the transition to Go 1.9:

> Go 1.9 adds transparent monotonic time support, which makes computing durations between two Time values a safe operation in the presence of wall-clock adjustments.

Not a Go expert and I'm grasping at straws, but maybe this could be a problem on the win2008r2 OS.

**Comment by banks** [comment] 2018-03-14 11:27
Yeah I was going to suggest go version change might be the root cause since we've not changed anything in our usage of timing AFAIK.

A colleague who is familiar with Windows also noticed the monotonic time change which looks like a reasonable lead. The issue is, I can't find any trace on the internet of go1.9 programs affecting windows servers which seems unbelievable if it's a simple as "calling time.* a lot in a go app on windows causes drift since 1.9".

It's interesting to note though that there are other anecdotal cases where Java had similar issues see https://stackoverflow.com/questions/102064/clock-drift-on-windows

> There's an issue with Windows that if you change the timer resolution with timeBeginPeriod() a lot, the clock will drift.

It may well be that the new go 1.9 timing Assembly does something like that affecting older windows versions. But again it seems unlikely that no one noticed this in the last 7 months since go 1.9 release.

The final quirk is that you report drift only really noticeable once connected to cluster.

Our best guess there so far which may be overfitting the evidence is that if go1.9 timing code is to blame, Consul only really starts managing a lot of timers once network connections come up and timeouts are being handled etc so it could just be that Consul in dev mode isn't hitting time API frequently enough for you to see the drift before NTP corrects it.

We'll try to dig some more on precisely what the windows go1.9 assembly does and whether it may trigger that bug that was proposed.

If you are able, it might be interesting (although not sure how likely to work) to write a short go program like:

```go
package main
import "time"
import "fmt"
func main() {
  for {
     fmt.Println("Now it is %s", time.Now())
     time.Sleep(1 * time.Millisecond)
  }
}
```

Download go 1.9 and run it with `go run time.go`. The output will be super spammy so you can discard it - it's just to make sure the timer call is not removed by the compiler because the value is unused by anything.

If it's a simple as we are suggesting, that program should immediately have a noticeable affect on your clock drift.

I may well try this if you don't get to it but so far don't have a windows server handy to test it on. 

Hope this helps.

**Comment by banks** [comment] 2018-03-14 11:58
Interestingly there was a new patch in go1.10 that further optimised the windows time ASM: https://go-review.googlesource.com/c/go/+/36428

The comment mentions "reducing skew" but I think it's referring to skew between the monotonic and wall times recorded rather than reference to a known issue with clock drift (no such issue or discussion found).

The most likely cause still seems to be interaction of Go monotonic clock code and your windows versions.

More concrete references for the possibly-related JVM issue: https://bugs.java.com/view_bug.do?bug_id=4717583 although they were only speculating that regularly changing timer resolution was the cause of clock drift.

I can't find any obvious code in Golang that calls the problematic windows APIs that Java did but I've never done work in ASM much let alone on windows so I'll have someone more familiar take a quick look too.

**Comment by dennisdupont** [comment] 2018-03-14 15:56
Thanks for the suggestions.  I was going a slightly different route.  I downloaded Go 1.8 and rebuilt Consul v0.9.3 with the older compiler (crossing my fingers that there was no incompatibility).  That compiled fine, so I put this on my test client and voila - no clock drift!

As you said, this is astounding that 7 months into the Go release there is not a peep of this on the Internet (at least that my good friend Google can find).  There has to be some obscure combination of Windows version, Consul timer usage and the Go changes that conspired against me :)  

I will still be going down the path of testing on later Windows versions, but I'm pretty sure win2008r2 is still widely used.  Maybe just not by Consul users, perhaps they are more cutting edge and are generally on later versions.

I will also try the latest go and see whether that makes any difference.  I too got lost in their ASM code so just fault isolating by trial and error seems the best next step.

Will keep you updated. Thanks for the assistance/ideas/etc.

**Comment by dennisdupont** [comment] 2018-03-14 17:38
Latest go@1.10 also exhibits the clock drift (still with Consul@0.9.3).

I think now the trick will be to find a test program that shows the same behavior.  I will try the small snippet you sent for starters.

**Comment by dennisdupont** [comment] 2018-03-14 18:13
No joy on the simple time.go test.  I added a time.Since() call as well.  Can you suggest some code with the Timer type?  I have never coded in Go and it might take me some time to understand using channels.

**Comment by banks** [comment] 2018-03-14 20:17
Something like https://play.golang.org/p/EDkbMCCNSfN

That is a limited for loop just to make it work in go playground but remove the loop condition to `for {` for infinite loop.

I doubt it will be different though - as far as I could see Timer uses same system primitives as Time and Sleep.

**Comment by dennisdupont** [comment] 2018-03-15 04:25
I think we have something here.  I changed your sample code to use a log of simultaneous timers (I think):  https://play.golang.org/p/NRDKbUEP6-S

This will cause a shift in the clock, although not nearly as dramatic as with consul running.  The two graphs below show a change from a stable clock with drift on the order of .01 without the Go test running to a drift of up to 0.35 with the test.    Of course if this was all we experienced, I would not care, but with Consul running we get much larger problems (nominally 50 seconds but up to 180).

![image](https://user-images.githubusercontent.com/8162159/37444135-250149fa-27de-11e8-977f-93ef2e2ccfcb.png)
![image](https://user-images.githubusercontent.com/8162159/37444307-ca465536-27de-11e8-992f-869e39e4957a.png)

**Comment by dennisdupont** [comment] 2018-03-15 04:28
BTW - tomorrow I will try to re-run both the consul measurements as well as the test code on win2012 and/or win2016.

Also - let me know if you have better ideas on the test code to simulate more of what Consul does.  I fear my changes reek of Go ignorance.

**Comment by banks** [comment] 2018-03-15 12:05
Wow good job.

The go you linked is not bad Go style although what it's doing is odd in the sense that there are simpler ways to get lots of timers running. It's so far from obvious what is actually causing the drift though that it might be you need all the complexity in there to actually trigger the right symptom!

Strange thing is I don't _think_ Consul would normally use wildly more timers than that so it may not be the number but the frequency they trigger or something?

Here are a couple of suggestions that try to narrow down to a specific timer behaviour, perhaps you could try each one and report the level of drift it induces (if any) and maybe we can hone in on a minimal reproduction?

https://play.golang.org/p/4y79262HSrJ

You can call this with arguments to try varying the number of timers, the time before they alarm and the sleep between iterations:

```
$ go run timers.go -h
Usage of /var/folders/8t/n45q26t16fvg2z1hwp1_g2240000gn/T/go-build648388310/b001/exe/timers:
  -n int
    	number of timers to run per iteration (default 5000)
  -s int
    	milliseconds to sleep between iteration run for (default 100)
  -t int
    	milliseconds timers run for (default 1)
```

Would be interested to see if the defaults trigger the drift. If not try with different `-t` say 10,100, different `-n` say 1000, 10000, different `-s` say 1,10.

If none reproduce or none to the same extent as your example, then there is a chance it's something I removed like the `Reset()` that causes it. You could try again with:

https://play.golang.org/p/mrcF0T7yozP

same but resetting instead of recreating.

If still no luck then then it could be the fact that your example is cancelling all the timers as well before they can fire so a version that does the same would be:

https://play.golang.org/p/-U2UcJ1Eh_A

Those are just some suggestions that might help isolate if it's specific to resetting timer, stopping timers, many concurrent timers etc.

I'll see if I can come up with any more plausible Consul-like simulation but most timers are not explicit ones but ones buried under read and write deadlines on network connections and similar.

Hope this is useful, if we can get a reasonable reproduction that is at least somewhat minimal, I'd say it's worth filing a go bug for.

**Comment by dennisdupont** [comment] 2018-03-15 20:43
I will add these to my testing tasks.

Since this only occurs when the agent joins the cluster (but not as a server), then I was thinking something in the serf code - maybe there is some serf unit testing code we could use as a starting point?

**Comment by banks** [comment] 2018-03-19 14:49
https://github.com/hashicorp/memberlist/blob/9bdd37bfb26bd039c08b0f36be6f80ceede4aaf3/state.go#L82

`Schedule` there and the methods below seem to be the foundation of what Serf is doing - making tickers (although not thousands if I understand that code right) and `time.After` calls to enforce timeouts etc.

**Comment by dennisdupont** [comment] 2018-03-20 15:41
Finally got free from my real job again.  Ran consul on win2012 and the drift problem does NOT appear on that version.  Most (if not all) feedback I've had on the forums have indicated they were using win2012 or greater, so this makes a lot more sense now.

I will try to get back to the go examples to see if I can get to a simple reproduction snippet.

**Comment by dennisdupont** [comment] 2018-03-20 22:46
Found this interesting issue/discussion on the go site:  https://github.com/golang/go/issues/22394
Unfortunately consul built under 1.9.4 has the same issue.  Still need to find the right example code.

**Comment by dennisdupont** [comment] 2018-03-21 02:02
"Okey dokey. Lets fire blue particle cannons full, red particle cannons full..." - all three of your test snippets resulted in the consul level clock drift!  Way more than my measly millisecond drifts, clock was off and running quickly:

19:01:09, +00.1004366s
19:01:11, +00.1004750s
19:01:13, +00.1161380s
19:01:15, +00.1005518s
19:01:17, +00.1162148s
19:01:19, +00.0977069s
19:01:21, -00.1268551s
19:01:23, -00.2908723s
19:01:25, -00.5056711s
19:01:27, -00.6911698s
19:01:29, -00.8874145s
19:01:31, -01.0787722s
19:01:33, -01.2652513s
19:01:35, -01.4660892s
19:01:37, -01.5328950s

**Comment by pearkes** [comment] 2018-07-24 20:38
I tagged this a "bug" even though it seems to be upstream at this point. We'll leave it open for the sake of future users but otherwise it'd be great if you could keep us posted here @dennisdupont. Note we typically upgrade to the latest stable Go version ahead of each release, and that you can view the go version a binary was built with using `consul info` against a running agent.

**Comment by david-yu** [comment] 2023-09-28 03:21
Closing as this is issue is quite old and now outdated due to its age. Please file a new issue if this issue still exists.

**Closed by david-yu** 2023-09-28 03:21 UTC
Labels: type/bug, theme/windows
