### ISSUE TITLE
Incorrect ModifyIndex of unchanged KV entry in response on transaction

### ISSUE THREAD

**Issue by a-zagaevskiy** [hashicorp/consul#7826] opened 2020-05-09 11:59 UTC
#### Overview of the Issue

Before I've updated a cluster on Consul v1.6.5, I could rely on ModifyIndexes that are returned in a response of a transaction. But now ModifyIndexes returned in the response are wrong for the entries that are not actually changed during the transaction.

#### Reproduction Steps

1. Create a cluster
2. Create an entry into KVStore
3. Execute a `cas` transaction that tries to change the entry. The provided value should be the same.
4. See at ModifyIndex returned in the response of the transaction
5. Check actual ModifyIndex for the entry (with another reading transaction or with simple /v1/kv/ request)

ModifyIndexes should be equal but they don't.

### Consul info for both Client and Server

I think it doesn't matter.

### Operating system and Environment details

Consul v1.6.5

### Log Fragments

I think it doesn't matter too.

**Comment by AlexanderZagaevskiy** [comment] 2020-05-09 12:02
There is my proposal on how it could be fixed: https://github.com/hashicorp/consul/pull/5885/files#r422432993

**Comment by i0rek** [comment] 2020-05-11 06:35
Thank you for your detailed report, I think you are absolutely right. Would you like to create a PR for it?

**Comment by a-zagaevskiy** [comment] 2020-05-11 11:08
Sure. Here it is: https://github.com/hashicorp/consul/pull/7832

**Comment by i0rek** [comment] 2020-05-11 19:36
@a-zagaevskiy I tried to reproduce your problem, but it seems to work for me unless I am doing something else than you described:

```
consul agent -dev
consul kv put a 1
curl -X PUT --data @payload.json http://127.0.0.1:8500/v1/txn
```

with payload.json:

```
[
  {
    "KV": {
      "Verb": "cas",
      "Key": "a",
      "Value": "MQo=",
      "Index": 15
    }
  }
]
```

When I repeat 

```
curl -X PUT --data @payload.json http://127.0.0.1:8500/v1/txn
```

over and over, and only change the Index to what was returned from the call before, it works for me.

Could you help me reproduce your issue?

**Comment by a-zagaevskiy** [comment] 2020-05-11 21:04
@i0rek I've just downloaded the latest official release (v1.7.3) and been able to reproduce the issue just by following your steps. Below is what I've gotten.

Just after the creation of `a`
```
$ curl http://localhost:8500/v1/kv/a
[
    {
        "LockIndex": 0,
        "Key": "a",
        "Flags": 0,
        "Value": "MQ==",
        "CreateIndex": 13,
        "ModifyIndex": 13
    }
]
```
To get quickier to the matter, let's change payload.json from your example so that it has the same `Value` from the very beginning:
```
[
    {
        "KV": {
            "Verb": "cas",
            "Key": "a",
            "Value": "MQ==",
            "Index": 13
        }
    }
]
```
That is what I've had after the first transaction:
```
$ curl -XPUT --data @payload.json http://localhost:8500/v1/txn
{
    "Results": [
        {
            "KV": {
                "LockIndex": 0,
                "Key": "a",
                "Flags": 0,
                "Value": null,
                "CreateIndex": 13,
                "ModifyIndex": 65
            }
        }
    ],
    "Errors": null
}
```
It is already possible to check that actual ModifyIndex remains unchanged despite what we've seen above. You just have to run `curl http://localhost:8500/v1/kv/a` (the output will be equal to the above one).

And finally, after changing `Index` in payload.json to the one that was returned in the respond of the previous transaction (in my case, it is 65), I've bumped into the error:
```
$ curl -XPUT --data @payload.json http://localhost:8500/v1/txn
{
    "Results": null,
    "Errors": [
        {
            "OpIndex": 0,
            "What": "failed to set key \"a\", index is stale"
        }
    ]
}
```

I hope I've described it quite clear.

**Comment by freddygv** [comment] 2020-05-12 01:34
@i0rek it seems like the issue stems from how the TXN returns the entry that it tries to insert:
https://github.com/hashicorp/consul/blob/master/agent/consul/state/txn.go#L95-L108

Before #5885 the ModifyIndex would always be the index of the transaction, since we didn't check if the existing entry was the same. 

The problem now is that TXN API will return the index of the operation as if it was applied, even though it isn't applied when the value is the same.

We might try a set an entry in a transaction at index 5 for an entry in index 3. The insert is rejected because the entry is the same (due to #5885). TXN returns modify index of 5 because it assumes the index is applied, but the entry was never modified and is still at 3. More calls to the TXN api would show a growing ModifyIndex on the entry that doesn't reflect the index in the state store.

**Comment by freddygv** [comment] 2020-05-19 17:43
Fixed by: #7832

**Closed by freddygv** 2020-05-19 17:43 UTC
Labels: post-beta, type/bug

**Comment by chnrxn** [comment] 2023-07-05 14:57
I have code that depends on ModifyIndex to be updated on a PUT (even with the same value) because we want to detect stale keys. With this change, our code now is not able to detect when keys are actually being written to. 

Is it possible to have an option to retain the old behavior?

**Comment by a-zagaevskiy** [comment] 2023-09-13 12:07
@chnrxn I think the original behavior was changed in #5885 . These changes are just logical continuation of new behavior.
