### ISSUE TITLE
configuration file client_addr is ignored in consul 1.4.0

### ISSUE THREAD

**Issue by vvitayau** [hashicorp/consul#5066] opened 2018-12-06 19:19 UTC
Misbehavior by https://www.consul.io/docs/agent/options.html#client_addr

"client_addr": "0.0.0.0", does not properly work when specified within the configuration file.
```
$ netstat -na | grep -E "8500|8600"
tcp        0      0 169.254.1.1:8500        0.0.0.0:*               LISTEN
tcp        0      0 169.254.1.1:8600        0.0.0.0:*               LISTEN
udp        0      0 169.254.1.1:8600        0.0.0.0:*
```

The expected behavior only works if I pass the argument via command line during startup -client 0.0.0.0
```
$ netstat -na | grep -E "8500|8600"
tcp6       0      0 :::8500                 :::*                    LISTEN
tcp6       0      0 :::8600                 :::*                    LISTEN
udp6       0      0 :::8600                 :::*
```

#### Overview of the Issue

https://www.consul.io/docs/agent/options.html#client_addr is ignore when specified ``"client_addr": "0.0.0.0",`` within the configuration file.

I was able to ``nslookup consul.service.consul`` through the dummy interface 169.254.1.1 but unable to query against consul directly on port 8500. That's because it was only listening on the dummy interface and not available via eth0 nor the loopback interface.

I was able to resolve the issue by including `-client 0.0.0.0` in the command line arguments

### Consul info for both Client and Server

<details>
  <summary>Client info</summary>
agent:
        check_monitors = 0
        check_ttls = 0
        checks = 0
        services = 3
build:
        prerelease =
        revision = 0bddfa23
        version = 1.4.0
consul:
        acl = disabled
        bootstrap = false
        known_datacenters = 1
        leader = true
        leader_addr = 172.31.87.21:8300
        server = true
raft:
        applied_index = 20
        commit_index = 20
        fsm_pending = 0
        last_contact = 0
        last_log_index = 20
        last_log_term = 2
        last_snapshot_index = 0
        last_snapshot_term = 0
        latest_configuration = [{Suffrage:Voter ID:c31a468f-e261-5015-7895-9be8c17392c7 Address:172.31.87.21:8300}]
        latest_configuration_index = 1
        num_peers = 0
        protocol_version = 3
        protocol_version_max = 3
        protocol_version_min = 0
        snapshot_version_max = 1
        snapshot_version_min = 0
        state = Leader
        term = 2
runtime:
        arch = amd64
        cpu_count = 2
        goroutines = 78
        max_procs = 2
        os = linux
        version = go1.11.1
serf_lan:
        coordinate_resets = 0
        encrypted = true
        event_queue = 1
        event_time = 2
        failed = 0
        health_score = 0
        intent_queue = 1
        left = 0
        member_time = 2
        members = 1
        query_queue = 0
        query_time = 1
serf_wan:
        coordinate_resets = 0
        encrypted = true
        event_queue = 0
        event_time = 1
        failed = 0
        health_score = 0
        intent_queue = 0
        left = 0
        member_time = 1
        members = 1
        query_queue = 0
        query_time = 1
</details>

<details>
  <summary>Server info</summary>

```
output from server 'consul info' command here
```

</details>

### Operating system and Environment details

CentOS Linux release 7.5.1804 (Core)
Consul v1.4.0

### Log Fragments

```
Dec 06 17:24:23 node1 consul[20349]: agent: Started DNS server 169.254.1.1:8600 (tcp)
Dec 06 17:24:23 node1 consul[20349]: agent: Started HTTP server on 169.254.1.1:8500 (tcp)
```

**Comment by pearkes** [comment] 2018-12-07 17:01
Thanks for opening an issue! I'm having trouble reproducing this. See below for an example, I'd verify your configuration and look into go-sockaddr.

```
$ cat foo.hcl
enable_debug = false
bootstrap = true
server = true
data_dir = "/tmp/csl-debug"
bind_addr = "{{ GetPrivateIP }}"
log_level = "WARN"
client_addr = "{{ GetPrivateIP }}"
debug-conf $ consul agent -config-file=foo.hcl
bootstrap = true: do not enable unless necessary
==> Starting Consul agent...
==> Consul agent running!
           Version: 'v1.4.0'
           Node ID: '36aa7a6f-d862-fa94-60f5-a04bb4acb393'
         Node name: 'pearkes'
        Datacenter: 'dc1' (Segment: '<all>')
            Server: true (Bootstrap: true)
       Client Addr: [192.168.2.1] (HTTP: 8500, HTTPS: -1, gRPC: -1, DNS: 8600)
      Cluster Addr: 192.168.2.1 (LAN: 8301, WAN: 8302)
           Encrypt: Gossip: false, TLS-Outgoing: false, TLS-Incoming: false

==> Log data will now stream in as it occurs:

    2018/12/07 08:55:50 [WARN] serf: Failed to re-join any previously known node
    2018/12/07 08:55:50 [WARN] serf: Failed to re-join any previously known node
^C    2018/12/07 08:55:51 [WARN] serf: Shutdown without a Leave
    2018/12/07 08:55:51 [ERR] agent: failed to sync remote state: No cluster leader
    2018/12/07 08:55:51 [WARN] serf: Shutdown without a Leave
$ cat foo.hcl
enable_debug = false
bootstrap = true
server = true
data_dir = "/tmp/csl-debug"
bind_addr = "{{ GetPrivateIP }}"
log_level = "WARN"
client_addr = "0.0.0.0"
$ consul agent -config-file=foo.hcl
bootstrap = true: do not enable unless necessary
==> Starting Consul agent...
==> Consul agent running!
           Version: 'v1.4.0'
           Node ID: '36aa7a6f-d862-fa94-60f5-a04bb4acb393'
         Node name: 'pearkes'
        Datacenter: 'dc1' (Segment: '<all>')
            Server: true (Bootstrap: true)
       Client Addr: [0.0.0.0] (HTTP: 8500, HTTPS: -1, gRPC: -1, DNS: 8600)
      Cluster Addr: 192.168.2.1 (LAN: 8301, WAN: 8302)
           Encrypt: Gossip: false, TLS-Outgoing: false, TLS-Incoming: false

==> Log data will now stream in as it occurs:

    2018/12/07 08:56:23 [WARN] serf: Failed to re-join any previously known node
    2018/12/07 08:56:23 [WARN] serf: Failed to re-join any previously known node
    2018/12/07 08:56:30 [ERR] agent: failed to sync remote state: No cluster leader
    2018/12/07 08:56:30 [WARN] raft: Heartbeat timeout from "" reached, starting election
c^C    2018/12/07 08:56:35 [WARN] serf: Shutdown without a Leave
    2018/12/07 08:56:35 [WARN] serf: Shutdown without a Leave
```

Going to close this for now but if you're able to reproduce the problem let us know.

**Closed by pearkes** 2018-12-07 17:01 UTC

**Comment by aurelienrb** [comment] 2019-02-21 19:14
fyi I faced the same issue after upgrading my Consul version, and that was caused by an invalid extension for my config file (`.conf` to be changed to `.json`)

Maybe the CLI interface could check the file extension and trigger an error if it is invalid rather than silently ignoring the file?
