### ISSUE TITLE
Key/Value Store: Long Keys are displayed wrong

### ISSUE THREAD

**Issue by Fival85** [hashicorp/consul#2952] opened 2017-04-25 06:25 UTC
Hello, we are using Consul and Consul UI and have the following bug. I dont find an issue for this.

### `consul version` for both Client and Server
Client: Browser
Server: Consul v0.7.5

### `consul info` for both Client and Server
Client:
```
not necessary because it is a UI bug
```

Server:
```
 ./consul info
agent:
        check_monitors = 0
        check_ttls = 0
        checks = 8
        services = 9
build:
        prerelease =
        revision = '21f2d5a
        version = 0.7.5
consul:
        bootstrap = false
        known_datacenters = 1
        leader = false
        leader_addr = 10.196.3.145:8300
        server = true
raft:
        applied_index = 2464860
        commit_index = 2464860
        fsm_pending = 0
        last_contact = 20.320819ms
        last_log_index = 2464860
        last_log_term = 145
        last_snapshot_index = 2458042
        last_snapshot_term = 145
        latest_configuration = [{Suffrage:Voter ID:10.196.3.144:8300 Address:10.196.3.144:8300} {Suffrage:Voter ID:10.196.3.145:8300 Address:10.196.3.145:8300} {Suffrage:Voter ID:10.196.3.143:8300 Address:10.196.3.143:8300}]
        latest_configuration_index = 1954581
        num_peers = 2
        protocol_version = 1
        protocol_version_max = 3
        protocol_version_min = 0
        snapshot_version_max = 1
        snapshot_version_min = 0
        state = Follower
        term = 145
runtime:
        arch = amd64
        cpu_count = 4
        goroutines = 89
        max_procs = 4
        os = linux
        version = go1.7.5
serf_lan:
        encrypted = true
        event_queue = 0
        event_time = 7
        failed = 0
        health_score = 0
        intent_queue = 0
        left = 0
        member_time = 79
        members = 3
        query_queue = 0
        query_time = 1
serf_wan:
        encrypted = true
        event_queue = 0
        event_time = 1
        failed = 0
        health_score = 0
        intent_queue = 0
        left = 0
        member_time = 4
        members = 1
        query_queue = 0
        query_time = 1
```

### Operating system and Environment details
Linux

### Description of the Issue (and unexpected/desired result)
In the KeyValue-Store from Consul a long key like an "hystrix command key" will be not displayed correctly. The key is behind the Textbox and the Textbox is empty

### Reproduction steps
Use this key _hystrix.command.commandName.execution.isolation.thread.timeoutInMilliseconds_

**Comment by Fival85** [comment] 2017-04-25 06:41
Here you could see the problem
![to_long_key](https://cloud.githubusercontent.com/assets/11659931/25371828/eec821dc-2992-11e7-80e0-7e4c97e52e87.JPG)

**Comment by slackpad** [comment] 2017-04-26 00:53
Hi @Fival85 thanks for opening an issue. I'm going to close this as a duplicate of https://github.com/hashicorp/consul/issues/1769, since the fix'll be in the same place.

**Closed by slackpad** 2017-04-26 00:53 UTC
