### ISSUE TITLE
DNS resolving using master and replica tags does not work

### ISSUE THREAD

**Issue by uranru** [hashicorp/consul#21359] opened 2024-06-21 11:34 UTC
#### Overview of the Issue

DNS resolution using master and replica tags does not work in version 1.19.
It works in version 1.18.2

---

#### Reproduction Steps

dig A master.grafana-db.service.consul @127.0.0.1 -p 8600
dig A replica.grafana-db.service.consul @127.0.0.1 -p 8600

### Consul info for both Client and Server

<details>
  <summary>Client info</summary>

```
Output from client 'consul info' command here
```

```
Client agent HCL config
```

</details>

<details>
  <summary>Server info</summary>

```
Output from server 'consul info' command here
```

```
Server agent HCL config
```

</details>

**Comment by maxadamo** [comment] 2024-06-22 19:53
duplicate of #21336

**Comment by DanStough** [comment] 2024-06-24 15:53
Closing as a duplicate of #21336

**Closed by DanStough** 2024-06-24 15:53 UTC
