### ISSUE TITLE
Connection reset by peer

### ISSUE THREAD

**Issue by phamtai97** [hashicorp/consul#7257] opened 2020-02-11 04:26 UTC
Hi all.
I deploy the Consul server cluster includes 3 nodes and 3 Consul agent. Then I use [vertx-consul-client](https://vertx.io/docs/vertx-consul-client/java/) to call Consul agent. I see error:

```sh
syscall:read(..) failed: Connection reset by peer
, stackTrace: io.netty.channel.unix.Errors$NativeIoException: syscall:read(..) failed: Connection reset by peer
	at io.netty.channel.unix.FileDescriptor.readAddress(..)(Unknown Source)
```

So, before I only deploy a single node Consul server, I have not this issue.

**Comment by ygilbaum** [comment] 2020-02-13 19:50
The same. 3 of each 10 attempts to read key via API finished with the error. The same behavior on 1.6.3 and 1.7.0. I reverted to use 1.6.2, that works perfect.

**Comment by obourdon** [comment] 2020-02-14 05:24
Also seems like #7259

**Comment by phamtai97** [comment] 2020-02-14 09:38
oh yes, I rollbacked version to v.1.6.1 and it works perfectly.

**Comment by ChipV223** [comment] 2020-03-23 14:13
Closing this as this is a dupe of #7259

**Closed by ChipV223** 2020-03-23 14:13 UTC
