### ISSUE TITLE
Memory leak when many clients are watching /v1/event/list

### ISSUE THREAD

**Issue by choppedpork** [hashicorp/consul#3941] opened 2018-03-06 13:35 UTC
@banks note: repro case described in https://github.com/hashicorp/consul/issues/3941#issuecomment-409914501

### Description of the Issue (and unexpected/desired result)
I'm seeing a slow but definitely consistent memory leak from Consul. From all I can see, this is only happening to agent nodes but not server nodes. The most we've seen the usage creep up to is 2GB.

The setup (for the environment I grabbed the profiling data from) is:
- 3 node server cluster
- 8 agent nodes
- 60 KVs
- 101 services registered in the consul catalog
- 179 registered healthchecks

Most of the services and almost all the healthchecks are registered by our applications, which use the spring-cloud-consul library for direct API integration (this is also why we're still on 0.9.3 - we've not updated our framework yet). We don't use Consul DNS nor watches / sessions from the applications.

We see this in differently dimensioned environments too - sometimes we have less/more services, healthchecks + KVs and/or less/more agent nodes (the server cluster is always 3 nodes).

Here's some memory usage (RSS) data I gathered using cAdvisor. This does not seem to be happening to the server nodes:
![screen shot 2018-03-06 at 13 21 11](https://user-images.githubusercontent.com/11997044/37034475-4f36bf82-2141-11e8-81a4-6dd7635727d7.png)

On the agent nodes however:
![screen shot 2018-03-06 at 13 22 31](https://user-images.githubusercontent.com/11997044/37034529-76dd1108-2141-11e8-9397-932b0307b9e7.png)

CPU usage seems to match the memory usage pattern which I guess has to do with more GC runs as the heap increases?
![screen shot 2018-03-06 at 13 23 50](https://user-images.githubusercontent.com/11997044/37034578-a8b93aa8-2141-11e8-8c7b-ed92be89b68c.png)

The mid-February dip in the graphs is when the entire cluster was stopped and started back up again.

### Reproduction steps
Not sure - but this happens to every environment we bring up after some time, we recycle most as often as we can but the long running ones are exhibiting this behaviour.

### `consul version`
Both: `v0.9.3`

### `consul info` for  Server and Client
Server:
```
agent:
	check_monitors = 0
	check_ttls = 1
	checks = 2
	services = 27
build:
	prerelease =
	revision = 112c060
	version = 0.9.3
consul:
	bootstrap = false
	known_datacenters = 1
	leader = false
	leader_addr = x.x.x.78:8300
	server = true
raft:
	applied_index = 15145808
	commit_index = 15145808
	fsm_pending = 0
	last_contact = 53.984863ms
	last_log_index = 15145808
	last_log_term = 27
	last_snapshot_index = 15145516
	last_snapshot_term = 27
	latest_configuration = [{Suffrage:Voter ID:x.x.x.78:8300 Address:x.x.x.78:8300} {Suffrage:Voter ID:x.x.x.29:8300 Address:x.x.x.29:8300} {Suffrage:Voter ID:x.x.x.147:8300 Address:x.x.x.147:8300}]
	latest_configuration_index = 1
	num_peers = 2
	protocol_version = 2
	protocol_version_max = 3
	protocol_version_min = 0
	snapshot_version_max = 1
	snapshot_version_min = 0
	state = Follower
	term = 27
runtime:
	arch = amd64
	cpu_count = 4
	goroutines = 160
	max_procs = 4
	os = linux
	version = go1.9
serf_lan:
	coordinate_resets = 0
	encrypted = false
	event_queue = 0
	event_time = 12
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 54
	members = 11
	query_queue = 0
	query_time = 1
serf_wan:
	coordinate_resets = 0
	encrypted = false
	event_queue = 0
	event_time = 1
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 5
	members = 3
	query_queue = 0
	query_time = 1
```

Client:
```
agent:
	check_monitors = 0
	check_ttls = 0
	checks = 19
	services = 20
build:
	prerelease =
	revision = 112c060
	version = 0.9.3
consul:
	known_servers = 3
	server = false
runtime:
	arch = amd64
	cpu_count = 2
	goroutines = 110
	max_procs = 2
	os = linux
	version = go1.9
serf_lan:
	coordinate_resets = 0
	encrypted = false
	event_queue = 0
	event_time = 12
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 54
	members = 11
	query_queue = 0
	query_time = 1
```

### Operating system and Environment details
Ubuntu 16.04 / AWS / Docker 17.12.0-ce

### Link to [gist](https://gist.github.com/)
I've captured some profiling data from right after startup as well as from 20hrs later. I guess there might still not be enough information so please let me know if (and how long) I should wait before grabbing another heap profile.
https://gist.github.com/choppedpork/9f64a2929a9ddaa3de6ba3c0e045021d

Here's a memory graph for the node I took the profiles from (20h):
![screen shot 2018-03-06 at 13 33 41](https://user-images.githubusercontent.com/11997044/37035000-04b33f60-2143-11e8-97cf-9010a681615d.png)

edit: added `consul info` for server as well as client / agent
edit2: obscured IP address

**Comment by preetapan** [comment] 2018-03-06 15:12
@choppedpork there is very little state stored in memory on the agents, its mostly just service/checks needed for anti entropy syncing, so this is quite surprising. Will you be able to run one of the agent with  [enable_debug](https://www.consul.io/docs/agent/options.html#enable_debug) to give us some more info? 

After you have enable_debug turned on, and you see it get to this state where memory usage has crept up to hundreds of MB, you will need to take a heap profile by doing the following:

`curl -s http://localhost:<agent_port>/debug/pprof/heap > ~/agent_memory.heap` 

Note that having `enable_debug` does not hurt performance, and visiting /debug/pprof/heap has a one time low cost. (In case you are concerned that this will hurt your production environment even more). 

Having a heap dump will help us figure out what's happening here.

**Comment by jippi** [comment] 2018-03-06 16:17
FYI: we saw same issue in `0.9.3` - bumping to `1.0.6` fixed all of them :)

**Comment by choppedpork** [comment] 2018-03-06 17:04
@preetapan I've got one node running with `enable_debug` since yesterday and have uploaded a couple of those heap reports as a gist already (link in the original post). The memory usage should take about 3 days to go past 100m and some 15 days to go past 300m so I can keep adding more as it grows - would one past 100m be useful or should I just wait for a week or two?

**Comment by preetapan** [comment] 2018-03-06 17:09
@choppedpork oops, I missed seeing that link. let me see how far I can get with what you already have for now. Would still appreciate another heap dump when it gets to 100MB.

**Comment by choppedpork** [comment] 2018-03-06 17:13
No probs @preetapan - I seem to have messed up my gist upload too, here's an up-to-date heap dump: https://gist.github.com/choppedpork/3a7bcd4e36cd172a1624bbe70d919b59 (at 42m so far).

**Comment by preetapan** [comment] 2018-03-09 15:57
@choppedpork I tried looking at this heap dump using `go tool pprof` and seeing some really weird attribution to what's taking up memory. I think the root cause is that symbolization needs information from the binary on which the heap dump was taken. Can you run the following command and attach the file `consul_heap.pprof` ? This makes it easier to view heap profiles that are not remote. 

```
go tool pprof -proto -output consul_heap.prof /path/to/your/consul/binary http://<your agent:port>/debug/pprof/heap
```

**Comment by choppedpork** [comment] 2018-03-09 17:16
Thanks @preetapan! I'm assuming a profile generated as per your command might contain sensitive data - what's the best way of getting it to you?

We got to 132m memory usage today, in the meantime here's the non-debug text profile like the ones I shared before: https://gist.github.com/choppedpork/c75309b53713259001d5d97b691adcf5

**Comment by preetapan** [comment] 2018-03-09 20:44
@choppedpork it shouldn't contain any sensitive data - it is a summary of objects in the heap.

**Comment by choppedpork** [comment] 2018-03-12 17:09
Thanks @preetapan. I've uploaded both versions to https://gist.github.com/choppedpork/4c3216aabfae8ce675bac3a5a8eab5f7 - we're now at ~180m memory used.

WRT to upgrading - this would be my preferred choice but unfortunately the library our software is using needs updating to support versions higher than 1.0. While the developers are currently working on this, it might take a while before these updates trickle down to our customers.

**Comment by banks** [comment] 2018-03-13 14:44
Hmm I see almost all the memory being used up in sending serf notifications to the group from many many calles to the EventList API.

```
$go tool pprof -top -sample_index=inuse_objects ./consul_heap.prof
File: consul
Type: inuse_objects
Time: Mar 12, 2018 at 5:01pm (GMT)
Showing nodes accounting for 701300, 100% of 701431 total
Dropped 11 nodes (cum <= 3507)
      flat  flat%   sum%        cum   cum%
    688191 98.11% 98.11%     701300   100%  github.com/hashicorp/consul/agent.(*HTTPServer).EventList
     13109  1.87%   100%      13109  1.87%  github.com/hashicorp/consul/agent.(*NotifyGroup).Wait
         0     0%   100%     701300   100%  github.com/hashicorp/consul/agent.(*HTTPServer).EventList-fm
         0     0%   100%     701300   100%  github.com/hashicorp/consul/agent.(*HTTPServer).handler.func1.1
         0     0%   100%     701300   100%  github.com/hashicorp/consul/agent.(*HTTPServer).wrap.func1
         0     0%   100%     701300   100%  net/http.(*ServeMux).ServeHTTP
         0     0%   100%     701428   100%  net/http.(*conn).serve
         0     0%   100%     701300   100%  net/http.HandlerFunc.ServeHTTP
         0     0%   100%     701300   100%  net/http.serverHandler.ServeHTTP
```

Assuming this is actually accurate now and not just picking random symbols...

Also looking at the `inuse_objects` count it seems there are ~600k http connections stuck in `EventList` method. (I may be misreading this but that's how this seems):

![image](https://user-images.githubusercontent.com/120915/37348520-2d358d88-26cc-11e8-894e-a7d96ec33933.png)

@choppedpork can you check debug logs on your servers (if not enabled you can use `consul monitor -log-level=debug` to see these live). And see if you have clients hammering the servers with event list requests?

https://www.consul.io/api/event.html#list-events

Also can you check how many open TCP connections there are on your servers - if I'm reading this right you should see a lot of connections.

I could be totally wrong of course but that info might help rule out bad client behaviour blocking on event listings and for some reason not dropping connections but opening new ones?

**Comment by banks** [comment] 2018-03-13 14:49
For reference here is the code for EventList from version 0.5.2:

https://github.com/hashicorp/consul/blob/9a9cc9341bb487651a0399e3fc5e1e8a42e62dd9/command/agent/event_endpoint.go#L69

**Comment by banks** [comment] 2018-03-13 17:44
Thanks.

> 14 calls to /event/list?wait=5s&index=1

Hmm no nothing excessive there. It _seems_ to be these event list requests that are "leaking" for some reason given the count of currently allocated EventList.

To further prove/disprove the hypothesis, do you have an easy way to alter the config for whatever is calling /event/list and change the `wait` parameter to something significantly longer - say 30 seconds.

If it is those that's leaking you should see slow down in the rate of growth of memory and it at least confirms that call as the culprit.

Or if it's at all possible without impact, you could try stopping those clients entirely for a period long enough to see if it prevents further growth?

Can you share any details about the client that is calling that? It certainly seems buggy that any client behaviour can leak memory like that, but it might help narrow down what it is if we know what that client is actually doing - like if it perhaps is not closing connections properly or something.

**Comment by choppedpork** [comment] 2018-03-14 18:49
Still early days (will add more tomorrow) but this does seem to have helped:
![screen shot 2018-03-14 at 18 48 47](https://user-images.githubusercontent.com/11997044/37424452-632be742-27b8-11e8-9fb9-e0aacb1c03b5.png)

**Comment by choppedpork** [comment] 2018-03-15 12:08
Yup - definitely onto something here @banks:
![screen shot 2018-03-15 at 12 07 54](https://user-images.githubusercontent.com/11997044/37462352-8f1765d4-2849-11e8-9bbe-544a1806c954.png)

**Comment by banks** [comment] 2018-03-15 12:22
@choppedpork great, thanks for doing all that digging. That certainly seems to corroborate that it is something to do with that events list query and I wasn't just reading the heap profile backwards.

Hopefully this buys you a little more time too although it's clear it's just slowed the leak not fixed it. I'll try and poke at the 0.5.2 code and see if I can spot a way resources could leak on a timeout there or reproduce locally.

**Comment by choppedpork** [comment] 2018-03-15 12:24
Thanks @banks! For clarity - this is Consul 0.9.3, not 0.5.2 (unless you're referring to a version of something else).

**Comment by banks** [comment] 2018-03-15 12:26
Heh thanks, I was confusing issues clearly - we had another "old but can't upgrade" issue that was on 0.5.2. That saved me some time :)

**Comment by choppedpork** [comment] 2018-03-19 16:43
A small update from my side - it looks like the memory usage still grows but much, much slower. It seems to be we've got to the 'jagged' memory usage stage (I'm guessing this could be Golang switching to a different GC algorithm after a certain size? but I might just be projecting my Java experiences here).

![screen shot 2018-03-19 at 16 39 00](https://user-images.githubusercontent.com/11997044/37609177-51fb1b7a-2b94-11e8-9d68-3cbb9ece582f.png)

What I might do is restart the consul agent on this node so that we can get a graph of how the memory usage changes over time with the wait=30s workaround applied from the get-go as well.

**Comment by choppedpork** [comment] 2018-05-29 13:16
Hey @banks / @preetapan,

A few months have passed and we're finally in a position to upgrade! Unfortunately it looks like we still have the very same issue on our agent nodes in 1.1.0 (this is w/o the event-timeout change we've tried previously)..

![screen shot 2018-05-29 at 14 10 40](https://user-images.githubusercontent.com/11997044/40660936-5c7c4630-634a-11e8-9a19-ee298be65ef2.png)

**Comment by choppedpork** [comment] 2018-06-11 12:47
Hello @preetapan - apologies for taking so long to get back to you. It's currently non-trivial for me to set up a sufficiently long-lived application stack running Consul 1.1.0 (as we're still testing all nodes get rebuilt / restarted very often) but I'll try to set something up for this purpose today / this week.

**Comment by choppedpork** [comment] 2018-06-14 14:32
Alright - I finally have some data for you @preetapan / @banks.

Here's the heap dump: https://gist.github.com/choppedpork/49bec5a26bad977465596bd2a8aa4550#file-agent_memory-heap
Here's the heap dump taken with `go tool pprof`: https://gist.github.com/choppedpork/49bec5a26bad977465596bd2a8aa4550#file-consul_heap-prof

Here's a memory usage graph for the node this dump belongs to:
![screen shot 2018-06-14 at 15 16 10](https://user-images.githubusercontent.com/11997044/41417729-12869b2c-6fe6-11e8-87fd-d6cf6bec720f.png)

**Comment by choppedpork** [comment] 2018-06-19 11:48
I've done a little bit more digging and it looks like the memory pattern is pretty much identical in 1.1.0 and 0.9.3:
<img width="1324" alt="screen shot 2018-06-19 at 12 41 16" src="https://user-images.githubusercontent.com/11997044/41595305-38b5b914-73be-11e8-9ebc-945c51a68fd4.png">
The upgrade happened on the 22nd May.

I've uploaded a new heap dump, the memory usage is at ~150m now - hopefully that will make it easier to see what's accumulating.
https://gist.github.com/choppedpork/49bec5a26bad977465596bd2a8aa4550#file-consul_heap-150m-prof

**Comment by choppedpork** [comment] 2018-08-01 10:27
Hello,

I don't suppose you've managed to get anywhere with this issue yet? We're currently resorting to setting memory limits on the consul agent containers to force the kernel to OOM kill and then restart.

**Comment by banks** [comment] 2018-08-02 12:49
Hey thanks for the extra data @choppedpork, 

From a quick initial look it seems just the same as before:

![image](https://user-images.githubusercontent.com/120915/43583641-fe838674-9657-11e8-90b0-3ca5f7ab2851.png)

Over 400k allocations still "inuse" in the EventList method.

I managed to make a simple repro:

```
wrk -d 6000 -c 1000 -t 4 'http://localhost:8500/v1/event/list?wait=10s&index=1'
```

Lots of shortish blocking queries to local dev agent in parallel. I tried first with much shorter waits and couldn't see inuse_objects actually growing but with the above configuration it certainly does.

My Consul process started at 9.1MB reported by OS X Activity Monitor. After playing around with settings and profiling for a bit I was at about 40MB. I then ran the above `wrk` load and after a few minutes was at ~65MB. That alone is still pretty inconclusive but the part that's interesting is the pprof:

Before I tried with fewer client threads and short waits of 1s or less:

![image](https://user-images.githubusercontent.com/120915/43584486-6648a2ec-965a-11e8-84b0-68464f7f7e89.png)

2034 allocations made in the method but none still in use (none leaked).

With the `wrk` command above after a few minutes I see:

![image](https://user-images.githubusercontent.com/120915/43584525-8089214a-965a-11e8-8b3e-f1388b1ed09b.png)

11k allocation with 10k still "in use".

I stopped wrk after a while:

```
29301 requests in 5.02m, 4.25MB rea
```

and the final pprof a minute or so after stopping the load (i.e. no current HTTP requests being handled:)

![image](https://user-images.githubusercontent.com/120915/43584597-b5eb5e20-965a-11e8-9a0e-87fbbc994be1.png)

This was all using current master branch.

So good news is, we can reproduce. Bad news is it seems like a real leak we'll need to spend some time tracking down in details. I'm going to rename the task so we can track it.

**Comment by banks** [comment] 2018-08-02 13:16
It seems from the heap profile source view, the leaking objects are the notify chans:

![image](https://user-images.githubusercontent.com/120915/43585095-1c8b6a16-965c-11e8-999b-9281bfb2baf8.png)

That gets added to the `NotifyGroup`:

https://github.com/hashicorp/consul/blob/ec755b4ba7cdbee391b51750238250948774e741/agent/notify.go#L30:L39

But we don't clear that chan from the group at then end of the method body it seems...

I think I have a fix: defer `Clear` on the notifyChan. After the fix (PR incoming) I ran the same 5 mins test and see no inuse objects from EventList anymore after:

![image](https://user-images.githubusercontent.com/120915/43586026-71a3e508-965e-11e8-9d9d-feb581033075.png)

Memory usage is still ~58MB by the end but I think that is just too little signal to notice - things like metrics and gzip buffers being handled normally. I'll put up the PR and then once we have next release out I'll wait for you to confirm this is fixed in your production @choppedpork.

The lesson learned here from me is that if we'd looked at the original heap dump correctly (looked at source view) this probably would have been obvious a while ago. I'll chalk this up as a learning experience in reading heap dumps!

I think this is the only place affected by this since every other use of the NotifyGroup is by genuinely long-running goroutines that should stay running for the whole agent lifetime anyway.

**Comment by choppedpork** [comment] 2018-08-03 16:19
Woohoo 🎉
That's amazing news @banks, thanks a lot. Looking forward to the next release!

**Comment by mkeeler** [comment] 2018-08-09 13:43
Closing as the fix was merged.

**Closed by mkeeler** 2018-08-09 13:43 UTC
Labels: bug

**Comment by choppedpork** [comment] 2018-10-16 10:28
@banks just wanted to confirm (now that we've had this running for a few weeks) that 1.2.3 has indeed solved this problem for us, thanks again for looking into this!
👏

**Comment by banks** [comment] 2018-10-16 11:55
Thanks for the follow up @choppedpork, glad it worked!
