### ISSUE TITLE
Telemetry float values

### ISSUE THREAD

**Issue by panda87** [hashicorp/consul#1624] opened 2016-01-18 18:16 UTC
Hi

I recently installed Consul 0.6 in my env and I wanted to start pull telemetry metrics.
I'm using Telegraf statsd plugin in order to send the metrics directly to my influx cluster, but I found in the telegraf log many of these:
```
2016/01/18 17:17:47 Error: parsing value to int64: consul.memberlist.udp.sent:183.000000|c
2016/01/18 17:17:47 Error: parsing value to int64: consul.memberlist.udp.received:60.000000|c
2016/01/18 17:17:47 Error: parsing value to int64: consul.memberlist.udp.sent:183.000000|c
2016/01/18 17:17:47 Error: parsing value to int64: consul.memberlist.udp.received:60.000000|c
2016/01/18 17:17:47 Error: parsing value to int64: consul.memberlist.udp.sent:183.000000|c
2016/01/18 17:17:48 Error: parsing value to int64: consul.memberlist.udp.sent:69.000000|c
```
Which means the I expect to get int64 values and instead of that Im getting floats.
I think that in version 0.5.x these values were int64, so I wanted to ask if there is any reason so these metrics will be floats and not int? 

Thanks
D.

**Comment by slackpad** [comment] 2016-02-02 01:38
Hi @panda87 I took a look back through the code and these have been floats since the beginning. I'll tag @armon to see if he can lend any insight into why they were built this way, but I'll go ahead and close this out since it is the intended behavior and didn't change in 0.6.x.

**Closed by slackpad** 2016-02-02 01:38 UTC
