### ISSUE TITLE
Add tags to health check definition

### ISSUE THREAD

**Issue by cruatta** [hashicorp/consul#367] opened 2014-09-25 18:22 UTC
Now that we have a watch system, having tags in health check definitions would allow you to get very intelligent about routing status information once it's been passed to an alerting system. You could, for instance, tag a check as "dba" so that when it alerts, your alert routing system passes this on to your DBA on call team.

**Comment by mfischer-zd** [comment] 2015-02-16 20:50
See also https://github.com/hashicorp/consul/issues/418#issuecomment-74570266

**Comment by hugochinchilla** [comment] 2015-07-27 07:24
+1

**Comment by adrianlop** [comment] 2016-04-11 15:01
yeah great idea, we need this too. the problem is that you can only filter using tags in `consul watch -type service`, but it'd be very useful with serviceS or checks type, right?

any update on this?

**Comment by koalalam** [comment] 2019-01-16 21:35
+1, any update on this?

**Comment by i0rek** [comment] 2020-02-18 21:44
This issue is very old, yet relevant. These days, services can be tagged and health checks can be bound to a service. Which should solve your problem. I am closing this issue, because it is ancient. If you think this still deserves an open issue, feel free to create a new one.

**Closed by i0rek** 2020-02-18 21:44 UTC
Labels: close-old-issue-🤖, enhancement, theme/service-metadata
