### ISSUE TITLE
How to change the "-ui" default path "ui" to another name?

### ISSUE THREAD

**Issue by printfcoder** [hashicorp/consul#4495] opened 2018-08-07 01:52 UTC
#### Feature Description

We all know how to enable build-in ui and set the custom ui-dir, but I want to know how rename the "ui" path of consul web server to other name?

![image](https://user-images.githubusercontent.com/20906540/43749521-1297765c-9a27-11e8-95b6-75ec27250390.png)

just change "ui".

#### Use Case(s)

I want run the webapp behind a proxy server, but the default path "ui" is too sample.  How can I change it to "consul" or others ?

**Comment by pearkes** [comment] 2018-08-07 22:31
I believe this is a duplicate of #1930. See also #1382 for more context.

**Closed by pearkes** 2018-08-07 22:31 UTC
Labels: question
