### ISSUE TITLE
Probable Buggy DNS Behavior when Registering Multiple Nodes as External Services

### ISSUE THREAD

**Issue by consultantRR** [hashicorp/consul#790] opened 2015-03-16 22:33 UTC
I am seeing probable buggy DNS behavior in regards to external service registrations.

Basically, I am registering an external service, as documented here:

https://www.consul.io/docs/guides/external.html

ie:

curl -X PUT -d '{"Datacenter": "dc1", "Node": "search1", "Address": "search1.mygreatexampledomain.com", "Service": {"Service": "search", "Tags": [ "prod" ], "Port": 80}}' "http://127.0.0.1:8500/v1/catalog/register"

This works fine, and "prod.search.service.dc1.consul" resolves fine in Consul DNS.

However, I need to add additional external nodes to this service for high availability. As soon as I add a second:

curl -X PUT -d '{"Datacenter": "dc1", "Node": "search2", "Address": "search2.mygreatexampledomain.com", "Service": {"Service": "search", "Tags": [ "prod" ], "Port": 80}}' "http://127.0.0.1:8500/v1/catalog/register"

Then "prod.search.service.dc1.consul" no longer resolves at all in Consul DNS.

Consul version is 0.5.0.

**Comment by ryanuber** [comment] 2015-03-17 00:06
Hey @consultantRR, this behavior should be supported. I just ran your exact example against a local cluster, and I can't reproduce the issue. It might be useful to have some debug-level logs to get a better idea of what's going on. Can you provide the debug logs?

**Comment by consultantRR** [comment] 2015-03-17 12:53
Yes, thanks. Let me gather some logging and see what I can report back with.

**Comment by slackpad** [comment] 2016-04-13 05:36
Closing this out as we couldn't repro and haven't seen any more reports of this. Please re-open if you are still having trouble.

**Closed by slackpad** 2016-04-13 05:36 UTC
