### ISSUE TITLE
Issues while upgrading Version 0.7.4 to 0.8.5

### ISSUE THREAD

**Issue by hbmelachuru10** [hashicorp/consul#3242] opened 2017-07-07 16:18 UTC
Old Consul Server : 0.7.4
Old Consul Server: 0.7.4

**Upgraded consul server to version 0.8.5:**
a) Enabled debug mode level and found an error message for the agent in the log. 
[debug] agent: systemd notify failed: %!(EXTRA *errors.errorString=No socket)  
What is this error mean? Is it related to, agent: Added automatic notify to systemd on Linux after LAN join is complete, which makes it easier to order services that depend on Consul being available. [GH-2121] ?

**Upgraded consul server to Version 0.8.4:**
a) In the cluster, i have upgraded consul server from 0.7.4 to 0.8.4 but my consul clients are still 0.7.4. I tried to deploy another new consul client version 0.8.4 (some joined the cluster) but some throwed an error and didnot join the cluster:

==> 3 error(s) occurred:
  |  
  | * Failed to join 10.0.38.52: Member 'events-rj1c5' has conflicting node ID '75bb05de-2827-4764-bd96-9e85421feee5' with member 'test-0'
  | * Failed to join 10.0.37.89: Member 'consul-0' has conflicting node ID '50810000-0c12-43a9-bb5a-94cfda32c33c' with member 'replicate-2-71a66'
  | * Failed to join 10.0.32.43: Member 'example-1' has conflicting node ID '75bb05de-2827-4764-bd96-9e85421feee5' with member 'example-0'
 
b) And also i see a warning in the server logs, as:
2017/07/07 15:56:58 [WARN] consul.fsm: EnsureRegistration failed: failed inserting node: node ID "50811073-0c12-43a9-bb5a-94cfda32c33c" for node "example-0" aliases existing node "example-1"

c) I didnot include -node-id in my configuration for old clients (version 0.7.4). First i have upgraded my consul servers to 0.8.4 version. Then while deploying new version clients we are facing this node conflict issue.  Should i need to include -node-id or disable_host_node_id in the old version client(0.7.4) and deploy it before upgrading? 

d) Consul client v 0.8.4 is unable to join the cluster due to the conflicting node issue with client 0.7.4. Can i disable the host id checks?
What is the best way that you would suggest to upgrade the version.

Appreciate your time and help.

**Comment by slackpad** [comment] 2017-08-28 23:58
Hi @hbmelachuru10 sorry for the late response:

> [debug] agent: systemd notify failed: %!(EXTRA *errors.errorString=No socket)

Yeah that's from [GH-2121] (we've since made that error message print properly as well) - if you aren't using systemd you can ignore that one.

> What is the best way that you would suggest to upgrade the version.

This is tricky if you have a large pool of existing agents with duplicate node IDs. Please see https://github.com/hashicorp/consul/issues/3070#issuecomment-325515212 for some ideas on how to give these agents unique IDs during the transition.

Closing this out as a duplicate of #3070.

**Closed by slackpad** 2017-08-28 23:58 UTC
