### ISSUE TITLE
Name/Address conflicts when rebuilding clients.

### ISSUE THREAD

**Issue by j-slater** [hashicorp/consul#4806] opened 2018-10-16 18:11 UTC
#### Overview of the Issue

Conflicting Address and Name Conflict errors when rebuilding clients, even when clients have left cleanly.

#### Reproduction Steps

1. Create some fresh hosts, start consul client (leave_on_terminate=true) and join the server cluster.
2. Stop the clients cleanly, then delete the hosts, confirming all server nodes are aware the clients have left the cluster.
3. Re-create the hosts with the same hostname and random IP address and start the consul client.
4. Address and Name conflict logs can be seen on servers and many other clients.
5. Client that is in conflict is prevented from performing write operations until these logs go away.
6. Eventually the servers accept the client joining the cluster, but this can delay a deployment that should take minutes, into hours.

### Consul info for both Client and Server

<details>
  <summary>Client info</summary>

```
agent:
        check_monitors = 0
        check_ttls = 0
        checks = 0
        services = 0
build:
        prerelease =
        revision = 48d287ef
        version = 1.2.3
consul:
        known_servers = 5
        server = false
runtime:
        arch = amd64
        cpu_count = 2
        goroutines = 44
        max_procs = 1
        os = linux
        version = go1.10.1
serf_lan:
        coordinate_resets = 0
        encrypted = true
        event_queue = 0
        event_time = 57
        failed = 0
        health_score = 0
        intent_queue = 0
        left = 0
        member_time = 133446
        members = 703
        query_queue = 0
        query_time = 309
```

</details>

<details>
  <summary>Server info</summary>

```
agent:
        check_monitors = 0
        check_ttls = 0
        checks = 0
        services = 0
build:
        prerelease =
        revision = 48d287ef
        version = 1.2.3
consul:
        bootstrap = false
        known_datacenters = 1
        leader = true
        leader_addr = 10.0.69.228:8300
        server = true
raft:
        applied_index = 20502488
        commit_index = 20502488
        fsm_pending = 0
        last_contact = 0
        last_log_index = 20502488
        last_log_term = 183
        last_snapshot_index = 20500609
        last_snapshot_term = 183
        latest_configuration = [{Suffrage:Voter ID:828a42de-543b-1890-fae2-795b5ea05e61 Address:10.0.69.195:8300} {Suffrage:Voter ID:6abbf969-8023-33dc-4cce-e230d8a6ea9b Address:10.0.69.218:8300} {Suffrage:Voter ID:bf8dc985-3087-22e6-b6e0-4f02fd76adc8 Address:10.0.69.221:8300} {Suffrage:Voter ID:e30661f7-9b87-b69d-c2f2-e4f112ad7cba Address:10.0.69.228:8300} {Suffrage:Voter ID:3917a5be-9e19-e59f-7e68-889b9e7144d2 Address:10.0.69.194:8300}]
        latest_configuration_index = 20401253
        num_peers = 4
        protocol_version = 3
        protocol_version_max = 3
        protocol_version_min = 0
        snapshot_version_max = 1
        snapshot_version_min = 0
        state = Leader
        term = 183
runtime:
        arch = amd64
        cpu_count = 2
        goroutines = 3434
        max_procs = 2
        os = linux
        version = go1.10.1
serf_lan:
        coordinate_resets = 0
        encrypted = true
        event_queue = 0
        event_time = 57
        failed = 23
        health_score = 0
        intent_queue = 0
        left = 709
        member_time = 133412
        members = 1425
        query_queue = 0
        query_time = 309
serf_wan:
        coordinate_resets = 0
        encrypted = true
        event_queue = 0
        event_time = 1
        failed = 0
        health_score = 0
        intent_queue = 0
        left = 0
        member_time = 101
        members = 5
        query_queue = 0
        query_time = 1
```

</details>

### Operating system and Environment details

5 server hosts with anywhere from 500-1000 clients per datacenter (same issue will surface on a single data center cluster as well as federated multi-datacenter clusters). Consul agent on both server and clients is a direct download of the binary, running on CentOS 7.5 KVM hosts deployed by an OpenStack cloud.

### Log Fragments
The host is cleanly stopped and the client is seen leaving the cluster by all 5 server members (03 is the leader)
```
2018-10-16T15:43:40.513529+00:00 dev-consul-server-01 consul 2018/10/16 15:43:40 [INFO] serf: EventMemberLeave: dev-client10 10.0.68.204
2018-10-16T15:43:40.352633+00:00 dev-consul-server-04 consul 2018/10/16 15:43:40 [INFO] serf: EventMemberLeave: dev-client10 10.0.68.204
2018-10-16T15:43:40.294878+00:00 dev-consul-server-03 consul 2018/10/16 15:43:40 [INFO] consul: member 'dev-client10' left, deregistering
2018-10-16T15:43:40.288761+00:00 dev-consul-server-03 consul 2018/10/16 15:43:40 [INFO] serf: EventMemberLeave: dev-client10 10.0.68.204
2018-10-16T15:43:40.232394+00:00 dev-consul-server-05 consul 2018/10/16 15:43:40 [INFO] serf: EventMemberLeave: dev-client10 10.0.68.204
2018-10-16T15:43:40.135801+00:00 dev-consul-server-02 consul 2018/10/16 15:43:40 [INFO] serf: EventMemberLeave: dev-client10 10.0.68.204
```

After rebuilding the client, 4 of the 5 servers complain about conflicting name and address, including the leader. This prevents the client from performing write operations such as registering services.
```
2018-10-16T15:48:19.039528+00:00 dev-consul-server-04 consul 2018/10/16 15:48:19 [WARN] serf: Name conflict for 'dev-client10' both 10.0.68.204:8301 and 10.0.69.1:8301 are claiming
2018-10-16T15:47:52.858125+00:00 dev-consul-server-03 consul 2018/10/16 15:47:52 [WARN] serf: Name conflict for 'dev-client10' both 10.0.68.204:8301 and 10.0.69.1:8301 are claiming
2018-10-16T15:47:52.857832+00:00 dev-consul-server-03 consul 2018/10/16 15:47:52 [ERR] memberlist: Conflicting address for dev-client10. Mine: 10.0.68.204:8301 Theirs: 10.0.69.1:8301
2018-10-16T15:47:52.796195+00:00 dev-consul-server-02 consul 2018/10/16 15:47:52 [ERR] memberlist: Conflicting address for dev-client10. Mine: 10.0.68.204:8301 Theirs: 10.0.69.1:8301
2018-10-16T15:47:52.728059+00:00 dev-consul-server-01 consul 2018/10/16 15:47:52 [WARN] serf: Name conflict for 'dev-client10' both 10.0.68.204:8301 and 10.0.69.1:8301 are claiming
2018-10-16T15:47:52.030711+00:00 dev-consul-server-02 consul 2018/10/16 15:47:52 [WARN] serf: Name conflict for 'dev-client10' both 10.0.68.204:8301 and 10.0.69.1:8301 are claiming
2018-10-16T15:47:51.804308+00:00 dev-consul-server-01 consul 2018/10/16 15:47:51 [ERR] memberlist: Conflicting address for dev-client10. Mine: 10.0.68.204:8301 Theirs: 10.0.69.1:8301
2018-10-16T15:47:51.696955+00:00 dev-consul-server-05 consul 2018/10/16 15:47:51 [INFO] serf: EventMemberJoin: dev-client10 10.0.69.1
2018-10-16T15:47:51.469676+00:00 dev-consul-server-04 consul 2018/10/16 15:47:51 [ERR] memberlist: Conflicting address for dev-client10. Mine: 10.0.68.204:8301 Theirs: 10.0.69.1:8301
```

**Comment by pearkes** [comment] 2018-10-26 16:41
I believe we can close this as a duplicate of #4741.

**Closed by pearkes** 2018-10-26 16:41 UTC
