### ISSUE TITLE
Unable to change the client token in UI when it expires.

### ISSUE THREAD

**Issue by ars05** [hashicorp/consul#3239] opened 2017-07-07 10:23 UTC
Client: `0.8.5`
Server: `0.8.5`

### Operating system and Environment details
Server OS - CentOS Linux release 7.2.1511 (Core) 
Chrome Mac OS - Version 59.0.3071.115 (Official Build) (64-bit)

### Description of the Issue (and unexpected/desired result)
When using UI there is a setting button where user/client can provide a token to be able to read/write using UI - When token expires the setting button disagrees and there is no way to change the token except clearing browser cache. 

### Reproduction steps
- generate a token
- open a incognito tab and copy paste it to the UI under setting 
- remove the token
- generate another one
- refresh the UI loaded in incognito tab 
- try to change the token (you may not because there is no setting button)

**Comment by slackpad** [comment] 2017-07-09 00:09
Hi @ars05 closing this as a duplicate of #2370.

**Closed by slackpad** 2017-07-09 00:09 UTC
