### ISSUE TITLE
When changing IP Consul Servers get registered twice in the peers list

### ISSUE THREAD

**Issue by tarrant** [hashicorp/consul#613] opened 2015-01-17 01:02 UTC
Hey,

Our systems people have been changing IPs on some of our boxes which happen to also be our Consul Servers.

They did this by changing the IP and then running puppet which updated consul. The issue we ran into is that the peers list ended up with both the new and old IP.

This then caused a pop to outage due to our peer list going from 3 -> 6. Since there was only three real servers we were unable to maintain quorum. I was able to resolve this by stopping all of the consul servers, deleting the peer list and then starting the servers again (with bootstrap on).

Ideally consul should have some safeguard to detect which consul server is which regardless of its IP.

We are changing our playbook on how to do this operation and are instead making the consul server leave, then change the IP then re add it.

**Comment by armon** [comment] 2015-01-20 22:42
Duplicate of #457. Looking into handling this!

**Closed by armon** 2015-01-20 22:42 UTC
