### ISSUE TITLE
Command to leave WAN pool without leaving LAN pool

### ISSUE THREAD

**Issue by freddygv** [hashicorp/consul#6548] opened 2019-09-26 00:17 UTC
#### Feature Description

Currently the [`consul leave`](https://www.consul.io/docs/commands/leave.html) command will trigger a graceful leave and shutdown of the agent it is called on. 

Consul should provide a command and HTTP API endpoint for servers to leave a WAN pool without:
- Being removed from the raft config
- Leaving the LAN pool
- Shutting down

#### Use Case(s)

The main use-case would be to split up two WAN-joined datacenters. 

~The only way to do this without downtime currently is to:~
~1. Block cross-DC server communication.~
~2. Have a server in each DC call `consul force-leave <node-name>.<dc>` on all the servers in the other DC (once the servers in the other DC are marked as failed).~

There is currently no workaround for this.

**Comment by slackpad** [comment] 2019-09-27 02:44
This is a duplicate of #3307 but this has more context so might be a better issue. There was an attempt to do this in #3414 that has some more context and some issues that we ran into.

**Comment by banks** [comment] 2020-05-14 14:56
Relatedly, I don't think `consul force-leave <node-name>.<dc>` actually works as documented currently. When I test it with a federated cluster, even when all nodes are up and healthy I get:

```sh
$ consul members -wan
Node            Address          Status  Type    Build     Protocol  DC   Segment
node-24507.dc1  127.0.0.1:24509  alive   server  1.7.0dev  2         dc1  <all>
node-24512.dc1  127.0.0.1:24514  alive   server  1.7.0dev  2         dc1  <all>
node-24532.dc2  127.0.0.1:24534  alive   server  1.7.0dev  2         dc2  <all>
node-24537.dc2  127.0.0.1:24539  alive   server  1.7.0dev  2         dc2  <all>
node-24542.dc2  127.0.0.1:24544  alive   server  1.7.0dev  2         dc2  <all>
node-24562.dc3  127.0.0.1:24564  alive   server  1.7.0dev  2         dc3  <all>
node-24567.dc3  127.0.0.1:24569  alive   server  1.7.0dev  2         dc3  <all>
node-24572.dc3  127.0.0.1:24574  alive   server  1.7.0dev  2         dc3  <all>
node-8500.dc1   127.0.0.1:8302   alive   server  1.7.0dev  2         dc1  <all>
```

```sh
$ consul force-leave -prune node-24562.dc3
Error force leaving: Unexpected response code: 500 (agent: No node found with name 'node-24562.dc3')
```

**Comment by freddygv** [comment] 2020-05-14 17:22
@banks there was a change made that broke that workaround. This was to fix an issue where force-leave called in the current DC without the DC suffix led to the force-left node not leaving the WAN pool.

The relevant code is here:
https://github.com/hashicorp/consul/blob/master/agent/consul/server.go#L1127

When you call `<node-name>.dc2` from `dc1` we naively append `dc1` for the WAN pool removal, and the call is made with `<node-name>.dc2.dc1`.

**Comment by banks** [comment] 2020-05-15 12:50
There was another change made recently that is the reason the workaround now doesn't work: https://github.com/hashicorp/consul/commit/aed5cb76690aee5a77a15a1cf3992c517ab5fd17

In an attempt to improve the error message on force-leave (a great idea) we missed the case that it could be a WAN node so need to fix that.

**Comment by sriyer** [comment] 2020-10-08 07:02
@banks @freddygv , it seems that at the moment there is no way to un-federate a cluster from another. Is the force-leave option going to be fixed soon?

**Closed** 2021-12-02 23:15 UTC
Labels: type/enhancement, theme/operator-usability
