### ISSUE TITLE
Consul Connect: CA Root does not store the intermediate

### ISSUE THREAD

**Issue by saltxwater** [hashicorp/consul#10826] opened 2021-08-11 11:15 UTC
#### Overview of the Issue

v1/agent/connect/ca/roots is returning the RootCert but IntermediateCerts is null, despite all leaf certs being signed by the intermediate.
Connect is configured to use the vault provider.
This happens for us after a consul leadership change. Looking at the logs and corresponding code I can see the SigningKeyID is changing (not what we'd expect...) but then the control flow of the code doesn't appear to set the intermediate on the rootCA.

https://github.com/hashicorp/consul/blob/v1.10.1/agent/consul/leader_connect_ca.go#L500

In the case that the SigningKeyID does NOT change, it's meant to set the intermediate:
https://github.com/hashicorp/consul/blob/v1.10.1/agent/consul/leader_connect_ca.go#L470

Surely it's meant to also set the intermediate on the rootCA on line 499? Or potentially before the raftApply, so line 486?

We're running 1.10.1, but I can see the same in main:

https://github.com/hashicorp/consul/blob/main/agent/consul/leader_connect_ca.go#L563

### Operating system and Environment details

Consul 1.10.1 (enterprise)

### Log Fragments

```
[18148]: 2021-08-10T17:51:34.590+0100 [INFO]  agent.server.connect: Correcting stored SigningKeyID value: previous=b9:98:.... updated=19:5d:......
[18148]: 2021-08-10T17:51:34.602+0100 [INFO]  agent.server.connect: initialized primary datacenter CA with provider: provider=vault
[18148]: 2021-08-10T17:51:34.602+0100 [INFO]  agent.server.connect: Successfully initialized the Connect CA
[18148]: 2021-08-10T17:51:34.602+0100 [INFO]  agent.leader: started routine: routine="intermediate cert renew watch"
```

**Comment by jkirschner-hashicorp** [comment] 2021-08-16 22:16
Hi @saltxwater,

Thanks for reporting this. We recently discovered it as well (#10532).

Our understanding is that the impact is limited to the intermediate not being returned in the API call. The intermediate is still in memory and everything internally works as expected (e.g., leaf certs are signed by the intermediate), but one code path needs to be adjusted to fix the API return value.

**Comment by dnephin** [comment] 2021-11-01 22:05
Possibly a duplicate of #10532

**Closed** 2021-12-02 21:02 UTC
Labels: type/bug, theme/consul-vault, theme/certificates
