### ISSUE TITLE
Support a 1 service : N port abstraction

### ISSUE THREAD

**Issue by armon** [hashicorp/consul#287] opened 2014-08-18 18:25 UTC
Many services expose more than one port. This currently is done by exporting multiple service entries, but can be done more nicely.

**Comment by wwalker** [comment] 2015-02-04 17:03
+1  Have multiple multi-port apps here

**Comment by niclashoyer** [comment] 2015-02-08 00:04
@armon is there any roadmap for this?

**Comment by ryanuber** [comment] 2015-02-08 20:00
@niclashoyer we will likely get this added once the 0.5.0 release is complete. We are trying to lock down on features to get that release out the door since we already slipped the intended release date.

**Comment by sigil66** [comment] 2015-05-11 21:39
+1

**Comment by slackpad** [comment] 2016-03-11 07:03
Closing this as a duplicate of https://github.com/hashicorp/consul/issues/1202, since there's some slightly more recent discussion going on there.

**Closed by slackpad** 2016-03-11 07:03 UTC
Labels: enhancement
