### ISSUE TITLE
Allow consul to bind to non-private ip addresses

### ISSUE THREAD

**Issue by telmich** [hashicorp/consul#789] opened 2015-03-16 19:46 UTC
Running consul 0.4.1 and 0.5.0, using generic bind address fails (see below).

This in term means that *any* server that has only public ip addresses needs
to use -bind-addr=the-public-ip, which is rather cumbersome to use for bigger
installations.

Thus I wonder if it is possible to change consul to allow to listening to IN_ANY 
address if -bind=0.0.0.0 is given?

    [20:42:50] mx-hetzner01:~# consul agent  -data-dir /tmp/
    ==> WARNING: It is highly recommended to set GOMAXPROCS higher than 1
    ==> Starting Consul agent...
    ==> Error starting agent: Failed to get advertise address: No private IP address found
    [20:42:54] mx-hetzner01:~# consul agent  -data-dir /tmp/ -bind=0.0.0.0
    ==> WARNING: It is highly recommended to set GOMAXPROCS higher than 1
    ==> Starting Consul agent...
    ==> Error starting agent: Failed to get advertise address: No private IP address found
    [20:43:02] mx-hetzner01:~#

**Comment by ryanuber** [comment] 2015-03-16 19:59
Hey @telmich, thanks for opening an issue. This is a dupe of #725, so let's track the issue there. Thanks!

**Closed by ryanuber** 2015-03-16 19:59 UTC
