### ISSUE TITLE
New checks and services are registered separately

### ISSUE THREAD

**Issue by clstokes** [hashicorp/consul#1955] opened 2016-04-16 01:28 UTC
If I add new node-level check and service (w/o a check) definitions and perform a `consul reload`, the services are registered first and immediately set as _passing_. The check seems to be registered immediately after, but in a separate "commit" which causes the service to flap from _passing_ to _critical_ and back to _passing_ if the check is indeed healthy. This seems to only occur during a `consul reload` and only when the check is for the node and not bound to the particular service. When using consul-template, this causes excessive flapping and reloads. 

Gist to help reproduce is at https://gist.github.com/clstokes/298895c737a6d0957987e802259d9c06.

**Comment by clstokes** [comment] 2016-04-16 01:28
Assigning to James as he and I already discussed this in some detail.

**Comment by slackpad** [comment] 2016-04-25 06:51
It looks like the logic to disable syncing during these changes doesn't wait until any sync-in-progress completes. The code is "safe" because the locks are in the right place, but it's not working as intended. We need to lock out future syncs and wait for any in-progress sync to complete if we want these changes to be atomic.

**Comment by i0rek** [comment] 2020-02-03 19:18
Thanks for reporting @clstokes! I tried to reproduce the problem with your gist, but I wasn't able to . 

1. consul: `consul agent -dev -ui -config-file client.json`
2. reload: `while true; consul reload; end`
3. checks: `while true; curl -s localhost:8500/v1/agent/checks | jq  -r '.web.Status';end`

I never saw it failing. Am I missing something?

It is possible that this problem was fixed in the 2,5y that have passed.

**Comment by ChipV223** [comment] 2021-04-08 14:57
Hi @clstokes!

Since it's been a couple of years since we've heard from you concerning this issue and like @i0rek , I've not been able to reproduce this behavior using the latest release(v1.9.4), I'll go ahead and close this.

But do feel free to reach out if you are still seeing this behavior in the latest versions!

**Closed by ChipV223** 2021-04-08 14:57 UTC
Labels: theme/internal-cleanup, type/bug, waiting-reply
