### ISSUE TITLE
watch config fails when args length is 1

### ISSUE THREAD

**Issue by rossrochford** [hashicorp/consul#8332] opened 2020-07-18 15:28 UTC
#### Overview of the Issue

When adding an event watch to the Consul agent config, it fails when the length of args is 1.

#### Reproduction Steps

Steps to reproduce this issue, eg:

1. create a HCL config file with a watches stanza:

`watches {
  type = "event"
  name = "my-event"
  handler_type = "script"
  args = ["/scripts/test-event.sh"]
}`

2. run agent:

`$ consul agent -dev -config-file=agent_conf.hcl`

3. view the error: "Watch args must be a list of strings"

4. retry with the following config and it will succeed:

`watches {
  type = "event"
  name = "my-event"
  handler_type = "script"
  args = ["/scripts/test-event.sh", "1"]
}`

### Consul info for both Client and Server

Single Consul agent in -dev mode

### Operating system and Environment details

Consul 1.8.0
Ubuntu 20.04

### Log Fragments

`2020-07-18T16:24:19.274+0100 [ERROR] agent: Error starting agent: error="Watch args must be a list of strings"`

**Comment by dnephin** [comment] 2020-07-20 15:55
Thank you for reporting this issue! It looks like this is a duplicate of #8284, which has a pending fix in #8290. The fix should be in the next patch release.

I've updated the title of the other issue to make it easier to find. I will close this as a duplicate.

**Closed by dnephin** 2020-07-20 15:55 UTC
