### ISSUE TITLE
consul lock: go default QUIT handler leaves stranded child process

### ISSUE THREAD

**Issue by babbottscott** [hashicorp/consul#1210] opened 2015-08-31 22:40 UTC
On SIGQUIT, consul lock will dump stacktrace/core and exit.  If this happens while lock is acquired and child process is running, that process will be stranded and continue running outside of lock.  A quit signal should probably trigger an attempt to terminate a running child process.

Seen on 0.5.2

**Comment by slackpad** [comment] 2017-05-03 21:34
Closing this as a duplicate of #2489.

**Closed by slackpad** 2017-05-03 21:34 UTC
