### ISSUE TITLE
Deleting old payload of a watch

### ISSUE THREAD

**Issue by mrinal93** [hashicorp/consul#2618] opened 2016-12-28 07:31 UTC
Hi,
I am facing an issue when I re-setup or reload an existing watch. The handler which executes when the watch is reloaded or re-setup, takes up the old payload provided earlier along with the event (that was fired to trigger that watch).

Is there a way to remove old payload? 

Consul version: v0.7.1

**Comment by taharah** [comment] 2016-12-29 00:20
All watches are fired after a reload, which as of this writing is an intended feature. I've been storing the modify indexes of the payload either locally or within Consul itself depending on the watch. I have my handler script check to see if the index has changed, and if it has, then actually run the handler script. This seems to be the most common way of handling "old payloads" currently. There is an issue opened requesting that the current behavior be changed to at least a boolean configuration option so that reloads don't fire all watches if that's not desired, but I can't find it right now since I am on my mobile.

**Comment by slackpad** [comment] 2017-02-08 02:42
Closing this as a duplicate of https://github.com/hashicorp/consul/issues/571.

**Closed by slackpad** 2017-02-08 02:42 UTC
